#!/usr/bin/env python3
"""Write docs/VIDEO-SCRIPT.md from the narration files: chapter times, on-screen message, voice-over, evidence."""
import os, sys
os.environ.setdefault("CUT", "3min")
import importlib
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

SLIDE_MSG = {
    "deck-01": ("Know the business you invest in.", "Product and promise"),
    "deck-02": ("Investing in a business is hard to follow.", "Four investor gaps: understand, follow, own, get paid"),
    "deck-03": ("Trillions in private businesses. Investors still can't see inside.", "Market size and unmet need"),
    "deck-04": ("One passport per business. Five things every investor gets.", "Solution"),
    "deck-09": ("Real benefits for investors. Clear duties for the business.", "Investor protection"),
    "deck-10": ("Built for the tokenised future: clear custody from day one.", "Custody and tokenised assets"),
    "deck-11": ("People decide. Every step is on the record.", "How it works"),
    "deck-13": ("A real app, ready to run on your chain.", "Join us: Ethereum investors, L1 and L2 teams, licensed partners"),
    "deck-12": ("Built by founders who have run tech at scale.", "Team"),
    "progress": ("Live on testnet, end to end.", "Current progress"),
    "close": ("Know the business you invest in.", "Next steps and contact"),
}
EVIDENCE = {
    "m01": "Preqin Oct 2025 ($32T alternatives AUM by 2030) · Crunchbase Jan 2026 ($425B VC in 2025) · Bain GPER Mar 2025 (distributions 11% of NAV, a decade low)",
    "m02": "Corporations Act s169 · Law on Enterprises 2020 Art. 122 · ASIC RG 261 · NASC Targeting Scams 2025 (A$837.7M) · Bain (29% → 11%)",
    "m03": "rwa.xyz ($6.6B Mar 2025 → $38.7B Oct 2026) · Citi GPS Jun 2026 ($5.5T by 2030) · MiCA, VN Resolution 05/2025, VN Law 71/2025, AU Digital Assets Framework",
    "p01": "Live platform stats (GET /api/v1/platform/stats): 14 sample listings, 42 token contracts, 14/14 verified",
    "t01": "docs/TEAM.md (owner-confirmed)",
}

def mmss(t):
    return f"{int(t // 60)}:{int(t % 60):02d}"

def section(cut):
    os.environ["CUT"] = cut
    import build; importlib.reload(build)
    rs = build.rows(); d = build.durations(); n = len(rs)
    D = [d[r[0]] for r in rs]
    starts = [sum(D[:i]) - build.XF * i for i in range(n)]
    total = sum(D) - build.XF * (n - 1)
    name = build.NAME
    out = [f"## {'3-minute cut' if cut == '3min' else 'Full cut'} ({mmss(total)})", "",
           f"Video: https://eth.blockid.au/deck/{name}-captions.mp4 · captions: https://eth.blockid.au/deck/{name}.srt", "",
           "| Time | Scene | On screen (key message) | Voice-over | Evidence |", "|---|---|---|---|---|"]
    chapters = []
    for i, (k, slot, text) in enumerate(rs):
        kind, nm = slot.split(":")
        if kind == "rec":
            lab, msg = build.HEADS.get(k, (k, ""))
            scene = f"Live app: {lab}"
        else:
            msg, lab = SLIDE_MSG.get(nm, (nm, nm))
            scene = f"Slide: {lab}"
        out.append(f"| {mmss(starts[i])} | {scene} | {msg} | {text} | {EVIDENCE.get(k, '')} |")
        chapters.append((mmss(starts[i]), lab, msg))
    return "\n".join(out), chapters

if __name__ == "__main__":
    s3, ch3 = section("3min")
    sf, _ = section("full")
    md = ["# Demo video script (EAG Global Buildathon submission)", "",
          "Generated by `docs/video/full/script_md.py` from the narration files, so times and words match the videos.",
          "Every recorded scene shows the live testnet app at https://eth.blockid.au (sample data, no real users yet) above a",
          "message band with its key line, so the pitch reads with the sound off. Sources for all numbers:",
          "[MARKET-EVIDENCE.md](MARKET-EVIDENCE.md).", "", s3, "", sf, ""]
    open(os.path.join(HERE, "..", "..", "VIDEO-SCRIPT.md"), "w").write("\n".join(md))
    with open(os.path.join(HERE, "chapters-3min.txt"), "w") as f:
        for t, lab, msg in ch3:
            f.write(f"{t}\t{lab}\t{msg}\n")
    print(open(os.path.join(HERE, "chapters-3min.txt")).read())
