/**
 * eth.blockid.au ↔ hr.blockid.au link strings (docs/PLAN-HR-V2.md §3): the "Founding team" card on the valuation
 * report, the team panel on /start and the "Team" tile of the company workspace. Plain words (docs/FACTS.md).
 * VI must cover every EN key (checked by the type).
 */
export const hlEn = {
  "hl.h": "Founding team",
  "hl.weight": "Founding team = {p}% of the business score",
  "hl.none.p": "Nobody has assessed the founders of this business yet. We check each person's public professional information and how well they fit this business.",
  "hl.cta.assess": "Assess the founders",
  "hl.cta.open": "Open the team report",
  "hl.cta.full": "Open full team report",
  "hl.found": "Found on your website:",
  "hl.found.add": "add",
  "hl.found.addp": "Add {n} to the assessment",
  "hl.found.all": "Assess these {n} people",
  "hl.st.draft": "Saved but not started yet.",
  "hl.st.queued": "Waiting to start",
  "hl.st.running": "Checking the founders",
  "hl.st.stalled": "Taking longer than usual",
  "hl.ph.queued": "Waiting in line",
  "hl.ph.reading": "Reading their pages",
  "hl.ph.searching": "Searching public sources",
  "hl.ph.extracting": "Checking the facts",
  "hl.ph.scoring": "Scoring the team",
  "hl.ph.done": "Done",
  "hl.ph.failed": "Stopped",
  "hl.ph.stalled": "Taking longer than usual",
  "hl.eta": "about {t} left",
  "hl.eta.soon": "almost done",
  "hl.runon": "Running on hr.blockid.au",
  "hl.min": "{n} min",
  "hl.sec": "{n} sec",
  "hl.auto": "This card updates every 5 seconds. You can leave the page; the assessment keeps running.",
  "hl.pdone": "{a} of {b} people done",
  "hl.p.waiting": "waiting",
  "hl.p.working": "checking now",
  "hl.p.done": "done",
  "hl.p.failed": "stopped",
  "hl.score": "Team score",
  "hl.conf": "Confidence: {c}",
  "hl.conf.high": "high",
  "hl.conf.medium": "medium",
  "hl.conf.low": "low",
  "hl.fit": "fit to this business",
  "hl.quality": "profile",
  "hl.fit.short": "fit",
  "hl.legend": "For each person: fit to this business (0–100), then profile strength.",
  "hl.top": "Top strength",
  "hl.gap": "Main gap",
  "hl.person.open": "Open the report on {n}",
  "hl.applied": "Applied to this valuation's score.",
  "hl.applied.on": "Applied to this valuation's score on {d}.",
  "hl.notapplied": "Not applied to the score: {r}.",
  "hl.notapplied.wait": "The team score is applied to the valuation when the assessment is done.",
  "hl.failed": "The founders' assessment stopped.",
  "hl.failed.reason": "Reason: {r}",
  "hl.retry": "Try again on hr.blockid.au",
  "hl.private": "The team report is private. Ask the person who started it to share it.",
  "hl.bt.strong": "Strong team",
  "hl.bt.good": "Good team",
  "hl.bt.partial": "Partial team",
  "hl.bt.weak": "Weak team",
  "hl.bt.poor": "Poor team",
  "hl.kind.founder": "Founder",
  "hl.kind.cofounder": "Co-founder",
  "hl.kind.executive": "Executive",
  "hl.kind.employee": "Team member",
  "hl.kind.advisor": "Advisor",
  "hl.bf.strong": "Strong fit",
  "hl.bf.good": "Good fit",
  "hl.bf.partial": "Partial fit",
  "hl.bf.weak": "Weak fit",
  "hl.bf.poor": "Poor fit",

  // /start team panel
  "hl.wz.h": "Founding team",
  "hl.wz.badge": "Recommended",
  "hl.wz.sub": "Counts for 30% of the business score. Add the people now, or later from the valuation report.",
  "hl.wz.p": "List the people behind the business. We check their public professional information, only with their agreement.",
  "hl.wz.looking": "Looking for people on {h}…",
  "hl.wz.found": "Found on {h}:",
  "hl.wz.add": "Add",
  "hl.wz.added": "Added",
  "hl.wz.addall": "Add all",
  "hl.wz.none": "No names found on {h}. Type them below.",
  "hl.wz.people": "{n} people",
  "hl.wz.bad": "Check the founding team: {n} fields need fixing.",

  // company workspace overview
  "hl.co.h": "Team",
  "hl.co.sub": "30% of the business score",
  "hl.co.none": "The founders have not been assessed yet.",
  "hl.co.running": "Assessment running · {p}%",
};

export const hlVi: Record<keyof typeof hlEn, string> = {
  "hl.h": "Đội ngũ sáng lập",
  "hl.weight": "Đội ngũ sáng lập = {p}% điểm doanh nghiệp",
  "hl.none.p": "Chưa ai đánh giá những người sáng lập doanh nghiệp này. Chúng tôi kiểm tra thông tin nghề nghiệp công khai của từng người và mức độ phù hợp với doanh nghiệp.",
  "hl.cta.assess": "Đánh giá người sáng lập",
  "hl.cta.open": "Mở báo cáo đội ngũ",
  "hl.cta.full": "Mở báo cáo đội ngũ đầy đủ",
  "hl.found": "Tìm thấy trên website của bạn:",
  "hl.found.add": "thêm",
  "hl.found.addp": "Thêm {n} vào đánh giá",
  "hl.found.all": "Đánh giá {n} người này",
  "hl.st.draft": "Đã lưu nhưng chưa bắt đầu.",
  "hl.st.queued": "Đang chờ bắt đầu",
  "hl.st.running": "Đang kiểm tra người sáng lập",
  "hl.st.stalled": "Lâu hơn bình thường",
  "hl.ph.queued": "Đang xếp hàng",
  "hl.ph.reading": "Đang đọc các trang của họ",
  "hl.ph.searching": "Đang tìm nguồn công khai",
  "hl.ph.extracting": "Đang kiểm tra dữ kiện",
  "hl.ph.scoring": "Đang chấm điểm đội ngũ",
  "hl.ph.done": "Xong",
  "hl.ph.failed": "Đã dừng",
  "hl.ph.stalled": "Lâu hơn bình thường",
  "hl.eta": "còn khoảng {t}",
  "hl.eta.soon": "sắp xong",
  "hl.runon": "Đang chạy trên hr.blockid.au",
  "hl.min": "{n} phút",
  "hl.sec": "{n} giây",
  "hl.auto": "Thẻ này tự cập nhật mỗi 5 giây. Bạn có thể rời trang; việc đánh giá vẫn tiếp tục.",
  "hl.pdone": "Xong {a}/{b} người",
  "hl.p.waiting": "đang chờ",
  "hl.p.working": "đang kiểm tra",
  "hl.p.done": "xong",
  "hl.p.failed": "đã dừng",
  "hl.score": "Điểm đội ngũ",
  "hl.conf": "Độ tin cậy: {c}",
  "hl.conf.high": "cao",
  "hl.conf.medium": "trung bình",
  "hl.conf.low": "thấp",
  "hl.fit": "phù hợp với doanh nghiệp",
  "hl.quality": "hồ sơ",
  "hl.fit.short": "phù hợp",
  "hl.legend": "Mỗi người: mức phù hợp với doanh nghiệp này (0–100), sau đó là độ mạnh hồ sơ.",
  "hl.top": "Điểm mạnh nhất",
  "hl.gap": "Điểm thiếu chính",
  "hl.person.open": "Mở báo cáo về {n}",
  "hl.applied": "Đã áp dụng vào điểm của định giá này.",
  "hl.applied.on": "Đã áp dụng vào điểm của định giá này ngày {d}.",
  "hl.notapplied": "Chưa áp dụng vào điểm: {r}.",
  "hl.notapplied.wait": "Điểm đội ngũ được áp dụng vào định giá khi đánh giá xong.",
  "hl.failed": "Việc đánh giá người sáng lập đã dừng.",
  "hl.failed.reason": "Lý do: {r}",
  "hl.retry": "Thử lại trên hr.blockid.au",
  "hl.private": "Báo cáo đội ngũ ở chế độ riêng tư. Hãy nhờ người tạo báo cáo chia sẻ.",
  "hl.bt.strong": "Đội ngũ mạnh",
  "hl.bt.good": "Đội ngũ tốt",
  "hl.bt.partial": "Đội ngũ trung bình",
  "hl.bt.weak": "Đội ngũ yếu",
  "hl.bt.poor": "Đội ngũ rất yếu",
  "hl.kind.founder": "Nhà sáng lập",
  "hl.kind.cofounder": "Đồng sáng lập",
  "hl.kind.executive": "Quản lý cấp cao",
  "hl.kind.employee": "Thành viên",
  "hl.kind.advisor": "Cố vấn",
  "hl.bf.strong": "Rất phù hợp",
  "hl.bf.good": "Phù hợp tốt",
  "hl.bf.partial": "Phù hợp một phần",
  "hl.bf.weak": "Ít phù hợp",
  "hl.bf.poor": "Không phù hợp",

  "hl.wz.h": "Đội ngũ sáng lập",
  "hl.wz.badge": "Nên có",
  "hl.wz.sub": "Chiếm 30% điểm doanh nghiệp. Thêm ngay bây giờ, hoặc sau này từ báo cáo định giá.",
  "hl.wz.p": "Liệt kê những người đứng sau doanh nghiệp. Chúng tôi kiểm tra thông tin nghề nghiệp công khai của họ, chỉ khi họ đồng ý.",
  "hl.wz.looking": "Đang tìm người trên {h}…",
  "hl.wz.found": "Tìm thấy trên {h}:",
  "hl.wz.add": "Thêm",
  "hl.wz.added": "Đã thêm",
  "hl.wz.addall": "Thêm tất cả",
  "hl.wz.none": "Không tìm thấy tên nào trên {h}. Hãy nhập bên dưới.",
  "hl.wz.people": "{n} người",
  "hl.wz.bad": "Kiểm tra lại đội ngũ sáng lập: {n} ô cần sửa.",

  "hl.co.h": "Đội ngũ",
  "hl.co.sub": "30% điểm doanh nghiệp",
  "hl.co.none": "Những người sáng lập chưa được đánh giá.",
  "hl.co.running": "Đang đánh giá · {p}%",
};
