// Ported verbatim from docs/prototype.html (approved copy).
export const protoEn = {
 "nav.how": "How it works",
 "nav.walk": "Walkthrough",
 "nav.dash": "Cap table",
 "nav.net": "Testnet",
 "nav.next": "Next",
 "nav.back": "Back",
 "cta.primary": "List your business",
 "cta.secondary": "See a sample report",
 "hero.eyebrow": "BlockID Business Passport",
 "hero.h1a": "Know the business",
 "hero.h1b": "before you invest.",
 "hero.pitch": "See how a private business is really doing, in plain words. Get regular updates with a fair value checked by people, proof of the shares you own, and dividends paid straight to your wallet.",
 "hero.legal": "Testnet demo. Not an offer of securities or financial advice.",
 "hv.try": "Try it now — no sign-up",
 "hv.trying": "Opening your demo…",
 "hv.tryNote": "No wallet or password needed. We create a private key in your browser.",
 "hv.card.aria": "Example of an investor's holding: shares owned, stake, fair value, latest update and a dividend paid to the wallet.",
 "hv.card.label": "Your holding",
 "hv.card.example": "Example",
 "hv.card.shares": "Shares you own",
 "hv.card.stake": "Your stake",
 "hv.card.value": "Fair value of your shares",
 "hv.card.checked": "Checked and approved by people",
 "hv.card.update": "Latest update · Quarterly",
 "hv.card.updateTxt": "Sales up 12%. Profit up 4%. New warehouse opened.",
 "hv.card.div": "Dividend paid to your wallet",
 "hv.card.proof": "Your shares are on the public record",
 "hv.prob.eyebrow": "The problem",
 "hv.prob.h2": "Investing in a private business is hard to follow.",
 "hv.prob.p": "Big or small, most investors in private businesses face the same gaps.",
 "hv.prob.1h": "You don't really understand the business",
 "hv.prob.1p": "Reports are long, late or missing. The numbers are hard to read and hard to compare.",
 "hv.prob.2h": "You lose sight of it after you invest",
 "hv.prob.2p": "Sales, profit and new share sales happen without you seeing them clearly.",
 "hv.prob.3h": "You're not sure what you own",
 "hv.prob.3p": "Ownership sits in a spreadsheet or a lawyer's file. Your share can shrink when new shares are issued, and no one tells you.",
 "hv.prob.4h": "Dividends are slow, or never arrive",
 "hv.prob.4p": "Payments depend on paperwork and bank transfers, if they happen at all.",
 "hv.get.eyebrow": "What you get",
 "hv.get.h2": "Everything you need to follow your investment.",
 "hv.get.p": "One place to understand the business, follow it, prove what you own and get paid.",
 "hv.get.1h": "Understand it",
 "hv.get.1p": "A plain-language profile of the business, with every number linked to where it came from.",
 "hv.get.2h": "Follow it",
 "hv.get.2p": "Regular updates, weekly, monthly, quarterly or yearly, with a fair value checked and approved by people.",
 "hv.get.3h": "Own it",
 "hv.get.3p": "Your shares are recorded in an online share register on blockchain. That record is your proof of ownership.",
 "hv.get.4h": "Get paid",
 "hv.get.4p": "Dividends go straight into your wallet, automatically.",
 "hv.get.5h": "Check it",
 "hv.get.5p": "Anyone can check the numbers and the share register for themselves.",
 "hv.inv.eyebrow": "For every investor",
 "hv.inv.h2": "The same clear view, whether you invest A$500 or A$5 million.",
 "hv.inv.all.h": "Every shareholder",
 "hv.inv.all.1": "See your shares, your stake and its fair value in one place.",
 "hv.inv.all.2": "Get the same updates, at the same time, as everyone else.",
 "hv.inv.all.3": "See how new shares would change your stake before they are issued.",
 "hv.inv.all.4": "Receive dividends in your wallet. No forms.",
 "hv.inv.small.h": "Small investors",
 "hv.inv.small.1": "Plain words. No finance degree needed.",
 "hv.inv.small.2": "Try it free, with no sign-up.",
 "hv.inv.small.3": "Proof of ownership you hold yourself, not just a letter.",
 "hv.inv.large.h": "Large investors",
 "hv.inv.large.1": "Regular numbers on sales, profit and value for each holding.",
 "hv.inv.large.2": "Every figure traced to its source and approved by a person.",
 "hv.inv.large.3": "A share register you can check yourself, at any time.",
 "hv.how.h2": "From the business to your wallet, in four steps.",
 "hv.how.p": "Businesses list with us to offer shares with all the information investors need. Here is what happens next.",
 "hv.how.1h": "The business shares its numbers",
 "hv.how.1p": "Its website, sales and key facts.",
 "hv.how.2h": "Independent analysis sets a fair value",
 "hv.how.2p": "Every number is checked, and a person approves the value before anything goes live.",
 "hv.how.3h": "Shares are recorded on blockchain",
 "hv.how.3p": "You hold your shares in your own wallet. The record is public and can't be quietly changed.",
 "hv.how.4h": "You get updates and dividends",
 "hv.how.4p": "Plain-language updates on a set schedule, and dividends paid straight to your wallet.",
 "hv.check.h": "Don't just take our word for it.",
 "hv.check.p": "Every fair value and every share record can be checked by anyone, right in your browser.",
 "hv.check.link": "Check the records",
 "hv.check.tech": "How it's built",
 "chip.1": "Valuation in minutes, every number cited",
 "chip.2": "KYC-gated cap table for verified shareholders",
 "chip.3": "Dividends in mAUD, holders pay no gas",
 "chip.4": "One human approval, proven on 3 chains",
 "hs.1": "Research",
 "hs.2": "Value",
 "hs.3": "Issue",
 "hs.4": "Anchor",
 "ht.sources": "Sources cited",
 "ht.svi": "SVI valuation",
 "ht.range": "Range A$2.4M – A$4.3M · SVI 66.7",
 "ht.token": "Share token",
 "ht.holders": "3,360,000 shares · A$1.00 each",
 "ht.anchored": "Anchored · Hoodi + HashKey",
 "how.eyebrow": "How it works",
 "how.h2": "Agents propose. Humans approve. Chains prove.",
 "how.p": "AI agents read your public site, run at most 3 web searches and draft a cited valuation. They hold no keys. An admin reviews the numbers and gives one issuance approval. Only then does the issuer create the share register on BlockID and sync it to Ethereum Hoodi and HashKey Chain, with the report hash anchored on all three so anyone can check it.",
 "how.cap": "The gold arrow is the only path from AI output to a blockchain: one admin approval. The dashed boundary is the issuer, the only component that holds keys, running on an isolated network.",
 "d.lane1": "AI AGENTS · READ-ONLY · NO KEYS",
 "d.lane2": "ISSUER · ONLY KEY HOLDER · ISOLATED NETWORK",
 "d.n1": "Your website",
 "d.n1s": "public pages",
 "d.n2": "Site intake",
 "d.n2s": "company profile",
 "d.n3": "Competitor search",
 "d.n4": "Market analysis",
 "d.n4s": "cited findings",
 "d.n5": "SVI valuation",
 "d.n5s": "grade + A$ range",
 "d.e1": "reads",
 "d.e2": "names",
 "d.e3": "sources",
 "d.e4": "scores",
 "d.gate": "one admin approval",
 "d.b1": "Issue on BlockID",
 "d.b1s": "register of record · KYC + mint",
 "d.b2": "Sync Ethereum Hoodi",
 "d.b2s": "paused mirror + Merkle root",
 "d.b3": "Sync HashKey Chain",
 "d.b4": "Wallets & cap table",
 "d.b4s": "MetaMask · dividends · /verify",
 "d.f1": "auto",
 "d.f2": "auto",
 "d.f3": "prove",
 "walk.eyebrow": "Walkthrough",
 "walk.h2": "Eight steps from website to wallet",
 "walk.p": "Click through the flow with an example company. Gold steps need a person: an admin approves the valuation, then gives one issuance approval. The sync to Hoodi and HashKey runs automatically.",
 "step.1": "Website",
 "step.2": "AI research",
 "step.3": "Valuation",
 "step.4": "Ticker",
 "step.5": "Shareholders",
 "step.6": "Issue",
 "step.7": "Sync chains",
 "step.8": "Wallet",
 "gate.admin": "Admin approval",
 "s1.h": "Paste your website",
 "s1.p": "We read public pages only: product, team, pricing, press. No login or documents needed to start.",
 "s1.btn": "Start valuation",
 "s1.c1": "What we read",
 "s1.c1p": "Up to 6 public pages, fetched safely, plus at most 3 web searches per valuation. Emails and phone numbers are stripped before any search.",
 "s1.c2": "What you get",
 "s1.c2p": "An SVI grade from A to E, an A$ valuation range and a competitor table, each figure linked to its source.",
 "s1.c3": "Time and limits",
 "s1.c3p": "About 2–4 minutes. 3 valuations per wallet per day on the testnet.",
 "s2.h": "AI agents at work",
 "s2.p": "Each agent reports as it finishes. You can close the tab; the link resumes the job.",
 "s2.replay": "Replay",
 "s2.found": "Collected so far",
 "s2.pages": "pages read",
 "s2.comp": "competitors",
 "s2.src": "sources",
 "s2.note": "Findings that cite a page the agent did not actually fetch are dropped automatically.",
 "log.1": "Read website",
 "log.2": "Extract company profile",
 "log.3": "Find competitors (≤ 3 web searches)",
 "log.4": "Analyse market with sources",
 "log.5": "Score 7 SVI dimensions",
 "log.6": "Write valuation narrative",
 "s3.h": "Valuation report",
 "s3.p": "Scores come from the model and from your numbers. The admin can adjust any AI score before approving.",
 "s3.radar": "SVI profile",
 "s3.build": "How the index is built",
 "s3.buildp": "Score × weight = contribution. The sum is the SVI index.",
 "s3.range": "Valuation range",
 "s3.method": "Method: revenue × cited sector multiple (low · median · high) × SVI factor 1.17.",
 "s3.comp": "Competitors · capital raised (A$M)",
 "s3.approve": "Approve valuation",
 "s3.total": "SVI index · grade B",
 "dim.founder": "Founders",
 "dim.product": "Product",
 "dim.market": "Market",
 "dim.revenue": "Revenue",
 "dim.growth": "Growth",
 "dim.ready": "Readiness",
 "dim.trust": "Trust",
 "s4.h": "Your share ticker",
 "s4.p": "Three letters with a clear link to your company name, in the style of ASX codes. Pick one or type your own.",
 "s4.name": "Token name",
 "s4.rules": "How it was chosen",
 "s4.r1": "Drop \"Pty Ltd\" → HARBOURLINE LOGISTICS",
 "s4.r2": "First letter + next consonants",
 "s4.r3": "Not on the blocklist",
 "s4.r4": "Not used by another token on BlockID Chain",
 "s4.r5": "HAR is taken (Harvest Agri)",
 "s5.h": "Shareholders",
 "s5.p": "Shares are issued at A$1.00 each by default, so the total follows the approved valuation. Enter each holder's wallet and percentage; we convert to whole shares so the total is always exact.",
 "s5.supply": "Total shares",
 "s5.preview": "Ownership preview",
 "s5.kyc": "Every wallet is KYC-registered on-chain before shares are minted, and receives a small BLKD gas allowance.",
 "s5.review": "Review issuance",
 "s5.ok": "Total 100.00% · ready",
 "s5.bad": "Total {p}% · must equal 100%",
 "t.holder": "Holder",
 "t.wallet": "Wallet",
 "t.shares": "Shares",
 "s6.h": "Approve and issue on BlockID Chain",
 "s6.p": "The admin sees every transaction before it is sent. After signing, the issuer service sends them on the zero-gas chain.",
 "s6.net": "Network",
 "s6.token": "Token",
 "s6.txn": "Transactions",
 "s6.signer": "Signer",
 "s6.sign": "Sign approval & issue",
 "s6.reject": "Reject",
 "tx.reg": "Deploy IdentityRegistry",
 "tx.tok": "Deploy HBL share token",
 "tx.div": "Deploy DividendDistributor",
 "tx.kyc": "KYC 5 wallets",
 "tx.gas": "Gas allowance to 5 wallets",
 "tx.mint": "Mint 3,360,000 HBL",
 "tx.val": "Anchor SVI report hash",
 "tx.wait": "waiting for signature",
 "s7.h": "Sync to Ethereum Hoodi and HashKey Chain",
 "s7.p": "Runs automatically after the issuance approval: each chain gets a paused copy of the token and a fingerprint of the whole cap table.",
 "s7.cap": "Any holder can prove their balance against the public root without revealing the full register. The mirror token exists so wallets and Etherscan can display it; the BlockID Chain ledger stays the source of truth.",
 "s7.approve": "Sign & anchor",
 "a.block": "at block 18,204",
 "a.hash": "hash rows",
 "a.anchor": "anchor",
 "a.mirror": "HBL mirror token",
 "a.paused": "same balances · transfers paused",
 "a.mint": "mint same balances, then pause",
 "s8.h": "HBL is live. Add it to your wallet",
 "s8.p": "Use the button, or copy the contract address and import it in MetaMask yourself.",
 "s8.local": "Token contract · BlockID Chain (262626)",
 "s8.hoodi": "Anchored copy · Ethereum Hoodi (560048)",
 "s8.copy": "Copy address",
 "s8.scan": "View on scan.blockid.au",
 "s8.ether": "View on Etherscan",
 "s8.add": "Add to MetaMask",
 "s8.manual": "Add it manually",
 "s8.m1": "Open MetaMask and choose the network: BlockID Chain, Ethereum Hoodi or HashKey Chain testnet.",
 "s8.m2": "Go to Tokens → Import tokens.",
 "s8.m3": "Paste the contract address above. Symbol HBL and decimals 0 fill in automatically.",
 "s8.m4": "Confirm. Your balance shows whole shares.",
 "s8.m5": "On a phone, open this page inside the MetaMask app browser.",
 "s8.net": "Network details",
 "s8.name": "Name",
 "s8.sym": "Currency",
 "s8.dash": "Open dashboard",
 "toast.copied": "Address copied.",
 "toast.nomm": "MetaMask not found in this browser. Use the manual steps below.",
 "toast.added": "Token added to MetaMask.",
 "dash.eyebrow": "After issuance",
 "dash.h2": "Your cap table, always current",
 "dash.p": "Read straight from the chain. Model a new round before you mint, and pay dividends that holders claim without paying gas.",
 "k.shares": "Shares outstanding",
 "k.holders": "Holders",
 "k.kyc": "all KYC-verified",
 "k.price": "Value per share",
 "k.pricesub": "issue price · SVI mid A$3.36M",
 "k.anchor": "Last anchor",
 "m.h": "Model a new round",
 "m.p": "New shares for an incoming investor. Existing holders are diluted pro rata.",
 "m.new": "New shares",
 "m.before": "Before",
 "m.after": "After",
 "m.request": "Request approval",
 "m.investor": "New investor",
 "dv.h": "Plan a dividend",
 "dv.p": "Split pro rata at a record block, published as a Merkle root. Holders claim; the relayer pays their gas.",
 "dv.amt": "Total (mAUD)",
 "dv.root": "Merkle root",
 "dv.deadline": "claim deadline 30 days",
 "dv.request": "Send for approval",
 "fin.h": "See it for yourself in one minute.",
 "fin.p": "Open the demo as an investor, or list your business and give your investors a clear view.",
 "nav.admin": "Admin",
 "ad.eyebrow": "Admin console",
 "ad.h2": "Every tokenised company, one live view",
 "ad.p": "Approve issuer wallets, watch platform value and drill into each company's share mark. Sign in with an admin wallet or the admin account.",
 "ad.signin": "Sign in to admin",
 "ad.m.wallet": "MetaMask",
 "ad.m.pass": "Username",
 "ad.walletp": "Sign a one-time message (SIWE). Only wallets on the admin list can enter.",
 "ad.siwe": "Sign in with MetaMask",
 "ad.user": "Username",
 "ad.pass": "Password",
 "ad.enter": "Sign in",
 "ad.demo": "Demo account: admin / admin. You will be asked to change it after the first sign-in.",
 "ad.signedas": "Signed in as",
 "ad.logout": "Sign out",
 "ad.t.ov": "Overview",
 "ad.t.co": "Company detail",
 "ad.t.wa": "Issuer wallets",
 "ad.pv": "Platform value (marked)",
 "ad.pvnote": "Sum of each company's valuation mark. Steps happen on issuance and on approved SVI revaluations. Simulated values are never included.",
 "ad.grades": "Companies by grade",
 "ad.movers": "Top movers · 30 days",
 "ad.co": "Tokenised companies",
 "ad.clickrow": "Click a row for detail",
 "ad.c.tk": "Ticker",
 "ad.c.name": "Company",
 "ad.c.grade": "Grade",
 "ad.c.val": "Valuation",
 "ad.c.mark": "Mark / share",
 "ad.c.trend": "30d trend",
 "ad.c.hold": "Holders",
 "ad.c.anch": "Anchor",
 "ad.feed": "Activity",
 "ad.simt": "Show simulated growth",
 "ad.l.mark": "Mark (SVI-derived, A$ per share)",
 "ad.l.sim": "Simulated · not a price (P10–P90 band)",
 "ad.l.ev": "Event: issuance, revaluation",
 "ad.aw": "Admin wallet · server keystore · visible to admins only",
 "ad.aw2": "Owner wallet · MetaMask",
 "ad.awnote": "Both hold DEFAULT_ADMIN_ROLE. Grants and revokes below are sent on-chain after you confirm, and appear here once the RoleGranted event is indexed.",
 "ad.iw": "Wallets approved to issue",
 "ad.grant": "Grant role",
 "ad.w.label": "Label",
 "ad.w.status": "Status",
 "ad.w.since": "Since",
 "ad.audit": "Audit log",
 "ad.k.30d": "30d",
 "ad.k.co": "Companies tokenised",
 "ad.k.tok": "Token contracts",
 "ad.k.toksub": "BlockID + Hoodi + HashKey",
 "ad.k.sh": "Shares issued",
 "ad.k.tx": "Transaction value",
 "ad.k.val": "Total valuation",
 "ad.k.avg": "Average valuation",
 "ad.k.median": "median",
 "ad.k.mult": "Avg mark vs A$1",
 "ad.k.anch": "Cap tables anchored",
 "ad.k.anchsub": "all roots match",
 "ad.ev.iss": "issued",
 "ad.ev.rv": "revalued",
 "ad.ev.div": "dividend round",
 "ad.today": "today",
 "ad.ago": "{n}d ago",
 "ad.range": "selected range",
 "ad.cagr": "CAGR since issue",
 "ad.issue1": "issue price A$1.00",
 "ad.simnote": "Simulated with geometric Brownian motion for grade {g}: drift {mu}%/yr, volatility {sg}%/yr, 240 paths, seed {seed}. Illustration only, never used in totals.",
 "ad.marknote": "The mark changes only on issuance and on approved SVI revaluations. Between events it stays flat.",
 "ad.k.issued1": "issued at A$1.00",
 "ad.k.kyc": "all KYC-verified",
 "ad.k.simlive": "Simulated live",
 "ad.k.mark": "Current mark",
 "ad.k.asof": "as of last revaluation",
 "ad.st.active": "Active",
 "ad.st.pending": "Pending grant",
 "ad.st.revoked": "Revoked",
 "ad.confirm": "Confirm revoke",
 "ad.revoke": "Revoke",
 "au.grant": "granted ISSUER_ROLE to",
 "au.revoke": "revoked ISSUER_ROLE from",
 "au.req": "requested ISSUER_ROLE for",
 "ad.bad.addr": "Enter a 0x address with 40 hex characters.",
 "ad.bad.label": "Add a label so others know whose wallet this is.",
 "ad.bad.pass": "Wrong username or password.",
 "ad.bad.wallet": "This wallet is not on the admin list.",
 "ad.live": "Live · updated {s}s ago",
 "foot.deck": "Pitch deck (3 min)",
 "foot.deckFull": "full deck",
 "foot.legal": "Testnet demo. Not an offer of securities or financial advice."
} as const;

export const protoVi: Record<keyof typeof protoEn, string> = {
 "nav.how": "Cách hoạt động",
 "nav.walk": "Từng bước",
 "nav.dash": "Sổ cổ đông",
 "nav.net": "Testnet",
 "nav.next": "Tiếp",
 "nav.back": "Quay lại",
 "cta.primary": "Đăng doanh nghiệp của bạn",
 "cta.secondary": "Xem báo cáo mẫu",
 "hero.eyebrow": "BlockID Business Passport",
 "hero.h1a": "Hiểu rõ doanh nghiệp",
 "hero.h1b": "trước khi bạn đầu tư.",
 "hero.pitch": "Xem một doanh nghiệp tư nhân thực sự đang làm ăn ra sao, bằng lời dễ hiểu. Nhận cập nhật định kỳ kèm giá trị hợp lý do con người kiểm tra, bằng chứng về cổ phần bạn sở hữu, và cổ tức trả thẳng vào ví của bạn.",
 "hero.legal": "Bản demo testnet. Không phải chào bán chứng khoán hay tư vấn tài chính.",
 "hv.try": "Dùng thử ngay — không cần đăng ký",
 "hv.trying": "Đang mở bản demo…",
 "hv.tryNote": "Không cần ví hay mật khẩu. Chúng tôi tạo một khoá riêng ngay trong trình duyệt của bạn.",
 "hv.card.aria": "Ví dụ về khoản nắm giữ của một nhà đầu tư: số cổ phần, tỷ lệ sở hữu, giá trị hợp lý, cập nhật mới nhất và cổ tức đã trả vào ví.",
 "hv.card.label": "Khoản nắm giữ của bạn",
 "hv.card.example": "Ví dụ",
 "hv.card.shares": "Cổ phần bạn sở hữu",
 "hv.card.stake": "Tỷ lệ sở hữu",
 "hv.card.value": "Giá trị hợp lý của cổ phần",
 "hv.card.checked": "Đã được con người kiểm tra và phê duyệt",
 "hv.card.update": "Cập nhật mới nhất · Hằng quý",
 "hv.card.updateTxt": "Doanh thu tăng 12%. Lợi nhuận tăng 4%. Mở thêm một kho hàng mới.",
 "hv.card.div": "Cổ tức đã trả vào ví của bạn",
 "hv.card.proof": "Cổ phần của bạn nằm trong hồ sơ công khai",
 "hv.prob.eyebrow": "Vấn đề",
 "hv.prob.h2": "Đầu tư vào doanh nghiệp tư nhân rất khó theo dõi.",
 "hv.prob.p": "Dù lớn hay nhỏ, hầu hết nhà đầu tư vào doanh nghiệp tư nhân đều gặp những khoảng trống giống nhau.",
 "hv.prob.1h": "Bạn không thật sự hiểu doanh nghiệp",
 "hv.prob.1p": "Báo cáo dài, chậm hoặc không có. Con số khó đọc và khó so sánh.",
 "hv.prob.2h": "Bạn mất dấu doanh nghiệp sau khi đầu tư",
 "hv.prob.2p": "Doanh thu, lợi nhuận và các đợt bán cổ phần mới diễn ra mà bạn không nhìn thấy rõ.",
 "hv.prob.3h": "Bạn không chắc mình sở hữu những gì",
 "hv.prob.3p": "Quyền sở hữu nằm trong một bảng tính hay hồ sơ luật sư. Tỷ lệ của bạn có thể giảm khi phát hành thêm cổ phần mà không ai báo.",
 "hv.prob.4h": "Cổ tức chậm, hoặc không bao giờ đến",
 "hv.prob.4p": "Việc chi trả phụ thuộc vào giấy tờ và chuyển khoản ngân hàng, nếu có.",
 "hv.get.eyebrow": "Bạn nhận được gì",
 "hv.get.h2": "Mọi thứ bạn cần để theo dõi khoản đầu tư.",
 "hv.get.p": "Một nơi để hiểu doanh nghiệp, theo dõi nó, chứng minh bạn sở hữu gì và nhận tiền.",
 "hv.get.1h": "Hiểu rõ",
 "hv.get.1p": "Hồ sơ doanh nghiệp viết bằng lời dễ hiểu, mỗi con số đều dẫn tới nơi nó được lấy.",
 "hv.get.2h": "Theo dõi",
 "hv.get.2p": "Cập nhật định kỳ, hằng tuần, tháng, quý hoặc năm, kèm giá trị hợp lý do con người kiểm tra và phê duyệt.",
 "hv.get.3h": "Sở hữu",
 "hv.get.3p": "Cổ phần của bạn được ghi trong sổ cổ đông trực tuyến trên blockchain. Bản ghi đó là bằng chứng sở hữu của bạn.",
 "hv.get.4h": "Nhận tiền",
 "hv.get.4p": "Cổ tức được chuyển thẳng vào ví của bạn, tự động.",
 "hv.get.5h": "Kiểm tra",
 "hv.get.5p": "Ai cũng có thể tự kiểm tra các con số và sổ cổ đông.",
 "hv.inv.eyebrow": "Cho mọi nhà đầu tư",
 "hv.inv.h2": "Cùng một góc nhìn rõ ràng, dù bạn đầu tư A$500 hay A$5 triệu.",
 "hv.inv.all.h": "Mọi cổ đông",
 "hv.inv.all.1": "Xem cổ phần, tỷ lệ sở hữu và giá trị hợp lý ở cùng một nơi.",
 "hv.inv.all.2": "Nhận cùng một bản cập nhật, cùng lúc với mọi người.",
 "hv.inv.all.3": "Biết cổ phần mới sẽ thay đổi tỷ lệ của bạn ra sao trước khi phát hành.",
 "hv.inv.all.4": "Nhận cổ tức vào ví. Không cần giấy tờ.",
 "hv.inv.small.h": "Nhà đầu tư nhỏ",
 "hv.inv.small.1": "Lời lẽ dễ hiểu. Không cần kiến thức tài chính.",
 "hv.inv.small.2": "Dùng thử miễn phí, không cần đăng ký.",
 "hv.inv.small.3": "Bằng chứng sở hữu do chính bạn giữ, không chỉ là một lá thư.",
 "hv.inv.large.h": "Nhà đầu tư lớn",
 "hv.inv.large.1": "Số liệu định kỳ về doanh thu, lợi nhuận và giá trị của từng khoản nắm giữ.",
 "hv.inv.large.2": "Mỗi con số đều có nguồn và được một người phê duyệt.",
 "hv.inv.large.3": "Sổ cổ đông bạn có thể tự kiểm tra, bất cứ lúc nào.",
 "hv.how.h2": "Từ doanh nghiệp tới ví của bạn, trong bốn bước.",
 "hv.how.p": "Doanh nghiệp đăng ký với chúng tôi để chào bán cổ phần kèm đầy đủ thông tin nhà đầu tư cần. Đây là những gì diễn ra tiếp theo.",
 "hv.how.1h": "Doanh nghiệp chia sẻ số liệu",
 "hv.how.1p": "Website, doanh thu và các thông tin chính.",
 "hv.how.2h": "Phân tích độc lập đưa ra giá trị hợp lý",
 "hv.how.2p": "Mọi con số đều được kiểm tra, và một người phê duyệt giá trị trước khi đưa lên.",
 "hv.how.3h": "Cổ phần được ghi trên blockchain",
 "hv.how.3p": "Bạn giữ cổ phần trong ví của chính mình. Bản ghi là công khai và không thể bị sửa lén.",
 "hv.how.4h": "Bạn nhận cập nhật và cổ tức",
 "hv.how.4p": "Cập nhật bằng lời dễ hiểu theo lịch cố định, và cổ tức trả thẳng vào ví của bạn.",
 "hv.check.h": "Đừng chỉ tin lời chúng tôi.",
 "hv.check.p": "Mọi giá trị hợp lý và mọi bản ghi cổ phần đều có thể được bất kỳ ai kiểm tra, ngay trong trình duyệt.",
 "hv.check.link": "Kiểm tra hồ sơ",
 "hv.check.tech": "Cách chúng tôi xây dựng",
 "chip.1": "Định giá trong vài phút, mọi con số có dẫn nguồn",
 "chip.2": "Sổ cổ đông có KYC, chỉ dành cho cổ đông đã xác minh",
 "chip.3": "Cổ tức bằng mAUD, cổ đông không tốn phí gas",
 "chip.4": "Một lần người duyệt, chứng minh trên 3 chuỗi",
 "hs.1": "Nghiên cứu",
 "hs.2": "Định giá",
 "hs.3": "Phát hành",
 "hs.4": "Neo",
 "ht.sources": "Nguồn trích dẫn",
 "ht.svi": "Định giá SVI",
 "ht.range": "Khoảng A$2,4 tr – A$4,3 tr · SVI 66,7",
 "ht.token": "Token cổ phần",
 "ht.holders": "3.360.000 cổ phần · A$1,00 mỗi cổ phần",
 "ht.anchored": "Đã neo · Hoodi + HashKey",
 "how.eyebrow": "Cách hoạt động",
 "how.h2": "Agent đề xuất. Con người phê duyệt. Blockchain chứng minh.",
 "how.p": "AI agent đọc website công khai của bạn, tìm kiếm web tối đa 3 lần và soạn bản định giá có dẫn nguồn. Agent không giữ khoá. Admin xem xét các con số và duyệt phát hành một lần duy nhất. Chỉ khi đó issuer mới tạo sổ cổ đông trên BlockID và đồng bộ sang Ethereum Hoodi và HashKey Chain, với hash của báo cáo được neo trên cả ba chuỗi để ai cũng kiểm tra được.",
 "how.cap": "Mũi tên vàng là đường duy nhất từ kết quả AI tới blockchain: một lần admin duyệt. Khung nét đứt là issuer, thành phần duy nhất giữ khoá, chạy trong mạng cô lập.",
 "d.lane1": "AI AGENT · CHỈ ĐỌC · KHÔNG GIỮ KEY",
 "d.lane2": "ISSUER · BÊN DUY NHẤT GIỮ KHOÁ · MẠNG CÔ LẬP",
 "d.n1": "Website của bạn",
 "d.n1s": "trang công khai",
 "d.n2": "Đọc website",
 "d.n2s": "hồ sơ công ty",
 "d.n3": "Tìm đối thủ",
 "d.n4": "Phân tích thị trường",
 "d.n4s": "có dẫn nguồn",
 "d.n5": "Định giá SVI",
 "d.n5s": "hạng + khoảng A$",
 "d.e1": "đọc",
 "d.e2": "tên",
 "d.e3": "nguồn",
 "d.e4": "điểm",
 "d.gate": "một lần admin duyệt",
 "d.b1": "Phát hành trên BlockID",
 "d.b1s": "sổ gốc · KYC + mint",
 "d.b2": "Đồng bộ Ethereum Hoodi",
 "d.b2s": "bản sao khoá + Merkle root",
 "d.b3": "Đồng bộ HashKey Chain",
 "d.b4": "Ví & sổ cổ đông",
 "d.b4s": "MetaMask · cổ tức · /verify",
 "d.f1": "tự động",
 "d.f2": "tự động",
 "d.f3": "chứng minh",
 "walk.eyebrow": "Từng bước",
 "walk.h2": "Tám bước từ website tới ví",
 "walk.p": "Bấm qua luồng với một công ty ví dụ. Các bước màu vàng cần người duyệt: admin duyệt định giá, rồi duyệt phát hành một lần. Việc đồng bộ sang Hoodi và HashKey chạy tự động.",
 "step.1": "Website",
 "step.2": "AI nghiên cứu",
 "step.3": "Định giá",
 "step.4": "Mã cổ phần",
 "step.5": "Cổ đông",
 "step.6": "Phát hành",
 "step.7": "Đồng bộ chuỗi",
 "step.8": "Vào ví",
 "gate.admin": "Admin duyệt",
 "s1.h": "Dán website của bạn",
 "s1.p": "Chúng tôi chỉ đọc trang công khai: sản phẩm, đội ngũ, bảng giá, báo chí. Không cần đăng nhập hay tài liệu để bắt đầu.",
 "s1.btn": "Bắt đầu định giá",
 "s1.c1": "Đọc những gì",
 "s1.c1p": "Tối đa 6 trang công khai, tải an toàn, cộng tối đa 3 lượt tìm kiếm web cho mỗi lần định giá. Email và số điện thoại bị loại trước mọi truy vấn tìm kiếm.",
 "s1.c2": "Bạn nhận được",
 "s1.c2p": "Hạng SVI từ A tới E, khoảng định giá A$ và bảng đối thủ, mỗi con số đều dẫn nguồn.",
 "s1.c3": "Thời gian và giới hạn",
 "s1.c3p": "Khoảng 2–4 phút. Mỗi ví 3 lượt định giá mỗi ngày trên testnet.",
 "s2.h": "AI agent đang làm việc",
 "s2.p": "Mỗi agent báo kết quả khi xong. Bạn có thể đóng tab; link này mở lại được tác vụ.",
 "s2.replay": "Chạy lại",
 "s2.found": "Đã thu thập",
 "s2.pages": "trang đã đọc",
 "s2.comp": "đối thủ",
 "s2.src": "nguồn",
 "s2.note": "Nhận định nào dẫn tới trang mà agent chưa thực sự tải sẽ bị loại tự động.",
 "log.1": "Đọc website",
 "log.2": "Trích hồ sơ công ty",
 "log.3": "Tìm đối thủ (≤ 3 lượt tìm kiếm web)",
 "log.4": "Phân tích thị trường có nguồn",
 "log.5": "Chấm 7 tiêu chí SVI",
 "log.6": "Viết nhận định định giá",
 "s3.h": "Báo cáo định giá",
 "s3.p": "Điểm đến từ mô hình và từ số liệu của bạn. Admin có thể chỉnh bất kỳ điểm nào do AI chấm trước khi duyệt.",
 "s3.radar": "Hồ sơ SVI",
 "s3.build": "Chỉ số được tính thế nào",
 "s3.buildp": "Điểm × trọng số = đóng góp. Tổng là chỉ số SVI.",
 "s3.range": "Khoảng định giá",
 "s3.method": "Phương pháp: doanh thu × hệ số ngành có dẫn nguồn (thấp · trung vị · cao) × hệ số SVI 1,17.",
 "s3.comp": "Đối thủ · vốn đã gọi (triệu A$)",
 "s3.approve": "Duyệt định giá",
 "s3.total": "Chỉ số SVI · hạng B",
 "dim.founder": "Sáng lập",
 "dim.product": "Sản phẩm",
 "dim.market": "Thị trường",
 "dim.revenue": "Doanh thu",
 "dim.growth": "Tăng trưởng",
 "dim.ready": "Sẵn sàng",
 "dim.trust": "Tin cậy",
 "s4.h": "Mã cổ phần của bạn",
 "s4.p": "Ba chữ cái gắn rõ với tên công ty, theo kiểu mã ASX. Chọn một mã hoặc tự nhập.",
 "s4.name": "Tên token",
 "s4.rules": "Cách chọn mã",
 "s4.r1": "Bỏ \"Pty Ltd\" → HARBOURLINE LOGISTICS",
 "s4.r2": "Chữ đầu + các phụ âm tiếp theo",
 "s4.r3": "Không nằm trong danh sách cấm",
 "s4.r4": "Chưa có token nào dùng trên BlockID Chain",
 "s4.r5": "HAR đã có người dùng (Harvest Agri)",
 "s5.h": "Cổ đông",
 "s5.p": "Mặc định mỗi cổ phần phát hành giá A$1,00, nên tổng số cổ phần bằng mức định giá đã duyệt. Nhập ví và tỷ lệ của từng cổ đông; hệ thống đổi sang số cổ phần nguyên để tổng luôn chính xác.",
 "s5.supply": "Tổng cổ phần",
 "s5.preview": "Xem trước sở hữu",
 "s5.kyc": "Mỗi ví được đăng ký KYC on-chain trước khi mint, và được cấp một ít BLKD làm phí gas.",
 "s5.review": "Xem lại phát hành",
 "s5.ok": "Tổng 100,00% · sẵn sàng",
 "s5.bad": "Tổng {p}% · phải bằng 100%",
 "t.holder": "Cổ đông",
 "t.wallet": "Ví",
 "t.shares": "Cổ phần",
 "s6.h": "Duyệt và phát hành trên BlockID Chain",
 "s6.p": "Admin thấy từng giao dịch trước khi gửi. Sau khi ký, issuer service gửi chúng lên chain không phí gas.",
 "s6.net": "Mạng",
 "s6.token": "Token",
 "s6.txn": "Giao dịch",
 "s6.signer": "Người ký",
 "s6.sign": "Ký duyệt & phát hành",
 "s6.reject": "Từ chối",
 "tx.reg": "Deploy IdentityRegistry",
 "tx.tok": "Deploy token cổ phần HBL",
 "tx.div": "Deploy DividendDistributor",
 "tx.kyc": "KYC 5 ví",
 "tx.gas": "Cấp phí gas cho 5 ví",
 "tx.mint": "Mint 3.360.000 HBL",
 "tx.val": "Neo hash báo cáo SVI",
 "tx.wait": "chờ ký duyệt",
 "s7.h": "Đồng bộ sang Ethereum Hoodi và HashKey Chain",
 "s7.p": "Chạy tự động sau khi duyệt phát hành: mỗi chuỗi nhận một bản sao token bị khoá và dấu vân tay của toàn bộ sổ cổ đông.",
 "s7.cap": "Mỗi cổ đông có thể chứng minh số dư của mình với root công khai mà không lộ toàn bộ sổ. Token bản sao giúp ví và Etherscan hiển thị được; sổ trên BlockID Chain vẫn là nguồn gốc.",
 "s7.approve": "Ký & neo",
 "a.block": "tại block 18.204",
 "a.hash": "băm từng dòng",
 "a.anchor": "neo",
 "a.mirror": "Token HBL bản sao",
 "a.paused": "cùng số dư · khoá chuyển nhượng",
 "a.mint": "mint cùng số dư, rồi khoá",
 "s8.h": "HBL đã phát hành. Thêm vào ví của bạn",
 "s8.p": "Bấm nút, hoặc sao chép contract address và tự nhập vào MetaMask.",
 "s8.local": "Contract token · BlockID Chain (262626)",
 "s8.hoodi": "Bản neo · Ethereum Hoodi (560048)",
 "s8.copy": "Sao chép địa chỉ",
 "s8.scan": "Xem trên scan.blockid.au",
 "s8.ether": "Xem trên Etherscan",
 "s8.add": "Thêm vào MetaMask",
 "s8.manual": "Thêm thủ công",
 "s8.m1": "Mở MetaMask và chọn mạng: BlockID Chain, Ethereum Hoodi hoặc HashKey Chain testnet.",
 "s8.m2": "Vào Tokens → Import tokens.",
 "s8.m3": "Dán contract address ở trên. Symbol HBL và decimals 0 tự điền.",
 "s8.m4": "Xác nhận. Số dư hiển thị số cổ phần nguyên.",
 "s8.m5": "Trên điện thoại, mở trang này trong trình duyệt của app MetaMask.",
 "s8.net": "Thông số mạng",
 "s8.name": "Tên",
 "s8.sym": "Đơn vị",
 "s8.dash": "Mở dashboard",
 "toast.copied": "Đã sao chép địa chỉ.",
 "toast.nomm": "Không tìm thấy MetaMask trong trình duyệt này. Làm theo các bước thủ công bên dưới.",
 "toast.added": "Đã thêm token vào MetaMask.",
 "dash.eyebrow": "Sau khi phát hành",
 "dash.h2": "Sổ cổ đông luôn cập nhật",
 "dash.p": "Đọc trực tiếp từ chain. Mô phỏng vòng gọi vốn trước khi mint, và chia cổ tức mà cổ đông nhận không tốn phí gas.",
 "k.shares": "Cổ phần lưu hành",
 "k.holders": "Cổ đông",
 "k.kyc": "đều đã KYC",
 "k.price": "Giá trị mỗi cổ phần",
 "k.pricesub": "giá phát hành · SVI giữa A$3,36 tr",
 "k.anchor": "Lần neo gần nhất",
 "m.h": "Mô phỏng vòng mới",
 "m.p": "Cổ phần mới cho nhà đầu tư. Cổ đông hiện hữu bị pha loãng theo tỷ lệ.",
 "m.new": "Cổ phần mới",
 "m.before": "Trước",
 "m.after": "Sau",
 "m.request": "Gửi admin duyệt",
 "m.investor": "Nhà đầu tư mới",
 "dv.h": "Lập kế hoạch cổ tức",
 "dv.p": "Chia theo tỷ lệ tại một block chốt, công bố dưới dạng Merkle root. Cổ đông tự nhận; relayer trả phí gas.",
 "dv.amt": "Tổng (mAUD)",
 "dv.root": "Merkle root",
 "dv.deadline": "hạn nhận 30 ngày",
 "dv.request": "Gửi duyệt",
 "fin.h": "Tự mình xem thử chỉ trong một phút.",
 "fin.p": "Mở bản demo với vai trò nhà đầu tư, hoặc đăng doanh nghiệp của bạn để nhà đầu tư nhìn thấy rõ ràng.",
 "nav.admin": "Admin",
 "ad.eyebrow": "Khu vực admin",
 "ad.h2": "Mọi doanh nghiệp đã token hoá trong một màn hình",
 "ad.p": "Duyệt ví phát hành, theo dõi tổng giá trị nền tảng và xem chi tiết giá cổ phần của từng doanh nghiệp. Đăng nhập bằng ví admin hoặc tài khoản admin.",
 "ad.signin": "Đăng nhập admin",
 "ad.m.wallet": "MetaMask",
 "ad.m.pass": "Tài khoản",
 "ad.walletp": "Ký một thông điệp dùng một lần (SIWE). Chỉ ví trong danh sách admin mới vào được.",
 "ad.siwe": "Đăng nhập bằng MetaMask",
 "ad.user": "Tên đăng nhập",
 "ad.pass": "Mật khẩu",
 "ad.enter": "Đăng nhập",
 "ad.demo": "Tài khoản demo: admin / admin. Bạn sẽ được yêu cầu đổi mật khẩu sau lần đăng nhập đầu.",
 "ad.signedas": "Đang đăng nhập",
 "ad.logout": "Đăng xuất",
 "ad.t.ov": "Tổng quan",
 "ad.t.co": "Chi tiết doanh nghiệp",
 "ad.t.wa": "Ví phát hành",
 "ad.pv": "Tổng giá trị nền tảng (theo định giá)",
 "ad.pvnote": "Tổng giá trị định giá của các doanh nghiệp. Chỉ thay đổi khi phát hành và khi định giá lại SVI được duyệt. Không bao gồm số liệu giả lập.",
 "ad.grades": "Doanh nghiệp theo hạng",
 "ad.movers": "Biến động mạnh · 30 ngày",
 "ad.co": "Doanh nghiệp đã token hoá",
 "ad.clickrow": "Bấm vào dòng để xem chi tiết",
 "ad.c.tk": "Mã",
 "ad.c.name": "Doanh nghiệp",
 "ad.c.grade": "Hạng",
 "ad.c.val": "Định giá",
 "ad.c.mark": "Giá / cổ phần",
 "ad.c.trend": "Xu hướng 30 ngày",
 "ad.c.hold": "Cổ đông",
 "ad.c.anch": "Neo",
 "ad.feed": "Hoạt động",
 "ad.simt": "Hiện tăng trưởng giả lập",
 "ad.l.mark": "Giá định giá (theo SVI, A$ mỗi cổ phần)",
 "ad.l.sim": "Giả lập · không phải giá (dải P10–P90)",
 "ad.l.ev": "Sự kiện: phát hành, định giá lại",
 "ad.aw": "Ví admin · keystore trên server · chỉ admin thấy",
 "ad.aw2": "Ví chủ sở hữu · MetaMask",
 "ad.awnote": "Cả hai giữ DEFAULT_ADMIN_ROLE. Cấp và thu hồi quyền bên dưới được gửi on-chain sau khi bạn xác nhận, và hiện ở đây khi sự kiện RoleGranted được index.",
 "ad.iw": "Ví được quyền phát hành",
 "ad.grant": "Cấp quyền",
 "ad.w.label": "Nhãn",
 "ad.w.status": "Trạng thái",
 "ad.w.since": "Từ ngày",
 "ad.audit": "Nhật ký kiểm toán",
 "ad.k.30d": "30 ngày",
 "ad.k.co": "Doanh nghiệp token hoá",
 "ad.k.tok": "Hợp đồng token",
 "ad.k.toksub": "BlockID + Hoodi + HashKey",
 "ad.k.sh": "Cổ phần đã phát hành",
 "ad.k.tx": "Giá trị giao dịch",
 "ad.k.val": "Tổng định giá",
 "ad.k.avg": "Định giá trung bình",
 "ad.k.median": "trung vị",
 "ad.k.mult": "Giá TB so với A$1",
 "ad.k.anch": "Sổ cổ đông đã neo",
 "ad.k.anchsub": "mọi root đều khớp",
 "ad.ev.iss": "phát hành",
 "ad.ev.rv": "định giá lại",
 "ad.ev.div": "vòng cổ tức",
 "ad.today": "hôm nay",
 "ad.ago": "{n} ngày trước",
 "ad.range": "khoảng đã chọn",
 "ad.cagr": "tăng trưởng kép từ khi phát hành",
 "ad.issue1": "giá phát hành A$1,00",
 "ad.simnote": "Giả lập bằng chuyển động Brown hình học cho hạng {g}: xu hướng {mu}%/năm, biến động {sg}%/năm, 240 kịch bản, seed {seed}. Chỉ để minh hoạ, không cộng vào tổng.",
 "ad.marknote": "Giá chỉ đổi khi phát hành và khi định giá lại SVI được duyệt. Giữa các sự kiện, giá đứng yên.",
 "ad.k.issued1": "phát hành giá A$1,00",
 "ad.k.kyc": "đều đã KYC",
 "ad.k.simlive": "Giả lập trực tiếp",
 "ad.k.mark": "Giá hiện tại",
 "ad.k.asof": "theo lần định giá gần nhất",
 "ad.st.active": "Đang hoạt động",
 "ad.st.pending": "Chờ cấp quyền",
 "ad.st.revoked": "Đã thu hồi",
 "ad.confirm": "Xác nhận thu hồi",
 "ad.revoke": "Thu hồi",
 "au.grant": "cấp ISSUER_ROLE cho",
 "au.revoke": "thu hồi ISSUER_ROLE của",
 "au.req": "yêu cầu ISSUER_ROLE cho",
 "ad.bad.addr": "Nhập địa chỉ 0x gồm 40 ký tự hex.",
 "ad.bad.label": "Thêm nhãn để mọi người biết ví này của ai.",
 "ad.bad.pass": "Sai tên đăng nhập hoặc mật khẩu.",
 "ad.bad.wallet": "Ví này không có trong danh sách admin.",
 "ad.live": "Trực tiếp · cập nhật {s} giây trước",
 "foot.deck": "Slide thuyết trình (3 phút)",
 "foot.deckFull": "bản đầy đủ",
 "foot.legal": "Bản demo testnet. Không phải chào bán chứng khoán hay tư vấn tài chính."
};
