/**
 * Evaluation + valuation v5 strings (report tabs, founder inputs, uploads, finalise & pricing, admin price queue).
 * Plain words per docs/FACTS.md: "Business score" (never SVI / AI in public copy). VI must cover every EN key.
 */
const F = {
  revenue_ttm_aud: ["Revenue, last 12 months", "All income from sales in the last 12 months. The starting point for every revenue-based value.", "Doanh thu 12 tháng gần nhất", "Toàn bộ doanh thu bán hàng 12 tháng qua. Là điểm khởi đầu của mọi cách định giá theo doanh thu."],
  revenue_model: ["How you make money", "Subscription, marketplace, services… decides which benchmarks we compare you with.", "Cách bạn kiếm tiền", "Thuê bao, sàn giao dịch, dịch vụ… quyết định bạn được so với chuẩn nào."],
  mrr_aud: ["Monthly recurring revenue (MRR)", "Recurring revenue this month. Early growth is judged month on month.", "Doanh thu định kỳ hàng tháng (MRR)", "Doanh thu định kỳ tháng này. Giai đoạn đầu, tăng trưởng được đánh giá theo từng tháng."],
  revenue_prev_ttm_aud: ["Revenue, the 12 months before", "Lets us compute year-on-year growth from two real numbers.", "Doanh thu 12 tháng trước đó", "Giúp tính tăng trưởng theo năm từ hai con số thật."],
  arr_aud: ["Annual recurring revenue (ARR)", "Recurring only: one-off and set-up fees are not ARR.", "Doanh thu định kỳ năm (ARR)", "Chỉ tính doanh thu định kỳ: phí một lần và phí cài đặt không phải ARR."],
  mrr_6m_ago_aud: ["MRR 6 months ago", "Gives your monthly growth rate (CMGR).", "MRR 6 tháng trước", "Cho biết tốc độ tăng trưởng hàng tháng (CMGR)."],
  mrr_12m_ago_aud: ["MRR 12 months ago", "Gives your growth over a full year.", "MRR 12 tháng trước", "Cho biết mức tăng trưởng trọn một năm."],
  gmv_ttm_aud: ["Gross merchandise value, 12 months", "For marketplaces: shown beside revenue, never used as revenue.", "Tổng giá trị giao dịch (GMV) 12 tháng", "Với sàn giao dịch: hiển thị cạnh doanh thu, không bao giờ tính là doanh thu."],
  take_rate_pct: ["Take rate", "Your share of each transaction (net revenue ÷ GMV).", "Tỷ lệ phí thu", "Phần bạn giữ lại trên mỗi giao dịch (doanh thu thuần ÷ GMV)."],
  gross_margin_pct: ["Gross margin", "Revenue minus direct costs, as a share of revenue. Drives the revenue multiple.", "Biên lợi nhuận gộp", "Doanh thu trừ chi phí trực tiếp, tính theo % doanh thu. Ảnh hưởng hệ số nhân doanh thu."],
  waitlist: ["People on the waitlist", "Before revenue, demand signals stand in for sales.", "Số người trong danh sách chờ", "Trước khi có doanh thu, tín hiệu nhu cầu thay cho doanh số."],
  pilots_paid: ["Paid pilots", "A customer paying to try it is strong early proof.", "Thử nghiệm có trả phí", "Khách hàng trả tiền để dùng thử là bằng chứng sớm rất mạnh."],
  lois: ["Letters of intent", "Signed intent to buy. Counts less than a paid pilot.", "Thư ý định mua", "Cam kết mua có chữ ký. Tính thấp hơn thử nghiệm có trả phí."],
  paying_customers: ["Paying customers", "How many customers pay you today.", "Khách hàng trả tiền", "Số khách hàng đang trả tiền cho bạn hôm nay."],
  active_users_monthly: ["Monthly active users", "For consumer products, users stand in for customers.", "Người dùng hoạt động hàng tháng", "Với sản phẩm tiêu dùng, người dùng thay cho khách hàng."],
  paying_customers_12m_ago: ["Paying customers 12 months ago", "Shows customer growth and logo churn.", "Khách hàng trả tiền 12 tháng trước", "Cho thấy tăng trưởng khách hàng và tỷ lệ rời bỏ."],
  active_users_daily: ["Daily active users", "Daily ÷ monthly users shows how sticky the product is.", "Người dùng hoạt động hàng ngày", "Tỷ lệ ngày ÷ tháng cho thấy sản phẩm được dùng thường xuyên đến đâu."],
  contracted_backlog_aud: ["Signed but not yet billed", "Contracted revenue still to come: a forward signal.", "Hợp đồng đã ký chưa xuất hoá đơn", "Doanh thu đã ký hợp đồng nhưng chưa ghi nhận: tín hiệu tương lai."],
  qualified_pipeline_aud: ["Qualified sales pipeline", "Counted at most as a medium signal unless documented.", "Cơ hội bán hàng đã sàng lọc", "Chỉ được tính ở mức trung bình nếu không có tài liệu."],
  top_customer_share_pct: ["Largest customer's share of revenue", "Above 20% is a risk; above 50% caps the customer score.", "Tỷ trọng doanh thu của khách lớn nhất", "Trên 20% là rủi ro; trên 50% giới hạn điểm khách hàng."],
  public_logos: ["Customers we may name", "Comma-separated. We check them against your website.", "Khách hàng được phép nêu tên", "Cách nhau bằng dấu phẩy. Chúng tôi đối chiếu với website của bạn."],
  logo_churn_monthly_pct: ["Customers lost per month", "Monthly logo churn. Lower is better.", "Tỷ lệ khách rời bỏ mỗi tháng", "Tỷ lệ khách hàng rời đi hàng tháng. Càng thấp càng tốt."],
  grr_pct: ["Gross revenue retention (GRR)", "Revenue kept from existing customers, before upsell. Max 100%.", "Giữ chân doanh thu gộp (GRR)", "Doanh thu giữ lại từ khách hiện có, chưa tính bán thêm. Tối đa 100%."],
  nrr_pct: ["Net revenue retention (NRR)", "Revenue kept plus upsell from last year's customers. Above 100% means they spend more.", "Giữ chân doanh thu ròng (NRR)", "Doanh thu giữ lại cộng bán thêm từ khách năm trước. Trên 100% nghĩa là họ chi nhiều hơn."],
  m3_retention_pct: ["Still active after 3 months", "Share of a starting group still using the product at month 3.", "Còn hoạt động sau 3 tháng", "Tỷ lệ một nhóm người dùng còn dùng sản phẩm ở tháng thứ 3."],
  m12_retention_pct: ["Still active after 12 months", "Share of a starting group still using the product at month 12.", "Còn hoạt động sau 12 tháng", "Tỷ lệ một nhóm người dùng còn dùng sản phẩm ở tháng thứ 12."],
  nps: ["Net promoter score (NPS)", "From −100 to 100. Counts with review ratings.", "Chỉ số NPS", "Từ −100 đến 100. Tính cùng điểm đánh giá."],
  raised_to_date_aud: ["Raised to date", "Total equity and convertible funding so far.", "Đã gọi vốn đến nay", "Tổng vốn cổ phần và vốn chuyển đổi đến nay."],
  cash_aud: ["Cash in the bank", "With the monthly burn, gives your runway.", "Tiền mặt hiện có", "Cùng mức đốt tiền hàng tháng, cho biết bạn trụ được bao lâu."],
  burn_monthly_aud: ["Net burn per month", "Cash out minus cash in, per month.", "Mức đốt tiền ròng mỗi tháng", "Tiền chi ra trừ tiền thu vào, mỗi tháng."],
  net_new_arr_12m_aud: ["New ARR added, last 12 months", "Burn ÷ new ARR is the burn multiple (lower is better).", "ARR tăng thêm 12 tháng qua", "Mức đốt tiền ÷ ARR mới là hệ số đốt tiền (càng thấp càng tốt)."],
  cac_aud: ["Cost to win a customer (CAC)", "Sales and marketing spend per new customer.", "Chi phí có một khách hàng (CAC)", "Chi phí bán hàng và marketing cho mỗi khách mới."],
  arpa_monthly_aud: ["Revenue per customer per month", "With CAC gives the payback period.", "Doanh thu mỗi khách mỗi tháng", "Cùng CAC cho biết thời gian hoàn vốn."],
  employees: ["Employees", "Shown, not scored.", "Số nhân viên", "Chỉ hiển thị, không tính điểm."],
  target_customer: ["Who you sell to", "One line. We size the market bottom-up from it.", "Bạn bán cho ai", "Một dòng. Chúng tôi tính quy mô thị trường từ dưới lên dựa trên đó."],
  target_customer_count: ["How many such customers exist", "In the places you sell. A source link makes it stronger.", "Có bao nhiêu khách hàng như vậy", "Tại nơi bạn bán hàng. Có link nguồn sẽ đáng tin hơn."],
  target_count_source_url: ["Source for that count", "e.g. ABS, an industry body or a government register.", "Nguồn của con số đó", "Ví dụ: Cục Thống kê, hiệp hội ngành hoặc cơ quan đăng ký nhà nước."],
  annual_price_aud: ["Average price per customer per year", "Customers × price = the market you can serve (SAM).", "Giá trung bình mỗi khách mỗi năm", "Số khách × giá = thị trường bạn phục vụ được (SAM)."],
  geographies: ["Where you sell", "Comma-separated countries or states.", "Nơi bạn bán hàng", "Các quốc gia hoặc bang, cách nhau bằng dấu phẩy."],
  patents: ["Patents (number + office)", "Registry numbers can be verified (level 3).", "Bằng sáng chế (số + cơ quan)", "Số đăng ký có thể được xác minh (mức 3)."],
  trademarks: ["Registered trade marks", "Numbers can be checked with IP Australia.", "Nhãn hiệu đã đăng ký", "Có thể kiểm tra số hiệu với IP Australia."],
  licences: ["Licences (type + number)", "e.g. AFSL, ACL, TGA — a verifiable licence is a moat.", "Giấy phép (loại + số)", "Ví dụ AFSL, ACL, TGA — giấy phép kiểm chứng được là lợi thế cạnh tranh."],
  integrations_count: ["Integrations with other tools", "More integrations make switching away harder.", "Số tích hợp với công cụ khác", "Càng nhiều tích hợp, khách càng khó chuyển đi."],
  exclusive_contracts: ["Exclusive contracts", "Exclusive partners or supply deals.", "Hợp đồng độc quyền", "Đối tác hoặc thoả thuận cung ứng độc quyền."],
  moat_note: ["Why others can't copy you (optional)", "Up to 500 characters. Shown as self-reported.", "Vì sao đối thủ khó sao chép (không bắt buộc)", "Tối đa 500 ký tự. Hiển thị là tự khai."],
  last_round_type: ["Last funding round", "A round in the last 30 months decides your stage first.", "Vòng gọi vốn gần nhất", "Vòng gọi vốn trong 30 tháng gần đây được ưu tiên khi xác định giai đoạn."],
  last_round_date: ["Month of that round", "Rounds older than 30 months are not used for the stage.", "Tháng của vòng đó", "Vòng cũ hơn 30 tháng không dùng để xác định giai đoạn."],
  last_round_post_money_aud: ["Valuation after that round", "Your own last price is the strongest anchor when fresh.", "Định giá sau vòng đó", "Giá của chính bạn là mốc mạnh nhất nếu còn mới."],
  lead_investor: ["Lead investor", "Named investors can be checked against public sources.", "Nhà đầu tư dẫn dắt", "Tên nhà đầu tư có thể được đối chiếu với nguồn công khai."],
} as const;
type FK = keyof typeof F;
const fEn = Object.fromEntries(Object.entries(F).flatMap(([k, v]) => [["v5.f." + k, v[0]], ["v5.f." + k + ".why", v[1]]])) as Record<`v5.f.${FK}` | `v5.f.${FK}.why`, string>;
const fVi = Object.fromEntries(Object.entries(F).flatMap(([k, v]) => [["v5.f." + k, v[2]], ["v5.f." + k + ".why", v[3]]])) as Record<`v5.f.${FK}` | `v5.f.${FK}.why`, string>;

export const v5En = {
  ...fEn,
  "v5.legal": "Indicative value, not a formal valuation or financial advice. Testnet demo. Not an offer of securities.",
  "v5.tabs": "Report sections",
  "v5.tab.overview": "Overview", "v5.tab.team": "Team", "v5.tab.traction": "Traction", "v5.tab.market": "Market", "v5.tab.moat": "Moat",
  "v5.tab.retention": "Retention", "v5.tab.valuation": "Valuation", "v5.tab.evidence": "Evidence", "v5.tab.finalise": "Finalise & price",
  "v5.seehow": "See how", "v5.seehow.score": "See how this score is worked out", "v5.astable": "Show as a table", "v5.nodata": "Not enough data yet.",
  "v5.grade": "Grade", "v5.pts": "points", "v5.eg": "e.g. {x}",
  "v5.u.months": "{n} months",
  "v5.stage": "Stage", "v5.stage.idea": "Idea", "v5.stage.pre-seed": "Pre-seed", "v5.stage.seed": "Seed", "v5.stage.series-a": "Series A", "v5.stage.growth": "Growth (Series B+)",
  "v5.stage.established": "Established", "v5.stage.profitable-sme": "Profitable business", "v5.stage.listed": "Listed",
  "v5.dim.founder_quality": "Team", "v5.dim.traction": "Traction", "v5.dim.market": "Market", "v5.dim.moat": "Moat", "v5.dim.retention": "Retention",
  "v5.dim.efficiency": "Capital efficiency", "v5.dim.product_strength": "Product", "v5.dim.investment_readiness": "Investment readiness", "v5.dim.trust_verification": "Verification",
  "v5.lv.h": "How well each figure is checked", "v5.lv.p": "Every figure carries a level. Checked figures move the score more.",
  "v5.lv.0": "Missing", "v5.lv.1": "Self-reported", "v5.lv.2": "Document-backed", "v5.lv.3": "Publicly corroborated", "v5.lv.4": "Connected",
  "v5.lv.0.d": "No data: left out, the dimension is capped.", "v5.lv.1.d": "Typed by the founder or only on the company's own site: keeps 60% of its effect.",
  "v5.lv.2.d": "Matches an uploaded document or CSV: keeps 80%.", "v5.lv.3.d": "Found in an independent source or an approved update: keeps 90%.", "v5.lv.4.d": "From a connected system (Stripe, Xero, bank): full effect.",
  "v5.lv.shrink": "A figure's effect shrinks toward the stage average by how well it is checked: self-reported 60%, document 80%, public 90%, connected 100%.",
  "v5.conf": "Confidence", "v5.conf.high": "High", "v5.conf.medium": "Medium", "v5.conf.low": "Low",
  "v5.conf.high.d": "Most of the key figures are checked and cover this stage well.", "v5.conf.medium.d": "Enough data, but some key figures are self-reported.", "v5.conf.low.d": "Too little checked data: add documents to raise it.",
  "v5.g.median": "stage avg", "v5.g.medtip": "the black mark is the typical company at this stage (50)",
  "v5.db.score": "Score (0–100)", "v5.db.median": "Typical {s} company (50)", "v5.db.top": "Top quarter (75)", "v5.db.weight": "counts {w}%", "v5.db.cov": "data for {c}% of it",
  "v5.db.thin": "Not enough data", "v5.db.vsstage": "vs stage",
  "v5.dh.cov": "We have data for {c}% of what this score measures.", "v5.dh.capped": "With so little data the score is capped at {c}.", "v5.dh.na": "Not applicable yet",
  "v5.raise.h": "What would raise this score",
  "v5.ov.score": "Business score", "v5.ov.value": "Fair value", "v5.ov.range": "Range {lo} – {hi}", "v5.ov.trust": "{p} of the score rests on checked figures",
  "v5.ov.why.stage": "Why we see this as {s}", "v5.ov.why.conf": "Why this confidence", "v5.ov.conflict": "The funding round and the revenue point to different stages: we used the lower one.",
  "v5.ov.stagekeys": "The stage sets the weights, the benchmarks and the recommended share price.", "v5.ov.tablever": "benchmark table {v}",
  "v5.ov.dims": "Score by dimension", "v5.ov.dims.p": "Each bar is 0–100 against a typical {s} company. Tap a bar for the detail.",
  "v5.ov.top3": "Top 3 things that would raise this score", "v5.ov.how": "How the business score adds up", "v5.ov.how.p": "Each dimension's score × its weight at this stage; the weights add up to 1.",
  "v5.basis.listing": "Decided by a verified stock-exchange listing.", "v5.basis.round": "Decided by your latest funding round (last 30 months).", "v5.basis.revenue": "Decided by your revenue band.",
  "v5.basis.raised": "Decided by how much you have raised.", "v5.basis.hint": "Best guess from the website: add figures to confirm it.", "v5.basis.human": "Set by a reviewer.", "v5.basis.default": "Default stage: add figures to confirm it.",
  "v5.col.dim": "Dimension", "v5.col.score": "Score", "v5.col.weight": "Weight", "v5.col.cov": "Data", "v5.col.level": "Level", "v5.col.contrib": "Adds", "v5.col.total": "Business score",
  "v5.col.measure": "Measure", "v5.col.value": "Value", "v5.col.method": "Method", "v5.col.low": "Low", "v5.col.mid": "Mid", "v5.col.high": "High", "v5.col.month": "Month",
  "v5.col.name": "Name", "v5.col.raised": "Raised", "v5.col.source": "Source", "v5.col.year": "Year", "v5.col.base": "Rule weight", "v5.col.note": "Note", "v5.col.power": "Advantage",
  "v5.col.cohort": "Group", "v5.col.analyst": "Check", "v5.col.claims": "Figures kept", "v5.col.dropped": "Dropped", "v5.col.searches": "Searches",
  "v5.cta.h": "Next: finalise the value and price", "v5.cta.p": "Confirm the value range and choose the price per share before shares are set up.", "v5.cta.btn": "Finalise & price",
  "v5.team.open": "Open the full team review",
  "v5.bb.you": "You", "v5.bb.med": "typical", "v5.bb.lower": "lower is better",
  "v5.sm.missing": "No figure yet", "v5.sm.noscore": "Not scored", "v5.sm.score": "Scores {s}/100", "v5.sm.src": "Source",
  "v5.sm.st.capped": "capped", "v5.sm.st.not_applicable": "not applicable", "v5.sm.st.not_benchmarked": "no benchmark", "v5.sm.st.scored": "scored", "v5.sm.st.missing": "missing",
  "v5.src.self": "Self-reported", "v5.src.doc": "Uploaded document",
  "v5.need.h": "What we need to score this", "v5.need.p": "Nothing here counts against you yet — the score sits at a cautious default until you add figures.", "v5.need.add": "Add a document or CSV",
  "v5.need.csv": "A monthly metrics CSV (template provided) — the strongest single input", "v5.need.mrr": "MRR today and 6 or 12 months ago", "v5.need.customers": "Paying customers now and a year ago",
  "v5.need.target": "Who you sell to and how many such customers exist", "v5.need.price": "Your average price per customer per year", "v5.need.geo": "Where you sell",
  "v5.need.ip": "Patents, trade marks or licences with their numbers", "v5.need.integrations": "How many tools you integrate with", "v5.need.licences": "Exclusive contracts or partnerships",
  "v5.need.rt.early": "At {s} retention is not expected yet: product evidence stands in for it.", "v5.need.pilots": "Paid pilots and letters of intent", "v5.need.reviews": "App store or review-site ratings",
  "v5.need.csvmov": "A metrics CSV with new / expansion / churned MRR by month", "v5.need.nrr": "Net revenue retention (NRR)", "v5.need.churn": "Customers lost per month", "v5.need.cohort": "Month-3 and month-12 retention",
  "v5.tr.mrr": "Monthly recurring revenue", "v5.tr.rev": "Monthly revenue", "v5.tr.metrics": "Each measure vs your stage", "v5.tr.metrics.p": "The dot is you; the shaded band is the middle half of companies at your stage; the dark mark is typical.",
  "v5.tr.how": "Traction = revenue scale 30% + growth 40% + customers 15% + forward signals 15%. Growth uses year-on-year when there are 12 months of data, else month-on-month.",
  "v5.mk.h": "Market size", "v5.mk.tam": "total market (top-down, cited)", "v5.mk.sam": "the part you can serve (bottom-up)", "v5.mk.som": "what you could win in 5 years",
  "v5.mk.som.r": "{lo} – {hi} in 5 years", "v5.mk.som.s": "{a}–{b} of SAM", "v5.mk.logscale": "Bar widths use a log scale so the smaller markets stay visible.",
  "v5.mk.bu": "Bottom-up: customers × price", "v5.mk.cust": "Target customers", "v5.mk.price": "Price per year", "v5.mk.td": "Top-down figure (cross-check)", "v5.mk.cagr": "Market growth per year",
  "v5.mk.abs": "ABS business counts", "v5.mk.tier": "Best source", "v5.tier.0": "unknown", "v5.tier.1": "government or statutory", "v5.tier.2": "industry body or listed-company filing", "v5.tier.3": "analyst report (press release)", "v5.tier.4": "blog or vendor",
  "v5.mo.radar": "Competitive advantages (7 Powers)", "v5.mo.radar.p": "Each advantage is rated 0–3: none, claimed, shown on public pages, verified in a registry or document.",
  "v5.mo.grid": "Evidence for each advantage", "v5.mo.level": "level {l} of 3", "v5.mo.l0": "none", "v5.mo.l1": "claimed", "v5.mo.l2": "shown publicly", "v5.mo.l3": "verified",
  "v5.mo.computed": "computed from competitors: {s}/100", "v5.mo.comp": "Competitors' funding (A$ millions)", "v5.mo.comp.p": "Well-funded direct competitors lower the competition score.",
  "v5.mo.how": "Moat = network effects 20% + switching costs 20% + IP and data 15% + scale 10% + brand 10% + counter-positioning 10% + competition 15%. Founder claims alone reach level 1.",
  "v5.pw.network_effects": "Network effects", "v5.pw.switching_costs": "Switching costs", "v5.pw.ip_data": "IP & data", "v5.pw.scale": "Scale", "v5.pw.brand": "Brand", "v5.pw.counter_positioning": "Counter-positioning", "v5.pw.competition": "Competition",
  "v5.rt.cohort": "Customers still active, by starting month", "v5.rt.cohort.p": "Each line follows a group of customers from the month they joined.",
  "v5.rt.conc.flag": "The largest customer is {p} of revenue: a concentration risk.", "v5.rt.conc.high": "The largest customer is {p} of revenue: high concentration risk.",
  "v5.rt.how": "Retention = NRR 30% + GRR 25% + usage retention 20% + reviews / NPS 15% + customer concentration 10%, benchmarked by contract size first, then stage.",
  "v5.ev.levels": "How the figures are checked", "v5.ev.levels.p": "{n} measures across all dimensions, by verification level.",
  "v5.ev.flags": "Consistency checks", "v5.ev.act.lower_used": "the lower figure was used", "v5.ev.act.capped": "capped for scoring", "v5.ev.act.review": "sent to a reviewer",
  "v5.ev.docs": "Documents used", "v5.ev.lookups": "Free public lookups", "v5.ev.dropped": "Figures we could not verify ({n})", "v5.ev.analysts": "What each check found",
  "v5.an.traction": "Traction", "v5.an.market_size": "Market size", "v5.an.moat": "Moat", "v5.an.retention": "Retention", "v5.an.deck": "Pitch deck",
  "v5.va.h": "How we reached this value", "v5.va.p": "Each bar is one method's range; the black line is the blended value and the gold band the final range. Better evidence counts for more.",
  "v5.va.ff": "Value by method", "v5.va.methods": "Methods, one at a time", "v5.va.excluded": "Not used in the blend", "v5.va.nochecks": "No problems found in this method's inputs.",
  "v5.va.inputs": "Every input used ({n})", "v5.va.weights": "How the methods are weighted", "v5.va.weights.p": "Rule weight by stage × evidence quality, then shared out to 100%. Methods far from the others are left out.",
  "v5.va.legal": "Indicative value, not a formal valuation or financial advice.", "v5.va.params": "parameters {v}", "v5.va.stagefallback": "Stage fallback: the typical {s} value, used only when nothing else applies.",
  "v5.ff.mid": "mid", "v5.ff.excl": "not used", "v5.ff.counts": "counts {w}%", "v5.ff.uncapped": "Your forecast as uploaded would give {v} (caps applied).",
  "v5.ff.lg.range": "Method range", "v5.ff.lg.blend": "Blended value", "v5.ff.lg.band": "Final range", "v5.ff.lg.offer": "Finalised value", "v5.ff.lg.off": "Not used",
  "v5.ff.offer": "Finalised value", "v5.ff.log": "Log scale: the methods are far apart.", "v5.ff.aria": "Football field: blended value {v}, range {lo} to {hi}",
  "v5.proj.label": "Based on management projections (unaudited, not verified by BlockID).", "v5.proj.without": "Without the forecast: {v}.",
  "v5.m.market_anchor": "Own price", "v5.m.revenue_multiple": "Revenue multiple", "v5.m.stage_scorecard": "Stage fallback", "v5.m.ebitda_multiple": "EBITDA multiple", "v5.m.precedents": "Deals",
  "v5.m.dcf": "Discounted cash flow", "v5.m.vc_method": "VC method", "v5.m.scorecard": "Scorecard", "v5.m.berkus": "Berkus", "v5.m.rfs": "Risk factors", "v5.m.first_chicago": "Scenarios",
  "v5.md.market_anchor": "its latest round, share sale or market value", "v5.md.revenue_multiple": "revenue × what similar companies are worth per dollar of revenue", "v5.md.stage_scorecard": "typical value at this stage",
  "v5.md.ebitda_multiple": "EBITDA × comparable multiples", "v5.md.precedents": "prices paid in comparable acquisitions", "v5.md.dcf": "future cash flows brought back to today",
  "v5.md.vc_method": "exit value ÷ the return investors need", "v5.md.scorecard": "typical pre-money × how you compare, dimension by dimension", "v5.md.berkus": "up to a fixed amount for each of 5 milestones",
  "v5.md.rfs": "typical value adjusted for 12 risks", "v5.md.first_chicago": "cash flows in a bad, base and good case, weighted",
  "v5.dcf.fcff": "Free cash flow", "v5.dcf.revenue": "Revenue", "v5.dcf.ebitda": "EBITDA", "v5.dcf.build": "Discount rate build-up", "v5.dcf.rf": "Risk-free rate", "v5.dcf.beta": "Beta",
  "v5.dcf.erp": "Equity risk premium", "v5.dcf.crp": "Country risk", "v5.dcf.size": "Size premium", "v5.dcf.rate": "Discount rate", "v5.dcf.g": "Long-term growth", "v5.dcf.exitm": "Exit multiple",
  "v5.dcf.terminal": "Terminal value", "v5.dcf.t.gordon": "steady growth forever", "v5.dcf.t.exit": "sale at an exit multiple", "v5.dcf.ev": "Enterprise value", "v5.dcf.nd": "Net debt",
  "v5.dcf.tv": "How much comes from the terminal value", "v5.dcf.tv.pv": "Forecast years", "v5.dcf.tv.tv": "Terminal value", "v5.dcf.tv.aria": "Terminal value is {p} of the value",
  "v5.dcf.tv.high": "Over 75% comes from the terminal value: the result leans on the long run.", "v5.dcf.tv.ok": "A healthy share comes from the forecast years.",
  "v5.dcf.sens": "Sensitivity", "v5.dcf.sens.p": "Value if the discount rate (rows) or long-term growth (columns) is a little different. The outlined cell is the base case.",
  "v5.dcf.lower": "lower than base", "v5.dcf.base": "near base", "v5.dcf.higher": "higher than base",
  "v5.fc.bad": "Bad case", "v5.fc.base": "Base case", "v5.fc.good": "Good case",
  "v5.cm.rev": "Revenue", "v5.cm.ebitda": "EBITDA", "v5.cm.mult": "Multiple", "v5.cm.disc": "Private discount", "v5.cm.val": "Value", "v5.cm.peers": "Comparable companies",
  "v5.cm.deals": "Comparable deals", "v5.cm.median": "multiple used", "v5.cm.band": "Cited range {lo}× / {mid}× / {hi}×",
  "v5.vc.exitrev": "Exit value in {y} years: {r} × {m}", "v5.vc.ret": "Kept after future rounds ({p})", "v5.vc.irr": "÷ (1 + {p}) for {y} years = value today", "v5.vc.div": "÷ target return {m}× ({lo}–{hi}×) = value after the round",
  "v5.vc.raise": "− the money being raised", "v5.vc.pre": "Value before the round",
  "v5.sc.p": "Typical pre-money {b} × your factor {f}. A score of 50 means typical for the stage.", "v5.sc.avg": "typical (50)",
  "v5.bk.p": "Up to {c} for each milestone.", "v5.bk.sound_idea": "Sound idea", "v5.bk.prototype": "Prototype", "v5.bk.quality_team": "Quality team", "v5.bk.strategic_relationships": "Strategic relationships", "v5.bk.product_rollout": "Product rollout",
  "v5.rfs.p": "Base {b}; each step up or down moves it by {s} (net {n}).", "v5.rfs.minus": "risk lowers value", "v5.rfs.plus": "strength raises value",
  "v5.rfs.management": "Management", "v5.rfs.stage": "Stage of the business", "v5.rfs.legislation": "Legislation / politics", "v5.rfs.manufacturing": "Manufacturing", "v5.rfs.sales_marketing": "Sales & marketing",
  "v5.rfs.funding": "Funding", "v5.rfs.competition": "Competition", "v5.rfs.technology": "Technology", "v5.rfs.litigation": "Litigation", "v5.rfs.international": "International", "v5.rfs.reputation": "Reputation", "v5.rfs.exit": "Exit potential",
  "v5.sev.error": "Must fix", "v5.sev.warning": "Warning", "v5.sev.info": "Note",
  /* finalise & pricing */
  "v5.fn.h": "Finalise the value and price", "v5.fn.p": "Three short steps. The result is frozen and used to set up your shares and any offer.",
  "v5.fn.s1": "Review the value", "v5.fn.s2": "Choose the price per share", "v5.fn.s3": "Confirm",
  "v5.fn.wait": "You can finalise once a reviewer has approved the valuation.", "v5.fn.owner": "Only the business owner or a platform admin can finalise.",
  "v5.fn.lowconf": "Confidence is low: add documents to raise it, or ask a platform admin to finalise with a reason.", "v5.fn.lowconf.adm": "Confidence is low: as an admin you can finalise with a written reason.",
  "v5.fn.lowconf.h": "Finalise despite low confidence", "v5.fn.override": "Why it is safe to finalise (admin)", "v5.fn.confok": "Confidence is enough to finalise.",
  "v5.fn.s1.p": "The finalised value stays valid for {d} days. After that, or if the report changes, it must be finalised again.",
  "v5.fn.recprice": "Recommended for a {s} company", "v5.fn.recprice.s": "Recommended price", "v5.fn.yourprice": "Your price per share", "v5.fn.reset": "Use the recommended price",
  "v5.fn.dev0": "Recommended", "v5.fn.dev": "{d} vs recommended", "v5.fn.bad": "Enter a price between {lo} and {hi}.", "v5.fn.few": "At this price you would have fewer than {n} shares: choose a lower price.",
  "v5.fn.zone.free": "Within ±{b}: applies at once", "v5.fn.zone.adm": "Needs admin approval", "v5.fn.zone.rec": "Recommended",
  "v5.fn.shares": "Number of shares", "v5.fn.existing": "your existing shares (fully diluted)", "v5.fn.newco": "for a new share register",
  "v5.fn.offer": "Offer price range", "v5.fn.offer.p": "from the low end of the value to your price", "v5.fn.implied": "Shares × price", "v5.fn.implied.p": "the fair value is {v}", "v5.fn.value": "Fair value",
  "v5.fn.raise": "Money you plan to raise (preview)", "v5.fn.raise.p": "Only for this preview of the split; not saved.", "v5.fn.raise.pj": "From your forecast; change it to preview another raise (not saved).",
  "v5.fn.split": "Who would own the business after the raise", "v5.fn.founders": "Current owners", "v5.fn.investors": "New investors", "v5.fn.post": "Value after the raise: {v}.",
  "v5.fn.needadmin": "This price needs a platform admin's approval", "v5.fn.needadmin.p": "It is more than {b} away from the recommendation. Explain why; a different admin will review it.",
  "v5.fn.reason": "Reason", "v5.fn.reason.ph": "e.g. a signed term sheet prices the round at A$0.40 per share", "v5.fn.reason.min": "At least {n} characters ({c} so far).",
  "v5.fn.note": "Note (optional)", "v5.fn.note.req": "Why this price", "v5.fn.note.ph": "e.g. a round number for investors", "v5.fn.note.p": "Recorded with the finalised value.", "v5.fn.note.min": "A short note is needed when you change the price (3+ characters).",
  "v5.fn.valid": "Valid for", "v5.fn.valid.v": "{d} days, until about {until}", "v5.fn.goesadmin": "This goes to a platform admin. You will see the result here.",
  "v5.fn.attest": "I confirm this value and price. I understand the value is indicative, stays valid for {d} days, and is used to set up the share register.",
  "v5.fn.next": "Next", "v5.fn.submit": "Finalise", "v5.fn.submitadm": "Send for approval",
  "v5.fn.expired": "The finalised value is older than {d} days. Finalise it again with the current report.", "v5.fn.stale": "The report changed after it was finalised. Finalise it again.", "v5.fn.again": "Finalise again",
  "v5.fz.st.valid": "Finalised", "v5.fz.st.expired": "Expired", "v5.fz.st.stale": "Out of date", "v5.fz.st.none": "Not finalised",
  "v5.fz.until": "valid until {d}", "v5.fz.ended": "ended {d}", "v5.fz.value": "Fair value", "v5.fz.price": "Price per share", "v5.fz.rec": "recommended {p} · {d}",
  "v5.fz.shares": "Shares", "v5.fz.offer": "Offer price range", "v5.fz.note": "Note", "v5.fz.reason": "Reason", "v5.fz.approvedby": "approved by {a}", "v5.fz.override": "Finalised at low confidence by {a}: {r}",
  "v5.fz.at": "Finalised {d}", "v5.fz.hash": "report {h}", "v5.fz.gate": "Open the admin approval", "v5.fz.next": "Set up your shares",
  "v5.pr.h": "Price waiting for approval", "v5.pr.p": "A platform admin other than you will approve or reject it. The recommended price stays available.", "v5.pr.at": "Sent {d}", "v5.pr.cancel": "Cancel the request",
  "v5.hint.final": "From your finalised proposal: {n} shares at {p} each (valid until {d}).", "v5.hint.first": "Finalise the value and price first: the share count and price come from it.",
  "v5.hint.pending": "Your price is waiting for a platform admin's approval.", "v5.hint.expired": "Your finalised value has expired or is out of date: finalise it again.",
  /* uploads */
  "v5.up.h": "Upload a pitch deck or metrics CSV", "v5.up.p": "Read in your browser: we keep the text and a fingerprint (SHA-256) of the file, never the file itself.",
  "v5.up.lvl": "Figures that match a document count as document-backed.", "v5.up.tpl": "Download the metrics CSV template", "v5.up.pick": "Choose a file",
  "v5.up.type": "Use a PDF, CSV, Markdown or text file (save slides as PDF).", "v5.up.size": "That file is too big (max {m}).", "v5.up.read": "We could not read that file.",
  "v5.up.deck": "Pitch deck", "v5.up.csv": "Metrics CSV", "v5.up.fin": "Financial statements", "v5.up.pages": "{n} pages",
  "v5.up.st.ready": "ready", "v5.up.st.queued": "sent after you start", "v5.up.st.sending": "sending…", "v5.up.st.sent": "added", "v5.up.st.error": "fix and try again",
  "v5.up.remove": "Remove {f}", "v5.up.clean": "No problems found.", "v5.up.months": "Months", "v5.up.lastmrr": "MRR {m}", "v5.up.yoy": "Growth, year on year",
  "v5.up.addh": "Add or update your data", "v5.up.addp": "Upload documents, then re-score: only the checks run again, no new web research.", "v5.up.rescore": "Re-score with the new data", "v5.up.rescored": "Re-scored. The report now uses your documents.",
  "v5.pj.h": "Add your forecast (optional)", "v5.pj.opt": "optional", "v5.pj.p": "3–5 years of projections unlock the cash-flow and VC methods. They are always labelled as unaudited management projections.",
  "v5.pj.s1": "Download the template", "v5.pj.s2": "Upload and check", "v5.pj.s3": "Confirm", "v5.pj.tpl.csv": "Template (CSV)", "v5.pj.tpl.xlsx": "Template (Excel)",
  "v5.pj.pick": "Choose your forecast", "v5.pj.drop": "Drop the filled-in template here (.xlsx or .csv, up to 512 KB).",
  "v5.pj.macro": "Files with macros (.xlsm, .xls) are not accepted: save as .xlsx.", "v5.pj.type": "Use the .xlsx or .csv template.",
  "v5.pj.gm": "Gross margin", "v5.pj.clean": "Every check passed.", "v5.pj.check": "Upload and check", "v5.pj.confirm": "Confirm the forecast", "v5.pj.confirmed": "Confirmed",
  "v5.pj.attest": "These are our management's projections, prepared with reasonable care. I understand BlockID does not verify them.",
  "v5.pj.queued": "Will be uploaded and confirmed after you start", "v5.pj.server": "Server checks: {e} to fix, {w} warnings (warnings apply a cap and lower the forecast's weight).",
  "v5.pj.done": "Forecast confirmed. The value has been recomputed.", "v5.pj.moved": "Forecast confirmed. Value {a} → {b} ({p}).", "v5.pj.back": "It moved more than 5%, so it goes back to a reviewer.",
  "v5.pj.r.year": "Fiscal year ending (YYYY)", "v5.pj.r.actual": "Actual (A) or Projection (P)", "v5.pj.r.revenue": "Revenue", "v5.pj.r.cogs": "Cost of sales", "v5.pj.r.opex": "Operating expenses (excl. D&A)",
  "v5.pj.r.ebitda": "EBITDA (optional check)", "v5.pj.r.d_and_a": "Depreciation & amortisation", "v5.pj.r.tax": "Income tax paid (optional)", "v5.pj.r.capex": "Capital expenditure",
  "v5.pj.r.nwc": "Net working capital (optional)", "v5.pj.r.headcount": "Employees (optional)", "v5.pj.r.customers": "Paying customers (optional)", "v5.pj.r.currency": "Currency",
  "v5.pj.r.fiscal_year_end": "Fiscal year end (MM-DD)", "v5.pj.r.cash": "Cash", "v5.pj.r.debt": "Debt", "v5.pj.r.shares_fd": "Shares on issue (fully diluted)", "v5.pj.r.planned_raise": "Planned raise", "v5.pj.r.audited": "Audited (Y/N)",
  /* local checks */
  "v5.chk.csv.empty": "The file has no data rows.", "v5.chk.csv.nomonth": "Add a 'month' column (YYYY-MM).", "v5.chk.csv.norev": "Add an 'mrr_aud' or 'revenue_aud' column.",
  "v5.chk.csv.rows": "At most {n} rows.", "v5.chk.csv.badmonth": "Row {r}: '{v}' is not a month (use YYYY-MM).", "v5.chk.csv.nan": "Row {r}: {c} is not a number.",
  "v5.chk.csv.neg": "Row {r}: {c} is negative.", "v5.chk.csv.dup": "Row {r}: {m} appears twice.", "v5.chk.csv.future": "Row {r}: {m} is in the future.",
  "v5.chk.csv.smooth": "Growth is almost perfectly smooth month after month: a reviewer will look at it.", "v5.chk.csv.nrrgrr": "NRR is below GRR: check the expansion and churn columns.",
  "v5.chk.csv.short": "Only {n} months: 6 or more give a reliable growth rate.",
  "v5.chk.pj.missingrow": "Row '{k}' is missing.", "v5.chk.pj.badyear": "'{v}' is not a year.", "v5.chk.pj.missing": "'{k}' is missing for {y}.", "v5.chk.pj.neg": "'{k}' is negative in {y}.",
  "v5.chk.pj.ap": "Mark {y} as A (actual) or P (projection).", "v5.chk.pj.gap": "Years must follow each other: {y} is out of order.", "v5.chk.pj.few": "At least 3 projected years are needed ({n} found).",
  "v5.chk.pj.noactual": "Adding your last actual year makes the forecast more credible.", "v5.chk.pj.identity": "EBITDA {y} doesn't add up: {g} given, {c} from the rows above.",
  "v5.chk.pj.gm": "Gross margin {p}% in {y} is outside the usual {lo}–{hi}% for this sector.", "v5.chk.pj.growth": "Revenue grows {g}% in {y}; we will use {c}% (limit for this stage).",
  "v5.chk.pj.jump": "Revenue in {y} is more than 3× the last actual year.", "v5.chk.pj.capex": "Long-run capital spending is below half of depreciation.", "v5.chk.pj.tax": "No tax row: the standard company tax rate will be used.",
  "v5.chk.pj.currency": "Currency {c} isn't supported.", "v5.chk.pj.xlsx": "Excel files are checked by the server after upload.",
  "v5.chk.deck.scan": "Very little text was found — is it a scanned deck? Save it with text, or add figures in the form.", "v5.chk.deck.cut": "Only the first {n} characters are used.",
  /* /start inputs */
  "v5.in.h": "Add your numbers and documents (optional, improves accuracy)", "v5.in.h.list": "Add your numbers and documents (optional, improves the listing)",
  "v5.in.p": "Only the questions that matter at your stage. Everything you type is shown as self-reported; a matching document makes it document-backed.",
  "v5.in.s0": "Your stage", "v5.in.s1": "Revenue & customers", "v5.in.s2": "Retention & efficiency", "v5.in.s3": "Market & moat", "v5.in.s4": "Documents",
  "v5.in.looks": "Looks like:", "v5.in.youchose": "you chose {s}", "v5.in.change": "Change the stage",
  "v5.in.basis.round": "From your latest funding round.", "v5.in.basis.revenue": "From your revenue.", "v5.in.basis.raised": "From how much you have raised.",
  "v5.in.basis.conflict": "Your round and your revenue point to different stages: we use the lower one.", "v5.in.basis.listing": "From a stock-exchange listing.", "v5.in.basis.hint": "A first guess.",
  "v5.in.basis.default": "A first guess — type your revenue or last round to confirm it.",
  "v5.in.stagep": "Choosing a stage only changes which questions you see. The report decides the stage from the evidence, and a reviewer can change it.",
  "v5.in.l1": "what you type", "v5.in.l2": "with a matching document", "v5.in.files": "{n} files", "v5.in.done": "That's all — start the evaluation above.",
  "v5.f.bad": "Check this value.",
  "v5.g.revenue": "Revenue & growth", "v5.g.revenue.p": "feeds Traction", "v5.g.customers": "Customers & pipeline", "v5.g.customers.p": "feeds Traction and Retention",
  "v5.g.retention": "Retention", "v5.g.retention.p": "feeds Retention", "v5.g.efficiency": "Cash & efficiency", "v5.g.efficiency.p": "feeds Capital efficiency",
  "v5.g.market": "Market", "v5.g.market.p": "feeds Market", "v5.g.moat": "Moat", "v5.g.moat.p": "feeds Moat", "v5.g.round": "Last round", "v5.g.round.p": "sets the stage and the own-price anchor",
  "v5.opt.subscription": "Subscription", "v5.opt.transactional": "Per transaction", "v5.opt.marketplace": "Marketplace", "v5.opt.services": "Services", "v5.opt.hardware": "Hardware", "v5.opt.other": "Other",
  "v5.opt.pre-seed": "Pre-seed", "v5.opt.angel": "Angel", "v5.opt.seed": "Seed", "v5.opt.series-a": "Series A", "v5.opt.series-b": "Series B", "v5.opt.series-c": "Series C or later",
  "v5.opt.grant": "Grant", "v5.opt.safe": "SAFE / convertible note",
  /* admin price queue */
  "v5.ad.h": "Share price approvals", "v5.ad.q": "Share prices",
  "v5.ad.d": "Prices per share more than 20% away from the stage recommendation. A different admin than the requester decides.",
  "v5.ad.p": "The founder chose a price outside ±20% of the recommendation. Check the reason against the report before approving.",
  "v5.ad.req": "Requested price", "v5.ad.by": "Requested by", "v5.ad.note": "Note (required to reject, 5+ characters)", "v5.ad.reason5": "Write a reason of at least 5 characters to reject.",
  "v5.ad.approve": "Approve this price", "v5.ad.reject": "Reject", "v5.ad.approved": "Price approved: the value is finalised.", "v5.ad.rejected": "Price rejected: the founder has been told.",
  "v5.ad.empty": "No share prices waiting for approval.", "v5.ad.open": "Open the report", "v5.ad.mine": "You sent this request: another admin must decide it.",
  "v5.ad.return": "You came here from the founder's flow.", "v5.ad.track": "Recommended {r}, requested {p} ({d})",
  "ad.q.pricing": "Share prices", "ad.d.pricing": "Prices per share more than 20% away from the stage recommendation. A different admin than the requester decides.",
  "v5.of.final": "Finalised value: {p} per share (offer range {lo} – {hi}), valid until {d}.", "v5.of.expired": "The finalised value has expired or is out of date: finalise it again before submitting.",
};

export type V5Key = keyof typeof v5En;

export const v5Vi: Record<V5Key, string> = {
  ...fVi,
  "v5.legal": "Giá trị tham khảo, không phải định giá chính thức hay tư vấn tài chính. Bản demo testnet. Không phải chào bán chứng khoán.",
  "v5.tabs": "Các phần của báo cáo",
  "v5.tab.overview": "Tổng quan", "v5.tab.team": "Đội ngũ", "v5.tab.traction": "Tăng trưởng", "v5.tab.market": "Thị trường", "v5.tab.moat": "Lợi thế",
  "v5.tab.retention": "Giữ chân", "v5.tab.valuation": "Định giá", "v5.tab.evidence": "Bằng chứng", "v5.tab.finalise": "Chốt giá trị & giá",
  "v5.seehow": "Xem cách tính", "v5.seehow.score": "Xem cách tính điểm này", "v5.astable": "Xem dạng bảng", "v5.nodata": "Chưa đủ dữ liệu.",
  "v5.grade": "Hạng", "v5.pts": "điểm", "v5.eg": "ví dụ {x}",
  "v5.u.months": "{n} tháng",
  "v5.stage": "Giai đoạn", "v5.stage.idea": "Ý tưởng", "v5.stage.pre-seed": "Tiền hạt giống", "v5.stage.seed": "Hạt giống", "v5.stage.series-a": "Series A", "v5.stage.growth": "Tăng trưởng (Series B+)",
  "v5.stage.established": "Đã ổn định", "v5.stage.profitable-sme": "Doanh nghiệp có lãi", "v5.stage.listed": "Đã niêm yết",
  "v5.dim.founder_quality": "Đội ngũ", "v5.dim.traction": "Tăng trưởng thương mại", "v5.dim.market": "Thị trường", "v5.dim.moat": "Lợi thế cạnh tranh", "v5.dim.retention": "Giữ chân khách hàng",
  "v5.dim.efficiency": "Hiệu quả vốn", "v5.dim.product_strength": "Sản phẩm", "v5.dim.investment_readiness": "Sẵn sàng gọi vốn", "v5.dim.trust_verification": "Mức kiểm chứng",
  "v5.lv.h": "Mức kiểm chứng của từng con số", "v5.lv.p": "Mỗi con số có một mức. Số đã kiểm chứng tác động lên điểm nhiều hơn.",
  "v5.lv.0": "Thiếu", "v5.lv.1": "Tự khai", "v5.lv.2": "Có tài liệu", "v5.lv.3": "Xác nhận công khai", "v5.lv.4": "Kết nối trực tiếp",
  "v5.lv.0.d": "Không có dữ liệu: bị bỏ qua, điểm của nhóm bị giới hạn.", "v5.lv.1.d": "Do founder nhập hoặc chỉ có trên website của công ty: giữ 60% tác động.",
  "v5.lv.2.d": "Khớp với tài liệu hoặc CSV đã tải lên: giữ 80%.", "v5.lv.3.d": "Có trong nguồn độc lập hoặc bản cập nhật đã duyệt: giữ 90%.", "v5.lv.4.d": "Lấy từ hệ thống kết nối (Stripe, Xero, ngân hàng): đủ 100%.",
  "v5.lv.shrink": "Tác động của một con số được kéo về mức trung bình của giai đoạn theo mức kiểm chứng: tự khai 60%, tài liệu 80%, công khai 90%, kết nối 100%.",
  "v5.conf": "Độ tin cậy", "v5.conf.high": "Cao", "v5.conf.medium": "Trung bình", "v5.conf.low": "Thấp",
  "v5.conf.high.d": "Phần lớn số liệu chính đã được kiểm chứng và đủ cho giai đoạn này.", "v5.conf.medium.d": "Đủ dữ liệu, nhưng một số số liệu chính là tự khai.", "v5.conf.low.d": "Quá ít dữ liệu đã kiểm chứng: hãy thêm tài liệu.",
  "v5.g.median": "TB giai đoạn", "v5.g.medtip": "vạch đen là công ty điển hình ở giai đoạn này (50)",
  "v5.db.score": "Điểm (0–100)", "v5.db.median": "Công ty {s} điển hình (50)", "v5.db.top": "Nhóm 25% dẫn đầu (75)", "v5.db.weight": "chiếm {w}%", "v5.db.cov": "có dữ liệu cho {c}%",
  "v5.db.thin": "Chưa đủ dữ liệu", "v5.db.vsstage": "so với giai đoạn",
  "v5.dh.cov": "Chúng tôi có dữ liệu cho {c}% những gì điểm này đo.", "v5.dh.capped": "Vì ít dữ liệu, điểm bị giới hạn ở {c}.", "v5.dh.na": "Chưa áp dụng",
  "v5.raise.h": "Điều gì sẽ nâng điểm này",
  "v5.ov.score": "Điểm doanh nghiệp", "v5.ov.value": "Giá trị hợp lý", "v5.ov.range": "Khoảng {lo} – {hi}", "v5.ov.trust": "{p} điểm dựa trên số liệu đã kiểm chứng",
  "v5.ov.why.stage": "Vì sao chúng tôi xếp vào {s}", "v5.ov.why.conf": "Vì sao có độ tin cậy này", "v5.ov.conflict": "Vòng gọi vốn và doanh thu chỉ ra hai giai đoạn khác nhau: chúng tôi dùng giai đoạn thấp hơn.",
  "v5.ov.stagekeys": "Giai đoạn quyết định trọng số, chuẩn so sánh và giá cổ phần đề xuất.", "v5.ov.tablever": "bảng chuẩn {v}",
  "v5.ov.dims": "Điểm theo từng nhóm", "v5.ov.dims.p": "Mỗi thanh là 0–100 so với công ty {s} điển hình. Chạm vào thanh để xem chi tiết.",
  "v5.ov.top3": "3 điều giúp nâng điểm nhiều nhất", "v5.ov.how": "Điểm doanh nghiệp được cộng thế nào", "v5.ov.how.p": "Điểm của mỗi nhóm × trọng số ở giai đoạn này; tổng trọng số bằng 1.",
  "v5.basis.listing": "Xác định bởi việc niêm yết đã kiểm chứng.", "v5.basis.round": "Xác định bởi vòng gọi vốn gần nhất (30 tháng qua).", "v5.basis.revenue": "Xác định bởi mức doanh thu.",
  "v5.basis.raised": "Xác định bởi số vốn đã gọi.", "v5.basis.hint": "Phỏng đoán từ website: thêm số liệu để xác nhận.", "v5.basis.human": "Do người duyệt đặt.", "v5.basis.default": "Giai đoạn mặc định: thêm số liệu để xác nhận.",
  "v5.col.dim": "Nhóm", "v5.col.score": "Điểm", "v5.col.weight": "Trọng số", "v5.col.cov": "Dữ liệu", "v5.col.level": "Mức", "v5.col.contrib": "Đóng góp", "v5.col.total": "Điểm doanh nghiệp",
  "v5.col.measure": "Chỉ số", "v5.col.value": "Giá trị", "v5.col.method": "Phương pháp", "v5.col.low": "Thấp", "v5.col.mid": "Giữa", "v5.col.high": "Cao", "v5.col.month": "Tháng",
  "v5.col.name": "Tên", "v5.col.raised": "Đã gọi vốn", "v5.col.source": "Nguồn", "v5.col.year": "Năm", "v5.col.base": "Trọng số gốc", "v5.col.note": "Ghi chú", "v5.col.power": "Lợi thế",
  "v5.col.cohort": "Nhóm", "v5.col.analyst": "Hạng mục", "v5.col.claims": "Số liệu giữ lại", "v5.col.dropped": "Bị loại", "v5.col.searches": "Lượt tìm",
  "v5.cta.h": "Tiếp theo: chốt giá trị và giá", "v5.cta.p": "Xác nhận khoảng giá trị và chọn giá mỗi cổ phần trước khi thiết lập cổ phần.", "v5.cta.btn": "Chốt giá trị & giá",
  "v5.team.open": "Mở bản đánh giá đội ngũ đầy đủ",
  "v5.bb.you": "Bạn", "v5.bb.med": "điển hình", "v5.bb.lower": "càng thấp càng tốt",
  "v5.sm.missing": "Chưa có số liệu", "v5.sm.noscore": "Chưa chấm điểm", "v5.sm.score": "Đạt {s}/100", "v5.sm.src": "Nguồn",
  "v5.sm.st.capped": "bị giới hạn", "v5.sm.st.not_applicable": "chưa áp dụng", "v5.sm.st.not_benchmarked": "chưa có chuẩn", "v5.sm.st.scored": "đã chấm", "v5.sm.st.missing": "thiếu",
  "v5.src.self": "Tự khai", "v5.src.doc": "Tài liệu đã tải lên",
  "v5.need.h": "Cần gì để chấm điểm phần này", "v5.need.p": "Hiện chưa có gì bất lợi cho bạn — điểm ở mức thận trọng mặc định cho đến khi bạn bổ sung số liệu.", "v5.need.add": "Thêm tài liệu hoặc CSV",
  "v5.need.csv": "File CSV số liệu hàng tháng (có mẫu) — dữ liệu đơn lẻ mạnh nhất", "v5.need.mrr": "MRR hiện tại và 6 hoặc 12 tháng trước", "v5.need.customers": "Số khách trả tiền hiện nay và một năm trước",
  "v5.need.target": "Bạn bán cho ai và có bao nhiêu khách như vậy", "v5.need.price": "Giá trung bình mỗi khách mỗi năm", "v5.need.geo": "Nơi bạn bán hàng",
  "v5.need.ip": "Bằng sáng chế, nhãn hiệu hoặc giấy phép kèm số hiệu", "v5.need.integrations": "Số công cụ bạn tích hợp", "v5.need.licences": "Hợp đồng hoặc đối tác độc quyền",
  "v5.need.rt.early": "Ở giai đoạn {s} chưa cần số liệu giữ chân: bằng chứng sản phẩm được dùng thay.", "v5.need.pilots": "Thử nghiệm có trả phí và thư ý định mua", "v5.need.reviews": "Điểm đánh giá trên kho ứng dụng hoặc trang review",
  "v5.need.csvmov": "CSV số liệu có MRR mới / mở rộng / mất theo tháng", "v5.need.nrr": "Tỷ lệ giữ chân doanh thu ròng (NRR)", "v5.need.churn": "Số khách rời bỏ mỗi tháng", "v5.need.cohort": "Tỷ lệ giữ chân tháng 3 và tháng 12",
  "v5.tr.mrr": "Doanh thu định kỳ hàng tháng", "v5.tr.rev": "Doanh thu hàng tháng", "v5.tr.metrics": "Từng chỉ số so với giai đoạn", "v5.tr.metrics.p": "Chấm tròn là bạn; dải tô là nửa giữa các công ty cùng giai đoạn; vạch đậm là mức điển hình.",
  "v5.tr.how": "Tăng trưởng = quy mô doanh thu 30% + tốc độ tăng 40% + khách hàng 15% + tín hiệu tương lai 15%. Tốc độ tăng tính theo năm khi có 12 tháng dữ liệu, nếu không thì theo tháng.",
  "v5.mk.h": "Quy mô thị trường", "v5.mk.tam": "toàn thị trường (từ trên xuống, có trích nguồn)", "v5.mk.sam": "phần bạn phục vụ được (từ dưới lên)", "v5.mk.som": "phần bạn có thể giành trong 5 năm",
  "v5.mk.som.r": "{lo} – {hi} trong 5 năm", "v5.mk.som.s": "{a}–{b} của SAM", "v5.mk.logscale": "Độ rộng thanh theo thang log để thị trường nhỏ vẫn nhìn thấy.",
  "v5.mk.bu": "Từ dưới lên: số khách × giá", "v5.mk.cust": "Khách hàng mục tiêu", "v5.mk.price": "Giá mỗi năm", "v5.mk.td": "Số liệu từ trên xuống (đối chiếu)", "v5.mk.cagr": "Tăng trưởng thị trường mỗi năm",
  "v5.mk.abs": "Số doanh nghiệp theo ABS", "v5.mk.tier": "Nguồn tốt nhất", "v5.tier.0": "không rõ", "v5.tier.1": "cơ quan nhà nước", "v5.tier.2": "hiệp hội ngành hoặc báo cáo công ty niêm yết", "v5.tier.3": "báo cáo phân tích (thông cáo)", "v5.tier.4": "blog hoặc nhà cung cấp",
  "v5.mo.radar": "Lợi thế cạnh tranh (7 Powers)", "v5.mo.radar.p": "Mỗi lợi thế được xếp 0–3: không có, tự nêu, thể hiện công khai, kiểm chứng qua sổ đăng ký hoặc tài liệu.",
  "v5.mo.grid": "Bằng chứng cho từng lợi thế", "v5.mo.level": "mức {l}/3", "v5.mo.l0": "không có", "v5.mo.l1": "tự nêu", "v5.mo.l2": "công khai", "v5.mo.l3": "đã kiểm chứng",
  "v5.mo.computed": "tính từ đối thủ: {s}/100", "v5.mo.comp": "Vốn đã gọi của đối thủ (triệu A$)", "v5.mo.comp.p": "Đối thủ trực tiếp có nhiều vốn làm giảm điểm cạnh tranh.",
  "v5.mo.how": "Lợi thế = hiệu ứng mạng 20% + chi phí chuyển đổi 20% + sở hữu trí tuệ & dữ liệu 15% + quy mô 10% + thương hiệu 10% + định vị ngược 10% + cạnh tranh 15%. Chỉ founder tự nêu thì tối đa mức 1.",
  "v5.pw.network_effects": "Hiệu ứng mạng", "v5.pw.switching_costs": "Chi phí chuyển đổi", "v5.pw.ip_data": "Sở hữu trí tuệ & dữ liệu", "v5.pw.scale": "Quy mô", "v5.pw.brand": "Thương hiệu", "v5.pw.counter_positioning": "Định vị ngược", "v5.pw.competition": "Cạnh tranh",
  "v5.rt.cohort": "Khách còn hoạt động, theo tháng bắt đầu", "v5.rt.cohort.p": "Mỗi đường theo một nhóm khách từ tháng họ bắt đầu.",
  "v5.rt.conc.flag": "Khách lớn nhất chiếm {p} doanh thu: rủi ro tập trung.", "v5.rt.conc.high": "Khách lớn nhất chiếm {p} doanh thu: rủi ro tập trung cao.",
  "v5.rt.how": "Giữ chân = NRR 30% + GRR 25% + giữ chân sử dụng 20% + đánh giá / NPS 15% + mức tập trung khách hàng 10%, so chuẩn theo quy mô hợp đồng trước, rồi đến giai đoạn.",
  "v5.ev.levels": "Các con số được kiểm chứng thế nào", "v5.ev.levels.p": "{n} chỉ số trên mọi nhóm, theo mức kiểm chứng.",
  "v5.ev.flags": "Kiểm tra tính nhất quán", "v5.ev.act.lower_used": "đã dùng số thấp hơn", "v5.ev.act.capped": "bị giới hạn khi chấm điểm", "v5.ev.act.review": "chuyển người duyệt",
  "v5.ev.docs": "Tài liệu đã dùng", "v5.ev.lookups": "Tra cứu công khai miễn phí", "v5.ev.dropped": "Số liệu không kiểm chứng được ({n})", "v5.ev.analysts": "Kết quả của từng hạng mục",
  "v5.an.traction": "Tăng trưởng", "v5.an.market_size": "Quy mô thị trường", "v5.an.moat": "Lợi thế", "v5.an.retention": "Giữ chân", "v5.an.deck": "Pitch deck",
  "v5.va.h": "Chúng tôi đi đến giá trị này thế nào", "v5.va.p": "Mỗi thanh là khoảng giá trị của một phương pháp; đường đen là giá trị tổng hợp, dải vàng là khoảng cuối cùng. Bằng chứng tốt hơn được tính nhiều hơn.",
  "v5.va.ff": "Giá trị theo phương pháp", "v5.va.methods": "Từng phương pháp", "v5.va.excluded": "Không dùng trong kết quả tổng hợp", "v5.va.nochecks": "Không thấy vấn đề ở dữ liệu đầu vào của phương pháp này.",
  "v5.va.inputs": "Mọi dữ liệu đầu vào ({n})", "v5.va.weights": "Trọng số của các phương pháp", "v5.va.weights.p": "Trọng số theo giai đoạn × chất lượng bằng chứng, rồi chia lại thành 100%. Phương pháp quá xa các phương pháp khác bị loại.",
  "v5.va.legal": "Giá trị tham khảo, không phải định giá chính thức hay tư vấn tài chính.", "v5.va.params": "tham số {v}", "v5.va.stagefallback": "Dự phòng theo giai đoạn: giá trị điển hình của {s}, chỉ dùng khi không có gì khác.",
  "v5.ff.mid": "giữa", "v5.ff.excl": "không dùng", "v5.ff.counts": "chiếm {w}%", "v5.ff.uncapped": "Dự báo gốc của bạn cho ra {v} (trước khi áp giới hạn).",
  "v5.ff.lg.range": "Khoảng của phương pháp", "v5.ff.lg.blend": "Giá trị tổng hợp", "v5.ff.lg.band": "Khoảng cuối cùng", "v5.ff.lg.offer": "Giá trị đã chốt", "v5.ff.lg.off": "Không dùng",
  "v5.ff.offer": "Giá trị đã chốt", "v5.ff.log": "Thang log: các phương pháp cách xa nhau.", "v5.ff.aria": "Biểu đồ football field: giá trị tổng hợp {v}, khoảng {lo} đến {hi}",
  "v5.proj.label": "Dựa trên dự báo của ban điều hành (chưa kiểm toán, BlockID không kiểm chứng).", "v5.proj.without": "Nếu không dùng dự báo: {v}.",
  "v5.m.market_anchor": "Giá của chính công ty", "v5.m.revenue_multiple": "Hệ số doanh thu", "v5.m.stage_scorecard": "Dự phòng theo giai đoạn", "v5.m.ebitda_multiple": "Hệ số EBITDA", "v5.m.precedents": "Thương vụ tương tự",
  "v5.m.dcf": "Dòng tiền chiết khấu", "v5.m.vc_method": "Phương pháp VC", "v5.m.scorecard": "Scorecard", "v5.m.berkus": "Berkus", "v5.m.rfs": "Yếu tố rủi ro", "v5.m.first_chicago": "Kịch bản",
  "v5.md.market_anchor": "vòng gọi vốn, giao dịch cổ phần hoặc giá thị trường gần nhất", "v5.md.revenue_multiple": "doanh thu × mức giá các công ty tương tự trên mỗi đồng doanh thu", "v5.md.stage_scorecard": "giá trị điển hình ở giai đoạn này",
  "v5.md.ebitda_multiple": "EBITDA × hệ số của công ty tương đương", "v5.md.precedents": "giá đã trả trong các thương vụ mua bán tương tự", "v5.md.dcf": "dòng tiền tương lai quy về hôm nay",
  "v5.md.vc_method": "giá trị khi thoái vốn ÷ lợi nhuận nhà đầu tư cần", "v5.md.scorecard": "định giá điển hình × mức so sánh theo từng nhóm", "v5.md.berkus": "tối đa một khoản cố định cho mỗi trong 5 cột mốc",
  "v5.md.rfs": "giá trị điển hình điều chỉnh theo 12 rủi ro", "v5.md.first_chicago": "dòng tiền trong kịch bản xấu, cơ sở và tốt, có trọng số",
  "v5.dcf.fcff": "Dòng tiền tự do", "v5.dcf.revenue": "Doanh thu", "v5.dcf.ebitda": "EBITDA", "v5.dcf.build": "Cấu thành lãi suất chiết khấu", "v5.dcf.rf": "Lãi suất phi rủi ro", "v5.dcf.beta": "Beta",
  "v5.dcf.erp": "Phần bù rủi ro cổ phần", "v5.dcf.crp": "Rủi ro quốc gia", "v5.dcf.size": "Phần bù quy mô", "v5.dcf.rate": "Lãi suất chiết khấu", "v5.dcf.g": "Tăng trưởng dài hạn", "v5.dcf.exitm": "Hệ số thoái vốn",
  "v5.dcf.terminal": "Giá trị cuối kỳ", "v5.dcf.t.gordon": "tăng trưởng đều mãi mãi", "v5.dcf.t.exit": "bán theo hệ số thoái vốn", "v5.dcf.ev": "Giá trị doanh nghiệp", "v5.dcf.nd": "Nợ ròng",
  "v5.dcf.tv": "Bao nhiêu đến từ giá trị cuối kỳ", "v5.dcf.tv.pv": "Các năm dự báo", "v5.dcf.tv.tv": "Giá trị cuối kỳ", "v5.dcf.tv.aria": "Giá trị cuối kỳ chiếm {p} giá trị",
  "v5.dcf.tv.high": "Hơn 75% đến từ giá trị cuối kỳ: kết quả phụ thuộc nhiều vào dài hạn.", "v5.dcf.tv.ok": "Phần lớn hợp lý đến từ các năm dự báo.",
  "v5.dcf.sens": "Độ nhạy", "v5.dcf.sens.p": "Giá trị nếu lãi suất chiết khấu (hàng) hoặc tăng trưởng dài hạn (cột) thay đổi một chút. Ô có viền là kịch bản cơ sở.",
  "v5.dcf.lower": "thấp hơn cơ sở", "v5.dcf.base": "gần cơ sở", "v5.dcf.higher": "cao hơn cơ sở",
  "v5.fc.bad": "Kịch bản xấu", "v5.fc.base": "Kịch bản cơ sở", "v5.fc.good": "Kịch bản tốt",
  "v5.cm.rev": "Doanh thu", "v5.cm.ebitda": "EBITDA", "v5.cm.mult": "Hệ số", "v5.cm.disc": "Chiết khấu công ty tư nhân", "v5.cm.val": "Giá trị", "v5.cm.peers": "Công ty tương đương",
  "v5.cm.deals": "Thương vụ tương tự", "v5.cm.median": "hệ số được dùng", "v5.cm.band": "Khoảng trích dẫn {lo}× / {mid}× / {hi}×",
  "v5.vc.exitrev": "Giá trị thoái vốn sau {y} năm: {r} × {m}", "v5.vc.ret": "Phần còn lại sau các vòng sau ({p})", "v5.vc.irr": "÷ (1 + {p}) trong {y} năm = giá trị hôm nay", "v5.vc.div": "÷ mức lợi nhuận mục tiêu {m}× ({lo}–{hi}×) = giá trị sau vòng",
  "v5.vc.raise": "− số tiền gọi vốn", "v5.vc.pre": "Giá trị trước vòng",
  "v5.sc.p": "Định giá điển hình {b} × hệ số của bạn {f}. Điểm 50 là điển hình cho giai đoạn.", "v5.sc.avg": "điển hình (50)",
  "v5.bk.p": "Tối đa {c} cho mỗi cột mốc.", "v5.bk.sound_idea": "Ý tưởng tốt", "v5.bk.prototype": "Nguyên mẫu", "v5.bk.quality_team": "Đội ngũ chất lượng", "v5.bk.strategic_relationships": "Quan hệ chiến lược", "v5.bk.product_rollout": "Ra mắt sản phẩm",
  "v5.rfs.p": "Mức gốc {b}; mỗi bậc lên hoặc xuống thay đổi {s} (tổng {n}).", "v5.rfs.minus": "rủi ro làm giảm giá trị", "v5.rfs.plus": "điểm mạnh làm tăng giá trị",
  "v5.rfs.management": "Ban điều hành", "v5.rfs.stage": "Giai đoạn kinh doanh", "v5.rfs.legislation": "Pháp lý / chính trị", "v5.rfs.manufacturing": "Sản xuất", "v5.rfs.sales_marketing": "Bán hàng & marketing",
  "v5.rfs.funding": "Nguồn vốn", "v5.rfs.competition": "Cạnh tranh", "v5.rfs.technology": "Công nghệ", "v5.rfs.litigation": "Kiện tụng", "v5.rfs.international": "Quốc tế", "v5.rfs.reputation": "Uy tín", "v5.rfs.exit": "Khả năng thoái vốn",
  "v5.sev.error": "Cần sửa", "v5.sev.warning": "Cảnh báo", "v5.sev.info": "Ghi chú",
  "v5.fn.h": "Chốt giá trị và giá", "v5.fn.p": "Ba bước ngắn. Kết quả được cố định và dùng để thiết lập cổ phần và mọi đợt chào bán.",
  "v5.fn.s1": "Xem lại giá trị", "v5.fn.s2": "Chọn giá mỗi cổ phần", "v5.fn.s3": "Xác nhận",
  "v5.fn.wait": "Bạn có thể chốt sau khi người duyệt phê duyệt định giá.", "v5.fn.owner": "Chỉ chủ doanh nghiệp hoặc admin nền tảng mới chốt được.",
  "v5.fn.lowconf": "Độ tin cậy thấp: thêm tài liệu để nâng lên, hoặc nhờ admin nền tảng chốt kèm lý do.", "v5.fn.lowconf.adm": "Độ tin cậy thấp: là admin, bạn có thể chốt kèm lý do bằng văn bản.",
  "v5.fn.lowconf.h": "Chốt dù độ tin cậy thấp", "v5.fn.override": "Vì sao an toàn để chốt (admin)", "v5.fn.confok": "Độ tin cậy đủ để chốt.",
  "v5.fn.s1.p": "Giá trị đã chốt có hiệu lực {d} ngày. Sau đó, hoặc nếu báo cáo thay đổi, cần chốt lại.",
  "v5.fn.recprice": "Đề xuất cho công ty {s}", "v5.fn.recprice.s": "Giá đề xuất", "v5.fn.yourprice": "Giá mỗi cổ phần của bạn", "v5.fn.reset": "Dùng giá đề xuất",
  "v5.fn.dev0": "Đề xuất", "v5.fn.dev": "{d} so với đề xuất", "v5.fn.bad": "Nhập giá từ {lo} đến {hi}.", "v5.fn.few": "Với giá này bạn sẽ có ít hơn {n} cổ phần: hãy chọn giá thấp hơn.",
  "v5.fn.zone.free": "Trong ±{b}: áp dụng ngay", "v5.fn.zone.adm": "Cần admin phê duyệt", "v5.fn.zone.rec": "Đề xuất",
  "v5.fn.shares": "Số cổ phần", "v5.fn.existing": "cổ phần hiện có (pha loãng hoàn toàn)", "v5.fn.newco": "cho sổ cổ đông mới",
  "v5.fn.offer": "Khoảng giá chào bán", "v5.fn.offer.p": "từ mức thấp của giá trị đến giá của bạn", "v5.fn.implied": "Số cổ phần × giá", "v5.fn.implied.p": "giá trị hợp lý là {v}", "v5.fn.value": "Giá trị hợp lý",
  "v5.fn.raise": "Số tiền dự định gọi vốn (xem trước)", "v5.fn.raise.p": "Chỉ để xem trước tỷ lệ sở hữu; không lưu.", "v5.fn.raise.pj": "Lấy từ dự báo của bạn; đổi để xem thử mức khác (không lưu).",
  "v5.fn.split": "Ai sở hữu doanh nghiệp sau khi gọi vốn", "v5.fn.founders": "Chủ sở hữu hiện tại", "v5.fn.investors": "Nhà đầu tư mới", "v5.fn.post": "Giá trị sau khi gọi vốn: {v}.",
  "v5.fn.needadmin": "Giá này cần admin nền tảng phê duyệt", "v5.fn.needadmin.p": "Giá lệch hơn {b} so với đề xuất. Hãy giải thích; một admin khác sẽ xem xét.",
  "v5.fn.reason": "Lý do", "v5.fn.reason.ph": "ví dụ: term sheet đã ký định giá vòng ở A$0,40 mỗi cổ phần", "v5.fn.reason.min": "Tối thiểu {n} ký tự (hiện có {c}).",
  "v5.fn.note": "Ghi chú (không bắt buộc)", "v5.fn.note.req": "Vì sao chọn giá này", "v5.fn.note.ph": "ví dụ: số tròn cho nhà đầu tư", "v5.fn.note.p": "Được lưu cùng giá trị đã chốt.", "v5.fn.note.min": "Cần ghi chú ngắn khi đổi giá (từ 3 ký tự).",
  "v5.fn.valid": "Hiệu lực", "v5.fn.valid.v": "{d} ngày, đến khoảng {until}", "v5.fn.goesadmin": "Yêu cầu này được gửi tới admin nền tảng. Kết quả sẽ hiện ở đây.",
  "v5.fn.attest": "Tôi xác nhận giá trị và giá này. Tôi hiểu giá trị chỉ mang tính tham khảo, có hiệu lực {d} ngày và được dùng để thiết lập sổ cổ đông.",
  "v5.fn.next": "Tiếp", "v5.fn.submit": "Chốt", "v5.fn.submitadm": "Gửi phê duyệt",
  "v5.fn.expired": "Giá trị đã chốt quá {d} ngày. Hãy chốt lại với báo cáo hiện tại.", "v5.fn.stale": "Báo cáo đã thay đổi sau khi chốt. Hãy chốt lại.", "v5.fn.again": "Chốt lại",
  "v5.fz.st.valid": "Đã chốt", "v5.fz.st.expired": "Hết hạn", "v5.fz.st.stale": "Đã lỗi thời", "v5.fz.st.none": "Chưa chốt",
  "v5.fz.until": "hiệu lực đến {d}", "v5.fz.ended": "hết hạn {d}", "v5.fz.value": "Giá trị hợp lý", "v5.fz.price": "Giá mỗi cổ phần", "v5.fz.rec": "đề xuất {p} · {d}",
  "v5.fz.shares": "Số cổ phần", "v5.fz.offer": "Khoảng giá chào bán", "v5.fz.note": "Ghi chú", "v5.fz.reason": "Lý do", "v5.fz.approvedby": "phê duyệt bởi {a}", "v5.fz.override": "Chốt khi độ tin cậy thấp bởi {a}: {r}",
  "v5.fz.at": "Chốt lúc {d}", "v5.fz.hash": "báo cáo {h}", "v5.fz.gate": "Mở mục phê duyệt của admin", "v5.fz.next": "Thiết lập cổ phần",
  "v5.pr.h": "Giá đang chờ phê duyệt", "v5.pr.p": "Một admin nền tảng khác bạn sẽ phê duyệt hoặc từ chối. Giá đề xuất vẫn dùng được.", "v5.pr.at": "Đã gửi {d}", "v5.pr.cancel": "Huỷ yêu cầu",
  "v5.hint.final": "Theo đề xuất đã chốt: {n} cổ phần, giá {p} mỗi cổ phần (hiệu lực đến {d}).", "v5.hint.first": "Hãy chốt giá trị và giá trước: số cổ phần và giá lấy từ đó.",
  "v5.hint.pending": "Giá của bạn đang chờ admin nền tảng phê duyệt.", "v5.hint.expired": "Giá trị đã chốt đã hết hạn hoặc lỗi thời: hãy chốt lại.",
  "v5.up.h": "Tải lên pitch deck hoặc CSV số liệu", "v5.up.p": "Được đọc ngay trong trình duyệt: chúng tôi giữ văn bản và dấu vân tay (SHA-256) của file, không bao giờ giữ file.",
  "v5.up.lvl": "Số liệu khớp với tài liệu được tính là có tài liệu.", "v5.up.tpl": "Tải mẫu CSV số liệu", "v5.up.pick": "Chọn file",
  "v5.up.type": "Dùng file PDF, CSV, Markdown hoặc văn bản (lưu slide dưới dạng PDF).", "v5.up.size": "File quá lớn (tối đa {m}).", "v5.up.read": "Không đọc được file này.",
  "v5.up.deck": "Pitch deck", "v5.up.csv": "CSV số liệu", "v5.up.fin": "Báo cáo tài chính", "v5.up.pages": "{n} trang",
  "v5.up.st.ready": "sẵn sàng", "v5.up.st.queued": "gửi sau khi bắt đầu", "v5.up.st.sending": "đang gửi…", "v5.up.st.sent": "đã thêm", "v5.up.st.error": "sửa rồi thử lại",
  "v5.up.remove": "Xoá {f}", "v5.up.clean": "Không thấy vấn đề.", "v5.up.months": "Số tháng", "v5.up.lastmrr": "MRR {m}", "v5.up.yoy": "Tăng trưởng theo năm",
  "v5.up.addh": "Thêm hoặc cập nhật dữ liệu", "v5.up.addp": "Tải tài liệu lên rồi chấm lại: chỉ chạy lại các bước kiểm tra, không tìm kiếm web mới.", "v5.up.rescore": "Chấm lại với dữ liệu mới", "v5.up.rescored": "Đã chấm lại. Báo cáo giờ dùng tài liệu của bạn.",
  "v5.pj.h": "Thêm dự báo của bạn (không bắt buộc)", "v5.pj.opt": "không bắt buộc", "v5.pj.p": "Dự báo 3–5 năm mở khoá phương pháp dòng tiền và phương pháp VC. Luôn được ghi rõ là dự báo của ban điều hành, chưa kiểm toán.",
  "v5.pj.s1": "Tải mẫu", "v5.pj.s2": "Tải lên và kiểm tra", "v5.pj.s3": "Xác nhận", "v5.pj.tpl.csv": "Mẫu (CSV)", "v5.pj.tpl.xlsx": "Mẫu (Excel)",
  "v5.pj.pick": "Chọn file dự báo", "v5.pj.drop": "Thả file mẫu đã điền vào đây (.xlsx hoặc .csv, tối đa 512 KB).",
  "v5.pj.macro": "Không nhận file có macro (.xlsm, .xls): hãy lưu thành .xlsx.", "v5.pj.type": "Dùng mẫu .xlsx hoặc .csv.",
  "v5.pj.gm": "Biên lợi nhuận gộp", "v5.pj.clean": "Mọi kiểm tra đều đạt.", "v5.pj.check": "Tải lên và kiểm tra", "v5.pj.confirm": "Xác nhận dự báo", "v5.pj.confirmed": "Đã xác nhận",
  "v5.pj.attest": "Đây là dự báo của ban điều hành, được lập cẩn trọng hợp lý. Tôi hiểu BlockID không kiểm chứng dự báo này.",
  "v5.pj.queued": "Sẽ được tải lên và xác nhận sau khi bạn bắt đầu", "v5.pj.server": "Kiểm tra của máy chủ: {e} lỗi cần sửa, {w} cảnh báo (cảnh báo áp giới hạn và giảm trọng số của dự báo).",
  "v5.pj.done": "Đã xác nhận dự báo. Giá trị đã được tính lại.", "v5.pj.moved": "Đã xác nhận dự báo. Giá trị {a} → {b} ({p}).", "v5.pj.back": "Thay đổi hơn 5% nên được chuyển lại người duyệt.",
  "v5.pj.r.year": "Năm tài chính kết thúc (YYYY)", "v5.pj.r.actual": "Thực tế (A) hay Dự báo (P)", "v5.pj.r.revenue": "Doanh thu", "v5.pj.r.cogs": "Giá vốn", "v5.pj.r.opex": "Chi phí hoạt động (trừ khấu hao)",
  "v5.pj.r.ebitda": "EBITDA (để đối chiếu, không bắt buộc)", "v5.pj.r.d_and_a": "Khấu hao", "v5.pj.r.tax": "Thuế thu nhập đã nộp (không bắt buộc)", "v5.pj.r.capex": "Chi đầu tư",
  "v5.pj.r.nwc": "Vốn lưu động ròng (không bắt buộc)", "v5.pj.r.headcount": "Nhân viên (không bắt buộc)", "v5.pj.r.customers": "Khách trả tiền (không bắt buộc)", "v5.pj.r.currency": "Tiền tệ",
  "v5.pj.r.fiscal_year_end": "Ngày kết thúc năm tài chính (MM-DD)", "v5.pj.r.cash": "Tiền mặt", "v5.pj.r.debt": "Nợ", "v5.pj.r.shares_fd": "Số cổ phần (pha loãng hoàn toàn)", "v5.pj.r.planned_raise": "Dự định gọi vốn", "v5.pj.r.audited": "Đã kiểm toán (Y/N)",
  "v5.chk.csv.empty": "File không có dòng dữ liệu.", "v5.chk.csv.nomonth": "Thêm cột 'month' (YYYY-MM).", "v5.chk.csv.norev": "Thêm cột 'mrr_aud' hoặc 'revenue_aud'.",
  "v5.chk.csv.rows": "Tối đa {n} dòng.", "v5.chk.csv.badmonth": "Dòng {r}: '{v}' không phải tháng (dùng YYYY-MM).", "v5.chk.csv.nan": "Dòng {r}: {c} không phải số.",
  "v5.chk.csv.neg": "Dòng {r}: {c} là số âm.", "v5.chk.csv.dup": "Dòng {r}: {m} xuất hiện hai lần.", "v5.chk.csv.future": "Dòng {r}: {m} là tháng trong tương lai.",
  "v5.chk.csv.smooth": "Tăng trưởng gần như đều tuyệt đối qua từng tháng: người duyệt sẽ xem xét.", "v5.chk.csv.nrrgrr": "NRR thấp hơn GRR: kiểm tra cột mở rộng và rời bỏ.",
  "v5.chk.csv.short": "Chỉ có {n} tháng: từ 6 tháng trở lên cho tốc độ tăng trưởng đáng tin hơn.",
  "v5.chk.pj.missingrow": "Thiếu dòng '{k}'.", "v5.chk.pj.badyear": "'{v}' không phải năm.", "v5.chk.pj.missing": "Thiếu '{k}' cho năm {y}.", "v5.chk.pj.neg": "'{k}' âm trong năm {y}.",
  "v5.chk.pj.ap": "Đánh dấu năm {y} là A (thực tế) hoặc P (dự báo).", "v5.chk.pj.gap": "Các năm phải liên tiếp: {y} bị lệch thứ tự.", "v5.chk.pj.few": "Cần ít nhất 3 năm dự báo (hiện có {n}).",
  "v5.chk.pj.noactual": "Thêm năm thực tế gần nhất giúp dự báo đáng tin hơn.", "v5.chk.pj.identity": "EBITDA năm {y} không khớp: ghi {g}, tính từ các dòng trên là {c}.",
  "v5.chk.pj.gm": "Biên lợi nhuận gộp {p}% năm {y} nằm ngoài mức thường gặp {lo}–{hi}% của ngành.", "v5.chk.pj.growth": "Doanh thu tăng {g}% năm {y}; chúng tôi sẽ dùng {c}% (giới hạn của giai đoạn).",
  "v5.chk.pj.jump": "Doanh thu năm {y} cao hơn 3 lần năm thực tế gần nhất.", "v5.chk.pj.capex": "Chi đầu tư dài hạn thấp hơn một nửa khấu hao.", "v5.chk.pj.tax": "Không có dòng thuế: sẽ dùng thuế suất doanh nghiệp tiêu chuẩn.",
  "v5.chk.pj.currency": "Chưa hỗ trợ tiền tệ {c}.", "v5.chk.pj.xlsx": "File Excel được máy chủ kiểm tra sau khi tải lên.",
  "v5.chk.deck.scan": "Tìm thấy rất ít chữ — đây có phải deck dạng ảnh quét? Hãy lưu kèm chữ, hoặc nhập số liệu vào biểu mẫu.", "v5.chk.deck.cut": "Chỉ dùng {n} ký tự đầu tiên.",
  "v5.in.h": "Thêm số liệu và tài liệu (không bắt buộc, giúp chính xác hơn)", "v5.in.h.list": "Thêm số liệu và tài liệu (không bắt buộc, giúp hồ sơ niêm yết tốt hơn)",
  "v5.in.p": "Chỉ những câu hỏi quan trọng ở giai đoạn của bạn. Mọi số bạn nhập được ghi là tự khai; có tài liệu khớp sẽ thành có tài liệu.",
  "v5.in.s0": "Giai đoạn", "v5.in.s1": "Doanh thu & khách hàng", "v5.in.s2": "Giữ chân & hiệu quả", "v5.in.s3": "Thị trường & lợi thế", "v5.in.s4": "Tài liệu",
  "v5.in.looks": "Có vẻ là:", "v5.in.youchose": "bạn chọn {s}", "v5.in.change": "Đổi giai đoạn",
  "v5.in.basis.round": "Theo vòng gọi vốn gần nhất.", "v5.in.basis.revenue": "Theo doanh thu.", "v5.in.basis.raised": "Theo số vốn đã gọi.",
  "v5.in.basis.conflict": "Vòng gọi vốn và doanh thu chỉ ra hai giai đoạn khác nhau: dùng giai đoạn thấp hơn.", "v5.in.basis.listing": "Theo việc niêm yết.", "v5.in.basis.hint": "Phỏng đoán ban đầu.",
  "v5.in.basis.default": "Phỏng đoán ban đầu — nhập doanh thu hoặc vòng gọi vốn gần nhất để xác nhận.",
  "v5.in.stagep": "Chọn giai đoạn chỉ thay đổi các câu hỏi bạn thấy. Báo cáo xác định giai đoạn từ bằng chứng và người duyệt có thể thay đổi.",
  "v5.in.l1": "số bạn nhập", "v5.in.l2": "khi có tài liệu khớp", "v5.in.files": "{n} file", "v5.in.done": "Xong — hãy bắt đầu đánh giá ở trên.",
  "v5.f.bad": "Kiểm tra lại giá trị này.",
  "v5.g.revenue": "Doanh thu & tăng trưởng", "v5.g.revenue.p": "dùng cho Tăng trưởng", "v5.g.customers": "Khách hàng & cơ hội", "v5.g.customers.p": "dùng cho Tăng trưởng và Giữ chân",
  "v5.g.retention": "Giữ chân", "v5.g.retention.p": "dùng cho Giữ chân", "v5.g.efficiency": "Tiền mặt & hiệu quả", "v5.g.efficiency.p": "dùng cho Hiệu quả vốn",
  "v5.g.market": "Thị trường", "v5.g.market.p": "dùng cho Thị trường", "v5.g.moat": "Lợi thế", "v5.g.moat.p": "dùng cho Lợi thế", "v5.g.round": "Vòng gần nhất", "v5.g.round.p": "xác định giai đoạn và mốc giá của chính công ty",
  "v5.opt.subscription": "Thuê bao", "v5.opt.transactional": "Theo giao dịch", "v5.opt.marketplace": "Sàn giao dịch", "v5.opt.services": "Dịch vụ", "v5.opt.hardware": "Phần cứng", "v5.opt.other": "Khác",
  "v5.opt.pre-seed": "Tiền hạt giống", "v5.opt.angel": "Thiên thần", "v5.opt.seed": "Hạt giống", "v5.opt.series-a": "Series A", "v5.opt.series-b": "Series B", "v5.opt.series-c": "Series C trở lên",
  "v5.opt.grant": "Tài trợ", "v5.opt.safe": "SAFE / trái phiếu chuyển đổi",
  "v5.ad.h": "Phê duyệt giá cổ phần", "v5.ad.q": "Giá cổ phần",
  "v5.ad.d": "Giá mỗi cổ phần lệch hơn 20% so với đề xuất theo giai đoạn. Một admin khác người gửi sẽ quyết định.",
  "v5.ad.p": "Founder chọn giá ngoài ±20% so với đề xuất. Đối chiếu lý do với báo cáo trước khi phê duyệt.",
  "v5.ad.req": "Giá đề nghị", "v5.ad.by": "Người gửi", "v5.ad.note": "Ghi chú (bắt buộc khi từ chối, từ 5 ký tự)", "v5.ad.reason5": "Viết lý do ít nhất 5 ký tự để từ chối.",
  "v5.ad.approve": "Phê duyệt giá này", "v5.ad.reject": "Từ chối", "v5.ad.approved": "Đã duyệt giá: giá trị đã được chốt.", "v5.ad.rejected": "Đã từ chối giá: founder đã được báo.",
  "v5.ad.empty": "Không có giá cổ phần nào chờ duyệt.", "v5.ad.open": "Mở báo cáo", "v5.ad.mine": "Bạn đã gửi yêu cầu này: admin khác phải quyết định.",
  "v5.ad.return": "Bạn đến đây từ luồng của founder.", "v5.ad.track": "Đề xuất {r}, đề nghị {p} ({d})",
  "ad.q.pricing": "Giá cổ phần", "ad.d.pricing": "Giá mỗi cổ phần lệch hơn 20% so với đề xuất theo giai đoạn. Một admin khác người gửi sẽ quyết định.",
  "v5.of.final": "Giá trị đã chốt: {p} mỗi cổ phần (khoảng chào bán {lo} – {hi}), hiệu lực đến {d}.", "v5.of.expired": "Giá trị đã chốt đã hết hạn hoặc lỗi thời: hãy chốt lại trước khi gửi.",
};
