/**
 * Founding team review strings (hr.blockid.au + the "Founding team" card on eth.blockid.au). docs/PLAN-HR.md Phase H2.
 * Plain words. "AI" appears in one pitch line only (hr.home.ai). We check "public professional information".
 * VI must cover every EN key (checked by the type).
 */
export const hrEn = {
  // the founder dimension of the business score is the founding team
  "dim.founder": "Founding team",

  "hr.brand": "BlockID HR",
  "hr.title": "Founding team review",
  "hr.nav.new": "Review a team",
  "hr.nav.me": "My reports",
  "hr.nav.how": "How scores work",
  "hr.nav.eth": "Business valuations",
  "hr.foot.site": "BlockID HR · hr.blockid.au",
  "hr.foot.remove": "Listed in a report and want your details removed? Write to info@blockid.au.",
  "hr.foot.eth": "Business valuation on eth.blockid.au",

  "hr.home.eyebrow": "Founding team review",
  "hr.home.h1a": "Know the people",
  "hr.home.h1b": "behind the business",
  "hr.home.pitch": "Investors back people first. List the founding team and we check each person's public professional information (roles, past ventures, results) against the sources, then score the team.",
  "hr.home.ai": "An AI research assistant reads the sources; every score comes from fixed rules and every fact links to the page it came from.",
  "hr.home.cta": "Review a founding team",
  "hr.home.mine": "My reports",
  "hr.home.legal": "Advisory only. Public professional information only, and only with the people's agreement.",
  "hr.home.card.label": "Example team report",
  "hr.home.card.example": "example",
  "hr.how.eyebrow": "How it works",
  "hr.how.h2": "Three steps, a few minutes",
  "hr.how.1h": "List the people",
  "hr.how.1p": "Name, role, start year, equity and public links such as LinkedIn or a company bio page.",
  "hr.how.2h": "We check the public record",
  "hr.how.2p": "Each claim is matched to a page that names the person. Anything we cannot match is marked unconfirmed.",
  "hr.how.3h": "Get the team report",
  "hr.how.3p": "A team score, each person's strengths and gaps, and the questions an investor should ask.",
  "hr.what.eyebrow": "What we score",
  "hr.what.h2": "Each person, then the team as a whole",
  "hr.what.p": "Every person gets a score from 0 to 100 built from six parts. The team score adds how well the people fit together.",
  "hr.priv.eyebrow": "Privacy",
  "hr.priv.h2": "Professional facts only, with consent",
  "hr.priv.1": "Whoever asks for a review confirms the people listed agreed to it.",
  "hr.priv.2": "We only look at public professional information: roles, companies, education, publications and awards.",
  "hr.priv.3": "We never collect health, religion, politics, family, home address, phone numbers or personal email.",
  "hr.priv.4": "Anyone listed can ask for their details to be removed at info@blockid.au.",
  "hr.home.final.h": "Valuing a business?",
  "hr.home.final.p": "The founding team carries 30% of the business score on eth.blockid.au. Link the team review to the valuation and the score updates.",
  "hr.home.final.btn": "Start a business valuation",

  "hr.sub.domain_fit": "Industry know-how",
  "hr.sub.domain_fit.d": "Knows the industry and the customers this business serves.",
  "hr.sub.track_record": "Track record",
  "hr.sub.track_record.d": "Past ventures, exits and the size of what they ran.",
  "hr.sub.leadership": "Leadership & role fit",
  "hr.sub.leadership.d": "Has led teams and fits the role they hold now.",
  "hr.sub.functional_depth": "Depth in their field",
  "hr.sub.functional_depth.d": "Real depth in technology, sales or finance.",
  "hr.sub.verifiability": "Claims we could confirm",
  "hr.sub.verifiability.d": "How much of what was said is backed by a public source.",
  "hr.sub.commitment": "Commitment",
  "hr.sub.commitment.d": "Full-time, holds equity, and has been there a while.",
  "hr.comp.complementarity": "Skills cover each other",
  "hr.comp.key_roles": "Key roles filled",
  "hr.comp.worked_together": "Worked together before",
  "hr.comp.advisors_board": "Advisors and board",
  "hr.comp.concentration": "Not reliant on one person",
  "hr.fn.tech": "Technology",
  "hr.fn.commercial": "Sales & market",
  "hr.fn.domain": "Industry know-how",
  "hr.fn.finance": "Finance",
  "hr.kind.founder": "Founder",
  "hr.kind.cofounder": "Co-founder",
  "hr.kind.executive": "Executive",
  "hr.kind.employee": "Employee",
  "hr.kind.advisor": "Advisor",

  "hr.new.eyebrow": "New team review",
  "hr.new.h1": "Review a founding team",
  "hr.new.p": "Tell us who runs the business. The more public links you add, the more we can confirm.",
  "hr.new.team": "The business",
  "hr.new.name": "Team or business name",
  "hr.new.website": "Website (optional)",
  "hr.new.val": "Business valuation (optional)",
  "hr.new.val.ph": "valuation id or eth.blockid.au link",
  "hr.new.val.hint": "Linked, the team score counts for 30% of that business score.",
  "hr.new.people": "People",
  "hr.new.people.p": "Start with the founders, then add key executives and advisors.",
  "hr.new.submit": "Start the review",
  "hr.new.starting": "Starting…",
  "hr.new.signin": "If you are not signed in, we open the demo account or make a key in this browser.",
  "hr.new.limit": "Daily review limit reached. Please try again tomorrow.",

  "hr.p.person": "Person {n}",
  "hr.p.name": "Full name",
  "hr.p.role": "Role",
  "hr.p.role.ph": "CEO, CTO, Head of Sales…",
  "hr.p.kind": "Type",
  "hr.p.ft": "Full-time",
  "hr.p.ft.yes": "Yes",
  "hr.p.ft.no": "No",
  "hr.p.ft.unknown": "Not sure",
  "hr.p.year": "Start year",
  "hr.p.equity": "Equity %",
  "hr.p.linkedin": "LinkedIn",
  "hr.p.links": "Other public links",
  "hr.p.links.ph": "One per line: company bio page, GitHub, Google Scholar, press",
  "hr.p.bio": "Short bio",
  "hr.p.bio.ph": "Past roles, companies and results. Shown as self-reported.",
  "hr.p.add": "Add a person",
  "hr.p.remove": "Remove",
  "hr.p.equity.total": "Equity listed: {p}%",
  "hr.p.consent": "These people agreed to a review of their public professional information",
  "hr.p.consent.sub": "Public professional information only. Anyone listed can ask for removal at info@blockid.au.",

  "hr.e.name": "Enter the full name.",
  "hr.e.name.long": "Keep the name under 120 characters.",
  "hr.e.role": "Keep the role under 80 characters.",
  "hr.e.year": "Use a year from 1950 to {y}.",
  "hr.e.equity": "Use a number from 0 to 100.",
  "hr.e.equity.total": "Equity adds up to {p}%. The total cannot be over 100%.",
  "hr.e.url": "Not a valid web link (http or https): {u}",
  "hr.e.urls.max": "Up to 6 links per person.",
  "hr.e.bio": "Keep the bio under 1,500 characters.",
  "hr.e.founder": "Mark at least one person as founder or co-founder.",
  "hr.e.consent": "Please confirm the people agreed to the review.",
  "hr.e.teamname": "Enter the team or business name.",
  "hr.e.website": "Enter a valid website, for example company.com.au.",
  "hr.e.val": "This does not look like a valuation id or link.",
  "hr.e.fix": "Fix the {n} marked fields to continue.",
  "hr.e.max": "Up to 20 people per team.",

  "hr.r.eyebrow": "Team report",
  "hr.r.st.draft": "Not started",
  "hr.r.st.queued": "Waiting to start",
  "hr.r.st.running": "Checking public information",
  "hr.r.st.done": "Report ready",
  "hr.r.st.failed": "Stopped",
  "hr.r.steps": "Progress",
  "hr.r.step.fetch": "Reading the links provided",
  "hr.r.step.search": "Searching public sources",
  "hr.r.step.extract": "Matching facts to sources",
  "hr.r.step.score": "Scoring",
  "hr.r.step.done": "Report written",
  "hr.r.step.start": "Started",
  "hr.r.waiting": "Starting in a moment…",
  "hr.r.found": "Found so far",
  "hr.r.people.n": "people",
  "hr.r.steps.n": "steps done",
  "hr.r.note": "Only pages that name the person count. Nothing is posted anywhere and no one is contacted.",
  "hr.r.run": "Start the review",
  "hr.r.retry": "Try again",
  "hr.r.stopped": "The review stopped: {e}",
  "hr.r.draft.p": "The people are saved. Start the review when you are ready.",
  "hr.r.score": "Team score",
  "hr.r.of": "out of 100",
  "hr.r.people_c": "People {s}",
  "hr.r.team_c": "Team fit {s}",
  "hr.r.penalty": "Red flags −{s}",
  "hr.r.radar": "How the team fits together",
  "hr.r.map": "Who covers what",
  "hr.r.map.p": "Each column is one area a business needs. A gap means no one on the team covers it yet.",
  "hr.r.map.gap": "gap",
  "hr.r.map.covered": "covered",
  "hr.r.strengths": "Strengths",
  "hr.r.gaps": "Gaps",
  "hr.r.risks": "Team risks",
  "hr.r.questions": "Questions to ask",
  "hr.r.flags": "Red flags (from cited public sources)",
  "hr.r.people": "The people",
  "hr.r.weight": "counts ×{m}",
  "hr.r.sub": "Score parts",
  "hr.r.capped": "capped at {c}: no cited source",
  "hr.r.facts": "Confirmed facts",
  "hr.r.facts.none": "No facts confirmed from public sources yet.",
  "hr.r.source": "source",
  "hr.r.unconf": "Unconfirmed",
  "hr.r.unconf.tip": "We found this but could not match it to a page that names the person.",
  "hr.r.self": "Self-reported",
  "hr.r.self.tip": "Typed by whoever asked for the review, not checked against a source.",
  "hr.r.ft": "Full-time",
  "hr.r.pt": "Part-time",
  "hr.r.since": "Since {y}",
  "hr.r.equity": "{p}% equity",
  "hr.r.method": "Method and sources",
  "hr.r.method.p": "Each person's score is built from six weighted parts. The team score is 60% the people scores (weighted by role) and 40% how the team fits together. Verified red flags lower it. A part with no cited or provided source is capped at {c}.",
  "hr.r.mult": "Role weights",
  "hr.r.parts": "Score part weights",
  "hr.r.sources": "Sources ({n})",
  "hr.r.fetched": "read {d}",
  "hr.r.counters": "{p} pages read · {s} of {b} searches · {f} facts confirmed · {u} unconfirmed",
  "hr.r.valuation": "Part of a business valuation",
  "hr.r.valuation.p": "This team score counts for 30% of the business score.",
  "hr.r.valuation.btn": "Open the business valuation",
  "hr.r.share": "Share link",
  "hr.r.share.make": "Create a share link",
  "hr.r.share.copy": "Copy",
  "hr.r.share.copied": "Copied",
  "hr.r.share.p": "Anyone with this link can read the report.",
  "hr.r.private.h": "This report is private",
  "hr.r.private.p": "Only the person who asked for it, the business's admins and platform admins can read it.",
  "hr.r.notfound": "Team report not found.",
  "hr.r.remove": "Remove this person",
  "hr.r.remove.q": "Remove {n} from this report? This cannot be undone.",
  "hr.r.advisory": "Advisory only. Based on public professional information on the date shown. Not a background check.",
  "hr.r.demo": "Demo report",
  "hr.r.new": "Review another team",

  "hr.me.h1": "My reports",
  "hr.me.p": "Person and team reports you asked for.",
  "hr.me.empty": "No team reviews yet.",
  "hr.me.col.team": "Team",
  "hr.me.col.status": "Status",
  "hr.me.col.score": "Score",
  "hr.me.col.people": "People",
  "hr.me.col.updated": "Updated",
  "hr.me.linked": "linked to a valuation",
  "hr.me.signin": "Sign in to see your reports.",
  "hr.me.demo": "Open the demo account",
  "hr.me.mm": "Use MetaMask",

  "hr.card.h": "Founding team",
  "hr.card.weight": "carries {p}% of the business score",
  "hr.card.open": "Open the full team report",
  "hr.card.add": "Add the founding team",
  "hr.card.add.p": "The people behind the business carry the most weight in the score. Add them for a full team review.",
  "hr.card.running": "Team review in progress…",
  "hr.card.watch": "Watch progress",
  "hr.card.failed": "The team review stopped.",
  "hr.card.noaccess": "The team report is private.",
  "hr.card.top": "Top strength",
  "hr.card.gap": "Main gap",
  "hr.basis.team": "team report",

  "hr.wiz.toggle": "Founding team (recommended — carries the most weight)",
  "hr.wiz.p": "List the people behind the business. We check their public professional information and the team score counts for 30% of the business score.",
  "hr.wiz.bad": "Check the founding team: {n} fields need fixing.",
  "hr.nav.person": "Analyse a person",
  "hr.home.start.person": "Analyse a person",
  "hr.home.start.person.p": "One person against a business or a role: a CV checked against public sources and a fit score.",
  "hr.home.start.team.p": "Everyone behind a business: each person's score and how the team fits together.",

  "hr.band.fit.strong": "Strong fit",
  "hr.band.fit.good": "Good fit",
  "hr.band.fit.partial": "Partial fit",
  "hr.band.fit.weak": "Weak fit",
  "hr.band.fit.poor": "Poor fit",
  "hr.band.q.strong": "Strong profile",
  "hr.band.q.good": "Good profile",
  "hr.band.q.partial": "Partial profile",
  "hr.band.q.weak": "Weak profile",
  "hr.band.q.poor": "Poor profile",
  "hr.band.team.strong": "Strong team",
  "hr.band.team.good": "Good team",
  "hr.band.team.partial": "Partial team",
  "hr.band.team.weak": "Weak team",
  "hr.band.team.poor": "Poor team",
  "hr.band.low": "Not enough evidence",
  "hr.bandshort.strong": "Strong",
  "hr.bandshort.good": "Good",
  "hr.bandshort.partial": "Partial",
  "hr.bandshort.weak": "Weak",
  "hr.bandshort.poor": "Poor",
  "hr.conf.high": "High confidence",
  "hr.conf.medium": "Medium confidence",
  "hr.conf.low": "Low confidence",
  "hr.next.high": "Use the questions in the Assessment tab in the interview.",
  "hr.next.medium": "Ask for a reference for the claims that are not confirmed.",
  "hr.next.low": "Add a company bio page, GitHub or press link and run the review again.",
  "hr.ev.verified": "Verified",
  "hr.ev.self": "Self-reported",
  "hr.ev.unconfirmed": "Unconfirmed",
  "hr.ev.none": "Not found",
  "hr.ev.conflict": "Sources differ",
  "hr.ev.computed": "Computed",
  "hr.ev.verified.d": "Quoted from a stored public page that names the person.",
  "hr.ev.self.d": "From the form, the bio or the CV. Not wrong, just not checked.",
  "hr.ev.unconfirmed.d": "We looked but could not match it to a page that names the person.",
  "hr.ev.none.d": "No evidence either way. A score part with no evidence is capped at 50.",
  "hr.ev.conflict.d": "Two sources say different things. Both are shown.",
  "hr.fit.skills_match": "Skills",
  "hr.fit.domain_match": "Industry",
  "hr.fit.stage_scale_match": "Stage and scale",
  "hr.fit.seniority_match": "Seniority",
  "hr.fit.track_record_relevance": "Relevant track record",
  "hr.fit.gaps": "Few gaps",
  "hr.src.page": "Web page",
  "hr.src.snippet": "Search result",
  "hr.src.provided": "Link given",
  "hr.r.step.team": "Scoring the team as a whole",
  "hr.r.step.queued": "Queued",
  "hr.r.step.failed": "Stopped",
  "hr.card.fit": "fit",
  "hr.card.quality": "profile",

  "hr.tab.overview": "Overview",
  "hr.tab.score": "Score",
  "hr.tab.requirements": "Requirements",
  "hr.tab.cv": "CV",
  "hr.tab.assessment": "Assessment",
  "hr.tab.sources": "Sources",
  "hr.tab.people": "People",
  "hr.tab.gaps": "Gaps & risks",

  "hr.pr.eyebrow": "Person report",
  "hr.pr.menu": "Report sections",
  "hr.pr.profile": "Profile",
  "hr.pr.links": "Links",
  "hr.pr.yrs": "{n} years of experience",
  "hr.pr.complete": "Profile {p}% complete",
  "hr.pr.complete.p": "More public links and a CV make the profile more complete.",
  "hr.pr.fit.business": "Founder–business fit",
  "hr.pr.fit.role": "Role fit",
  "hr.pr.quality.h": "Profile quality",
  "hr.pr.for": "for {n}",
  "hr.pr.asrole": "role: {r}",
  "hr.pr.range": "Likely range {lo}–{hi}",
  "hr.pr.range.cross": "likely {a}, could be {b}",
  "hr.pr.outof": "{s} out of 100",
  "hr.pr.conf.reason": "{v} facts confirmed on public pages, {u} unconfirmed, {s} score parts self-reported.",
  "hr.pr.next": "Next:",
  "hr.pr.track.aria": "Score {s} of 100, {b}, likely range {lo} to {hi}, {c}",
  "hr.pr.up": "Raised the score",
  "hr.pr.down": "Held it back",
  "hr.pr.hl.years": "years since the first role listed",
  "hr.pr.hl.ventures": "ventures",
  "hr.pr.hl.exits": "exits (sold, acquired or listed)",
  "hr.pr.hl.facts": "facts confirmed",
  "hr.pr.qualityline": "Profile quality {s} ({b}). The fit score above compares the person with the target.",
  "hr.pr.teamline": "Counts {m}× in the {n} team score: {b} {s}. The founding team is 30% of the business score.",
  "hr.pr.openteam": "Open the team report",
  "hr.pr.pdf": "Download PDF",
  "hr.pr.copy": "Copy share link",
  "hr.pr.sbmeta": "{s} searches · {p} pages read · {f} facts confirmed",
  "hr.pr.parts.n": "{n} parts · fixed weights",
  "hr.pr.parts.lead": "Each part is suggested with quotes from the sources; the total is computed from fixed weights. A part with no evidence is capped at {c}.",
  "hr.pr.parts.cap": "Score parts with weight, value, points and evidence",
  "hr.pr.col.part": "Part",
  "hr.pr.col.weight": "Weight",
  "hr.pr.col.score": "Score",
  "hr.pr.col.points": "Points",
  "hr.pr.col.evidence": "Evidence",
  "hr.pr.col.req": "Requirement",
  "hr.pr.col.result": "Result",
  "hr.pr.col.sources": "Sources",
  "hr.pr.col.page": "Page",
  "hr.pr.col.type": "Type",
  "hr.pr.col.fetched": "Read on · hash",
  "hr.pr.total": "Total",
  "hr.pr.capped": "capped at {c}",
  "hr.pr.capnote": "Line at 50 = the cap for a part with no evidence (the cap is {c}). Gold bar = below 65.",
  "hr.pr.reqs": "Requirements",
  "hr.pr.req.count": "{n} requirements",
  "hr.pr.req.must": "Must-have",
  "hr.pr.req.nice": "Nice to have",
  "hr.pr.req.none": "No requirements were checked for this target.",
  "hr.pr.req.notarget": "No target was set, so there are no requirements to check. The profile quality score still applies.",
  "hr.pr.res.met": "Met",
  "hr.pr.res.part": "Partly",
  "hr.pr.res.nf": "Not found",
  "hr.pr.res.unv": "Not confirmed",
  "hr.pr.summary": "Summary",
  "hr.pr.exp": "Experience",
  "hr.pr.exp.count": "{n} roles · most recent first",
  "hr.pr.present": "now",
  "hr.pr.dur": "{n} yr",
  "hr.pr.edu": "Education",
  "hr.pr.edu.note": "Education is shown for context. School names are not scored.",
  "hr.pr.skills": "Skills",
  "hr.pr.ventures": "Ventures & exits",
  "hr.pr.ventures.count": "{n} ventures · {x} exits",
  "hr.pr.out.active": "Operating",
  "hr.pr.out.exit": "Exit",
  "hr.pr.out.acquired": "Acquired",
  "hr.pr.out.ipo": "Listed (IPO)",
  "hr.pr.out.closed": "Closed",
  "hr.pr.out.unknown": "Outcome not known",
  "hr.pr.pubs": "Publications and talks",
  "hr.pr.awards": "Awards",
  "hr.pr.none": "Nothing on the public record yet.",
  "hr.pr.sr": "Strengths and things to check",
  "hr.pr.check": "Things to check",
  "hr.pr.questions": "Questions to ask {n}",
  "hr.pr.questions.p": "each one tests a gap above",
  "hr.pr.unconf": "Claims we could not confirm",
  "hr.pr.sources": "Sources",
  "hr.pr.sources.count": "{n} sources",
  "hr.pr.nosources": "No public sources were stored for this report.",
  "hr.pr.method.title": "How this score was made",
  "hr.pr.method.h": "Method",
  "hr.pr.m.1": "We read the links given, then ran {s} of up to {b} web searches. {p} pages kept, each stored with a hash.",
  "hr.pr.m.2": "A fact is Verified only if a stored page names the person and says it in words we quote. Otherwise it is Self-reported or Unconfirmed.",
  "hr.pr.m.3": "Each part score is suggested with quotes; code computes the total with fixed weights ({w}). A part with no evidence is capped at {c}.",
  "hr.pr.m.4": "Confidence is the share of weighted points backed by verified facts: 75% or more High, 45–74% Medium, under 45% Low. The likely range is ±4, ±6 or ±10.",
  "hr.pr.m.5": "Bands: Strong 85+ · Good 70–84 · Partial 55–69 · Weak 40–54 · Poor under 40. With Low confidence the band reads \"Not enough evidence\".",
  "hr.pr.m.team": "Team score = 60% the people scores (weighted by role: founder 1.5×, co-founder 1.2×, executive 1.0×, advisor 0.4×) + 40% team factors. Verified red flags lower it.",
  "hr.pr.person.h": "Checked by a person",
  "hr.pr.p.val": "Before a team score changes a business valuation, a BlockID admin reviews it at the valuation approval step.",
  "hr.pr.p.noval": "This report is not linked to a business valuation, so it changes no business score.",
  "hr.pr.p.2": "A reviewer can change a part score; every change is logged with a reason.",
  "hr.pr.p.3": "This report supports a decision; it does not make one.",
  "hr.pr.mistake": "Report a mistake",
  "hr.pr.cf.h": "Consent and fairness",
  "hr.pr.cf.agreed": "The requester confirmed on {d} that {n} agreed to this review. Only public professional information is used, for this review only.",
  "hr.pr.cf.remove": "Anyone listed can see, correct or remove this report:",
  "hr.pr.cf.never": "Never collected or scored:",
  "hr.pr.cf.n1": "Age, gender, ethnicity, nationality, photo",
  "hr.pr.cf.n2": "Family, health, religion, politics",
  "hr.pr.cf.n3": "Home address, personal phone or email",
  "hr.pr.cf.n4": "School or employer prestige, career breaks",
  "hr.pr.legal": "Testnet demo. Not an offer of securities or financial advice. This report supports a decision; it does not make one. BlockID HR · report {id} · {d}.",

  "hr.tr.formula": "People {p} × 60% + team factors {f} × 40% − red flags {r}",
  "hr.tr.contrib": "Share of the business score",
  "hr.tr.contrib.aria": "The founding team gives {s} of 30 points of the business score",
  "hr.tr.contrib.p": "The founding team is 30% of the business score. Team score {s} gives {x} of 30 points.",
  "hr.tr.noval": "Not linked to a business valuation yet.",
  "hr.tr.comp": "Composition",
  "hr.tr.comp.n": "{n} people · sorted by weight",
  "hr.tr.weight": "Weight",
  "hr.tr.open": "Open the person report",
  "hr.tr.team": "Whole team",
  "hr.tr.q.p": "for the founders",

  "hr.m.p": "The same rules are printed on every report. Scores support a decision; they do not make one.",
  "hr.m.fit": "Fit score",
  "hr.m.fit.p": "Compares the person with a business (founder–business fit) or a role (role fit), from six parts:",
  "hr.m.team": "Team score",
  "hr.m.bands": "Bands",
  "hr.m.conf": "Confidence (High, Medium, Low) is the share of the score backed by verified facts. With Low confidence the band reads \"Not enough evidence\".",
  "hr.m.ev": "Evidence labels",

  "hr.me.col.kind": "Report",
  "hr.me.kind.person": "Person",
  "hr.me.kind.team": "Team",

  "hr.np.eyebrow": "New person report",
  "hr.np.h1": "Analyse a person",
  "hr.np.p": "A CV checked against public sources and a fit score, with every fact linked to where it came from. Takes about 2–4 minutes.",
  "hr.np.s1": "The person",
  "hr.np.s1.p": "Name, role and public links. What you type is labelled self-reported.",
  "hr.np.role": "Role at the target",
  "hr.np.rel": "Relationship",
  "hr.np.headline": "Headline (optional)",
  "hr.np.headline.ph": "e.g. Freight operator, ex-Toll Group",
  "hr.np.works": "Works",
  "hr.np.equity": "Equity % (optional)",
  "hr.np.links": "Public links",
  "hr.np.link": "Link {n}",
  "hr.np.addlink": "Add a link (company bio, GitHub, Scholar, press)",
  "hr.np.linkedin": "LinkedIn pages cannot be read; details from it are shown as self-reported.",
  "hr.np.bio.hint": "{n} / 1,500 · shown as self-reported. Please leave out personal details.",
  "hr.np.cv": "Paste a CV (optional)",
  "hr.np.cv.ph": "Paste the CV text. Emails and phone numbers are removed before any search.",
  "hr.np.cv.hint": "{n} / 20,000 · shown as self-reported",
  "hr.np.s2": "Fit against",
  "hr.np.s2.p": "Pick what to compare the person with.",
  "hr.np.t.business": "A BlockID business",
  "hr.np.t.business.p": "Uses the business profile and stage. Feeds the team score of that business.",
  "hr.np.t.role": "A role",
  "hr.np.t.role.p": "A job the person applies to or you are hiring for.",
  "hr.np.biz": "Business",
  "hr.np.biz.ph": "Search your valuations or listed businesses",
  "hr.np.biz.val": "valuation",
  "hr.np.biz.none": "No match. Enter the website below instead.",
  "hr.np.biz.web": "…or the business website",
  "hr.np.biz.web.hint": "Any public website works, even if the business is not on BlockID yet.",
  "hr.np.change": "Change",
  "hr.np.company": "Company",
  "hr.np.company.ph": "e.g. Southern Cross Freight",
  "hr.np.title": "Role title",
  "hr.np.title.ph": "e.g. Chief Operating Officer",
  "hr.np.desc": "Job description (optional)",
  "hr.np.desc.ph": "Paste the job ad or describe the scope, team size and goals.",
  "hr.np.desc.hint": "{n} / 5,000",
  "hr.np.s3": "Requirements",
  "hr.np.s3.p": "Up to 5 must-haves and 4 nice-to-haves. Everyone reviewed for this role gets the same list.",
  "hr.np.s3.biz": "For a business, we take the requirements from its profile, stage and team gaps. You will see each one in the report.",
  "hr.np.req.count": "{n} of {m}",
  "hr.np.req.empty": "None yet",
  "hr.np.req.ph": "Type a requirement and press Enter",
  "hr.np.req.full": "Lists are full: remove one first",
  "hr.np.req.add": "Add",
  "hr.np.req.up": "Move to must-have",
  "hr.np.req.down": "Move to nice to have",
  "hr.np.req.n": "{n} requirements",
  "hr.np.s4": "Consent",
  "hr.np.s4.p": "Required before we look anything up.",
  "hr.np.c1": "{n} agreed to this review.",
  "hr.np.c1.sub": "We record the date on the report.",
  "hr.np.c2": "I will use it only for {n}.",
  "hr.np.theperson": "The person",
  "hr.np.thistarget": "this business or role",
  "hr.np.never.b": "We only read public professional pages.",
  "hr.np.never": "We never collect or score age, gender, ethnicity, nationality, photos, family, health, religion, politics, home address, personal phone or email, or school prestige.",
  "hr.np.sum": "Summary",
  "hr.np.sum.person": "Person",
  "hr.np.sum.reqs": "{m} must · {n} nice",
  "hr.np.sum.search": "Web searches",
  "hr.np.sum.search.v": "up to 3",
  "hr.np.sum.time": "Time",
  "hr.np.sum.time.v": "about 2–4 min",
  "hr.np.gate": "Tick both consent boxes to start.",
  "hr.np.fine": "You get a status line while it runs. The report stays private to you until you share it.",
  "hr.np.e.headline": "Keep the headline under 200 characters.",
  "hr.np.e.cv": "Keep the CV under 20,000 characters.",
  "hr.np.e.biz": "Pick a business or enter its website.",
  "hr.np.e.company": "Enter the company.",
  "hr.np.e.title": "Enter the role title.",
  "hr.np.e.desc": "Keep the description under 5,000 characters.",
  "hr.np.e.use": "Please confirm how the report will be used.",
} as const;

export const hrVi: Record<keyof typeof hrEn, string> = {
  "dim.founder": "Đội ngũ sáng lập",

  "hr.brand": "BlockID HR",
  "hr.title": "Đánh giá đội ngũ sáng lập",
  "hr.nav.new": "Đánh giá đội ngũ",
  "hr.nav.me": "Báo cáo của tôi",
  "hr.nav.how": "Cách tính điểm",
  "hr.nav.eth": "Định giá doanh nghiệp",
  "hr.foot.site": "BlockID HR · hr.blockid.au",
  "hr.foot.remove": "Có tên trong báo cáo và muốn gỡ thông tin? Viết cho info@blockid.au.",
  "hr.foot.eth": "Định giá doanh nghiệp trên eth.blockid.au",

  "hr.home.eyebrow": "Đánh giá đội ngũ sáng lập",
  "hr.home.h1a": "Hiểu rõ những người",
  "hr.home.h1b": "đứng sau doanh nghiệp",
  "hr.home.pitch": "Nhà đầu tư đặt cược vào con người trước tiên. Hãy liệt kê đội ngũ sáng lập, chúng tôi đối chiếu thông tin nghề nghiệp công khai của từng người (vai trò, các công ty đã làm, kết quả) với nguồn, rồi chấm điểm cả đội.",
  "hr.home.ai": "Một trợ lý nghiên cứu AI đọc các nguồn; mọi điểm số được tính theo quy tắc cố định và mọi dữ kiện đều dẫn tới trang gốc.",
  "hr.home.cta": "Đánh giá đội ngũ sáng lập",
  "hr.home.mine": "Báo cáo của tôi",
  "hr.home.legal": "Chỉ mang tính tham khảo. Chỉ dùng thông tin nghề nghiệp công khai và chỉ khi những người đó đồng ý.",
  "hr.home.card.label": "Ví dụ báo cáo đội ngũ",
  "hr.home.card.example": "ví dụ",
  "hr.how.eyebrow": "Cách hoạt động",
  "hr.how.h2": "Ba bước, vài phút",
  "hr.how.1h": "Liệt kê mọi người",
  "hr.how.1p": "Họ tên, vai trò, năm bắt đầu, tỷ lệ cổ phần và các đường dẫn công khai như LinkedIn hay trang giới thiệu trên web công ty.",
  "hr.how.2h": "Chúng tôi đối chiếu nguồn công khai",
  "hr.how.2p": "Mỗi thông tin được khớp với một trang có nêu tên người đó. Điều gì không khớp được sẽ ghi là chưa xác nhận.",
  "hr.how.3h": "Nhận báo cáo đội ngũ",
  "hr.how.3p": "Điểm của cả đội, điểm mạnh và điểm còn thiếu của từng người, và các câu nhà đầu tư nên hỏi.",
  "hr.what.eyebrow": "Chúng tôi chấm gì",
  "hr.what.h2": "Từng người, rồi cả đội",
  "hr.what.p": "Mỗi người có điểm từ 0 đến 100, gồm sáu phần. Điểm đội cộng thêm mức độ mọi người bổ sung cho nhau.",
  "hr.priv.eyebrow": "Quyền riêng tư",
  "hr.priv.h2": "Chỉ thông tin nghề nghiệp, có sự đồng ý",
  "hr.priv.1": "Người yêu cầu đánh giá xác nhận những người được liệt kê đã đồng ý.",
  "hr.priv.2": "Chúng tôi chỉ xem thông tin nghề nghiệp công khai: vai trò, công ty, học vấn, bài viết và giải thưởng.",
  "hr.priv.3": "Chúng tôi không bao giờ thu thập sức khỏe, tôn giáo, chính trị, gia đình, địa chỉ nhà, số điện thoại hay email cá nhân.",
  "hr.priv.4": "Bất kỳ ai có tên đều có thể yêu cầu gỡ thông tin qua info@blockid.au.",
  "hr.home.final.h": "Đang định giá một doanh nghiệp?",
  "hr.home.final.p": "Đội ngũ sáng lập chiếm 30% điểm doanh nghiệp trên eth.blockid.au. Liên kết bản đánh giá đội ngũ với bản định giá và điểm sẽ được cập nhật.",
  "hr.home.final.btn": "Bắt đầu định giá doanh nghiệp",

  "hr.sub.domain_fit": "Am hiểu ngành",
  "hr.sub.domain_fit.d": "Hiểu ngành và khách hàng mà doanh nghiệp phục vụ.",
  "hr.sub.track_record": "Thành tích",
  "hr.sub.track_record.d": "Các công ty đã lập hoặc điều hành, thương vụ bán lại và quy mô đã quản lý.",
  "hr.sub.leadership": "Lãnh đạo & phù hợp vai trò",
  "hr.sub.leadership.d": "Đã từng dẫn dắt đội nhóm và phù hợp với vai trò hiện tại.",
  "hr.sub.functional_depth": "Chiều sâu chuyên môn",
  "hr.sub.functional_depth.d": "Chuyên môn sâu về công nghệ, kinh doanh hoặc tài chính.",
  "hr.sub.verifiability": "Thông tin xác nhận được",
  "hr.sub.verifiability.d": "Bao nhiêu phần thông tin được một nguồn công khai xác nhận.",
  "hr.sub.commitment": "Mức độ gắn bó",
  "hr.sub.commitment.d": "Làm toàn thời gian, có cổ phần và đã gắn bó một thời gian.",
  "hr.comp.complementarity": "Kỹ năng bổ sung cho nhau",
  "hr.comp.key_roles": "Đủ các vai trò chính",
  "hr.comp.worked_together": "Từng làm việc cùng nhau",
  "hr.comp.advisors_board": "Cố vấn và hội đồng quản trị",
  "hr.comp.concentration": "Không phụ thuộc một người",
  "hr.fn.tech": "Công nghệ",
  "hr.fn.commercial": "Kinh doanh & thị trường",
  "hr.fn.domain": "Am hiểu ngành",
  "hr.fn.finance": "Tài chính",
  "hr.kind.founder": "Nhà sáng lập",
  "hr.kind.cofounder": "Đồng sáng lập",
  "hr.kind.executive": "Quản lý cấp cao",
  "hr.kind.employee": "Nhân viên",
  "hr.kind.advisor": "Cố vấn",

  "hr.new.eyebrow": "Đánh giá đội ngũ mới",
  "hr.new.h1": "Đánh giá đội ngũ sáng lập",
  "hr.new.p": "Cho chúng tôi biết ai đang điều hành doanh nghiệp. Càng có nhiều đường dẫn công khai, chúng tôi càng xác nhận được nhiều.",
  "hr.new.team": "Doanh nghiệp",
  "hr.new.name": "Tên đội ngũ hoặc doanh nghiệp",
  "hr.new.website": "Website (không bắt buộc)",
  "hr.new.val": "Bản định giá doanh nghiệp (không bắt buộc)",
  "hr.new.val.ph": "mã định giá hoặc đường dẫn eth.blockid.au",
  "hr.new.val.hint": "Khi liên kết, điểm đội ngũ chiếm 30% điểm của doanh nghiệp đó.",
  "hr.new.people": "Thành viên",
  "hr.new.people.p": "Bắt đầu với các nhà sáng lập, sau đó thêm quản lý chủ chốt và cố vấn.",
  "hr.new.submit": "Bắt đầu đánh giá",
  "hr.new.starting": "Đang bắt đầu…",
  "hr.new.signin": "Nếu bạn chưa đăng nhập, chúng tôi mở tài khoản demo hoặc tạo khóa trong trình duyệt này.",
  "hr.new.limit": "Đã hết lượt đánh giá trong ngày. Vui lòng thử lại vào ngày mai.",

  "hr.p.person": "Người thứ {n}",
  "hr.p.name": "Họ và tên",
  "hr.p.role": "Vai trò",
  "hr.p.role.ph": "CEO, CTO, Trưởng phòng kinh doanh…",
  "hr.p.kind": "Loại",
  "hr.p.ft": "Toàn thời gian",
  "hr.p.ft.yes": "Có",
  "hr.p.ft.no": "Không",
  "hr.p.ft.unknown": "Chưa rõ",
  "hr.p.year": "Năm bắt đầu",
  "hr.p.equity": "Cổ phần %",
  "hr.p.linkedin": "LinkedIn",
  "hr.p.links": "Đường dẫn công khai khác",
  "hr.p.links.ph": "Mỗi dòng một đường dẫn: trang giới thiệu trên web công ty, GitHub, Google Scholar, báo chí",
  "hr.p.bio": "Giới thiệu ngắn",
  "hr.p.bio.ph": "Vai trò, công ty và kết quả trước đây. Hiển thị là tự khai.",
  "hr.p.add": "Thêm người",
  "hr.p.remove": "Xóa",
  "hr.p.equity.total": "Tổng cổ phần đã nhập: {p}%",
  "hr.p.consent": "Những người này đã đồng ý cho đánh giá thông tin nghề nghiệp công khai của họ",
  "hr.p.consent.sub": "Chỉ thông tin nghề nghiệp công khai. Bất kỳ ai có tên đều có thể yêu cầu gỡ qua info@blockid.au.",

  "hr.e.name": "Nhập họ và tên.",
  "hr.e.name.long": "Tên không quá 120 ký tự.",
  "hr.e.role": "Vai trò không quá 80 ký tự.",
  "hr.e.year": "Nhập năm từ 1950 đến {y}.",
  "hr.e.equity": "Nhập số từ 0 đến 100.",
  "hr.e.equity.total": "Tổng cổ phần là {p}%. Tổng không được vượt quá 100%.",
  "hr.e.url": "Đường dẫn web không hợp lệ (http hoặc https): {u}",
  "hr.e.urls.max": "Tối đa 6 đường dẫn cho mỗi người.",
  "hr.e.bio": "Phần giới thiệu không quá 1.500 ký tự.",
  "hr.e.founder": "Đánh dấu ít nhất một người là nhà sáng lập hoặc đồng sáng lập.",
  "hr.e.consent": "Vui lòng xác nhận những người này đã đồng ý được đánh giá.",
  "hr.e.teamname": "Nhập tên đội ngũ hoặc doanh nghiệp.",
  "hr.e.website": "Nhập website hợp lệ, ví dụ congty.com.vn.",
  "hr.e.val": "Đây không giống mã hoặc đường dẫn của bản định giá.",
  "hr.e.fix": "Sửa {n} ô được đánh dấu để tiếp tục.",
  "hr.e.max": "Tối đa 20 người mỗi đội.",

  "hr.r.eyebrow": "Báo cáo đội ngũ",
  "hr.r.st.draft": "Chưa bắt đầu",
  "hr.r.st.queued": "Đang chờ bắt đầu",
  "hr.r.st.running": "Đang kiểm tra thông tin công khai",
  "hr.r.st.done": "Báo cáo đã sẵn sàng",
  "hr.r.st.failed": "Đã dừng",
  "hr.r.steps": "Tiến độ",
  "hr.r.step.fetch": "Đọc các đường dẫn được cung cấp",
  "hr.r.step.search": "Tìm kiếm nguồn công khai",
  "hr.r.step.extract": "Khớp dữ kiện với nguồn",
  "hr.r.step.score": "Chấm điểm",
  "hr.r.step.done": "Đã viết báo cáo",
  "hr.r.step.start": "Bắt đầu",
  "hr.r.waiting": "Sắp bắt đầu…",
  "hr.r.found": "Đã tìm được",
  "hr.r.people.n": "người",
  "hr.r.steps.n": "bước đã xong",
  "hr.r.note": "Chỉ các trang có nêu tên người đó mới được tính. Không đăng gì ở đâu và không liên hệ với ai.",
  "hr.r.run": "Bắt đầu đánh giá",
  "hr.r.retry": "Thử lại",
  "hr.r.stopped": "Việc đánh giá đã dừng: {e}",
  "hr.r.draft.p": "Danh sách đã được lưu. Hãy bắt đầu đánh giá khi bạn sẵn sàng.",
  "hr.r.score": "Điểm đội ngũ",
  "hr.r.of": "trên 100",
  "hr.r.people_c": "Cá nhân {s}",
  "hr.r.team_c": "Độ ăn khớp {s}",
  "hr.r.penalty": "Cảnh báo −{s}",
  "hr.r.radar": "Đội ngũ ăn khớp thế nào",
  "hr.r.map": "Ai đảm nhận mảng nào",
  "hr.r.map.p": "Mỗi cột là một mảng doanh nghiệp cần có. Ô trống nghĩa là chưa ai trong đội đảm nhận.",
  "hr.r.map.gap": "thiếu",
  "hr.r.map.covered": "đã có",
  "hr.r.strengths": "Điểm mạnh",
  "hr.r.gaps": "Điểm còn thiếu",
  "hr.r.risks": "Rủi ro của đội",
  "hr.r.questions": "Câu nên hỏi",
  "hr.r.flags": "Cảnh báo (từ nguồn công khai có trích dẫn)",
  "hr.r.people": "Thành viên",
  "hr.r.weight": "hệ số ×{m}",
  "hr.r.sub": "Các phần điểm",
  "hr.r.capped": "giới hạn ở {c}: chưa có nguồn trích dẫn",
  "hr.r.facts": "Dữ kiện đã xác nhận",
  "hr.r.facts.none": "Chưa xác nhận được dữ kiện nào từ nguồn công khai.",
  "hr.r.source": "nguồn",
  "hr.r.unconf": "Chưa xác nhận",
  "hr.r.unconf.tip": "Chúng tôi thấy thông tin này nhưng chưa khớp được với trang nào có nêu tên người đó.",
  "hr.r.self": "Tự khai",
  "hr.r.self.tip": "Do người yêu cầu đánh giá nhập, chưa đối chiếu với nguồn.",
  "hr.r.ft": "Toàn thời gian",
  "hr.r.pt": "Bán thời gian",
  "hr.r.since": "Từ {y}",
  "hr.r.equity": "{p}% cổ phần",
  "hr.r.method": "Phương pháp và nguồn",
  "hr.r.method.p": "Điểm mỗi người gồm sáu phần có trọng số. Điểm đội ngũ gồm 60% điểm cá nhân (theo trọng số vai trò) và 40% mức độ ăn khớp của đội. Cảnh báo đã xác minh sẽ làm giảm điểm. Phần nào không có nguồn trích dẫn hoặc được cung cấp bị giới hạn ở {c}.",
  "hr.r.mult": "Trọng số vai trò",
  "hr.r.parts": "Trọng số các phần điểm",
  "hr.r.sources": "Nguồn ({n})",
  "hr.r.fetched": "đọc lúc {d}",
  "hr.r.counters": "{p} trang đã đọc · {s} trên {b} lượt tìm · {f} dữ kiện đã xác nhận · {u} chưa xác nhận",
  "hr.r.valuation": "Thuộc một bản định giá doanh nghiệp",
  "hr.r.valuation.p": "Điểm đội ngũ này chiếm 30% điểm doanh nghiệp.",
  "hr.r.valuation.btn": "Mở bản định giá doanh nghiệp",
  "hr.r.share": "Đường dẫn chia sẻ",
  "hr.r.share.make": "Tạo đường dẫn chia sẻ",
  "hr.r.share.copy": "Sao chép",
  "hr.r.share.copied": "Đã sao chép",
  "hr.r.share.p": "Ai có đường dẫn này đều đọc được báo cáo.",
  "hr.r.private.h": "Báo cáo này ở chế độ riêng tư",
  "hr.r.private.p": "Chỉ người yêu cầu, quản trị viên của doanh nghiệp và quản trị viên nền tảng mới đọc được.",
  "hr.r.notfound": "Không tìm thấy báo cáo đội ngũ.",
  "hr.r.remove": "Xóa người này",
  "hr.r.remove.q": "Xóa {n} khỏi báo cáo này? Không thể hoàn tác.",
  "hr.r.advisory": "Chỉ mang tính tham khảo. Dựa trên thông tin nghề nghiệp công khai tại ngày ghi trên báo cáo. Không phải thẩm tra lý lịch.",
  "hr.r.demo": "Báo cáo demo",
  "hr.r.new": "Đánh giá đội ngũ khác",

  "hr.me.h1": "Báo cáo của tôi",
  "hr.me.p": "Các báo cáo cá nhân và đội ngũ bạn đã yêu cầu.",
  "hr.me.empty": "Chưa có bản đánh giá đội ngũ nào.",
  "hr.me.col.team": "Đội ngũ",
  "hr.me.col.status": "Trạng thái",
  "hr.me.col.score": "Điểm",
  "hr.me.col.people": "Số người",
  "hr.me.col.updated": "Cập nhật",
  "hr.me.linked": "đã liên kết bản định giá",
  "hr.me.signin": "Đăng nhập để xem báo cáo của bạn.",
  "hr.me.demo": "Mở tài khoản demo",
  "hr.me.mm": "Dùng MetaMask",

  "hr.card.h": "Đội ngũ sáng lập",
  "hr.card.weight": "chiếm {p}% điểm doanh nghiệp",
  "hr.card.open": "Mở báo cáo đội ngũ đầy đủ",
  "hr.card.add": "Thêm đội ngũ sáng lập",
  "hr.card.add.p": "Những người đứng sau doanh nghiệp có trọng số lớn nhất trong điểm. Hãy thêm họ để được đánh giá đội ngũ đầy đủ.",
  "hr.card.running": "Đang đánh giá đội ngũ…",
  "hr.card.watch": "Xem tiến độ",
  "hr.card.failed": "Việc đánh giá đội ngũ đã dừng.",
  "hr.card.noaccess": "Báo cáo đội ngũ ở chế độ riêng tư.",
  "hr.card.top": "Điểm mạnh nhất",
  "hr.card.gap": "Điểm thiếu chính",
  "hr.basis.team": "báo cáo đội ngũ",

  "hr.wiz.toggle": "Đội ngũ sáng lập (nên có — trọng số lớn nhất)",
  "hr.wiz.p": "Liệt kê những người đứng sau doanh nghiệp. Chúng tôi kiểm tra thông tin nghề nghiệp công khai của họ và điểm đội ngũ chiếm 30% điểm doanh nghiệp.",
  "hr.wiz.bad": "Kiểm tra lại đội ngũ sáng lập: {n} ô cần sửa.",
  "hr.nav.person": "Phân tích một người",
  "hr.home.start.person": "Phân tích một người",
  "hr.home.start.person.p": "Một người so với một doanh nghiệp hoặc một vị trí: CV được đối chiếu với nguồn công khai và điểm phù hợp.",
  "hr.home.start.team.p": "Toàn bộ những người đứng sau doanh nghiệp: điểm của từng người và mức độ ăn khớp của cả đội.",

  "hr.band.fit.strong": "Rất phù hợp",
  "hr.band.fit.good": "Phù hợp tốt",
  "hr.band.fit.partial": "Phù hợp một phần",
  "hr.band.fit.weak": "Ít phù hợp",
  "hr.band.fit.poor": "Không phù hợp",
  "hr.band.q.strong": "Hồ sơ mạnh",
  "hr.band.q.good": "Hồ sơ tốt",
  "hr.band.q.partial": "Hồ sơ trung bình",
  "hr.band.q.weak": "Hồ sơ yếu",
  "hr.band.q.poor": "Hồ sơ rất yếu",
  "hr.band.team.strong": "Đội ngũ mạnh",
  "hr.band.team.good": "Đội ngũ tốt",
  "hr.band.team.partial": "Đội ngũ trung bình",
  "hr.band.team.weak": "Đội ngũ yếu",
  "hr.band.team.poor": "Đội ngũ rất yếu",
  "hr.band.low": "Chưa đủ bằng chứng",
  "hr.bandshort.strong": "Mạnh",
  "hr.bandshort.good": "Tốt",
  "hr.bandshort.partial": "Trung bình",
  "hr.bandshort.weak": "Yếu",
  "hr.bandshort.poor": "Rất yếu",
  "hr.conf.high": "Độ tin cậy cao",
  "hr.conf.medium": "Độ tin cậy trung bình",
  "hr.conf.low": "Độ tin cậy thấp",
  "hr.next.high": "Dùng các câu hỏi trong thẻ Đánh giá khi phỏng vấn.",
  "hr.next.medium": "Xin người tham chiếu cho những thông tin chưa được xác nhận.",
  "hr.next.low": "Thêm trang giới thiệu trên web công ty, GitHub hoặc bài báo rồi chạy lại.",
  "hr.ev.verified": "Đã xác minh",
  "hr.ev.self": "Tự khai",
  "hr.ev.unconfirmed": "Chưa xác nhận",
  "hr.ev.none": "Không tìm thấy",
  "hr.ev.conflict": "Nguồn khác nhau",
  "hr.ev.computed": "Tính toán",
  "hr.ev.verified.d": "Trích nguyên văn từ một trang công khai đã lưu có nêu tên người đó.",
  "hr.ev.self.d": "Từ biểu mẫu, phần giới thiệu hoặc CV. Không sai, chỉ là chưa được kiểm tra.",
  "hr.ev.unconfirmed.d": "Đã tìm nhưng chưa khớp được với trang nào có nêu tên người đó.",
  "hr.ev.none.d": "Không có bằng chứng nào. Phần điểm không có bằng chứng bị giới hạn ở 50.",
  "hr.ev.conflict.d": "Hai nguồn nói khác nhau. Cả hai đều được hiển thị.",
  "hr.fit.skills_match": "Kỹ năng",
  "hr.fit.domain_match": "Ngành",
  "hr.fit.stage_scale_match": "Giai đoạn và quy mô",
  "hr.fit.seniority_match": "Cấp bậc",
  "hr.fit.track_record_relevance": "Thành tích liên quan",
  "hr.fit.gaps": "Ít điểm thiếu",
  "hr.src.page": "Trang web",
  "hr.src.snippet": "Kết quả tìm kiếm",
  "hr.src.provided": "Đường dẫn được cung cấp",
  "hr.r.step.team": "Chấm điểm cả đội",
  "hr.r.step.queued": "Đang chờ",
  "hr.r.step.failed": "Đã dừng",
  "hr.card.fit": "phù hợp",
  "hr.card.quality": "hồ sơ",

  "hr.tab.overview": "Tổng quan",
  "hr.tab.score": "Điểm",
  "hr.tab.requirements": "Yêu cầu",
  "hr.tab.cv": "CV",
  "hr.tab.assessment": "Đánh giá",
  "hr.tab.sources": "Nguồn",
  "hr.tab.people": "Thành viên",
  "hr.tab.gaps": "Điểm thiếu & rủi ro",

  "hr.pr.eyebrow": "Báo cáo cá nhân",
  "hr.pr.menu": "Các phần của báo cáo",
  "hr.pr.profile": "Hồ sơ",
  "hr.pr.links": "Đường dẫn",
  "hr.pr.yrs": "{n} năm kinh nghiệm",
  "hr.pr.complete": "Hồ sơ đầy đủ {p}%",
  "hr.pr.complete.p": "Thêm đường dẫn công khai và CV để hồ sơ đầy đủ hơn.",
  "hr.pr.fit.business": "Phù hợp nhà sáng lập – doanh nghiệp",
  "hr.pr.fit.role": "Phù hợp vị trí",
  "hr.pr.quality.h": "Chất lượng hồ sơ",
  "hr.pr.for": "cho {n}",
  "hr.pr.asrole": "vai trò: {r}",
  "hr.pr.range": "Khoảng có thể {lo}–{hi}",
  "hr.pr.range.cross": "nhiều khả năng {a}, có thể là {b}",
  "hr.pr.outof": "{s} trên 100",
  "hr.pr.conf.reason": "{v} dữ kiện được xác nhận trên trang công khai, {u} chưa xác nhận, {s} phần điểm tự khai.",
  "hr.pr.next": "Tiếp theo:",
  "hr.pr.track.aria": "Điểm {s} trên 100, {b}, khoảng có thể từ {lo} đến {hi}, {c}",
  "hr.pr.up": "Làm tăng điểm",
  "hr.pr.down": "Kéo điểm xuống",
  "hr.pr.hl.years": "năm kể từ vai trò đầu tiên",
  "hr.pr.hl.ventures": "công ty đã tham gia sáng lập/điều hành",
  "hr.pr.hl.exits": "thương vụ thoái vốn (bán, sáp nhập, niêm yết)",
  "hr.pr.hl.facts": "dữ kiện đã xác nhận",
  "hr.pr.qualityline": "Chất lượng hồ sơ {s} ({b}). Điểm phù hợp ở trên so sánh người này với mục tiêu.",
  "hr.pr.teamline": "Hệ số {m}× trong điểm đội ngũ {n}: {b} {s}. Đội ngũ sáng lập chiếm 30% điểm doanh nghiệp.",
  "hr.pr.openteam": "Mở báo cáo đội ngũ",
  "hr.pr.pdf": "Tải PDF",
  "hr.pr.copy": "Sao chép đường dẫn chia sẻ",
  "hr.pr.sbmeta": "{s} lượt tìm · {p} trang đã đọc · {f} dữ kiện đã xác nhận",
  "hr.pr.parts.n": "{n} phần · trọng số cố định",
  "hr.pr.parts.lead": "Mỗi phần được đề xuất kèm trích dẫn từ nguồn; tổng điểm được tính theo trọng số cố định. Phần không có bằng chứng bị giới hạn ở {c}.",
  "hr.pr.parts.cap": "Các phần điểm với trọng số, giá trị, điểm đóng góp và bằng chứng",
  "hr.pr.col.part": "Phần",
  "hr.pr.col.weight": "Trọng số",
  "hr.pr.col.score": "Điểm",
  "hr.pr.col.points": "Đóng góp",
  "hr.pr.col.evidence": "Bằng chứng",
  "hr.pr.col.req": "Yêu cầu",
  "hr.pr.col.result": "Kết quả",
  "hr.pr.col.sources": "Nguồn",
  "hr.pr.col.page": "Trang",
  "hr.pr.col.type": "Loại",
  "hr.pr.col.fetched": "Ngày đọc · mã băm",
  "hr.pr.total": "Tổng",
  "hr.pr.capped": "giới hạn ở {c}",
  "hr.pr.capnote": "Vạch ở 50 = giới hạn cho phần không có bằng chứng (giới hạn là {c}). Thanh vàng = dưới 65.",
  "hr.pr.reqs": "Yêu cầu",
  "hr.pr.req.count": "{n} yêu cầu",
  "hr.pr.req.must": "Bắt buộc",
  "hr.pr.req.nice": "Nên có",
  "hr.pr.req.none": "Không có yêu cầu nào được kiểm tra cho mục tiêu này.",
  "hr.pr.req.notarget": "Chưa đặt mục tiêu nên không có yêu cầu để kiểm tra. Điểm chất lượng hồ sơ vẫn được áp dụng.",
  "hr.pr.res.met": "Đạt",
  "hr.pr.res.part": "Đạt một phần",
  "hr.pr.res.nf": "Không tìm thấy",
  "hr.pr.res.unv": "Chưa xác nhận",
  "hr.pr.summary": "Tóm tắt",
  "hr.pr.exp": "Kinh nghiệm",
  "hr.pr.exp.count": "{n} vai trò · mới nhất trước",
  "hr.pr.present": "nay",
  "hr.pr.dur": "{n} năm",
  "hr.pr.edu": "Học vấn",
  "hr.pr.edu.note": "Học vấn chỉ để tham khảo. Tên trường không được chấm điểm.",
  "hr.pr.skills": "Kỹ năng",
  "hr.pr.ventures": "Công ty đã lập & thoái vốn",
  "hr.pr.ventures.count": "{n} công ty · {x} thoái vốn",
  "hr.pr.out.active": "Đang hoạt động",
  "hr.pr.out.exit": "Đã thoái vốn",
  "hr.pr.out.acquired": "Đã được mua lại",
  "hr.pr.out.ipo": "Đã niêm yết (IPO)",
  "hr.pr.out.closed": "Đã đóng cửa",
  "hr.pr.out.unknown": "Chưa rõ kết quả",
  "hr.pr.pubs": "Bài viết và bài nói",
  "hr.pr.awards": "Giải thưởng",
  "hr.pr.none": "Chưa có thông tin công khai nào.",
  "hr.pr.sr": "Điểm mạnh và điều cần kiểm tra",
  "hr.pr.check": "Điều cần kiểm tra",
  "hr.pr.questions": "Câu nên hỏi {n}",
  "hr.pr.questions.p": "mỗi câu kiểm tra một điểm thiếu ở trên",
  "hr.pr.unconf": "Thông tin chưa xác nhận được",
  "hr.pr.sources": "Nguồn",
  "hr.pr.sources.count": "{n} nguồn",
  "hr.pr.nosources": "Không có nguồn công khai nào được lưu cho báo cáo này.",
  "hr.pr.method.title": "Điểm được tính thế nào",
  "hr.pr.method.h": "Phương pháp",
  "hr.pr.m.1": "Chúng tôi đọc các đường dẫn được cung cấp, rồi chạy {s} trên tối đa {b} lượt tìm kiếm. Giữ lại {p} trang, mỗi trang được lưu kèm mã băm.",
  "hr.pr.m.2": "Một dữ kiện chỉ Đã xác minh khi một trang đã lưu nêu tên người đó và nói điều đó bằng lời chúng tôi trích dẫn. Nếu không, nó là Tự khai hoặc Chưa xác nhận.",
  "hr.pr.m.3": "Mỗi phần điểm được đề xuất kèm trích dẫn; mã chương trình tính tổng theo trọng số cố định ({w}). Phần không có bằng chứng bị giới hạn ở {c}.",
  "hr.pr.m.4": "Độ tin cậy là tỷ lệ điểm có trọng số được dữ kiện đã xác minh hỗ trợ: từ 75% là Cao, 45–74% là Trung bình, dưới 45% là Thấp. Khoảng có thể là ±4, ±6 hoặc ±10.",
  "hr.pr.m.5": "Mức: Mạnh 85+ · Tốt 70–84 · Trung bình 55–69 · Yếu 40–54 · Rất yếu dưới 40. Khi độ tin cậy Thấp, mức ghi là \"Chưa đủ bằng chứng\".",
  "hr.pr.m.team": "Điểm đội ngũ = 60% điểm cá nhân (theo trọng số vai trò: nhà sáng lập 1,5×, đồng sáng lập 1,2×, quản lý 1,0×, cố vấn 0,4×) + 40% yếu tố đội ngũ. Cảnh báo đã xác minh làm giảm điểm.",
  "hr.pr.person.h": "Được người kiểm tra",
  "hr.pr.p.val": "Trước khi điểm đội ngũ thay đổi bản định giá doanh nghiệp, quản trị viên BlockID xem xét nó ở bước duyệt định giá.",
  "hr.pr.p.noval": "Báo cáo này chưa liên kết với bản định giá nào nên không làm thay đổi điểm doanh nghiệp.",
  "hr.pr.p.2": "Người duyệt có thể chỉnh một phần điểm; mọi thay đổi đều được ghi lại kèm lý do.",
  "hr.pr.p.3": "Báo cáo này hỗ trợ quyết định, không thay thế quyết định.",
  "hr.pr.mistake": "Báo lỗi",
  "hr.pr.cf.h": "Đồng ý và công bằng",
  "hr.pr.cf.agreed": "Ngày {d}, người yêu cầu xác nhận {n} đã đồng ý với việc đánh giá này. Chỉ dùng thông tin nghề nghiệp công khai và chỉ cho lần đánh giá này.",
  "hr.pr.cf.remove": "Bất kỳ ai có tên đều có thể xem, sửa hoặc gỡ báo cáo:",
  "hr.pr.cf.never": "Không bao giờ thu thập hoặc chấm điểm:",
  "hr.pr.cf.n1": "Tuổi, giới tính, dân tộc, quốc tịch, ảnh",
  "hr.pr.cf.n2": "Gia đình, sức khỏe, tôn giáo, chính trị",
  "hr.pr.cf.n3": "Địa chỉ nhà, số điện thoại hoặc email cá nhân",
  "hr.pr.cf.n4": "Danh tiếng trường học hay nơi làm việc, khoảng nghỉ trong sự nghiệp",
  "hr.pr.legal": "Bản demo trên testnet. Không phải chào bán chứng khoán hay tư vấn tài chính. Báo cáo này hỗ trợ quyết định, không thay thế quyết định. BlockID HR · báo cáo {id} · {d}.",

  "hr.tr.formula": "Cá nhân {p} × 60% + yếu tố đội ngũ {f} × 40% − cảnh báo {r}",
  "hr.tr.contrib": "Phần trong điểm doanh nghiệp",
  "hr.tr.contrib.aria": "Đội ngũ sáng lập đóng góp {s} trên 30 điểm của điểm doanh nghiệp",
  "hr.tr.contrib.p": "Đội ngũ sáng lập chiếm 30% điểm doanh nghiệp. Điểm đội ngũ {s} đóng góp {x} trên 30 điểm.",
  "hr.tr.noval": "Chưa liên kết với bản định giá doanh nghiệp.",
  "hr.tr.comp": "Thành phần",
  "hr.tr.comp.n": "{n} người · xếp theo trọng số",
  "hr.tr.weight": "Trọng số",
  "hr.tr.open": "Mở báo cáo cá nhân",
  "hr.tr.team": "Cả đội",
  "hr.tr.q.p": "dành cho các nhà sáng lập",

  "hr.m.p": "Các quy tắc này được in trên mọi báo cáo. Điểm số hỗ trợ quyết định, không thay thế quyết định.",
  "hr.m.fit": "Điểm phù hợp",
  "hr.m.fit.p": "So sánh người đó với một doanh nghiệp (phù hợp nhà sáng lập – doanh nghiệp) hoặc một vị trí (phù hợp vị trí), gồm sáu phần:",
  "hr.m.team": "Điểm đội ngũ",
  "hr.m.bands": "Các mức",
  "hr.m.conf": "Độ tin cậy (Cao, Trung bình, Thấp) là tỷ lệ điểm được dữ kiện đã xác minh hỗ trợ. Khi độ tin cậy Thấp, mức ghi là \"Chưa đủ bằng chứng\".",
  "hr.m.ev": "Nhãn bằng chứng",

  "hr.me.col.kind": "Báo cáo",
  "hr.me.kind.person": "Cá nhân",
  "hr.me.kind.team": "Đội ngũ",

  "hr.np.eyebrow": "Báo cáo cá nhân mới",
  "hr.np.h1": "Phân tích một người",
  "hr.np.p": "CV được đối chiếu với nguồn công khai và điểm phù hợp, mọi dữ kiện đều dẫn tới nơi tìm thấy. Mất khoảng 2–4 phút.",
  "hr.np.s1": "Người được đánh giá",
  "hr.np.s1.p": "Họ tên, vai trò và đường dẫn công khai. Những gì bạn nhập được ghi là tự khai.",
  "hr.np.role": "Vai trò tại mục tiêu",
  "hr.np.rel": "Quan hệ",
  "hr.np.headline": "Dòng giới thiệu (không bắt buộc)",
  "hr.np.headline.ph": "vd. Chuyên gia vận tải, từng làm tại Toll Group",
  "hr.np.works": "Hình thức làm việc",
  "hr.np.equity": "Cổ phần % (không bắt buộc)",
  "hr.np.links": "Đường dẫn công khai",
  "hr.np.link": "Đường dẫn {n}",
  "hr.np.addlink": "Thêm đường dẫn (trang giới thiệu, GitHub, Scholar, báo chí)",
  "hr.np.linkedin": "Không đọc được trang LinkedIn; thông tin từ đó được ghi là tự khai.",
  "hr.np.bio.hint": "{n} / 1.500 · hiển thị là tự khai. Vui lòng không nhập thông tin cá nhân.",
  "hr.np.cv": "Dán CV (không bắt buộc)",
  "hr.np.cv.ph": "Dán nội dung CV. Email và số điện thoại được xóa trước khi tìm kiếm.",
  "hr.np.cv.hint": "{n} / 20.000 · hiển thị là tự khai",
  "hr.np.s2": "So sánh với",
  "hr.np.s2.p": "Chọn đối tượng để so sánh người này.",
  "hr.np.t.business": "Một doanh nghiệp trên BlockID",
  "hr.np.t.business.p": "Dùng hồ sơ và giai đoạn của doanh nghiệp. Góp vào điểm đội ngũ của doanh nghiệp đó.",
  "hr.np.t.role": "Một vị trí",
  "hr.np.t.role.p": "Công việc người này ứng tuyển hoặc bạn đang tuyển.",
  "hr.np.biz": "Doanh nghiệp",
  "hr.np.biz.ph": "Tìm trong các bản định giá của bạn hoặc doanh nghiệp đã niêm yết",
  "hr.np.biz.val": "định giá",
  "hr.np.biz.none": "Không có kết quả. Hãy nhập website bên dưới.",
  "hr.np.biz.web": "…hoặc website của doanh nghiệp",
  "hr.np.biz.web.hint": "Website công khai nào cũng được, kể cả khi doanh nghiệp chưa có trên BlockID.",
  "hr.np.change": "Đổi",
  "hr.np.company": "Công ty",
  "hr.np.company.ph": "vd. Southern Cross Freight",
  "hr.np.title": "Tên vị trí",
  "hr.np.title.ph": "vd. Giám đốc vận hành",
  "hr.np.desc": "Mô tả công việc (không bắt buộc)",
  "hr.np.desc.ph": "Dán tin tuyển dụng hoặc mô tả phạm vi, quy mô đội và mục tiêu.",
  "hr.np.desc.hint": "{n} / 5.000",
  "hr.np.s3": "Yêu cầu",
  "hr.np.s3.p": "Tối đa 5 yêu cầu bắt buộc và 4 yêu cầu nên có. Mọi người được đánh giá cho vị trí này dùng cùng một danh sách.",
  "hr.np.s3.biz": "Với doanh nghiệp, chúng tôi lấy yêu cầu từ hồ sơ, giai đoạn và các điểm thiếu của đội. Bạn sẽ thấy từng yêu cầu trong báo cáo.",
  "hr.np.req.count": "{n} trên {m}",
  "hr.np.req.empty": "Chưa có",
  "hr.np.req.ph": "Nhập một yêu cầu rồi nhấn Enter",
  "hr.np.req.full": "Danh sách đã đầy: hãy xóa bớt một yêu cầu",
  "hr.np.req.add": "Thêm",
  "hr.np.req.up": "Chuyển sang bắt buộc",
  "hr.np.req.down": "Chuyển sang nên có",
  "hr.np.req.n": "{n} yêu cầu",
  "hr.np.s4": "Sự đồng ý",
  "hr.np.s4.p": "Bắt buộc trước khi chúng tôi tìm kiếm bất cứ điều gì.",
  "hr.np.c1": "{n} đã đồng ý với việc đánh giá này.",
  "hr.np.c1.sub": "Chúng tôi ghi ngày đồng ý trên báo cáo.",
  "hr.np.c2": "Tôi chỉ dùng báo cáo cho {n}.",
  "hr.np.theperson": "Người này",
  "hr.np.thistarget": "doanh nghiệp hoặc vị trí này",
  "hr.np.never.b": "Chúng tôi chỉ đọc các trang nghề nghiệp công khai.",
  "hr.np.never": "Chúng tôi không bao giờ thu thập hay chấm điểm tuổi, giới tính, dân tộc, quốc tịch, ảnh, gia đình, sức khỏe, tôn giáo, chính trị, địa chỉ nhà, số điện thoại hay email cá nhân, hoặc danh tiếng trường học.",
  "hr.np.sum": "Tóm tắt",
  "hr.np.sum.person": "Người",
  "hr.np.sum.reqs": "{m} bắt buộc · {n} nên có",
  "hr.np.sum.search": "Lượt tìm trên web",
  "hr.np.sum.search.v": "tối đa 3",
  "hr.np.sum.time": "Thời gian",
  "hr.np.sum.time.v": "khoảng 2–4 phút",
  "hr.np.gate": "Đánh dấu cả hai ô đồng ý để bắt đầu.",
  "hr.np.fine": "Bạn sẽ thấy dòng trạng thái trong lúc chạy. Báo cáo chỉ mình bạn xem được cho đến khi bạn chia sẻ.",
  "hr.np.e.headline": "Dòng giới thiệu không quá 200 ký tự.",
  "hr.np.e.cv": "CV không quá 20.000 ký tự.",
  "hr.np.e.biz": "Chọn một doanh nghiệp hoặc nhập website của doanh nghiệp.",
  "hr.np.e.company": "Nhập tên công ty.",
  "hr.np.e.title": "Nhập tên vị trí.",
  "hr.np.e.desc": "Mô tả không quá 5.000 ký tự.",
  "hr.np.e.use": "Vui lòng xác nhận cách bạn sẽ dùng báo cáo.",
};
