/**
 * Admin "AI health" screen (/admin/ai, docs/PLAN-AI-GATEWAY.md §3; API studio/ai_admin.py). Plain words.
 * VI must cover every EN key (checked by the type).
 */
export const aiEn = {
  "ad.t.ai": "AI health",
  "ad.d.ai": "Every AI model and search service: how close each is to its limits, errors, speed and spend. Refreshes every 15 s.",
  "ai.sb.ok": "All models healthy",
  "ai.sb.warn": "{n} need attention",
  "ai.sb.bad": "No healthy model left",
  "ai.sb.meta": "Updated {s} s ago · refreshes every 15 s",
  "ai.routing.dynamic": "Routing: best quality × reliability ÷ cost",
  "ai.routing.static": "Routing: fixed order from the settings",
  "ai.k.healthy": "Healthy",
  "ai.k.demoted": "Fallback only",
  "ai.k.down": "Skipped / open / paused",
  "ai.k.spend": "Spend today",
  "ai.k.of": "of {n} in total",
  "ai.k.budget": "budget {b}",
  "ai.k.nobudget": "no daily budget",
  "ai.prov.h": "Providers",
  "ai.prov.conc": "up to {n} calls at once",
  "ai.prov.models": "Models: {n}",
  "ai.models.h": "Models and services",
  "ai.models.empty": "No AI model is configured.",
  "ai.st.healthy": "Healthy",
  "ai.st.demoted": "Fallback only",
  "ai.st.skipped": "Skipped",
  "ai.st.open": "Circuit open",
  "ai.st.paused": "Paused",
  "ai.kind.llm": "AI model",
  "ai.kind.search": "Search",
  "ai.w.minute": "Per minute",
  "ai.w.day": "Per day",
  "ai.w.month": "Per month",
  "ai.w.budget_day": "Daily budget",
  "ai.w.used": "{u} of {l}",
  "ai.w.headers": "from the provider",
  "ai.w.none": "No known limit",
  "ai.w.marks": "Marks at 80 % (fallback only) and 95 % (skipped until the reset)",
  "ai.w.resets": "resets {t}",
  "ai.m.err": "Errors (24 h)",
  "ai.m.lat": "Speed p50 / p90",
  "ai.m.spend": "Spend today",
  "ai.m.calls": "Calls (24 h)",
  "ai.m.reset": "Next reset",
  "ai.m.valid": "Valid answers",
  "ai.m.lasterr": "Last error {t}:",
  "ai.m.circuit": "Circuit open until {t} after {n} failures in a row",
  "ai.m.pausedby": "Paused by {w}",
  "ai.m.until": "until {t}",
  "ai.m.untilres": "until resumed",
  "ai.pause": "Pause",
  "ai.resume": "Resume",
  "ai.pause.for": "Pause for",
  "ai.pause.30": "30 minutes",
  "ai.pause.60": "1 hour",
  "ai.pause.1440": "1 day",
  "ai.pause.0": "until resumed",
  "ai.pause.done": "{m} paused",
  "ai.resume.done": "{m} resumed",
  "ai.adminonly": "Only platform admins can pause or resume a model.",
  "ai.prof.h": "Order per task",
  "ai.prof.extract_json": "Fact extraction",
  "ai.prof.reason_score": "Scoring and reasoning",
  "ai.prof.long_context": "Long documents",
  "ai.prof.search": "Web search",
  "ai.fb.h": "Recent fallbacks",
  "ai.fb.empty": "No fallback in the recent calls.",
  "ai.fb.line": "{f} → {n}",
  "ai.fb.none": "no model left",
  "ai.out.error": "error",
  "ai.out.timeout": "timed out",
  "ai.out.schema_invalid": "invalid answer",
  "ai.out.rate_limited": "rate-limited",
  "ai.out.skipped": "skipped",
  "ai.out.cancelled": "cancelled (hedged)",
  "ai.table": "Show as table",
  "ai.cards": "Show as cards",
  "ai.col.model": "Model",
  "ai.col.status": "Status",
  "ai.col.usage": "Highest use",
  "ai.err.down": "The AI health service did not answer. The models keep working; try again in a moment.",
};

export const aiVi: Record<keyof typeof aiEn, string> = {
  "ad.t.ai": "Sức khoẻ AI",
  "ad.d.ai": "Mọi mô hình AI và dịch vụ tìm kiếm: mức gần giới hạn, lỗi, tốc độ và chi phí. Tự làm mới mỗi 15 giây.",
  "ai.sb.ok": "Mọi mô hình đều ổn",
  "ai.sb.warn": "{n} mô hình cần chú ý",
  "ai.sb.bad": "Không còn mô hình nào hoạt động tốt",
  "ai.sb.meta": "Cập nhật {s} giây trước · làm mới mỗi 15 giây",
  "ai.routing.dynamic": "Định tuyến: chất lượng × độ tin cậy ÷ chi phí tốt nhất",
  "ai.routing.static": "Định tuyến: thứ tự cố định theo cấu hình",
  "ai.k.healthy": "Hoạt động tốt",
  "ai.k.demoted": "Chỉ dùng dự phòng",
  "ai.k.down": "Bỏ qua / ngắt / tạm dừng",
  "ai.k.spend": "Chi phí hôm nay",
  "ai.k.of": "trên {n} mô hình",
  "ai.k.budget": "ngân sách {b}",
  "ai.k.nobudget": "không có ngân sách ngày",
  "ai.prov.h": "Nhà cung cấp",
  "ai.prov.conc": "tối đa {n} lệnh gọi cùng lúc",
  "ai.prov.models": "{n} mô hình",
  "ai.models.h": "Mô hình và dịch vụ",
  "ai.models.empty": "Chưa cấu hình mô hình AI nào.",
  "ai.st.healthy": "Hoạt động tốt",
  "ai.st.demoted": "Chỉ dùng dự phòng",
  "ai.st.skipped": "Đang bỏ qua",
  "ai.st.open": "Đã ngắt mạch",
  "ai.st.paused": "Tạm dừng",
  "ai.kind.llm": "Mô hình AI",
  "ai.kind.search": "Tìm kiếm",
  "ai.w.minute": "Mỗi phút",
  "ai.w.day": "Mỗi ngày",
  "ai.w.month": "Mỗi tháng",
  "ai.w.budget_day": "Ngân sách ngày",
  "ai.w.used": "{u} / {l}",
  "ai.w.headers": "theo nhà cung cấp",
  "ai.w.none": "Không rõ giới hạn",
  "ai.w.marks": "Mốc 80 % (chỉ dùng dự phòng) và 95 % (bỏ qua đến khi đặt lại)",
  "ai.w.resets": "đặt lại {t}",
  "ai.m.err": "Lỗi (24 giờ)",
  "ai.m.lat": "Tốc độ p50 / p90",
  "ai.m.spend": "Chi phí hôm nay",
  "ai.m.calls": "Lệnh gọi (24 giờ)",
  "ai.m.reset": "Lần đặt lại tới",
  "ai.m.valid": "Câu trả lời hợp lệ",
  "ai.m.lasterr": "Lỗi gần nhất {t}:",
  "ai.m.circuit": "Ngắt mạch đến {t} sau {n} lần lỗi liên tiếp",
  "ai.m.pausedby": "Tạm dừng bởi {w}",
  "ai.m.until": "đến {t}",
  "ai.m.untilres": "đến khi tiếp tục",
  "ai.pause": "Tạm dừng",
  "ai.resume": "Tiếp tục",
  "ai.pause.for": "Tạm dừng trong",
  "ai.pause.30": "30 phút",
  "ai.pause.60": "1 giờ",
  "ai.pause.1440": "1 ngày",
  "ai.pause.0": "đến khi tiếp tục",
  "ai.pause.done": "Đã tạm dừng {m}",
  "ai.resume.done": "Đã tiếp tục {m}",
  "ai.adminonly": "Chỉ admin nền tảng mới được tạm dừng hoặc tiếp tục mô hình.",
  "ai.prof.h": "Thứ tự theo từng việc",
  "ai.prof.extract_json": "Trích xuất dữ kiện",
  "ai.prof.reason_score": "Chấm điểm và suy luận",
  "ai.prof.long_context": "Tài liệu dài",
  "ai.prof.search": "Tìm kiếm web",
  "ai.fb.h": "Lần chuyển dự phòng gần đây",
  "ai.fb.empty": "Không có lần chuyển dự phòng nào gần đây.",
  "ai.fb.line": "{f} → {n}",
  "ai.fb.none": "không còn mô hình",
  "ai.out.error": "lỗi",
  "ai.out.timeout": "quá thời gian",
  "ai.out.schema_invalid": "câu trả lời không hợp lệ",
  "ai.out.rate_limited": "bị giới hạn tốc độ",
  "ai.out.skipped": "bỏ qua",
  "ai.out.cancelled": "đã huỷ (gọi song song)",
  "ai.table": "Xem dạng bảng",
  "ai.cards": "Xem dạng thẻ",
  "ai.col.model": "Mô hình",
  "ai.col.status": "Trạng thái",
  "ai.col.usage": "Mức dùng cao nhất",
  "ai.err.down": "Dịch vụ sức khoẻ AI chưa phản hồi. Các mô hình vẫn hoạt động; hãy thử lại sau giây lát.",
};
