import { protoEn, protoVi } from "./dict.proto";
import { invEn, invVi } from "./dict.investor";
import { updEn, updVi } from "./dict.updates";
import { divEn, divVi } from "./dict.dividends";

/** App strings added on top of the prototype copy. VI must cover every EN key (checked by the type). */
const appEn = {
  "nav.companies": "Businesses",
  "nav.connect": "Connect wallet",
  "nav.connecting": "Signing in…",
  "nav.signout": "Sign out",
  "nav.account": "Account menu",
  "nav.lang": "Language",
  "nav.primary": "Primary",
  "nav.skip": "Skip to content",
  "nav.role.admin": "admin",
  "nav.role.user": "wallet",
  "nav.adminlink": "Open admin console",
  "common.loading": "Loading…",
  "common.error": "Something went wrong.",
  "common.retry": "Retry",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.none": "–",
  "common.back": "Back",
  "common.yes": "Yes",
  "err.unauth": "Please connect your wallet and sign in first.",
  "err.forbidden": "Your account is not allowed to do this.",
  "err.rate": "Too many requests. Try again later.",
  "err.network": "Network error. Check your connection and try again.",
  "err.rejected": "Request rejected in the wallet.",
  "err.nomm": "MetaMask not found in this browser.",

  "home.stats.eyebrow": "Live on the testnet",
  "home.stats.h2": "The platform today",
  "home.stats.p": "Live numbers from the demo. Values are fair values checked by people, not market prices.",
  "home.st.co": "Businesses listed",
  "home.st.val": "Total fair value",
  "home.st.tok": "Share records on blockchain",
  "home.st.tokSub": "kept on 3 public blockchains",
  "home.st.asof": "updated at block #{b}",
  "home.recent": "Recently listed",
  "home.recent.all": "See all businesses",
  "home.recent.empty": "No businesses yet. Yours could be the first.",
  "home.walk.cta": "Start with your website",
  "home.walk.sample": "Open a sample company",

  "new.eyebrow": "New valuation",
  "new.h2": "Eight steps from website to wallet",
  "new.p": "Gold steps need a person: an admin approves the valuation, then gives one issuance approval. The sync to Hoodi and HashKey runs automatically.",
  "new.signin": "Connect your wallet to start. Each valuation belongs to the wallet that requested it.",
  "new.bad.url": "Enter a website address, for example https://example.com.au.",
  "new.limit": "Daily limit reached: 3 valuations per wallet per day. Try again tomorrow.",
  "new.starting": "Starting…",

  "v.eyebrow": "Valuation",
  "v.st.queued": "Queued",
  "v.st.running": "AI agents running",
  "v.st.waiting_approval": "Waiting for admin approval",
  "v.st.approved": "Approved",
  "v.st.rejected": "Rejected",
  "v.st.failed": "Failed",
  "v.waiting": "Waiting for admin approval. An admin reviews every AI score before anything can be issued. This page updates by itself.",
  "v.rejected": "An admin rejected this valuation. You can start a new one.",
  "v.failed": "The valuation failed: {e}",
  "v.poll": "Updates every 3 s",
  "v.warn": "Warnings:",
  "v.verified": "verified via website",
  "v.verified.tip": "Suggested by the model, then confirmed by fetching the competitor's own website.",
  "v.mine": "Your valuations",
  "v.mine.co": "Your companies",
  "v.open": "Open",
  "v.queued": "Waiting for a free agent…",
  "v.signin": "Connect the wallet that requested this valuation to view it.",
  "v.notfound": "Valuation not found.",
  "v.total": "SVI index · grade {g}",
  "v.method": "Method: {m}",
  "v.nd": "not disclosed",
  "v.narr": "Analyst narrative",
  "v.evidence": "Evidence",
  "v.evidence.p": "Every page the agents fetched and cited.",
  "v.evidence.empty": "No evidence yet.",
  "v.retrieved": "retrieved {d}",
  "sr.toggle": "Add your numbers (optional, improves accuracy)",
  "sr.help": "Self-reported. Shown as such in the report.",
  "sr.why": "A website rarely states revenue, so without these figures the revenue and growth scores stay near zero.",
  "sr.revenue": "Revenue, last 12 months (A$)",
  "sr.growth": "Revenue growth, year on year (%)",
  "sr.margin": "Gross margin (%)",
  "sr.customers": "Paying customers",
  "sr.raised": "Raised to date (A$)",
  "sr.runway": "Runway (months)",
  "sr.employees": "Employees",
  "sr.bad": "Check the highlighted number: {f}",
  "sr.chip": "Self-reported",
  "sr.chip.tip": "Figure provided by the founder, not independently verified.",
  "sr.table": "Self-reported figures",
  "sr.table.p": "Provided by the founder when requesting the valuation. Not independently verified.",
  "v.sources": "{n} sources",
  "v.adm.h": "Admin review",
  "v.adm.p": "Adjust any AI score before approving. The server recalculates the index and valuation.",
  "v.adm.preview": "Index with your scores",
  "v.adm.reject": "Reject valuation",
  "v.adm.done": "Decision saved.",
  "v.continue": "Continue to ticker",
  "v.newval": "Start a new valuation",
  "v.running.note": "About 2–4 minutes. You can close the tab; this link resumes the job.",
  "v.tk.custom": "Or type your own",
  "v.tk.taken": "taken",
  "v.tk.bad": "Use exactly three letters A–Z.",
  "v.tk.cname": "Company name",
  "v.tk.none": "No suggestions yet.",
  "v.sh.add": "Add holder",
  "v.sh.remove": "Remove {n}",
  "v.sh.name": "Name",
  "v.sh.badaddr": "Not a valid address (EIP-55 checksum).",
  "v.sh.dup": "Wallet already listed.",
  "v.sh.badname": "Enter a name.",
  "v.sh.submit": "Create & submit for approval",
  "v.sh.creating": "Submitting…",
  "v.sh.need": "Fix the highlighted rows first.",
  "v.sh.default": "Default: valuation mid ÷ A$1.00 = {n}",
  "v.sh.draft": "Created as a draft, but it could not be submitted: {e}",

  "c.eyebrow": "Company",
  "c.st.draft": "Draft",
  "c.st.pending_issue": "Awaiting issue approval",
  "c.st.issuing": "Issuing on BlockID Chain",
  "c.st.issued": "Issued on BlockID Chain",
  "c.st.pending_anchor": "Awaiting chain sync",
  "c.st.anchoring": "Syncing to Hoodi & HashKey",
  "c.st.anchored": "Live on BlockID, Hoodi & HashKey",
  "c.st.rejected": "Rejected",
  "c.st.failed": "Failed",
  "c.tl.draft": "Draft",
  "c.tl.pending_issue": "Pending issue",
  "c.tl.issuing": "Issuing",
  "c.tl.issued": "Issued",
  "c.tl.anchoring": "Anchoring",
  "c.tl.anchored": "Anchored",
  "c.gate": "admin",
  "c.k.val": "Valuation",
  "c.k.valsub": "SVI {s} · grade {g}",
  "c.k.noanchor": "not yet",
  "c.cap": "Cap table",
  "c.cap.p": "Balances read from BlockID Chain.",
  "c.cap.empty": "No holders yet.",
  "c.other": "Other",
  "c.cap.chain": "Balances read from BlockID Chain at block #{b}.",
  "c.cap.db": "Issuance record (not yet on-chain, or the chain is unreachable).",
  "c.mark": "Share mark",
  "c.notyet": "Not deployed yet",
  "c.addr.localwait": "Appears after an admin approves issuance.",
  "c.addr.hoodiwait": "Appears automatically once issuance on BlockID completes.",
  "c.qr": "QR code for {a}",
  "c.mint.to": "Recipient wallet",
  "c.mint.name": "Holder name",
  "c.mint.reason": "Reason",
  "c.mint.sent": "Mint request sent for admin approval.",
  "c.mint.existing": "Existing holder: shares are added to their balance.",
  "c.div.sent": "Dividend plan sent for approval.",
  "c.div.root": "computed by the server at the record block",
  "c.ev": "Activity",
  "c.ev.empty": "No on-chain activity yet.",
  "c.notfound": "No company with ticker {t}.",
  "c.draftnote": "This company is a draft. An admin or an approved issuer wallet must submit it for approval.",
  "c.submit": "Submit for approval",
  "c.submitted": "Submitted. An admin will review the issuance.",
  "c.needauth": "Connect the owner wallet or sign in as admin to request mints or dividends.",
  "c.failed": "The issuer reported an error: {e}",
  "c.website": "Website",
  "c.anchor.root": "Merkle root",
  "c.onlyissued": "Available once the shares are issued.",

  "ev.issued": "Shares issued",
  "ev.kyc": "Investor KYC-registered",
  "ev.drip": "Gas allowance sent",
  "ev.minted": "Shares minted",
  "ev.valuation_anchored": "Valuation hash anchored",
  "ev.revalued": "Revalued",
  "ev.hoodi_mirrored": "Mirror token synced on Hoodi",
  "ev.anchored": "Cap table anchored",
  "ev.dividend_created": "Dividend round created",
  "ev.dividend_claimed": "Dividend claimed",
  "ev.mint_requested": "Mint requested",
  "ev.rejected": "Rejected",

  "co.eyebrow": "Market",
  "co.h2": "Tokenised companies",
  "co.p": "Every company issued on BlockID Chain. Marks change only on issuance and approved SVI revaluations; they are not market prices.",
  "co.search": "Search ticker or company",
  "co.empty": "No companies match.",
  "co.anchNo": "not yet",
  "co.anchYes": "✓ Hoodi",
  "co.sort": "Sort by {c}",

  "ad.t.ap": "Approvals",
  "ad.t.cos": "Companies",
  "ad.t.au": "Audit log",
  "ad.notadmin": "This wallet is signed in as a regular user. Only wallets on the admin list, or the admin account, can open the console.",
  "ad.bad.rate": "Too many attempts. Try again in 15 minutes.",
  "ad.paused": "Paused · tab hidden",
  "ad.cp.h": "Change the admin password",
  "ad.cp.p": "The demo password must be changed before you continue. Use at least 10 characters.",
  "ad.cp.cur": "Current password",
  "ad.cp.new": "New password",
  "ad.cp.rep": "Repeat new password",
  "ad.cp.go": "Change password",
  "ad.cp.short": "Use at least 10 characters.",
  "ad.cp.mismatch": "The passwords do not match.",
  "ad.cp.ok": "Password changed.",
  "ad.k.tokval": "{n} contracts",
  "ad.k.anchval": "{a} / {b}",
  "ad.aw.list": "Admin wallets · visible to admins only",
  "ad.aw.svc": "Service wallets",
  "ad.aw.issuer": "Issuer service",
  "ad.aw.relayer": "Relayer (claims only)",
  "ad.aw.bal": "BlockID {a} BLKD · Hoodi {b} ETH · HashKey {c} HSK",
  "ad.iw.empty": "No issuer wallets yet.",
  "ad.audit.empty": "No audit entries yet.",
  "ad.co.pick": "Pick a company in the table to see its mark chart and revalue it.",
  "ad.co.open": "Open public page",

  "ap.val": "Valuations waiting for review",
  "ap.co": "Companies to issue on BlockID Chain",
  "ap.anchor": "Issued · chains still to sync",
  "ap.mints": "Mint requests",
  "ap.divs": "Dividend plans",
  "ap.empty": "Nothing waiting. New requests appear here automatically.",
  "ap.open": "Open report",
  "ap.approve": "Approve",
  "ap.reject": "Reject",
  "ap.review": "Review transactions",
  "ap.hide": "Hide",
  "ap.anchorbtn": "Re-sync Hoodi & HashKey",
  "ap.reason": "Reason for rejection",
  "ap.txs": "Transactions the issuer service will send",
  "ap.sent": "Approved. The issuer service is working; status updates here.",
  "ap.rejected": "Rejected.",
  "ap.mintrow": "{n} {tk} → {name}",
  "ap.divrow": "{n} mAUD to {tk} holders",
  "ap.req": "requested by {w}",
  "ap.holders": "{n} holders",
  "ap.anchor.txs": "On Hoodi and HashKey: deploy mirror registry + token · register and mint {n} holders · pause · CapTableAnchor.anchor(root)",
  "tx.kycrole": "Grant KYC_AGENT_ROLE to issuer",
  "tx.tokN": "Deploy {tk} share token (decimals 0)",
  "tx.kycN": "KYC {n} wallets",
  "tx.gasN": "Gas allowance to up to {n} wallets",
  "tx.mintN": "Mint {s} {tk} to {n} holders",
  "tx.valN": "Anchor SVI report hash · mark A$1.00",

  "rv.h": "Revalue",
  "rv.p": "Sets a new valuation. The mark becomes valuation ÷ shares and the cap table is re-anchored.",
  "rv.val": "New valuation (A$)",
  "rv.note": "Note",
  "rv.go": "Submit revaluation",
  "rv.newmark": "New mark {m} ({p})",
  "rv.ok": "Revaluation recorded.",

  "nf.h": "Page not found",
  "nf.p": "The page you asked for does not exist or has moved.",
  "nf.home": "Back to home",
  "nav.hsk": "HashKey Chain",
  "hsk.eyebrow": "HashKey Chain testnet · chain 133",
  "hsk.title": "Live on HashKey Chain",
  "hsk.msg": "AI agents never hold keys. Every agent proposal is hashed on-chain, a human approver signs, and only then the issuer executes.",
  "hsk.live": "Live",
  "hsk.open": "See the deployment",
  "hsk.card.stats": "{c} contracts deployed · {p} agent proposals on-chain",
  "hsk.pending": "Deployment pending.",
  "hsk.pending.p": "The HashKey Chain contracts are being deployed. Addresses, proposals and transactions appear here as soon as they are published.",
  "hsk.addnet": "Add HashKey Chain to MetaMask",
  "hsk.added": "HashKey Chain testnet is ready in your wallet.",
  "hsk.explorer": "Open in explorer",
  "hsk.flow": "AI proposes → human approves → issuer executes",
  "hsk.f1": "AI proposes",
  "hsk.f1s": "hash recorded on-chain",
  "hsk.f2": "Human approves",
  "hsk.f2s": "approver signs",
  "hsk.f3": "Issuer executes",
  "hsk.f3s": "only key holder",
  "hsk.contracts": "Contracts",
  "hsk.deployed": "Deployed",
  "hsk.c.prov": "Agent provenance",
  "hsk.c.reg": "Identity registry (KYC)",
  "hsk.c.share": "Share token",
  "hsk.c.div": "Dividend distributor",
  "hsk.c.pay": "Payout token",
  "hsk.c.anchor": "Cap table anchor",
  "hsk.roles": "Roles",
  "hsk.r.op": "Operator (issuer)",
  "hsk.r.relayer": "Relayer (agents)",
  "hsk.r.approver": "Human approver",
  "hsk.roles.p": "The relayer can only submit proposal hashes. It cannot approve or execute anything.",
  "hsk.prov": "Agent provenance",
  "hsk.prov.p": "Each AI output is hashed and proposed on-chain. Check any hash against the AgentProvenance contract yourself.",
  "hsk.prov.empty": "No agent proposals published yet.",
  "hsk.hash": "Content hash",
  "hsk.model": "Model",
  "hsk.verify": "Verify on-chain",
  "hsk.v.ok": "Hash matches on-chain record",
  "hsk.v.no": "Hash does not match",
  "hsk.v.err": "Could not reach HashKey RPC",
  "hsk.div": "Dividends",
  "hsk.div.round": "Dividend round",
  "hsk.div.id": "Round",
  "hsk.div.total": "Total",
  "hsk.div.deadline": "Claim deadline",
  "hsk.div.root": "Merkle root",
  "hsk.div.units": "Amounts in mAUD (DemoAUD, 6 decimals). Holders claim with a Merkle proof.",
  "hsk.div.claims": "Holder claims",
  "hsk.div.amt": "Amount",
  "hsk.div.empty": "No dividend round published yet.",
  "hsk.txs": "Transactions",
  "nav.verify": "Check records",
  "vf.eyebrow": "Auditable AI valuation",
  "vf.title": "Verify a valuation yourself",
  "vf.lead": "The AI only scores the 7 SVI dimensions. A fixed public formula turns those scores into the index and the valuation, and the hash of the full report is written on-chain. Recompute it here, in your own browser.",
  "vf.s1": "AI suggests 7 dimension scores; an admin confirms them",
  "vf.s2": "A fixed public formula computes the SVI index and the value",
  "vf.s3": "keccak256 of the canonical report JSON is anchored on-chain",
  "vf.s4": "Anyone recomputes the hash and compares: same input, same output",
  "vf.pick": "Company",
  "vf.pick.none": "Paste my own report JSON…",
  "vf.opencompany": "Open company",
  "vf.paste.hint": "Pick a listed company to load its report and on-chain hashes, or paste any report JSON below to hash it.",
  "vf.paste.ph": "Paste a valuation report JSON here ({\"url\": …, \"profile\": …, \"svi\": …})",
  "vf.ok": "Verified: the on-chain hash matches this report",
  "vf.ok.p": "Browser, server and {n} on-chain record(s) agree byte for byte. Nobody changed this report after it was approved.",
  "vf.bad": "Mismatch: this report is not what was anchored on-chain",
  "vf.bad.p": "The hash of this report differs from at least one on-chain record.",
  "vf.bad.edited": "You edited the report, so its hash no longer matches the on-chain record. Press Reset to restore it.",
  "vf.bad.nochain": "Hash computed. Pick a listed company to compare it with the on-chain record.",
  "vf.info": "Hash computed",
  "vf.wait": "Checking…",
  "vf.wait.p": "Recomputing the hash on the server.",
  "vf.hashes": "Three independent hashes",
  "vf.browser": "Browser hash",
  "vf.browser.p": "keccak256 computed right here in your browser (viem).",
  "vf.server": "Server hash",
  "vf.server.p": "The same text re-hashed by the BlockID API (Python).",
  "vf.onchain": "On-chain hash",
  "vf.onchain.p": "valuationReportHash() read from each share token.",
  "vf.onchain.none": "This company has no token with an anchored report yet.",
  "vf.onchain.pick": "Pick a company to read its on-chain hashes.",
  "vf.explorer": "Token in explorer",
  "vf.report": "Report JSON",
  "vf.report.p": "Edit anything and watch the hashes change. Only url, profile, competitors, market, svi and self_reported are hashed.",
  "vf.tamper": "Tamper test: change one score",
  "vf.reset": "Reset",
  "vf.canonical": "Canonical JSON that is hashed",
  "vf.formula": "The fixed formula",
  "vf.formula.p": "No AI in this step. Every number below is recomputed in your browser from the report above.",
  "vf.svi": "SVI index = Σ score × weight",
  "vf.dim": "Dimension",
  "vf.basis": "Basis",
  "vf.score": "Score",
  "vf.weight": "Weight",
  "vf.contrib": "Contribution",
  "vf.sum": "SVI index",
  "vf.recomputed": "Recomputed vs report",
  "vf.inreport": "In report",
  "vf.recalc": "Recomputed",
  "vf.index": "SVI index",
  "vf.band": "Grade band",
  "vf.low": "Valuation low",
  "vf.mid": "Valuation mid",
  "vf.high": "Valuation high",
  "vf.bands": "Grade bands",
  "vf.method": "Valuation method",
  "mock.badge": "MOCK DATA",
  "err.chunk": "A new version of the app was published. Reload to continue — your data is safe.",
  "err.crash": "This page hit an unexpected error. Reloading usually fixes it.",
  "err.reload": "Reload",
  "err.slow": "Still loading…",
  "c.st.partially_anchored": "Partially synced · retry pending",
  "sh.stage.creating": "Creating company…",
  "sh.stage.submitting": "Submitting for approval…",
  "sh.stage.opening": "Opening tracker…",
  "trk.h": "Issuance tracker",
  "trk.p": "Live progress of your share issuance. It updates by itself.",
  "trk.now": "Now",
  "trk.elapsed": "Elapsed",
  "trk.feed": "Recent activity",
  "trk.s1": "Submitted",
  "trk.s1.p": "Company, ticker and shareholders were saved.",
  "trk.s2": "Waiting for admin approval",
  "trk.s2.p": "An admin reviews the valuation and shareholders. You can close this page; we'll keep going.",
  "trk.s2.rej": "Rejected by an admin",
  "trk.s3": "Issuing on BlockID Chain",
  "trk.s4": "Sync to Ethereum Hoodi",
  "trk.s5": "Sync to HashKey Chain testnet",
  "trk.s6": "Live",
  "trk.s6.p": "Your share token is live on BlockID Chain and mirrored to Ethereum Hoodi and HashKey Chain. Contract addresses are below.",
  "trk.st.done": "Done",
  "trk.st.running": "In progress",
  "trk.st.pending": "Waiting",
  "trk.st.failed": "Failed",
  "trk.st.skipped": "Skipped",
  "trk.sub.registry": "Identity registry deployed",
  "trk.sub.token": "Share token deployed",
  "trk.sub.dist": "Dividend distributor deployed",
  "trk.sub.kyc": "Shareholders KYC-registered {n}/{N}",
  "trk.sub.drip": "Gas allowance sent to {n} wallet(s)",
  "trk.sub.mint": "Shares issued {n}/{N}",
  "trk.sub.val": "Valuation report hash anchored",
  "trk.sub.mirror": "Mirror token deployed",
  "trk.sub.balances": "Balances mirrored",
  "trk.sub.paused": "Mirror paused (read-only copy)",
  "trk.sub.root": "Cap-table Merkle root anchored",
  "trk.approve": "Approve issuance (runs all chains)",
  "trk.retry": "Retry",
  "trk.resync": "Re-sync missing chains",
  "fix.cap_table_mismatch.h": "The cap table does not match BlockID Chain",
  "fix.cap_table_mismatch.p": "{n} shares sit in wallets that are missing from the studio cap table, usually after a share transfer. Refresh from chain rebuilds the cap table from on-chain balances, then re-syncs Hoodi and HashKey.",
  "fix.transfer_scan_failed.h": "Could not read share transfers from BlockID Chain",
  "fix.transfer_scan_failed.p": "The chain node refused the query. Refresh from chain retries it in smaller block ranges.",
  "fix.insufficient_gas.h": "The issuer wallet is out of gas{c}",
  "fix.insufficient_gas.p": "Top up the issuer wallet, then re-sync the missing chain.",
  "fix.chain_not_configured.h": "A chain is not configured{c}",
  "fix.chain_not_configured.p": "Set its RPC URL and CapTableAnchor address in app.env, restart the issuer, then re-sync.",
  "fix.mint_failed.h": "A share mint failed",
  "fix.mint_failed.p": "Open the Mints queue and approve the request again to retry it, or reject it.",
  "fix.dividend_failed.h": "A dividend round failed",
  "fix.dividend_failed.p": "Open the Dividends queue and approve it again to retry, or reject it.",
  "fix.not_issued.h": "Not issued on BlockID Chain yet",
  "fix.not_issued.p": "Approve the issuance first; the mirrors are created after it.",
  "fix.network.h": "A chain did not respond in time{c}",
  "fix.network.p": "This is usually temporary. Re-sync the missing chains.",
  "fix.unknown.h": "The issuer reported an error",
  "fix.unknown.p": "Refresh from chain clears the error and re-runs the sync. The technical message is below.",
  "fix.refresh": "Refresh from chain & re-sync",
  "fix.sent": "Refresh started. This page updates when the chains are synced.",
  "fix.adminonly": "An admin can fix this with “Refresh from chain & re-sync”.",
  "fix.raw": "Technical details",
  "fix.go.cap-table": "Show the cap table",
  "fix.go.sync": "Show chain status",
  "fix.go.issuer-wallets": "Open issuer wallets",
  "fix.go.approvals": "Open the queue",
  "fix.go.tracker": "Show the issuance tracker",
  "cap.total": "Total {p}%",
  "cap.left": "{p}% left to allocate",
  "cap.over": "{p}% over 100%",
  "cap.ok": "Adds up to 100%",
  "cap.balance": "Put the rest on the last row",
  "cap.fixrow": "Fix this row",
  "trk.sent": "Sent. The issuer is working on it.",
  "trk.waiting": "Waiting for an admin",
  "trk.done": "All chains synced",
  "trk.act.start": "Starting on {c}",
  "trk.act.deploy_registry": "Deploying the identity registry on {c}",
  "trk.act.deploy_token": "Deploying the share token on {c}",
  "trk.act.deploy_distributor": "Deploying the dividend distributor on {c}",
  "trk.act.kyc": "KYC-registering shareholder {n}/{N} on {c}",
  "trk.act.mint": "Issuing shares to holder {n}/{N} on {c}",
  "trk.act.anchor_valuation": "Anchoring the valuation report hash on {c}",
  "trk.act.check_balance": "Checking the issuer's gas balance on {c}",
  "trk.act.mirror_balances": "Mirroring balance {n}/{N} to {c}",
  "trk.act.mirror_reduce": "Correcting lowered balances on {c}",
  "trk.act.pause": "Pausing the mirror token on {c}",
  "trk.act.anchor_root": "Anchoring the cap-table root on {c}",
  "s8.hsk": "HashKey Chain testnet · mirror",
  "ev.hsk_mirrored": "Mirror token synced on HashKey Chain",
  "ev.deployed": "Contract deployed",
  "ev.sync_started": "Chain sync started",
  "ev.sync_failed": "Chain sync failed",
  "ev.sync_skipped": "Chain sync skipped",
  "ev.submitted": "Submitted for approval",
  "ev.issue_approved": "Issuance approved",
  "ev.resync_requested": "Re-sync requested",
  "ev.refresh_requested": "Refresh from chain requested",
  "ev.refreshed": "Cap table refreshed from BlockID Chain",
  "evd.holders": "{n} holders",
  "ad.sync": "Chains",
  "hero.sub": "Understand it. Follow it. Own it. Get paid. Check it.",
  "hero.tag": "Checked by people. Recorded on blockchain.",
  "d.n3s": "≤ 3 web searches",
  "d.b3s": "mirror + root + provenance",
  "home.st.cosub": "every record can be checked",
  "home.st.ver": "Records that check out",
  "home.st.verSub": "Check the records",
  "home.st.err": "Live numbers are unavailable right now. The register itself is unaffected.",
  "c.private.h": "This company isn't public yet",
  "c.private.p": "{t} is not listed. A company becomes public once its shares are issued on-chain. If it's yours, sign in with the owner wallet, or sign in as an admin.",
  "c.private.admin": "Admin sign-in",
  "c.private.signed": "No public company with ticker {t}. It may not exist, or it belongs to another wallet.",
  "co.anch3": "✓ 3 chains",
  "ev.resolved": "resolved by a later sync",
  "ad.r.since": "Since launch",
  "ad.r.all": "All",
  "ad.pin": "{d}: {v} · {n} companies",
  "ad.simbadge": "SIMULATED",
  "evd.shares": "{n} shares to {name}",
  "evd.mark": "mark {m} per share",
  "s8.hskscan": "View on HashKey explorer",
  "s8.dec18": "18 decimals",
  "c.k.sharesub": "{tk} · 1 token = 1 share",
  "ev.transferred": "Shares transferred",
  "ev.transfer_mode": "Transfer mode changed",
  "ev.mint_rejected": "Mint rejected",
  "ev.dividend_rejected": "Dividend rejected",
  "demo.tag": "Testnet demo convenience",
  "demo.h": "Judging the demo? Approve it yourself:",
  "demo.s1": "Open Admin",
  "demo.s2": "Choose the Username tab",
  "demo.s3": "Sign in with admin / admin",
  "demo.s4": "Press “{a}”",
  "demo.tail.issue": "You'll come straight back here and watch it go live on BlockID, Hoodi and HashKey.",
  "demo.tail.val": "You'll come straight back here and can continue to the ticker and shareholders.",
  "demo.btn": "Open admin to approve",
  "demo.return": "You'll return to {p} after signing in.",
  "demo.creds": "Demo account: admin / admin",
  "demo.home": "Demo: sign in at /admin with admin / admin to approve.",
  "lb.issuer": "Issuer wallet {a} is low on {u} ({v}).",
  "lb.relayer": "Relayer wallet {a} is low on {u} ({v}).",
  "lb.hoodi": "Top up before approving, or the Hoodi sync will wait for gas.",
  "lb.hsk": "Top up before approving, or the HashKey sync will wait for gas.",
  "lb.local": "Top up on BlockID EVM, or issuance and dividend claims will wait for gas.",
  "lb.min": "Minimum {m} {u}.",
  "lb.faucet": "Faucet",
  "lb.gas": "Gas: lowest-fee policy (tip 0.001–0.05 gwei, auto fee bump if stuck).",

  // company admins (components/CompanyAdmins.tsx)
  "nav.mycos": "My companies",
  "ca.h": "Company admins",
  "ca.p": "Wallets that run this company's token. Owners manage the admin list; owners and managers can request and approve this company's mints, dividends, transfers and revaluations. Initial issuance stays with the platform admins.",
  "ca.you.platform_admin": "You: platform admin",
  "ca.you.company_owner": "You: owner",
  "ca.you.company_manager": "You: manager",
  "ca.label": "Label",
  "ca.role": "Role",
  "ca.role.owner": "Owner",
  "ca.role.manager": "Manager",
  "ca.st.active": "Active",
  "ca.st.pending_grant": "Granting on-chain…",
  "ca.st.revoked": "Revoked",
  "ca.chain": "On-chain",
  "ca.chain.on": "On-chain roles",
  "ca.chain.off": "Off-chain",
  "ca.chain.roles": "ISSUER_ROLE, PAUSER_ROLE, TRANSFER_AGENT_ROLE on the share token + KYC_AGENT_ROLE on the registry (BlockID EVM)",
  "ca.empty": "No company admins yet.",
  "ca.addr.ph": "0x… wallet address (EIP-55)",
  "ca.add": "Add admin",
  "ca.added": "Company admin added.",
  "ca.added.chain": "Company admin added. The issuer is granting the on-chain roles; this list updates by itself.",
  "ca.bad.addr": "Enter a valid wallet address. Mixed-case addresses must match their EIP-55 checksum.",
  "ca.onchain.cb": "Also grant on-chain roles on this company's BlockID contracts",
  "ca.onchain.notyet": "available once the company is issued on BlockID EVM",
  "ca.onchain.note": "The issuer grants ISSUER_ROLE, PAUSER_ROLE and TRANSFER_AGENT_ROLE on the share token and KYC_AGENT_ROLE on the identity registry. The wallet also gets gas on BlockID EVM.",
  "ca.revoke": "Revoke",
  "ca.retry": "Retry on-chain revoke",
  "ca.revoked": "Company admin revoked.",
  "ca.revoked.chain": "Company admin revoked. The issuer is removing the on-chain roles.",
  "ca.confirm.h": "Revoke {a}? Their rights on this company end immediately.",
  "ca.confirm.chain": "Their on-chain roles are removed too.",
  "ca.confirm.p": "Type {tk} to confirm",
  "ca.readonly": "Only company owners and platform admins can change this list.",
  "ca.mirrors": "The Ethereum Hoodi and HashKey mirrors stay issuer-controlled (paused); roles are granted on BlockID EVM only.",
  "ca.ap.h": "Pending requests for this company",
  "ca.ap.p": "As an admin of this company you can approve or reject its mints, dividends and transfers. The issuer service then executes them on-chain.",
  "ca.ap.empty": "Nothing waiting for approval.",
  "ca.ap.tr": "Transfer of {n} shares",
  /* flow shell, workspace, admin queues */
  "flow.ph.a": "Value",
  "flow.ph.b": "Structure",
  "flow.ph.c": "Go live",
  "flow.ph.d": "Workspace",
  "flow.g1": "Admin approves the valuation",
  "flow.g1.wait": "Waiting: admin approves the valuation",
  "flow.g1.ok": "Valuation approved",
  "flow.g1.bad": "Valuation rejected",
  "flow.g2": "Admin approves the issue",
  "flow.g2.wait": "Waiting: admin approves the issue",
  "flow.g2.ok": "Issue approved",
  "flow.g2.bad": "Issue rejected",
  "flow.locked": "Opens after the previous step",
  "crumb.label": "Breadcrumb",
  "flow.stepof": "Step {n} of 8 · {p}",
  "flow.nav": "Issuance steps",
  "flow.auto.report": "Research finished. Here is the valuation report.",
  "flow.why.research": "The AI agents are still working. The report opens by itself.",
  "flow.why.g1": "The next step opens when an admin approves the valuation.",
  "flow.why.ticker": "Enter a company name and pick a free 3-letter ticker.",
  "flow.home": "Home",
  "flow.d6": "After the one issuance approval, the issuer creates the register on BlockID EVM: contracts, KYC for each holder, gas, shares and the report hash.",
  "flow.d7": "The issuer copies the register to Ethereum Hoodi and HashKey Chain: a paused mirror token with the same balances and the cap-table Merkle root.",
  "flow.d8": "Contract addresses on all three chains, with QR codes and Add to MetaMask.",
  "nav.studio": "For businesses",
  "nav.menu": "Menu",
  "gate.open": "Open this item in the admin console",
  "ws.h": "Company workspace",
  "ws.overview": "Overview",
  "ws.cap-table": "Cap table",
  "ws.transfers": "Transfers",
  "ws.mint": "Mint shares",
  "ws.dividends": "Dividends",
  "ws.activity": "Activity",
  "ws.team": "Team",
  "ws.verify": "Verify",
  "ws.needlive": "Available after the shares are issued",
  "ws.needsign": "Connect your wallet to transfer",
  "ws.needauth": "For company admins only",
  "ws.next": "Next step",
  "ws.next.draft": "The company is a draft. Submit it for the issuance approval.",
  "ws.next.wait": "The request is waiting for the issuance approval by an admin.",
  "ws.next.fail": "Issuance stopped. Open the issue step to see why.",
  "ws.next.issuing": "The issuer is creating {tk} on BlockID EVM.",
  "ws.next.sync": "{tk} is on BlockID EVM. The issuer is syncing Hoodi and HashKey.",
  "ws.next.live": "{tk} is live on three chains. Add it to your wallet.",
  "ws.d.overview": "Valuation, share mark and on-chain anchors at a glance.",
  "ws.d.cap-table": "Every holder, wallet and share count, read from the chain.",
  "ws.d.transfers": "Move shares between KYC-verified wallets.",
  "ws.d.mint": "Issue new shares with a live dilution preview. An admin approves the request.",
  "ws.d.dividends": "Pay a dividend in mAUD to every shareholder, in proportion to their shares. Shareholders pay no fees.",
  "ws.d.activity": "Every event and transaction for this company, newest first.",
  "ws.d.team": "Who can manage this company, and requests waiting for them.",
  "ad.ret.h": "Opened from the founder flow",
  "ad.ret.p": "After you decide, you go back to {p}.",
  "ad.ret.back": "Back without deciding",
  "ad.qv.mid": "Valuation (mid)",
  "ad.qv.note": "Open the full report to check the evidence or change a score before you approve.",
  "ad.q.gone": "That item was already handled. Showing the next one.",
  "ad.q.empty": "Nothing waiting in this queue.",
  "ad.q.nextq": "Next queue: {q}",
  "ad.q.pos": "Item {i} of {n}",
  "ad.q.keys": "J / K to move",
  "ad.q.prev": "Previous",
  "ad.q.next": "Next",
  "ad.q.valuations": "Valuations",
  "ad.q.issuance": "Issuance",
  "ad.q.sync": "Chain sync",
  "ad.q.mints": "Mints",
  "ad.q.dividends": "Dividends",
  "ad.q.transfers": "Transfers & KYC",
  "ad.q.eyebrow": "Queue {i} of 8",
  "ad.nav.inbox": "Inbox",
  "ad.nav.queues": "Queues · flow order",
  "ad.nav.registry": "Registry",
  "ad.nav.trust": "Trust",
  "ad.inbox.h": "Waiting for a decision: {n}",
  "ad.q.done": "This item has already been decided.",
  "ad.ret.go": "Back to the founder flow",
  "ad.inbox.first": "{n} waiting in {q}. Start with the oldest.",
  "ad.inbox.onlytr": "Only transfers and KYC requests are waiting.",
  "ad.inbox.q": "Queue",
  "ad.inbox.n": "Waiting",
  "ad.inbox.oldest": "Next item",
  "ad.review": "Review",
  "ad.inbox.p": "Queues follow the order a company moves through the flow. ◆ marks a human gate: nothing is signed until an admin approves.",
  "ad.d.inbox": "Everything waiting for an admin, in flow order.",
  "ad.d.dashboard": "Platform value, grades, movers and live activity.",
  "ad.d.valuations": "AI valuation reports waiting for a person to check the evidence.",
  "ad.d.issuance": "One approval per company: the issuer then signs the whole issue.",
  "ad.d.sync": "Companies issued on BlockID EVM whose Hoodi or HashKey sync is not finished.",
  "ad.d.mints": "Requests for new shares from company admins.",
  "ad.d.dividends": "Dividend rounds waiting to be funded.",
  "ad.d.transfers": "Transfers in approval mode and KYC requests from new holders.",
  "ad.d.companies": "Every company, its status per chain, revaluations and admins.",
  "ad.d.wallets": "Admin wallets, service wallets and their gas.",
  "ad.d.audit": "Every admin action, who did it and when.",
} as const;

type AppKey = keyof typeof appEn;

const appVi: Record<AppKey, string> = {
  "nav.companies": "Doanh nghiệp",
  "nav.connect": "Kết nối ví",
  "nav.connecting": "Đang đăng nhập…",
  "nav.signout": "Đăng xuất",
  "nav.account": "Menu tài khoản",
  "nav.lang": "Ngôn ngữ",
  "nav.primary": "Điều hướng chính",
  "nav.skip": "Bỏ qua tới nội dung",
  "nav.role.admin": "admin",
  "nav.role.user": "ví",
  "nav.adminlink": "Mở khu vực admin",
  "common.loading": "Đang tải…",
  "common.error": "Đã có lỗi xảy ra.",
  "common.retry": "Thử lại",
  "common.cancel": "Huỷ",
  "common.save": "Lưu",
  "common.none": "–",
  "common.back": "Quay lại",
  "common.yes": "Có",
  "err.unauth": "Vui lòng kết nối ví và đăng nhập trước.",
  "err.forbidden": "Tài khoản của bạn không có quyền làm việc này.",
  "err.rate": "Quá nhiều yêu cầu. Vui lòng thử lại sau.",
  "err.network": "Lỗi mạng. Kiểm tra kết nối rồi thử lại.",
  "err.rejected": "Yêu cầu đã bị từ chối trong ví.",
  "err.nomm": "Không tìm thấy MetaMask trong trình duyệt này.",

  "home.stats.eyebrow": "Trực tiếp trên testnet",
  "home.stats.h2": "Nền tảng hôm nay",
  "home.stats.p": "Số liệu trực tiếp từ bản demo. Giá trị là giá trị hợp lý do con người kiểm tra, không phải giá thị trường.",
  "home.st.co": "Doanh nghiệp đã đăng",
  "home.st.val": "Tổng giá trị hợp lý",
  "home.st.tok": "Bản ghi cổ phần trên blockchain",
  "home.st.tokSub": "lưu trên 3 blockchain công khai",
  "home.st.asof": "cập nhật tại block #{b}",
  "home.recent": "Mới đăng gần đây",
  "home.recent.all": "Xem tất cả doanh nghiệp",
  "home.recent.empty": "Chưa có doanh nghiệp nào. Bạn có thể là người đầu tiên.",
  "home.walk.cta": "Bắt đầu với website của bạn",
  "home.walk.sample": "Mở một doanh nghiệp mẫu",

  "new.eyebrow": "Định giá mới",
  "new.h2": "Tám bước từ website tới ví",
  "new.p": "Các bước màu vàng cần người duyệt: admin duyệt định giá, rồi duyệt phát hành một lần. Việc đồng bộ sang Hoodi và HashKey chạy tự động.",
  "new.signin": "Kết nối ví để bắt đầu. Mỗi lượt định giá thuộc về ví đã yêu cầu.",
  "new.bad.url": "Nhập địa chỉ website, ví dụ https://example.com.au.",
  "new.limit": "Đã hết lượt trong ngày: mỗi ví 3 lượt định giá mỗi ngày. Hãy thử lại vào ngày mai.",
  "new.starting": "Đang bắt đầu…",

  "v.eyebrow": "Định giá",
  "v.st.queued": "Đang xếp hàng",
  "v.st.running": "AI agent đang chạy",
  "v.st.waiting_approval": "Chờ admin duyệt",
  "v.st.approved": "Đã duyệt",
  "v.st.rejected": "Bị từ chối",
  "v.st.failed": "Thất bại",
  "v.waiting": "Đang chờ admin duyệt. Admin xem lại mọi điểm do AI chấm trước khi được phát hành. Trang này tự cập nhật.",
  "v.rejected": "Admin đã từ chối lượt định giá này. Bạn có thể bắt đầu lượt mới.",
  "v.failed": "Định giá thất bại: {e}",
  "v.poll": "Cập nhật mỗi 3 giây",
  "v.warn": "Cảnh báo:",
  "v.verified": "đã xác minh qua website",
  "v.verified.tip": "Do mô hình gợi ý, sau đó được xác nhận bằng cách tải website của chính đối thủ.",
  "v.mine": "Các lượt định giá của bạn",
  "v.mine.co": "Doanh nghiệp của bạn",
  "v.open": "Mở",
  "v.queued": "Đang chờ agent rảnh…",
  "v.signin": "Kết nối ví đã yêu cầu lượt định giá này để xem.",
  "v.notfound": "Không tìm thấy lượt định giá.",
  "v.total": "Chỉ số SVI · hạng {g}",
  "v.method": "Phương pháp: {m}",
  "v.nd": "không công bố",
  "v.narr": "Nhận định của chuyên viên",
  "v.evidence": "Bằng chứng",
  "v.evidence.p": "Mọi trang mà agent đã tải và trích dẫn.",
  "v.evidence.empty": "Chưa có bằng chứng.",
  "v.retrieved": "tải lúc {d}",
  "sr.toggle": "Thêm số liệu của bạn (không bắt buộc, giúp chính xác hơn)",
  "sr.help": "Tự khai báo. Được ghi rõ như vậy trong báo cáo.",
  "sr.why": "Website hiếm khi công bố doanh thu, nên nếu thiếu các số này thì điểm doanh thu và tăng trưởng gần như bằng 0.",
  "sr.revenue": "Doanh thu 12 tháng gần nhất (A$)",
  "sr.growth": "Tăng trưởng doanh thu so với cùng kỳ (%)",
  "sr.margin": "Biên lợi nhuận gộp (%)",
  "sr.customers": "Khách hàng trả phí",
  "sr.raised": "Tổng vốn đã huy động (A$)",
  "sr.runway": "Thời gian hoạt động còn lại (tháng)",
  "sr.employees": "Số nhân viên",
  "sr.bad": "Kiểm tra lại số được đánh dấu: {f}",
  "sr.chip": "Tự khai báo",
  "sr.chip.tip": "Số liệu do nhà sáng lập cung cấp, chưa được xác minh độc lập.",
  "sr.table": "Số liệu tự khai báo",
  "sr.table.p": "Do nhà sáng lập cung cấp khi yêu cầu định giá. Chưa được xác minh độc lập.",
  "v.sources": "{n} nguồn",
  "v.adm.h": "Admin xem xét",
  "v.adm.p": "Chỉnh bất kỳ điểm nào do AI chấm trước khi duyệt. Máy chủ sẽ tính lại chỉ số và mức định giá.",
  "v.adm.preview": "Chỉ số theo điểm của bạn",
  "v.adm.reject": "Từ chối định giá",
  "v.adm.done": "Đã lưu quyết định.",
  "v.continue": "Tiếp tục chọn mã",
  "v.newval": "Bắt đầu định giá mới",
  "v.running.note": "Khoảng 2–4 phút. Bạn có thể đóng tab; link này mở lại được tác vụ.",
  "v.tk.custom": "Hoặc tự nhập",
  "v.tk.taken": "đã có người dùng",
  "v.tk.bad": "Dùng đúng ba chữ cái A–Z.",
  "v.tk.cname": "Tên công ty",
  "v.tk.none": "Chưa có gợi ý.",
  "v.sh.add": "Thêm cổ đông",
  "v.sh.remove": "Xoá {n}",
  "v.sh.name": "Tên",
  "v.sh.badaddr": "Địa chỉ không hợp lệ (checksum EIP-55).",
  "v.sh.dup": "Ví này đã có trong danh sách.",
  "v.sh.badname": "Nhập tên.",
  "v.sh.submit": "Tạo & gửi duyệt",
  "v.sh.creating": "Đang gửi…",
  "v.sh.need": "Sửa các dòng được đánh dấu trước.",
  "v.sh.default": "Mặc định: định giá giữa ÷ A$1,00 = {n}",
  "v.sh.draft": "Đã tạo bản nháp nhưng chưa gửi duyệt được: {e}",

  "c.eyebrow": "Doanh nghiệp",
  "c.st.draft": "Bản nháp",
  "c.st.pending_issue": "Chờ duyệt phát hành",
  "c.st.issuing": "Đang phát hành trên BlockID Chain",
  "c.st.issued": "Đã phát hành trên BlockID Chain",
  "c.st.pending_anchor": "Chờ đồng bộ chuỗi",
  "c.st.anchoring": "Đang đồng bộ sang Hoodi & HashKey",
  "c.st.anchored": "Đã hoạt động trên BlockID, Hoodi & HashKey",
  "c.st.rejected": "Bị từ chối",
  "c.st.failed": "Thất bại",
  "c.tl.draft": "Bản nháp",
  "c.tl.pending_issue": "Chờ phát hành",
  "c.tl.issuing": "Đang phát hành",
  "c.tl.issued": "Đã phát hành",
  "c.tl.anchoring": "Đang neo",
  "c.tl.anchored": "Đã neo",
  "c.gate": "admin",
  "c.k.val": "Định giá",
  "c.k.valsub": "SVI {s} · hạng {g}",
  "c.k.noanchor": "chưa neo",
  "c.cap": "Sổ cổ đông",
  "c.cap.p": "Số dư đọc từ BlockID Chain.",
  "c.cap.empty": "Chưa có cổ đông.",
  "c.other": "Khác",
  "c.cap.chain": "Số dư đọc từ BlockID Chain tại block #{b}.",
  "c.cap.db": "Theo hồ sơ phát hành (chưa lên chain, hoặc không kết nối được chain).",
  "c.mark": "Giá cổ phần",
  "c.notyet": "Chưa deploy",
  "c.addr.localwait": "Sẽ hiện sau khi admin duyệt phát hành.",
  "c.addr.hoodiwait": "Tự hiện khi phát hành trên BlockID hoàn tất.",
  "c.qr": "Mã QR cho {a}",
  "c.mint.to": "Ví nhận",
  "c.mint.name": "Tên cổ đông",
  "c.mint.reason": "Lý do",
  "c.mint.sent": "Đã gửi yêu cầu mint cho admin duyệt.",
  "c.mint.existing": "Cổ đông hiện hữu: cổ phần được cộng vào số dư.",
  "c.div.sent": "Đã gửi kế hoạch cổ tức để duyệt.",
  "c.div.root": "máy chủ tính tại block chốt",
  "c.ev": "Hoạt động",
  "c.ev.empty": "Chưa có hoạt động on-chain.",
  "c.notfound": "Không có doanh nghiệp mã {t}.",
  "c.draftnote": "Doanh nghiệp này đang là bản nháp. Admin hoặc ví phát hành đã được duyệt phải gửi duyệt.",
  "c.submit": "Gửi duyệt",
  "c.submitted": "Đã gửi. Admin sẽ xem xét việc phát hành.",
  "c.needauth": "Kết nối ví chủ sở hữu hoặc đăng nhập admin để yêu cầu mint hoặc cổ tức.",
  "c.failed": "Issuer báo lỗi: {e}",
  "c.website": "Website",
  "c.anchor.root": "Merkle root",
  "c.onlyissued": "Có sau khi cổ phần được phát hành.",

  "ev.issued": "Đã phát hành cổ phần",
  "ev.kyc": "Nhà đầu tư đã đăng ký KYC",
  "ev.drip": "Đã cấp phí gas",
  "ev.minted": "Đã mint cổ phần",
  "ev.valuation_anchored": "Đã neo hash định giá",
  "ev.revalued": "Định giá lại",
  "ev.hoodi_mirrored": "Đã đồng bộ token bản sao trên Hoodi",
  "ev.anchored": "Đã neo sổ cổ đông",
  "ev.dividend_created": "Đã tạo vòng cổ tức",
  "ev.dividend_claimed": "Đã nhận cổ tức",
  "ev.mint_requested": "Yêu cầu mint",
  "ev.rejected": "Bị từ chối",

  "co.eyebrow": "Thị trường",
  "co.h2": "Doanh nghiệp đã token hoá",
  "co.p": "Mọi doanh nghiệp đã phát hành trên BlockID Chain. Giá chỉ đổi khi phát hành và khi định giá lại SVI được duyệt; đây không phải giá thị trường.",
  "co.search": "Tìm mã hoặc tên doanh nghiệp",
  "co.empty": "Không có doanh nghiệp phù hợp.",
  "co.anchNo": "chưa neo",
  "co.anchYes": "✓ Hoodi",
  "co.sort": "Sắp xếp theo {c}",

  "ad.t.ap": "Chờ duyệt",
  "ad.t.cos": "Doanh nghiệp",
  "ad.t.au": "Nhật ký kiểm toán",
  "ad.notadmin": "Ví này đang đăng nhập với vai trò người dùng. Chỉ ví trong danh sách admin, hoặc tài khoản admin, mới vào được khu vực này.",
  "ad.bad.rate": "Thử quá nhiều lần. Vui lòng thử lại sau 15 phút.",
  "ad.paused": "Tạm dừng · tab đang ẩn",
  "ad.cp.h": "Đổi mật khẩu admin",
  "ad.cp.p": "Bạn phải đổi mật khẩu demo trước khi tiếp tục. Dùng ít nhất 10 ký tự.",
  "ad.cp.cur": "Mật khẩu hiện tại",
  "ad.cp.new": "Mật khẩu mới",
  "ad.cp.rep": "Nhập lại mật khẩu mới",
  "ad.cp.go": "Đổi mật khẩu",
  "ad.cp.short": "Dùng ít nhất 10 ký tự.",
  "ad.cp.mismatch": "Hai mật khẩu không khớp.",
  "ad.cp.ok": "Đã đổi mật khẩu.",
  "ad.k.tokval": "{n} hợp đồng",
  "ad.k.anchval": "{a} / {b}",
  "ad.aw.list": "Ví admin · chỉ admin thấy",
  "ad.aw.svc": "Ví dịch vụ",
  "ad.aw.issuer": "Issuer service",
  "ad.aw.relayer": "Relayer (chỉ nhận cổ tức)",
  "ad.aw.bal": "BlockID {a} BLKD · Hoodi {b} ETH · HashKey {c} HSK",
  "ad.iw.empty": "Chưa có ví phát hành.",
  "ad.audit.empty": "Chưa có nhật ký.",
  "ad.co.pick": "Chọn một doanh nghiệp trong bảng để xem biểu đồ giá và định giá lại.",
  "ad.co.open": "Mở trang công khai",

  "ap.val": "Định giá chờ xem xét",
  "ap.co": "Doanh nghiệp chờ phát hành trên BlockID Chain",
  "ap.anchor": "Đã phát hành · còn chuỗi chưa đồng bộ",
  "ap.mints": "Yêu cầu mint",
  "ap.divs": "Kế hoạch cổ tức",
  "ap.empty": "Không có gì đang chờ. Yêu cầu mới sẽ tự hiện ở đây.",
  "ap.open": "Mở báo cáo",
  "ap.approve": "Duyệt",
  "ap.reject": "Từ chối",
  "ap.review": "Xem giao dịch",
  "ap.hide": "Ẩn",
  "ap.anchorbtn": "Đồng bộ lại Hoodi & HashKey",
  "ap.reason": "Lý do từ chối",
  "ap.txs": "Các giao dịch issuer service sẽ gửi",
  "ap.sent": "Đã duyệt. Issuer service đang xử lý; trạng thái cập nhật tại đây.",
  "ap.rejected": "Đã từ chối.",
  "ap.mintrow": "{n} {tk} → {name}",
  "ap.divrow": "{n} mAUD cho cổ đông {tk}",
  "ap.req": "yêu cầu bởi {w}",
  "ap.holders": "{n} cổ đông",
  "ap.anchor.txs": "Trên Hoodi và HashKey: deploy registry + token bản sao · đăng ký và mint {n} cổ đông · khoá · CapTableAnchor.anchor(root)",
  "tx.kycrole": "Cấp KYC_AGENT_ROLE cho issuer",
  "tx.tokN": "Deploy token cổ phần {tk} (decimals 0)",
  "tx.kycN": "KYC {n} ví",
  "tx.gasN": "Cấp phí gas cho tối đa {n} ví",
  "tx.mintN": "Mint {s} {tk} cho {n} cổ đông",
  "tx.valN": "Neo hash báo cáo SVI · giá A$1,00",

  "rv.h": "Định giá lại",
  "rv.p": "Đặt mức định giá mới. Giá mỗi cổ phần = định giá ÷ số cổ phần, và sổ cổ đông được neo lại.",
  "rv.val": "Định giá mới (A$)",
  "rv.note": "Ghi chú",
  "rv.go": "Gửi định giá lại",
  "rv.newmark": "Giá mới {m} ({p})",
  "rv.ok": "Đã ghi nhận định giá lại.",

  "nf.h": "Không tìm thấy trang",
  "nf.p": "Trang bạn yêu cầu không tồn tại hoặc đã được chuyển.",
  "nf.home": "Về trang chủ",
  "nav.hsk": "HashKey Chain",
  "hsk.eyebrow": "HashKey Chain testnet · chain 133",
  "hsk.title": "Đang chạy trên HashKey Chain",
  "hsk.msg": "AI agent không bao giờ giữ khoá. Mọi đề xuất của agent đều được băm lên chuỗi, một người duyệt ký xác nhận, và chỉ khi đó issuer mới thực thi.",
  "hsk.live": "Đang chạy",
  "hsk.open": "Xem triển khai",
  "hsk.card.stats": "{c} hợp đồng đã deploy · {p} đề xuất của agent trên chuỗi",
  "hsk.pending": "Đang chờ triển khai.",
  "hsk.pending.p": "Các hợp đồng trên HashKey Chain đang được deploy. Địa chỉ, đề xuất và giao dịch sẽ hiện ở đây ngay khi được công bố.",
  "hsk.addnet": "Thêm HashKey Chain vào MetaMask",
  "hsk.added": "Ví của bạn đã sẵn sàng với HashKey Chain testnet.",
  "hsk.explorer": "Mở trên explorer",
  "hsk.flow": "AI đề xuất → con người duyệt → issuer thực thi",
  "hsk.f1": "AI đề xuất",
  "hsk.f1s": "hash ghi lên chuỗi",
  "hsk.f2": "Con người duyệt",
  "hsk.f2s": "người duyệt ký",
  "hsk.f3": "Issuer thực thi",
  "hsk.f3s": "bên duy nhất giữ khoá",
  "hsk.contracts": "Hợp đồng",
  "hsk.deployed": "Đã deploy",
  "hsk.c.prov": "Nguồn gốc agent (provenance)",
  "hsk.c.reg": "Sổ định danh (KYC)",
  "hsk.c.share": "Token cổ phần",
  "hsk.c.div": "Phân phối cổ tức",
  "hsk.c.pay": "Token chi trả",
  "hsk.c.anchor": "Neo sổ cổ đông",
  "hsk.roles": "Vai trò",
  "hsk.r.op": "Vận hành (issuer)",
  "hsk.r.relayer": "Relayer (agent)",
  "hsk.r.approver": "Người duyệt",
  "hsk.roles.p": "Relayer chỉ có thể gửi hash đề xuất. Nó không thể duyệt hay thực thi bất cứ điều gì.",
  "hsk.prov": "Nguồn gốc agent",
  "hsk.prov.p": "Mỗi kết quả AI được băm và đề xuất trên chuỗi. Bạn có thể tự đối chiếu hash với hợp đồng AgentProvenance.",
  "hsk.prov.empty": "Chưa có đề xuất nào của agent.",
  "hsk.hash": "Hash nội dung",
  "hsk.model": "Mô hình",
  "hsk.verify": "Xác minh trên chuỗi",
  "hsk.v.ok": "Hash khớp với bản ghi trên chuỗi",
  "hsk.v.no": "Hash không khớp",
  "hsk.v.err": "Không kết nối được RPC HashKey",
  "hsk.div": "Cổ tức",
  "hsk.div.round": "Đợt cổ tức",
  "hsk.div.id": "Đợt",
  "hsk.div.total": "Tổng",
  "hsk.div.deadline": "Hạn nhận",
  "hsk.div.root": "Merkle root",
  "hsk.div.units": "Số tiền tính bằng mAUD (DemoAUD, 6 chữ số thập phân). Cổ đông nhận bằng Merkle proof.",
  "hsk.div.claims": "Quyền nhận của cổ đông",
  "hsk.div.amt": "Số lượng",
  "hsk.div.empty": "Chưa có đợt cổ tức nào được công bố.",
  "hsk.txs": "Giao dịch",
  "nav.verify": "Kiểm tra hồ sơ",
  "vf.eyebrow": "Định giá AI có thể kiểm toán",
  "vf.title": "Tự xác minh một bản định giá",
  "vf.lead": "AI chỉ chấm điểm 7 tiêu chí SVI. Một công thức công khai, cố định biến các điểm đó thành chỉ số và giá trị, và mã băm của toàn bộ báo cáo được ghi lên chuỗi khối. Hãy tự tính lại ngay trên trình duyệt của bạn.",
  "vf.s1": "AI đề xuất điểm 7 tiêu chí; quản trị viên xác nhận",
  "vf.s2": "Công thức công khai cố định tính chỉ số SVI và giá trị",
  "vf.s3": "keccak256 của JSON báo cáo chuẩn hoá được ghi lên chuỗi",
  "vf.s4": "Ai cũng tính lại và so sánh: cùng đầu vào, cùng kết quả",
  "vf.pick": "Doanh nghiệp",
  "vf.pick.none": "Dán JSON báo cáo của tôi…",
  "vf.opencompany": "Mở doanh nghiệp",
  "vf.paste.hint": "Chọn một doanh nghiệp để tải báo cáo và mã băm trên chuỗi, hoặc dán JSON báo cáo bất kỳ bên dưới để tính mã băm.",
  "vf.paste.ph": "Dán JSON báo cáo định giá vào đây ({\"url\": …, \"profile\": …, \"svi\": …})",
  "vf.ok": "Đã xác minh: mã băm trên chuỗi khớp với báo cáo này",
  "vf.ok.p": "Trình duyệt, máy chủ và {n} bản ghi trên chuỗi trùng khớp từng byte. Không ai sửa báo cáo sau khi được duyệt.",
  "vf.bad": "Không khớp: báo cáo này không phải bản đã ghi lên chuỗi",
  "vf.bad.p": "Mã băm của báo cáo khác với ít nhất một bản ghi trên chuỗi.",
  "vf.bad.edited": "Bạn đã sửa báo cáo nên mã băm không còn khớp bản ghi trên chuỗi. Bấm Khôi phục để trả lại.",
  "vf.bad.nochain": "Đã tính mã băm. Chọn một doanh nghiệp để so với bản ghi trên chuỗi.",
  "vf.info": "Đã tính mã băm",
  "vf.wait": "Đang kiểm tra…",
  "vf.wait.p": "Máy chủ đang tính lại mã băm.",
  "vf.hashes": "Ba mã băm độc lập",
  "vf.browser": "Mã băm trình duyệt",
  "vf.browser.p": "keccak256 tính ngay trong trình duyệt của bạn (viem).",
  "vf.server": "Mã băm máy chủ",
  "vf.server.p": "Cùng văn bản được API BlockID (Python) băm lại.",
  "vf.onchain": "Mã băm trên chuỗi",
  "vf.onchain.p": "valuationReportHash() đọc từ từng token cổ phần.",
  "vf.onchain.none": "Doanh nghiệp này chưa có token nào ghi báo cáo.",
  "vf.onchain.pick": "Chọn doanh nghiệp để đọc mã băm trên chuỗi.",
  "vf.explorer": "Token trên explorer",
  "vf.report": "JSON báo cáo",
  "vf.report.p": "Sửa bất kỳ chỗ nào và xem mã băm thay đổi. Chỉ url, profile, competitors, market, svi và self_reported được băm.",
  "vf.tamper": "Thử giả mạo: đổi một điểm",
  "vf.reset": "Khôi phục",
  "vf.canonical": "JSON chuẩn hoá được băm",
  "vf.formula": "Công thức cố định",
  "vf.formula.p": "Bước này không dùng AI. Mọi con số dưới đây được tính lại trong trình duyệt từ báo cáo ở trên.",
  "vf.svi": "Chỉ số SVI = Σ điểm × trọng số",
  "vf.dim": "Tiêu chí",
  "vf.basis": "Nguồn",
  "vf.score": "Điểm",
  "vf.weight": "Trọng số",
  "vf.contrib": "Đóng góp",
  "vf.sum": "Chỉ số SVI",
  "vf.recomputed": "Tính lại so với báo cáo",
  "vf.inreport": "Trong báo cáo",
  "vf.recalc": "Tính lại",
  "vf.index": "Chỉ số SVI",
  "vf.band": "Hạng",
  "vf.low": "Định giá thấp",
  "vf.mid": "Định giá giữa",
  "vf.high": "Định giá cao",
  "vf.bands": "Thang hạng",
  "vf.method": "Phương pháp định giá",
  "mock.badge": "DỮ LIỆU GIẢ",
  "err.chunk": "Ứng dụng vừa được cập nhật. Tải lại trang để tiếp tục — dữ liệu của bạn vẫn an toàn.",
  "err.crash": "Trang gặp lỗi không mong muốn. Tải lại thường sẽ khắc phục.",
  "err.reload": "Tải lại",
  "err.slow": "Vẫn đang tải…",
  "c.st.partially_anchored": "Đồng bộ một phần · chờ thử lại",
  "sh.stage.creating": "Đang tạo công ty…",
  "sh.stage.submitting": "Đang gửi duyệt…",
  "sh.stage.opening": "Đang mở trang theo dõi…",
  "trk.h": "Theo dõi phát hành",
  "trk.p": "Tiến độ phát hành cổ phần theo thời gian thực. Trang tự cập nhật.",
  "trk.now": "Hiện tại",
  "trk.elapsed": "Đã chạy",
  "trk.feed": "Hoạt động gần đây",
  "trk.s1": "Đã gửi",
  "trk.s1.p": "Công ty, mã cổ phiếu và danh sách cổ đông đã được lưu.",
  "trk.s2": "Chờ admin duyệt",
  "trk.s2.p": "Admin sẽ xem xét định giá và cổ đông. Bạn có thể đóng trang này; hệ thống vẫn tiếp tục.",
  "trk.s2.rej": "Admin đã từ chối",
  "trk.s3": "Phát hành trên BlockID Chain",
  "trk.s4": "Đồng bộ sang Ethereum Hoodi",
  "trk.s5": "Đồng bộ sang HashKey Chain testnet",
  "trk.s6": "Hoạt động",
  "trk.s6.p": "Token cổ phần đã hoạt động trên BlockID Chain và được sao sang Ethereum Hoodi và HashKey Chain. Địa chỉ hợp đồng ở bên dưới.",
  "trk.st.done": "Xong",
  "trk.st.running": "Đang chạy",
  "trk.st.pending": "Đang chờ",
  "trk.st.failed": "Thất bại",
  "trk.st.skipped": "Bỏ qua",
  "trk.sub.registry": "Đã deploy sổ định danh",
  "trk.sub.token": "Đã deploy token cổ phần",
  "trk.sub.dist": "Đã deploy hợp đồng chia cổ tức",
  "trk.sub.kyc": "KYC cổ đông {n}/{N}",
  "trk.sub.drip": "Đã cấp gas cho {n} ví",
  "trk.sub.mint": "Đã phát hành cổ phần {n}/{N}",
  "trk.sub.val": "Đã neo hash báo cáo định giá",
  "trk.sub.mirror": "Đã deploy token bản sao",
  "trk.sub.balances": "Đã sao số dư",
  "trk.sub.paused": "Đã tạm dừng bản sao (chỉ đọc)",
  "trk.sub.root": "Đã neo Merkle root sổ cổ đông",
  "trk.approve": "Duyệt phát hành (chạy tất cả chuỗi)",
  "trk.retry": "Thử lại",
  "trk.resync": "Đồng bộ lại các chuỗi còn thiếu",
  "fix.cap_table_mismatch.h": "Sổ cổ đông không khớp với BlockID Chain",
  "fix.cap_table_mismatch.p": "{n} cổ phần đang nằm ở các ví chưa có trong sổ cổ đông của studio, thường là sau một giao dịch chuyển nhượng. “Làm mới từ chuỗi” sẽ dựng lại sổ cổ đông từ số dư on-chain rồi đồng bộ lại Hoodi và HashKey.",
  "fix.transfer_scan_failed.h": "Không đọc được các giao dịch chuyển cổ phần trên BlockID Chain",
  "fix.transfer_scan_failed.p": "Node của chuỗi từ chối truy vấn. “Làm mới từ chuỗi” sẽ thử lại với các khoảng block nhỏ hơn.",
  "fix.insufficient_gas.h": "Ví issuer hết gas{c}",
  "fix.insufficient_gas.p": "Nạp thêm cho ví issuer, rồi đồng bộ lại chuỗi còn thiếu.",
  "fix.chain_not_configured.h": "Một chuỗi chưa được cấu hình{c}",
  "fix.chain_not_configured.p": "Điền RPC URL và địa chỉ CapTableAnchor trong app.env, khởi động lại issuer rồi đồng bộ lại.",
  "fix.mint_failed.h": "Một lượt phát hành thêm cổ phần bị lỗi",
  "fix.mint_failed.p": "Mở hàng chờ Mint và duyệt lại để thử lại, hoặc từ chối yêu cầu.",
  "fix.dividend_failed.h": "Một đợt cổ tức bị lỗi",
  "fix.dividend_failed.p": "Mở hàng chờ Cổ tức và duyệt lại để thử lại, hoặc từ chối.",
  "fix.not_issued.h": "Chưa phát hành trên BlockID Chain",
  "fix.not_issued.p": "Hãy duyệt phát hành trước; các bản sao trên chuỗi khác được tạo sau đó.",
  "fix.network.h": "Một chuỗi không phản hồi kịp{c}",
  "fix.network.p": "Thường chỉ là tạm thời. Hãy đồng bộ lại các chuỗi còn thiếu.",
  "fix.unknown.h": "Issuer báo lỗi",
  "fix.unknown.p": "“Làm mới từ chuỗi” sẽ xoá lỗi và chạy lại việc đồng bộ. Thông báo kỹ thuật ở bên dưới.",
  "fix.refresh": "Làm mới từ chuỗi & đồng bộ lại",
  "fix.sent": "Đã bắt đầu làm mới. Trang sẽ tự cập nhật khi các chuỗi đồng bộ xong.",
  "fix.adminonly": "Admin có thể sửa bằng nút “Làm mới từ chuỗi & đồng bộ lại”.",
  "fix.raw": "Chi tiết kỹ thuật",
  "fix.go.cap-table": "Xem sổ cổ đông",
  "fix.go.sync": "Xem trạng thái các chuỗi",
  "fix.go.issuer-wallets": "Mở ví issuer",
  "fix.go.approvals": "Mở hàng chờ",
  "fix.go.tracker": "Xem tiến trình phát hành",
  "cap.total": "Tổng {p}%",
  "cap.left": "Còn {p}% chưa phân bổ",
  "cap.over": "Vượt 100% là {p}%",
  "cap.ok": "Đã đủ 100%",
  "cap.balance": "Dồn phần còn lại vào dòng cuối",
  "cap.fixrow": "Sửa dòng này",
  "trk.sent": "Đã gửi. Issuer đang xử lý.",
  "trk.waiting": "Đang chờ admin",
  "trk.done": "Đã đồng bộ tất cả chuỗi",
  "trk.act.start": "Bắt đầu trên {c}",
  "trk.act.deploy_registry": "Đang deploy sổ định danh trên {c}",
  "trk.act.deploy_token": "Đang deploy token cổ phần trên {c}",
  "trk.act.deploy_distributor": "Đang deploy hợp đồng cổ tức trên {c}",
  "trk.act.kyc": "Đang KYC cổ đông {n}/{N} trên {c}",
  "trk.act.mint": "Đang phát hành cho cổ đông {n}/{N} trên {c}",
  "trk.act.anchor_valuation": "Đang neo hash báo cáo định giá trên {c}",
  "trk.act.check_balance": "Đang kiểm tra số dư gas của issuer trên {c}",
  "trk.act.mirror_balances": "Đang sao số dư {n}/{N} sang {c}",
  "trk.act.mirror_reduce": "Đang điều chỉnh số dư đã giảm trên {c}",
  "trk.act.pause": "Đang tạm dừng token bản sao trên {c}",
  "trk.act.anchor_root": "Đang neo root sổ cổ đông trên {c}",
  "s8.hsk": "HashKey Chain testnet · bản sao",
  "ev.hsk_mirrored": "Đã đồng bộ token bản sao trên HashKey Chain",
  "ev.deployed": "Đã deploy hợp đồng",
  "ev.sync_started": "Bắt đầu đồng bộ chuỗi",
  "ev.sync_failed": "Đồng bộ chuỗi thất bại",
  "ev.sync_skipped": "Bỏ qua đồng bộ chuỗi",
  "ev.submitted": "Đã gửi duyệt",
  "ev.issue_approved": "Đã duyệt phát hành",
  "ev.resync_requested": "Yêu cầu đồng bộ lại",
  "ev.refresh_requested": "Yêu cầu làm mới từ chuỗi",
  "ev.refreshed": "Đã làm mới sổ cổ đông từ BlockID Chain",
  "evd.holders": "{n} cổ đông",
  "ad.sync": "Chuỗi",
  "hero.sub": "Hiểu rõ. Theo dõi. Sở hữu. Nhận tiền. Kiểm tra.",
  "hero.tag": "Con người kiểm tra. Blockchain ghi nhận.",
  "d.n3s": "≤ 3 lượt tìm kiếm web",
  "d.b3s": "bản sao + root + provenance",
  "home.st.cosub": "mọi bản ghi đều kiểm tra được",
  "home.st.ver": "Hồ sơ khớp khi kiểm tra",
  "home.st.verSub": "Kiểm tra hồ sơ",
  "home.st.err": "Hiện chưa tải được số liệu trực tiếp. Sổ cổ đông không bị ảnh hưởng.",
  "c.private.h": "Doanh nghiệp này chưa công khai",
  "c.private.p": "{t} chưa được niêm yết. Doanh nghiệp chỉ công khai sau khi cổ phần được phát hành on-chain. Nếu đây là doanh nghiệp của bạn, hãy đăng nhập bằng ví chủ sở hữu hoặc đăng nhập admin.",
  "c.private.admin": "Đăng nhập admin",
  "c.private.signed": "Không có doanh nghiệp công khai mã {t}. Mã này có thể không tồn tại hoặc thuộc về ví khác.",
  "co.anch3": "✓ 3 chuỗi",
  "ev.resolved": "đã khắc phục ở lần đồng bộ sau",
  "ad.r.since": "Từ khi ra mắt",
  "ad.r.all": "Tất cả",
  "ad.pin": "{d}: {v} · {n} doanh nghiệp",
  "ad.simbadge": "GIẢ LẬP",
  "evd.shares": "{n} cổ phần cho {name}",
  "evd.mark": "giá {m} mỗi cổ phần",
  "s8.hskscan": "Xem trên HashKey explorer",
  "s8.dec18": "18 chữ số thập phân",
  "c.k.sharesub": "{tk} · 1 token = 1 cổ phần",
  "ev.transferred": "Đã chuyển nhượng cổ phần",
  "ev.transfer_mode": "Đã đổi chế độ chuyển nhượng",
  "ev.mint_rejected": "Đã từ chối mint",
  "ev.dividend_rejected": "Đã từ chối cổ tức",
  "demo.tag": "Tiện ích cho bản demo testnet",
  "demo.h": "Đang chấm demo? Hãy tự duyệt:",
  "demo.s1": "Mở trang Admin",
  "demo.s2": "Chọn tab Tài khoản",
  "demo.s3": "Đăng nhập bằng admin / admin",
  "demo.s4": "Bấm “{a}”",
  "demo.tail.issue": "Bạn sẽ được đưa về ngay trang này và xem cổ phần được phát hành trên BlockID, Hoodi và HashKey.",
  "demo.tail.val": "Bạn sẽ được đưa về ngay trang này và có thể tiếp tục chọn mã cổ phần và cổ đông.",
  "demo.btn": "Mở admin để duyệt",
  "demo.return": "Bạn sẽ quay lại {p} sau khi đăng nhập.",
  "demo.creds": "Tài khoản demo: admin / admin",
  "demo.home": "Demo: đăng nhập tại /admin bằng admin / admin để tự duyệt.",
  "lb.issuer": "Ví issuer {a} sắp hết {u} ({v}).",
  "lb.relayer": "Ví relayer {a} sắp hết {u} ({v}).",
  "lb.hoodi": "Hãy nạp thêm trước khi duyệt, nếu không việc đồng bộ Hoodi sẽ phải chờ gas.",
  "lb.hsk": "Hãy nạp thêm trước khi duyệt, nếu không việc đồng bộ HashKey sẽ phải chờ gas.",
  "lb.local": "Hãy nạp thêm trên BlockID EVM, nếu không việc phát hành và nhận cổ tức sẽ phải chờ gas.",
  "lb.min": "Tối thiểu {m} {u}.",
  "lb.faucet": "Faucet",
  "lb.gas": "Gas: chính sách phí thấp nhất (tip 0,001–0,05 gwei, tự tăng phí nếu giao dịch bị kẹt).",

  // company admins
  "nav.mycos": "Doanh nghiệp của tôi",
  "ca.h": "Quản trị viên doanh nghiệp",
  "ca.p": "Các ví điều hành token của doanh nghiệp này. Chủ sở hữu quản lý danh sách quản trị viên; chủ sở hữu và quản lý có thể đề nghị và duyệt mint, cổ tức, chuyển nhượng và định giá lại của doanh nghiệp này. Việc phát hành lần đầu vẫn do admin nền tảng duyệt.",
  "ca.you.platform_admin": "Bạn: admin nền tảng",
  "ca.you.company_owner": "Bạn: chủ sở hữu",
  "ca.you.company_manager": "Bạn: quản lý",
  "ca.label": "Nhãn",
  "ca.role": "Vai trò",
  "ca.role.owner": "Chủ sở hữu",
  "ca.role.manager": "Quản lý",
  "ca.st.active": "Đang hoạt động",
  "ca.st.pending_grant": "Đang cấp quyền on-chain…",
  "ca.st.revoked": "Đã thu hồi",
  "ca.chain": "On-chain",
  "ca.chain.on": "Có quyền on-chain",
  "ca.chain.off": "Chỉ off-chain",
  "ca.chain.roles": "ISSUER_ROLE, PAUSER_ROLE, TRANSFER_AGENT_ROLE trên token cổ phần + KYC_AGENT_ROLE trên registry (BlockID EVM)",
  "ca.empty": "Chưa có quản trị viên doanh nghiệp.",
  "ca.addr.ph": "Địa chỉ ví 0x… (EIP-55)",
  "ca.add": "Thêm quản trị viên",
  "ca.added": "Đã thêm quản trị viên doanh nghiệp.",
  "ca.added.chain": "Đã thêm quản trị viên. Issuer đang cấp quyền on-chain; danh sách sẽ tự cập nhật.",
  "ca.bad.addr": "Hãy nhập địa chỉ ví hợp lệ. Địa chỉ viết hoa lẫn thường phải khớp checksum EIP-55.",
  "ca.onchain.cb": "Đồng thời cấp quyền on-chain trên các hợp đồng BlockID của doanh nghiệp này",
  "ca.onchain.notyet": "khả dụng sau khi doanh nghiệp được phát hành trên BlockID EVM",
  "ca.onchain.note": "Issuer cấp ISSUER_ROLE, PAUSER_ROLE và TRANSFER_AGENT_ROLE trên token cổ phần và KYC_AGENT_ROLE trên identity registry. Ví cũng được cấp gas trên BlockID EVM.",
  "ca.revoke": "Thu hồi",
  "ca.retry": "Thử lại thu hồi on-chain",
  "ca.revoked": "Đã thu hồi quản trị viên doanh nghiệp.",
  "ca.revoked.chain": "Đã thu hồi quản trị viên. Issuer đang gỡ các quyền on-chain.",
  "ca.confirm.h": "Thu hồi {a}? Quyền của ví này với doanh nghiệp chấm dứt ngay.",
  "ca.confirm.chain": "Các quyền on-chain cũng bị gỡ.",
  "ca.confirm.p": "Nhập {tk} để xác nhận",
  "ca.readonly": "Chỉ chủ sở hữu doanh nghiệp và admin nền tảng mới được thay đổi danh sách này.",
  "ca.mirrors": "Bản sao trên Ethereum Hoodi và HashKey vẫn do issuer kiểm soát (tạm dừng); quyền chỉ được cấp trên BlockID EVM.",
  "ca.ap.h": "Yêu cầu đang chờ của doanh nghiệp này",
  "ca.ap.p": "Là quản trị viên doanh nghiệp, bạn có thể duyệt hoặc từ chối mint, cổ tức và chuyển nhượng của doanh nghiệp. Dịch vụ issuer sẽ thực hiện on-chain.",
  "ca.ap.empty": "Không có yêu cầu nào đang chờ duyệt.",
  "ca.ap.tr": "Chuyển nhượng {n} cổ phần",
  /* flow shell, workspace, admin queues */
  "flow.ph.a": "Định giá",
  "flow.ph.b": "Cấu trúc",
  "flow.ph.c": "Lên chuỗi",
  "flow.ph.d": "Không gian doanh nghiệp",
  "flow.g1": "Admin duyệt định giá",
  "flow.g1.wait": "Đang chờ admin duyệt định giá",
  "flow.g1.ok": "Đã duyệt định giá",
  "flow.g1.bad": "Định giá bị từ chối",
  "flow.g2": "Admin duyệt phát hành",
  "flow.g2.wait": "Đang chờ admin duyệt phát hành",
  "flow.g2.ok": "Đã duyệt phát hành",
  "flow.g2.bad": "Phát hành bị từ chối",
  "flow.locked": "Mở sau khi xong bước trước",
  "crumb.label": "Đường dẫn",
  "flow.stepof": "Bước {n}/8 · {p}",
  "flow.nav": "Các bước phát hành",
  "flow.auto.report": "AI đã nghiên cứu xong. Đây là báo cáo định giá.",
  "flow.why.research": "AI agent vẫn đang làm việc. Báo cáo sẽ tự mở khi xong.",
  "flow.why.g1": "Bước tiếp theo mở khi admin duyệt định giá.",
  "flow.why.ticker": "Nhập tên công ty và chọn một mã 3 chữ còn trống.",
  "flow.home": "Trang chủ",
  "flow.d6": "Sau một lần duyệt phát hành, issuer tạo sổ cổ đông trên BlockID EVM: hợp đồng, KYC từng cổ đông, gas, cổ phần và hash báo cáo.",
  "flow.d7": "Issuer sao chép sổ cổ đông sang Ethereum Hoodi và HashKey Chain: token mirror bị tạm dừng với cùng số dư và Merkle root của sổ cổ đông.",
  "flow.d8": "Địa chỉ hợp đồng trên cả ba chuỗi, kèm mã QR và nút Thêm vào MetaMask.",
  "nav.studio": "Cho doanh nghiệp",
  "nav.menu": "Menu",
  "gate.open": "Mở mục này trong khu admin",
  "ws.h": "Không gian doanh nghiệp",
  "ws.overview": "Tổng quan",
  "ws.cap-table": "Sổ cổ đông",
  "ws.transfers": "Chuyển nhượng",
  "ws.mint": "Phát hành thêm",
  "ws.dividends": "Cổ tức",
  "ws.activity": "Hoạt động",
  "ws.team": "Quản trị viên",
  "ws.verify": "Xác minh",
  "ws.needlive": "Có sau khi phát hành cổ phần",
  "ws.needsign": "Kết nối ví để chuyển nhượng",
  "ws.needauth": "Chỉ dành cho quản trị viên công ty",
  "ws.next": "Việc tiếp theo",
  "ws.next.draft": "Công ty đang là bản nháp. Gửi để admin duyệt phát hành.",
  "ws.next.wait": "Yêu cầu đang chờ admin duyệt phát hành.",
  "ws.next.fail": "Phát hành bị dừng. Mở bước phát hành để xem lý do.",
  "ws.next.issuing": "Issuer đang tạo {tk} trên BlockID EVM.",
  "ws.next.sync": "{tk} đã có trên BlockID EVM. Issuer đang đồng bộ Hoodi và HashKey.",
  "ws.next.live": "{tk} đã chạy trên ba chuỗi. Thêm vào ví của bạn.",
  "ws.d.overview": "Định giá, giá cổ phần và mốc neo on-chain trong một màn.",
  "ws.d.cap-table": "Mọi cổ đông, ví và số cổ phần, đọc từ chuỗi.",
  "ws.d.transfers": "Chuyển cổ phần giữa các ví đã KYC.",
  "ws.d.mint": "Phát hành thêm cổ phần, xem trước mức pha loãng. Admin duyệt yêu cầu.",
  "ws.d.dividends": "Chia cổ tức bằng mAUD cho mọi cổ đông theo tỷ lệ cổ phần. Cổ đông không mất phí.",
  "ws.d.activity": "Mọi sự kiện và giao dịch của công ty, mới nhất trước.",
  "ws.d.team": "Ai được quản lý công ty, và các yêu cầu đang chờ họ.",
  "ad.ret.h": "Mở từ luồng của founder",
  "ad.ret.p": "Sau khi quyết định, bạn sẽ quay về {p}.",
  "ad.ret.back": "Quay lại, không quyết định",
  "ad.qv.mid": "Định giá (giữa)",
  "ad.qv.note": "Mở báo cáo đầy đủ để kiểm tra bằng chứng hoặc chỉnh điểm trước khi duyệt.",
  "ad.q.gone": "Mục đó đã được xử lý. Đang hiện mục tiếp theo.",
  "ad.q.empty": "Hàng đợi này không có mục nào.",
  "ad.q.nextq": "Hàng đợi kế: {q}",
  "ad.q.pos": "Mục {i}/{n}",
  "ad.q.keys": "J / K để chuyển",
  "ad.q.prev": "Trước",
  "ad.q.next": "Sau",
  "ad.q.valuations": "Định giá",
  "ad.q.issuance": "Phát hành",
  "ad.q.sync": "Đồng bộ chuỗi",
  "ad.q.mints": "Phát hành thêm",
  "ad.q.dividends": "Cổ tức",
  "ad.q.transfers": "Chuyển nhượng & KYC",
  "ad.q.eyebrow": "Hàng đợi {i}/8",
  "ad.nav.inbox": "Hộp việc",
  "ad.nav.queues": "Hàng đợi · theo luồng",
  "ad.nav.registry": "Quản lý",
  "ad.nav.trust": "Kiểm soát",
  "ad.inbox.h": "{n} mục cần quyết định",
  "ad.q.done": "Mục này đã được quyết định.",
  "ad.ret.go": "Quay lại luồng founder",
  "ad.inbox.first": "{n} mục đang chờ ở {q}. Bắt đầu từ mục cũ nhất.",
  "ad.inbox.onlytr": "Chỉ còn yêu cầu chuyển nhượng và KYC đang chờ.",
  "ad.inbox.q": "Hàng đợi",
  "ad.inbox.n": "Đang chờ",
  "ad.inbox.oldest": "Mục kế tiếp",
  "ad.review": "Xem xét",
  "ad.inbox.p": "Hàng đợi xếp theo thứ tự công ty đi qua luồng. ◆ là cổng duyệt của con người: không có gì được ký khi admin chưa duyệt.",
  "ad.d.inbox": "Mọi việc đang chờ admin, theo thứ tự luồng.",
  "ad.d.dashboard": "Giá trị nền tảng, xếp hạng, biến động và hoạt động trực tiếp.",
  "ad.d.valuations": "Báo cáo định giá AI chờ người kiểm tra bằng chứng.",
  "ad.d.issuance": "Mỗi công ty một lần duyệt: sau đó issuer ký toàn bộ đợt phát hành.",
  "ad.d.sync": "Công ty đã phát hành trên BlockID EVM nhưng chưa đồng bộ xong Hoodi hoặc HashKey.",
  "ad.d.mints": "Yêu cầu phát hành thêm từ quản trị viên công ty.",
  "ad.d.dividends": "Đợt cổ tức chờ được cấp vốn.",
  "ad.d.transfers": "Chuyển nhượng ở chế độ cần duyệt và yêu cầu KYC của cổ đông mới.",
  "ad.d.companies": "Mọi công ty, trạng thái từng chuỗi, định giá lại và quản trị viên.",
  "ad.d.wallets": "Ví admin, ví dịch vụ và gas.",
  "ad.d.audit": "Mọi thao tác admin: ai làm và khi nào.",
};

export const en = { ...protoEn, ...appEn, ...invEn, ...updEn, ...divEn };
export type DictKey = keyof typeof en;
export const vi: Record<DictKey, string> = { ...protoVi, ...appVi, ...invVi, ...updVi, ...divVi };
