import { protoEn, protoVi } from "./dict.proto";

/** App strings added on top of the prototype copy. VI must cover every EN key (checked by the type). */
const appEn = {
  "nav.companies": "Companies",
  "nav.connect": "Connect wallet",
  "nav.connecting": "Signing in…",
  "nav.signout": "Sign out",
  "nav.account": "Account menu",
  "nav.lang": "Language",
  "nav.primary": "Primary",
  "nav.skip": "Skip to content",
  "nav.role.admin": "admin",
  "nav.role.user": "wallet",
  "nav.adminlink": "Open admin console",
  "common.loading": "Loading…",
  "common.error": "Something went wrong.",
  "common.retry": "Retry",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.none": "–",
  "common.back": "Back",
  "common.yes": "Yes",
  "err.unauth": "Please connect your wallet and sign in first.",
  "err.forbidden": "Your account is not allowed to do this.",
  "err.rate": "Too many requests. Try again later.",
  "err.network": "Network error. Check your connection and try again.",
  "err.rejected": "Request rejected in the wallet.",
  "err.nomm": "MetaMask not found in this browser.",

  "home.stats.eyebrow": "Live on the testnet",
  "home.stats.h2": "The platform today",
  "home.stats.p": "Read from the BlockID API. Values are SVI marks, not market prices.",
  "home.st.co": "Companies tokenized",
  "home.st.val": "Total valuation",
  "home.st.tok": "Token contracts",
  "home.st.tokSub": "BlockID Chain + Hoodi mirrors",
  "home.st.asof": "block #{b}",
  "home.recent": "Recently tokenized",
  "home.recent.all": "See all companies",
  "home.recent.empty": "No companies yet. Yours could be the first.",
  "home.walk.cta": "Start with your website",
  "home.walk.sample": "Open a sample company",

  "new.eyebrow": "New valuation",
  "new.h2": "Eight steps from website to wallet",
  "new.p": "Gold steps need an admin approval before anything is written on-chain.",
  "new.signin": "Connect your wallet to start. Each valuation belongs to the wallet that requested it.",
  "new.bad.url": "Enter a website address, for example https://example.com.au.",
  "new.limit": "Daily limit reached: 3 valuations per wallet per day. Try again tomorrow.",
  "new.starting": "Starting…",

  "v.eyebrow": "Valuation",
  "v.st.queued": "Queued",
  "v.st.running": "AI agents running",
  "v.st.waiting_approval": "Waiting for admin approval",
  "v.st.approved": "Approved",
  "v.st.rejected": "Rejected",
  "v.st.failed": "Failed",
  "v.waiting": "Waiting for admin approval. An admin reviews every AI score before anything can be issued. This page updates by itself.",
  "v.rejected": "An admin rejected this valuation. You can start a new one.",
  "v.failed": "The valuation failed: {e}",
  "v.poll": "Updates every 3 s",
  "v.warn": "Warnings:",
  "v.verified": "verified via website",
  "v.verified.tip": "Suggested by the model, then confirmed by fetching the competitor's own website.",
  "v.mine": "Your valuations",
  "v.mine.co": "Your companies",
  "v.open": "Open",
  "v.queued": "Waiting for a free agent…",
  "v.signin": "Connect the wallet that requested this valuation to view it.",
  "v.notfound": "Valuation not found.",
  "v.total": "SVI index · grade {g}",
  "v.method": "Method: {m}",
  "v.nd": "not disclosed",
  "v.narr": "Analyst narrative",
  "v.evidence": "Evidence",
  "v.evidence.p": "Every page the agents fetched and cited.",
  "v.evidence.empty": "No evidence yet.",
  "v.retrieved": "retrieved {d}",
  "sr.toggle": "Add your numbers (optional, improves accuracy)",
  "sr.help": "Self-reported. Shown as such in the report.",
  "sr.why": "A website rarely states revenue, so without these figures the revenue and growth scores stay near zero.",
  "sr.revenue": "Revenue, last 12 months (A$)",
  "sr.growth": "Revenue growth, year on year (%)",
  "sr.margin": "Gross margin (%)",
  "sr.customers": "Paying customers",
  "sr.raised": "Raised to date (A$)",
  "sr.runway": "Runway (months)",
  "sr.employees": "Employees",
  "sr.bad": "Check the highlighted number: {f}",
  "sr.chip": "Self-reported",
  "sr.chip.tip": "Figure provided by the founder, not independently verified.",
  "sr.table": "Self-reported figures",
  "sr.table.p": "Provided by the founder when requesting the valuation. Not independently verified.",
  "v.sources": "{n} sources",
  "v.adm.h": "Admin review",
  "v.adm.p": "Adjust any AI score before approving. The server recalculates the index and valuation.",
  "v.adm.preview": "Index with your scores",
  "v.adm.reject": "Reject valuation",
  "v.adm.done": "Decision saved.",
  "v.continue": "Continue to ticker",
  "v.newval": "Start a new valuation",
  "v.running.note": "About 2–4 minutes. You can close the tab; this link resumes the job.",
  "v.tk.custom": "Or type your own",
  "v.tk.taken": "taken",
  "v.tk.bad": "Use exactly three letters A–Z.",
  "v.tk.cname": "Company name",
  "v.tk.none": "No suggestions yet.",
  "v.sh.add": "Add holder",
  "v.sh.remove": "Remove {n}",
  "v.sh.name": "Name",
  "v.sh.badaddr": "Not a valid address (EIP-55 checksum).",
  "v.sh.dup": "Wallet already listed.",
  "v.sh.badname": "Enter a name.",
  "v.sh.submit": "Create & submit for approval",
  "v.sh.creating": "Submitting…",
  "v.sh.need": "Fix the highlighted rows first.",
  "v.sh.default": "Default: valuation mid ÷ A$1.00 = {n}",
  "v.sh.draft": "Created as a draft, but it could not be submitted: {e}",

  "c.eyebrow": "Company",
  "c.st.draft": "Draft",
  "c.st.pending_issue": "Awaiting issue approval",
  "c.st.issuing": "Issuing on BlockID Chain",
  "c.st.issued": "Issued · awaiting anchor approval",
  "c.st.pending_anchor": "Awaiting anchor approval",
  "c.st.anchoring": "Anchoring on Hoodi",
  "c.st.anchored": "Anchored on Hoodi",
  "c.st.rejected": "Rejected",
  "c.st.failed": "Failed",
  "c.tl.draft": "Draft",
  "c.tl.pending_issue": "Pending issue",
  "c.tl.issuing": "Issuing",
  "c.tl.issued": "Issued",
  "c.tl.anchoring": "Anchoring",
  "c.tl.anchored": "Anchored",
  "c.gate": "admin",
  "c.k.val": "Valuation",
  "c.k.valsub": "SVI {s} · grade {g}",
  "c.k.noanchor": "not yet",
  "c.cap": "Cap table",
  "c.cap.p": "Balances read from BlockID Chain.",
  "c.cap.empty": "No holders yet.",
  "c.other": "Other",
  "c.cap.chain": "Balances read from BlockID Chain at block #{b}.",
  "c.cap.db": "Issuance record (not yet on-chain, or the chain is unreachable).",
  "c.mark": "Share mark",
  "c.notyet": "Not deployed yet",
  "c.addr.localwait": "Appears after an admin approves issuance.",
  "c.addr.hoodiwait": "Appears after an admin approves the anchor.",
  "c.qr": "QR code for {a}",
  "c.mint.to": "Recipient wallet",
  "c.mint.name": "Holder name",
  "c.mint.reason": "Reason",
  "c.mint.sent": "Mint request sent for admin approval.",
  "c.mint.existing": "Existing holder: shares are added to their balance.",
  "c.div.sent": "Dividend plan sent for approval.",
  "c.div.root": "computed by the server at the record block",
  "c.ev": "Activity",
  "c.ev.empty": "No on-chain activity yet.",
  "c.notfound": "No company with ticker {t}.",
  "c.draftnote": "This company is a draft. An admin or an approved issuer wallet must submit it for approval.",
  "c.submit": "Submit for approval",
  "c.submitted": "Submitted. An admin will review the issuance.",
  "c.needauth": "Connect the owner wallet or sign in as admin to request mints or dividends.",
  "c.failed": "The issuer reported an error: {e}",
  "c.website": "Website",
  "c.anchor.root": "Merkle root",
  "c.onlyissued": "Available once the shares are issued.",

  "ev.issued": "Shares issued",
  "ev.kyc": "Investor KYC-registered",
  "ev.drip": "Gas allowance sent",
  "ev.minted": "Shares minted",
  "ev.valuation_anchored": "Valuation hash anchored",
  "ev.revalued": "Revalued",
  "ev.hoodi_mirrored": "Mirror token deployed on Hoodi",
  "ev.anchored": "Cap table anchored on Hoodi",
  "ev.dividend_created": "Dividend round created",
  "ev.dividend_claimed": "Dividend claimed",
  "ev.mint_requested": "Mint requested",
  "ev.rejected": "Rejected",

  "co.eyebrow": "Market",
  "co.h2": "Tokenized companies",
  "co.p": "Every company issued on BlockID Chain. Marks change only on issuance and approved SVI revaluations; they are not market prices.",
  "co.search": "Search ticker or company",
  "co.empty": "No companies match.",
  "co.anchNo": "not yet",
  "co.anchYes": "✓ Hoodi",
  "co.sort": "Sort by {c}",

  "ad.t.ap": "Approvals",
  "ad.t.cos": "Companies",
  "ad.t.au": "Audit log",
  "ad.notadmin": "This wallet is signed in as a regular user. Only wallets on the admin list, or the admin account, can open the console.",
  "ad.bad.rate": "Too many attempts. Try again in 15 minutes.",
  "ad.paused": "Paused · tab hidden",
  "ad.cp.h": "Change the admin password",
  "ad.cp.p": "The demo password must be changed before you continue. Use at least 10 characters.",
  "ad.cp.cur": "Current password",
  "ad.cp.new": "New password",
  "ad.cp.rep": "Repeat new password",
  "ad.cp.go": "Change password",
  "ad.cp.short": "Use at least 10 characters.",
  "ad.cp.mismatch": "The passwords do not match.",
  "ad.cp.ok": "Password changed.",
  "ad.k.tokval": "{n} contracts",
  "ad.k.anchval": "{a} / {b}",
  "ad.aw.list": "Admin wallets · visible to admins only",
  "ad.aw.svc": "Service wallets",
  "ad.aw.issuer": "Issuer service",
  "ad.aw.relayer": "Relayer (claims only)",
  "ad.aw.bal": "BlockID {a} BLKD · Hoodi {b} ETH",
  "ad.iw.empty": "No issuer wallets yet.",
  "ad.audit.empty": "No audit entries yet.",
  "ad.co.pick": "Pick a company in the table to see its mark chart and revalue it.",
  "ad.co.open": "Open public page",

  "ap.val": "Valuations waiting for review",
  "ap.co": "Companies to issue on BlockID Chain",
  "ap.anchor": "Issued · approve anchor to Hoodi",
  "ap.mints": "Mint requests",
  "ap.divs": "Dividend plans",
  "ap.empty": "Nothing waiting. New requests appear here automatically.",
  "ap.open": "Open report",
  "ap.approve": "Approve",
  "ap.reject": "Reject",
  "ap.review": "Review transactions",
  "ap.hide": "Hide",
  "ap.anchorbtn": "Approve anchor to Hoodi",
  "ap.reason": "Reason for rejection",
  "ap.txs": "Transactions the issuer service will send",
  "ap.sent": "Approved. The issuer service is working; status updates here.",
  "ap.rejected": "Rejected.",
  "ap.mintrow": "{n} {tk} → {name}",
  "ap.divrow": "{n} mAUD to {tk} holders",
  "ap.req": "requested by {w}",
  "ap.holders": "{n} holders",
  "ap.anchor.txs": "Deploy mirror registry + token on Hoodi · register and mint {n} holders · pause · CapTableAnchor.anchor(root)",
  "tx.kycrole": "Grant KYC_AGENT_ROLE to issuer",
  "tx.tokN": "Deploy {tk} share token (decimals 0)",
  "tx.kycN": "KYC {n} wallets",
  "tx.gasN": "Gas allowance to up to {n} wallets",
  "tx.mintN": "Mint {s} {tk} to {n} holders",
  "tx.valN": "Anchor SVI report hash · mark A$1.00",

  "rv.h": "Revalue",
  "rv.p": "Sets a new valuation. The mark becomes valuation ÷ shares and the cap table is re-anchored.",
  "rv.val": "New valuation (A$)",
  "rv.note": "Note",
  "rv.go": "Submit revaluation",
  "rv.newmark": "New mark {m} ({p})",
  "rv.ok": "Revaluation recorded.",

  "nf.h": "Page not found",
  "nf.p": "The page you asked for does not exist or has moved.",
  "nf.home": "Back to home",
  "nav.hsk": "HashKey Chain",
  "hsk.eyebrow": "HashKey Chain testnet · chain 133",
  "hsk.title": "Live on HashKey Chain",
  "hsk.msg": "AI agents never hold keys. Every agent proposal is hashed on-chain, a human approver signs, and only then the issuer executes.",
  "hsk.live": "Live",
  "hsk.open": "See the deployment",
  "hsk.card.stats": "{c} contracts deployed · {p} agent proposals on-chain",
  "hsk.pending": "Deployment pending.",
  "hsk.pending.p": "The HashKey Chain contracts are being deployed. Addresses, proposals and transactions appear here as soon as they are published.",
  "hsk.addnet": "Add HashKey Chain to MetaMask",
  "hsk.added": "HashKey Chain testnet is ready in your wallet.",
  "hsk.explorer": "Open in explorer",
  "hsk.flow": "AI proposes → human approves → issuer executes",
  "hsk.f1": "AI proposes",
  "hsk.f1s": "hash recorded on-chain",
  "hsk.f2": "Human approves",
  "hsk.f2s": "approver signs",
  "hsk.f3": "Issuer executes",
  "hsk.f3s": "only key holder",
  "hsk.contracts": "Contracts",
  "hsk.deployed": "Deployed",
  "hsk.c.prov": "Agent provenance",
  "hsk.c.reg": "Identity registry (KYC)",
  "hsk.c.share": "Share token",
  "hsk.c.div": "Dividend distributor",
  "hsk.c.pay": "Payout token",
  "hsk.c.anchor": "Cap table anchor",
  "hsk.roles": "Roles",
  "hsk.r.op": "Operator (issuer)",
  "hsk.r.relayer": "Relayer (agents)",
  "hsk.r.approver": "Human approver",
  "hsk.roles.p": "The relayer can only submit proposal hashes. It cannot approve or execute anything.",
  "hsk.prov": "Agent provenance",
  "hsk.prov.p": "Each AI output is hashed and proposed on-chain. Check any hash against the AgentProvenance contract yourself.",
  "hsk.prov.empty": "No agent proposals published yet.",
  "hsk.hash": "Content hash",
  "hsk.model": "Model",
  "hsk.verify": "Verify on-chain",
  "hsk.v.ok": "Hash matches on-chain record",
  "hsk.v.no": "Hash does not match",
  "hsk.v.err": "Could not reach HashKey RPC",
  "hsk.div": "Dividends",
  "hsk.div.round": "Dividend round",
  "hsk.div.id": "Round",
  "hsk.div.total": "Total",
  "hsk.div.deadline": "Claim deadline",
  "hsk.div.root": "Merkle root",
  "hsk.div.units": "Amounts are in payout-token base units. Holders claim with a Merkle proof.",
  "hsk.div.claims": "Holder claims",
  "hsk.div.amt": "Amount",
  "hsk.div.empty": "No dividend round published yet.",
  "hsk.txs": "Transactions",
  "mock.badge": "MOCK DATA",
} as const;

type AppKey = keyof typeof appEn;

const appVi: Record<AppKey, string> = {
  "nav.companies": "Doanh nghiệp",
  "nav.connect": "Kết nối ví",
  "nav.connecting": "Đang đăng nhập…",
  "nav.signout": "Đăng xuất",
  "nav.account": "Menu tài khoản",
  "nav.lang": "Ngôn ngữ",
  "nav.primary": "Điều hướng chính",
  "nav.skip": "Bỏ qua tới nội dung",
  "nav.role.admin": "admin",
  "nav.role.user": "ví",
  "nav.adminlink": "Mở khu vực admin",
  "common.loading": "Đang tải…",
  "common.error": "Đã có lỗi xảy ra.",
  "common.retry": "Thử lại",
  "common.cancel": "Huỷ",
  "common.save": "Lưu",
  "common.none": "–",
  "common.back": "Quay lại",
  "common.yes": "Có",
  "err.unauth": "Vui lòng kết nối ví và đăng nhập trước.",
  "err.forbidden": "Tài khoản của bạn không có quyền làm việc này.",
  "err.rate": "Quá nhiều yêu cầu. Vui lòng thử lại sau.",
  "err.network": "Lỗi mạng. Kiểm tra kết nối rồi thử lại.",
  "err.rejected": "Yêu cầu đã bị từ chối trong ví.",
  "err.nomm": "Không tìm thấy MetaMask trong trình duyệt này.",

  "home.stats.eyebrow": "Trực tiếp trên testnet",
  "home.stats.h2": "Nền tảng hôm nay",
  "home.stats.p": "Đọc từ API của BlockID. Giá trị là mức định giá SVI, không phải giá thị trường.",
  "home.st.co": "Doanh nghiệp token hoá",
  "home.st.val": "Tổng định giá",
  "home.st.tok": "Hợp đồng token",
  "home.st.tokSub": "BlockID Chain + bản sao Hoodi",
  "home.st.asof": "block #{b}",
  "home.recent": "Mới token hoá",
  "home.recent.all": "Xem tất cả doanh nghiệp",
  "home.recent.empty": "Chưa có doanh nghiệp nào. Bạn có thể là người đầu tiên.",
  "home.walk.cta": "Bắt đầu với website của bạn",
  "home.walk.sample": "Mở một doanh nghiệp mẫu",

  "new.eyebrow": "Định giá mới",
  "new.h2": "Tám bước từ website tới ví",
  "new.p": "Các bước màu vàng cần admin duyệt trước khi ghi lên chain.",
  "new.signin": "Kết nối ví để bắt đầu. Mỗi lượt định giá thuộc về ví đã yêu cầu.",
  "new.bad.url": "Nhập địa chỉ website, ví dụ https://example.com.au.",
  "new.limit": "Đã hết lượt trong ngày: mỗi ví 3 lượt định giá mỗi ngày. Hãy thử lại vào ngày mai.",
  "new.starting": "Đang bắt đầu…",

  "v.eyebrow": "Định giá",
  "v.st.queued": "Đang xếp hàng",
  "v.st.running": "AI agent đang chạy",
  "v.st.waiting_approval": "Chờ admin duyệt",
  "v.st.approved": "Đã duyệt",
  "v.st.rejected": "Bị từ chối",
  "v.st.failed": "Thất bại",
  "v.waiting": "Đang chờ admin duyệt. Admin xem lại mọi điểm do AI chấm trước khi được phát hành. Trang này tự cập nhật.",
  "v.rejected": "Admin đã từ chối lượt định giá này. Bạn có thể bắt đầu lượt mới.",
  "v.failed": "Định giá thất bại: {e}",
  "v.poll": "Cập nhật mỗi 3 giây",
  "v.warn": "Cảnh báo:",
  "v.verified": "đã xác minh qua website",
  "v.verified.tip": "Do mô hình gợi ý, sau đó được xác nhận bằng cách tải website của chính đối thủ.",
  "v.mine": "Các lượt định giá của bạn",
  "v.mine.co": "Doanh nghiệp của bạn",
  "v.open": "Mở",
  "v.queued": "Đang chờ agent rảnh…",
  "v.signin": "Kết nối ví đã yêu cầu lượt định giá này để xem.",
  "v.notfound": "Không tìm thấy lượt định giá.",
  "v.total": "Chỉ số SVI · hạng {g}",
  "v.method": "Phương pháp: {m}",
  "v.nd": "không công bố",
  "v.narr": "Nhận định của chuyên viên",
  "v.evidence": "Bằng chứng",
  "v.evidence.p": "Mọi trang mà agent đã tải và trích dẫn.",
  "v.evidence.empty": "Chưa có bằng chứng.",
  "v.retrieved": "tải lúc {d}",
  "sr.toggle": "Thêm số liệu của bạn (không bắt buộc, giúp chính xác hơn)",
  "sr.help": "Tự khai báo. Được ghi rõ như vậy trong báo cáo.",
  "sr.why": "Website hiếm khi công bố doanh thu, nên nếu thiếu các số này thì điểm doanh thu và tăng trưởng gần như bằng 0.",
  "sr.revenue": "Doanh thu 12 tháng gần nhất (A$)",
  "sr.growth": "Tăng trưởng doanh thu so với cùng kỳ (%)",
  "sr.margin": "Biên lợi nhuận gộp (%)",
  "sr.customers": "Khách hàng trả phí",
  "sr.raised": "Tổng vốn đã huy động (A$)",
  "sr.runway": "Thời gian hoạt động còn lại (tháng)",
  "sr.employees": "Số nhân viên",
  "sr.bad": "Kiểm tra lại số được đánh dấu: {f}",
  "sr.chip": "Tự khai báo",
  "sr.chip.tip": "Số liệu do nhà sáng lập cung cấp, chưa được xác minh độc lập.",
  "sr.table": "Số liệu tự khai báo",
  "sr.table.p": "Do nhà sáng lập cung cấp khi yêu cầu định giá. Chưa được xác minh độc lập.",
  "v.sources": "{n} nguồn",
  "v.adm.h": "Admin xem xét",
  "v.adm.p": "Chỉnh bất kỳ điểm nào do AI chấm trước khi duyệt. Máy chủ sẽ tính lại chỉ số và mức định giá.",
  "v.adm.preview": "Chỉ số theo điểm của bạn",
  "v.adm.reject": "Từ chối định giá",
  "v.adm.done": "Đã lưu quyết định.",
  "v.continue": "Tiếp tục chọn mã",
  "v.newval": "Bắt đầu định giá mới",
  "v.running.note": "Khoảng 2–4 phút. Bạn có thể đóng tab; link này mở lại được tác vụ.",
  "v.tk.custom": "Hoặc tự nhập",
  "v.tk.taken": "đã có người dùng",
  "v.tk.bad": "Dùng đúng ba chữ cái A–Z.",
  "v.tk.cname": "Tên công ty",
  "v.tk.none": "Chưa có gợi ý.",
  "v.sh.add": "Thêm cổ đông",
  "v.sh.remove": "Xoá {n}",
  "v.sh.name": "Tên",
  "v.sh.badaddr": "Địa chỉ không hợp lệ (checksum EIP-55).",
  "v.sh.dup": "Ví này đã có trong danh sách.",
  "v.sh.badname": "Nhập tên.",
  "v.sh.submit": "Tạo & gửi duyệt",
  "v.sh.creating": "Đang gửi…",
  "v.sh.need": "Sửa các dòng được đánh dấu trước.",
  "v.sh.default": "Mặc định: định giá giữa ÷ A$1,00 = {n}",
  "v.sh.draft": "Đã tạo bản nháp nhưng chưa gửi duyệt được: {e}",

  "c.eyebrow": "Doanh nghiệp",
  "c.st.draft": "Bản nháp",
  "c.st.pending_issue": "Chờ duyệt phát hành",
  "c.st.issuing": "Đang phát hành trên BlockID Chain",
  "c.st.issued": "Đã phát hành · chờ duyệt neo",
  "c.st.pending_anchor": "Chờ duyệt neo",
  "c.st.anchoring": "Đang neo lên Hoodi",
  "c.st.anchored": "Đã neo trên Hoodi",
  "c.st.rejected": "Bị từ chối",
  "c.st.failed": "Thất bại",
  "c.tl.draft": "Bản nháp",
  "c.tl.pending_issue": "Chờ phát hành",
  "c.tl.issuing": "Đang phát hành",
  "c.tl.issued": "Đã phát hành",
  "c.tl.anchoring": "Đang neo",
  "c.tl.anchored": "Đã neo",
  "c.gate": "admin",
  "c.k.val": "Định giá",
  "c.k.valsub": "SVI {s} · hạng {g}",
  "c.k.noanchor": "chưa neo",
  "c.cap": "Sổ cổ đông",
  "c.cap.p": "Số dư đọc từ BlockID Chain.",
  "c.cap.empty": "Chưa có cổ đông.",
  "c.other": "Khác",
  "c.cap.chain": "Số dư đọc từ BlockID Chain tại block #{b}.",
  "c.cap.db": "Theo hồ sơ phát hành (chưa lên chain, hoặc không kết nối được chain).",
  "c.mark": "Giá cổ phần",
  "c.notyet": "Chưa deploy",
  "c.addr.localwait": "Sẽ hiện sau khi admin duyệt phát hành.",
  "c.addr.hoodiwait": "Sẽ hiện sau khi admin duyệt neo.",
  "c.qr": "Mã QR cho {a}",
  "c.mint.to": "Ví nhận",
  "c.mint.name": "Tên cổ đông",
  "c.mint.reason": "Lý do",
  "c.mint.sent": "Đã gửi yêu cầu mint cho admin duyệt.",
  "c.mint.existing": "Cổ đông hiện hữu: cổ phần được cộng vào số dư.",
  "c.div.sent": "Đã gửi kế hoạch cổ tức để duyệt.",
  "c.div.root": "máy chủ tính tại block chốt",
  "c.ev": "Hoạt động",
  "c.ev.empty": "Chưa có hoạt động on-chain.",
  "c.notfound": "Không có doanh nghiệp mã {t}.",
  "c.draftnote": "Doanh nghiệp này đang là bản nháp. Admin hoặc ví phát hành đã được duyệt phải gửi duyệt.",
  "c.submit": "Gửi duyệt",
  "c.submitted": "Đã gửi. Admin sẽ xem xét việc phát hành.",
  "c.needauth": "Kết nối ví chủ sở hữu hoặc đăng nhập admin để yêu cầu mint hoặc cổ tức.",
  "c.failed": "Issuer báo lỗi: {e}",
  "c.website": "Website",
  "c.anchor.root": "Merkle root",
  "c.onlyissued": "Có sau khi cổ phần được phát hành.",

  "ev.issued": "Đã phát hành cổ phần",
  "ev.kyc": "Nhà đầu tư đã đăng ký KYC",
  "ev.drip": "Đã cấp phí gas",
  "ev.minted": "Đã mint cổ phần",
  "ev.valuation_anchored": "Đã neo hash định giá",
  "ev.revalued": "Định giá lại",
  "ev.hoodi_mirrored": "Đã deploy token bản sao trên Hoodi",
  "ev.anchored": "Đã neo sổ cổ đông trên Hoodi",
  "ev.dividend_created": "Đã tạo vòng cổ tức",
  "ev.dividend_claimed": "Đã nhận cổ tức",
  "ev.mint_requested": "Yêu cầu mint",
  "ev.rejected": "Bị từ chối",

  "co.eyebrow": "Thị trường",
  "co.h2": "Doanh nghiệp đã token hoá",
  "co.p": "Mọi doanh nghiệp đã phát hành trên BlockID Chain. Giá chỉ đổi khi phát hành và khi định giá lại SVI được duyệt; đây không phải giá thị trường.",
  "co.search": "Tìm mã hoặc tên doanh nghiệp",
  "co.empty": "Không có doanh nghiệp phù hợp.",
  "co.anchNo": "chưa neo",
  "co.anchYes": "✓ Hoodi",
  "co.sort": "Sắp xếp theo {c}",

  "ad.t.ap": "Chờ duyệt",
  "ad.t.cos": "Doanh nghiệp",
  "ad.t.au": "Nhật ký kiểm toán",
  "ad.notadmin": "Ví này đang đăng nhập với vai trò người dùng. Chỉ ví trong danh sách admin, hoặc tài khoản admin, mới vào được khu vực này.",
  "ad.bad.rate": "Thử quá nhiều lần. Vui lòng thử lại sau 15 phút.",
  "ad.paused": "Tạm dừng · tab đang ẩn",
  "ad.cp.h": "Đổi mật khẩu admin",
  "ad.cp.p": "Bạn phải đổi mật khẩu demo trước khi tiếp tục. Dùng ít nhất 10 ký tự.",
  "ad.cp.cur": "Mật khẩu hiện tại",
  "ad.cp.new": "Mật khẩu mới",
  "ad.cp.rep": "Nhập lại mật khẩu mới",
  "ad.cp.go": "Đổi mật khẩu",
  "ad.cp.short": "Dùng ít nhất 10 ký tự.",
  "ad.cp.mismatch": "Hai mật khẩu không khớp.",
  "ad.cp.ok": "Đã đổi mật khẩu.",
  "ad.k.tokval": "{n} hợp đồng",
  "ad.k.anchval": "{a} / {b}",
  "ad.aw.list": "Ví admin · chỉ admin thấy",
  "ad.aw.svc": "Ví dịch vụ",
  "ad.aw.issuer": "Issuer service",
  "ad.aw.relayer": "Relayer (chỉ nhận cổ tức)",
  "ad.aw.bal": "BlockID {a} BLKD · Hoodi {b} ETH",
  "ad.iw.empty": "Chưa có ví phát hành.",
  "ad.audit.empty": "Chưa có nhật ký.",
  "ad.co.pick": "Chọn một doanh nghiệp trong bảng để xem biểu đồ giá và định giá lại.",
  "ad.co.open": "Mở trang công khai",

  "ap.val": "Định giá chờ xem xét",
  "ap.co": "Doanh nghiệp chờ phát hành trên BlockID Chain",
  "ap.anchor": "Đã phát hành · duyệt neo lên Hoodi",
  "ap.mints": "Yêu cầu mint",
  "ap.divs": "Kế hoạch cổ tức",
  "ap.empty": "Không có gì đang chờ. Yêu cầu mới sẽ tự hiện ở đây.",
  "ap.open": "Mở báo cáo",
  "ap.approve": "Duyệt",
  "ap.reject": "Từ chối",
  "ap.review": "Xem giao dịch",
  "ap.hide": "Ẩn",
  "ap.anchorbtn": "Duyệt neo lên Hoodi",
  "ap.reason": "Lý do từ chối",
  "ap.txs": "Các giao dịch issuer service sẽ gửi",
  "ap.sent": "Đã duyệt. Issuer service đang xử lý; trạng thái cập nhật tại đây.",
  "ap.rejected": "Đã từ chối.",
  "ap.mintrow": "{n} {tk} → {name}",
  "ap.divrow": "{n} mAUD cho cổ đông {tk}",
  "ap.req": "yêu cầu bởi {w}",
  "ap.holders": "{n} cổ đông",
  "ap.anchor.txs": "Deploy registry + token bản sao trên Hoodi · đăng ký và mint {n} cổ đông · khoá · CapTableAnchor.anchor(root)",
  "tx.kycrole": "Cấp KYC_AGENT_ROLE cho issuer",
  "tx.tokN": "Deploy token cổ phần {tk} (decimals 0)",
  "tx.kycN": "KYC {n} ví",
  "tx.gasN": "Cấp phí gas cho tối đa {n} ví",
  "tx.mintN": "Mint {s} {tk} cho {n} cổ đông",
  "tx.valN": "Neo hash báo cáo SVI · giá A$1,00",

  "rv.h": "Định giá lại",
  "rv.p": "Đặt mức định giá mới. Giá mỗi cổ phần = định giá ÷ số cổ phần, và sổ cổ đông được neo lại.",
  "rv.val": "Định giá mới (A$)",
  "rv.note": "Ghi chú",
  "rv.go": "Gửi định giá lại",
  "rv.newmark": "Giá mới {m} ({p})",
  "rv.ok": "Đã ghi nhận định giá lại.",

  "nf.h": "Không tìm thấy trang",
  "nf.p": "Trang bạn yêu cầu không tồn tại hoặc đã được chuyển.",
  "nf.home": "Về trang chủ",
  "nav.hsk": "HashKey Chain",
  "hsk.eyebrow": "HashKey Chain testnet · chain 133",
  "hsk.title": "Đang chạy trên HashKey Chain",
  "hsk.msg": "AI agent không bao giờ giữ khoá. Mọi đề xuất của agent đều được băm lên chuỗi, một người duyệt ký xác nhận, và chỉ khi đó issuer mới thực thi.",
  "hsk.live": "Đang chạy",
  "hsk.open": "Xem triển khai",
  "hsk.card.stats": "{c} hợp đồng đã deploy · {p} đề xuất của agent trên chuỗi",
  "hsk.pending": "Đang chờ triển khai.",
  "hsk.pending.p": "Các hợp đồng trên HashKey Chain đang được deploy. Địa chỉ, đề xuất và giao dịch sẽ hiện ở đây ngay khi được công bố.",
  "hsk.addnet": "Thêm HashKey Chain vào MetaMask",
  "hsk.added": "Ví của bạn đã sẵn sàng với HashKey Chain testnet.",
  "hsk.explorer": "Mở trên explorer",
  "hsk.flow": "AI đề xuất → con người duyệt → issuer thực thi",
  "hsk.f1": "AI đề xuất",
  "hsk.f1s": "hash ghi lên chuỗi",
  "hsk.f2": "Con người duyệt",
  "hsk.f2s": "người duyệt ký",
  "hsk.f3": "Issuer thực thi",
  "hsk.f3s": "bên duy nhất giữ khoá",
  "hsk.contracts": "Hợp đồng",
  "hsk.deployed": "Đã deploy",
  "hsk.c.prov": "Nguồn gốc agent (provenance)",
  "hsk.c.reg": "Sổ định danh (KYC)",
  "hsk.c.share": "Token cổ phần",
  "hsk.c.div": "Phân phối cổ tức",
  "hsk.c.pay": "Token chi trả",
  "hsk.c.anchor": "Neo sổ cổ đông",
  "hsk.roles": "Vai trò",
  "hsk.r.op": "Vận hành (issuer)",
  "hsk.r.relayer": "Relayer (agent)",
  "hsk.r.approver": "Người duyệt",
  "hsk.roles.p": "Relayer chỉ có thể gửi hash đề xuất. Nó không thể duyệt hay thực thi bất cứ điều gì.",
  "hsk.prov": "Nguồn gốc agent",
  "hsk.prov.p": "Mỗi kết quả AI được băm và đề xuất trên chuỗi. Bạn có thể tự đối chiếu hash với hợp đồng AgentProvenance.",
  "hsk.prov.empty": "Chưa có đề xuất nào của agent.",
  "hsk.hash": "Hash nội dung",
  "hsk.model": "Mô hình",
  "hsk.verify": "Xác minh trên chuỗi",
  "hsk.v.ok": "Hash khớp với bản ghi trên chuỗi",
  "hsk.v.no": "Hash không khớp",
  "hsk.v.err": "Không kết nối được RPC HashKey",
  "hsk.div": "Cổ tức",
  "hsk.div.round": "Đợt cổ tức",
  "hsk.div.id": "Đợt",
  "hsk.div.total": "Tổng",
  "hsk.div.deadline": "Hạn nhận",
  "hsk.div.root": "Merkle root",
  "hsk.div.units": "Số lượng tính theo đơn vị cơ sở của token chi trả. Cổ đông nhận bằng Merkle proof.",
  "hsk.div.claims": "Quyền nhận của cổ đông",
  "hsk.div.amt": "Số lượng",
  "hsk.div.empty": "Chưa có đợt cổ tức nào được công bố.",
  "hsk.txs": "Giao dịch",
  "mock.badge": "DỮ LIỆU GIẢ",
};

export const en = { ...protoEn, ...appEn };
export type DictKey = keyof typeof en;
export const vi: Record<DictKey, string> = { ...protoVi, ...appVi };
