// Ported verbatim from docs/prototype.html (approved copy).
export const protoEn = {
 "nav.how": "How it works",
 "nav.walk": "Walkthrough",
 "nav.dash": "Cap table",
 "nav.net": "Testnet",
 "nav.next": "Next",
 "nav.back": "Back",
 "cta.primary": "Value my startup",
 "cta.secondary": "See a sample report",
 "hero.eyebrow": "AI valuation · Tokenized cap table · Testnet demo",
 "hero.h1a": "Know what your startup is worth,",
 "hero.h1b": "and who owns it.",
 "hero.pitch": "Paste your website. AI agents research your company and its competitors, score it on 7 dimensions and cite every figure. Then turn your shareholder list into a verified cap table you can grow and pay dividends from.",
 "hero.legal": "Testnet demo. Not an offer of securities.",
 "chip.1": "Every figure cites its source",
 "chip.2": "7 dimensions · A–E grade · A$ range",
 "chip.3": "Admin-approved, KYC-gated issuance",
 "chip.4": "Cap table anchored on Ethereum",
 "hs.1": "Research",
 "hs.2": "Value",
 "hs.3": "Issue",
 "hs.4": "Anchor",
 "ht.sources": "Sources cited",
 "ht.svi": "SVI valuation",
 "ht.range": "Range A$2.4M – A$4.3M · SVI 66.7",
 "ht.token": "Share token",
 "ht.holders": "3,360,000 shares · A$1.00 each",
 "ht.anchored": "Anchored · Hoodi #3,694,512",
 "how.eyebrow": "How it works",
 "how.h2": "AI does the research. People approve. Only one service holds keys.",
 "how.p": "Agents read public data and propose. Nothing reaches a blockchain until an admin signs the approval, and only the issuer service can send transactions.",
 "how.cap": "The gold arrow is the only path from AI output to a blockchain. It needs an admin signature, and the dashed boundary marks the one service that can sign transactions.",
 "d.lane1": "AI AGENTS · READ-ONLY · NO KEYS",
 "d.lane2": "ISSUER SERVICE · THE ONLY COMPONENT WITH KEYS",
 "d.n1": "Your website",
 "d.n1s": "public pages",
 "d.n2": "Site intake",
 "d.n2s": "company profile",
 "d.n3": "Competitor search",
 "d.n4": "Market analysis",
 "d.n4s": "cited findings",
 "d.n5": "SVI valuation",
 "d.n5s": "grade + A$ range",
 "d.e1": "reads",
 "d.e2": "names",
 "d.e3": "sources",
 "d.e4": "scores",
 "d.gate": "admin signs approval",
 "d.b1": "Issue on BlockID Chain",
 "d.b1s": "KYC + mint, zero gas",
 "d.b2": "Anchor on Hoodi",
 "d.b2s": "Merkle root + mirror",
 "d.b3": "Shareholder wallets",
 "d.b4": "Cap table & dividends",
 "d.b4s": "mint · claim · explorer",
 "d.f1": "hash",
 "d.f2": "add token",
 "d.f3": "track",
 "walk.eyebrow": "Walkthrough",
 "walk.h2": "Eight steps from website to wallet",
 "walk.p": "Click through the flow with an example company. Gold steps need an admin approval before anything is written on-chain.",
 "step.1": "Website",
 "step.2": "AI research",
 "step.3": "Valuation",
 "step.4": "Ticker",
 "step.5": "Shareholders",
 "step.6": "Issue",
 "step.7": "Anchor",
 "step.8": "Wallet",
 "gate.admin": "Admin approval",
 "s1.h": "Paste your website",
 "s1.p": "We read public pages only: product, team, pricing, press. No login or documents needed to start.",
 "s1.btn": "Start valuation",
 "s1.c1": "What we read",
 "s1.c1p": "Up to 20 public pages. robots.txt respected. Emails and phone numbers are stripped before any search.",
 "s1.c2": "What you get",
 "s1.c2p": "An SVI grade from A to E, an A$ valuation range and a competitor table, each figure linked to its source.",
 "s1.c3": "Time and limits",
 "s1.c3p": "About 2–4 minutes. 3 valuations per wallet per day on the testnet.",
 "s2.h": "AI agents at work",
 "s2.p": "Each agent reports as it finishes. You can close the tab; the link resumes the job.",
 "s2.replay": "Replay",
 "s2.found": "Collected so far",
 "s2.pages": "pages read",
 "s2.comp": "competitors",
 "s2.src": "sources",
 "s2.note": "Findings that cite a page the agent did not actually fetch are dropped automatically.",
 "log.1": "Read website",
 "log.2": "Extract company profile",
 "log.3": "Find competitors on Brave",
 "log.4": "Analyse market with sources",
 "log.5": "Score 7 SVI dimensions",
 "log.6": "Write valuation narrative",
 "s3.h": "Valuation report",
 "s3.p": "Scores come from the model and from your numbers. The admin can adjust any AI score before approving.",
 "s3.radar": "SVI profile",
 "s3.build": "How the index is built",
 "s3.buildp": "Score × weight = contribution. The sum is the SVI index.",
 "s3.range": "Valuation range",
 "s3.method": "Method: revenue × cited sector multiple (low · median · high) × SVI factor 1.17.",
 "s3.comp": "Competitors · capital raised (A$M)",
 "s3.approve": "Approve valuation",
 "s3.total": "SVI index · grade B",
 "dim.founder": "Founders",
 "dim.product": "Product",
 "dim.market": "Market",
 "dim.revenue": "Revenue",
 "dim.growth": "Growth",
 "dim.ready": "Readiness",
 "dim.trust": "Trust",
 "s4.h": "Your share ticker",
 "s4.p": "Three letters with a clear link to your company name, in the style of ASX codes. Pick one or type your own.",
 "s4.name": "Token name",
 "s4.rules": "How it was chosen",
 "s4.r1": "Drop \"Pty Ltd\" → HARBOURLINE LOGISTICS",
 "s4.r2": "First letter + next consonants",
 "s4.r3": "Not on the blocklist",
 "s4.r4": "Not used by another token on BlockID Chain",
 "s4.r5": "HAR is taken (Harvest Agri)",
 "s5.h": "Shareholders",
 "s5.p": "Shares are issued at A$1.00 each by default, so the total follows the approved valuation. Enter each holder's wallet and percentage; we convert to whole shares so the total is always exact.",
 "s5.supply": "Total shares",
 "s5.preview": "Ownership preview",
 "s5.kyc": "Every wallet is KYC-registered on-chain before shares are minted, and receives a small BLKD gas allowance.",
 "s5.review": "Review issuance",
 "s5.ok": "Total 100.00% · ready",
 "s5.bad": "Total {p}% · must equal 100%",
 "t.holder": "Holder",
 "t.wallet": "Wallet",
 "t.shares": "Shares",
 "s6.h": "Approve and issue on BlockID Chain",
 "s6.p": "The admin sees every transaction before it is sent. After signing, the issuer service sends them on the zero-gas chain.",
 "s6.net": "Network",
 "s6.token": "Token",
 "s6.txn": "Transactions",
 "s6.signer": "Signer",
 "s6.sign": "Sign approval & issue",
 "s6.reject": "Reject",
 "tx.reg": "Deploy IdentityRegistry",
 "tx.tok": "Deploy HBL share token",
 "tx.div": "Deploy DividendDistributor",
 "tx.kyc": "KYC 5 wallets",
 "tx.gas": "Gas allowance to 5 wallets",
 "tx.mint": "Mint 3,360,000 HBL",
 "tx.val": "Anchor SVI report hash",
 "tx.wait": "waiting for signature",
 "s7.h": "Anchor on Ethereum Hoodi",
 "s7.p": "Two things go to Hoodi: a fingerprint of the whole cap table, and a paused copy of the token so holders can see it in their wallet.",
 "s7.cap": "Any holder can prove their balance against the public root without revealing the full register. The mirror token exists so wallets and Etherscan can display it; the BlockID Chain ledger stays the source of truth.",
 "s7.approve": "Sign & anchor",
 "a.block": "at block 18,204",
 "a.hash": "hash rows",
 "a.anchor": "anchor",
 "a.mirror": "HBL mirror token",
 "a.paused": "same balances · transfers paused",
 "a.mint": "mint same balances, then pause",
 "s8.h": "HBL is live. Add it to your wallet",
 "s8.p": "Use the button, or copy the contract address and import it in MetaMask yourself.",
 "s8.local": "Token contract · BlockID Chain (262626)",
 "s8.hoodi": "Anchored copy · Ethereum Hoodi (560048)",
 "s8.copy": "Copy address",
 "s8.scan": "View on scan.blockid.au",
 "s8.ether": "View on Etherscan",
 "s8.add": "Add to MetaMask",
 "s8.manual": "Add it manually",
 "s8.m1": "Open MetaMask and choose the network: BlockID Chain or Ethereum Hoodi.",
 "s8.m2": "Go to Tokens → Import tokens.",
 "s8.m3": "Paste the contract address above. Symbol HBL and decimals 0 fill in automatically.",
 "s8.m4": "Confirm. Your balance shows whole shares.",
 "s8.m5": "On a phone, open this page inside the MetaMask app browser.",
 "s8.net": "Network details",
 "s8.name": "Name",
 "s8.sym": "Currency",
 "s8.dash": "Open dashboard",
 "toast.copied": "Address copied.",
 "toast.nomm": "MetaMask not found in this browser. Use the manual steps below.",
 "toast.added": "Token added to MetaMask.",
 "dash.eyebrow": "After issuance",
 "dash.h2": "Your cap table, always current",
 "dash.p": "Read straight from the chain. Model a new round before you mint, and pay dividends that holders claim without paying gas.",
 "k.shares": "Shares outstanding",
 "k.holders": "Holders",
 "k.kyc": "all KYC-verified",
 "k.price": "Value per share",
 "k.pricesub": "issue price · SVI mid A$3.36M",
 "k.anchor": "Last anchor",
 "m.h": "Model a new round",
 "m.p": "New shares for an incoming investor. Existing holders are diluted pro rata.",
 "m.new": "New shares",
 "m.before": "Before",
 "m.after": "After",
 "m.request": "Request approval",
 "m.investor": "New investor",
 "dv.h": "Plan a dividend",
 "dv.p": "Split pro rata at a record block, published as a Merkle root. Holders claim; the relayer pays their gas.",
 "dv.amt": "Total (mAUD)",
 "dv.root": "Merkle root",
 "dv.deadline": "claim deadline 30 days",
 "dv.request": "Send for approval",
 "fin.h": "See your startup's number in minutes.",
 "fin.p": "Sign in with MetaMask, paste your website and get a cited valuation. Issuing shares is optional and always needs approval.",
 "nav.admin": "Admin",
 "ad.eyebrow": "Admin console",
 "ad.h2": "Every tokenized company, one live view",
 "ad.p": "Approve issuer wallets, watch platform value and drill into each company's share mark. Sign in with an admin wallet or the admin account.",
 "ad.signin": "Sign in to admin",
 "ad.m.wallet": "MetaMask",
 "ad.m.pass": "Username",
 "ad.walletp": "Sign a one-time message (SIWE). Only wallets on the admin list can enter.",
 "ad.siwe": "Sign in with MetaMask",
 "ad.user": "Username",
 "ad.pass": "Password",
 "ad.enter": "Sign in",
 "ad.demo": "Demo account: admin / admin. You will be asked to change it after the first sign-in.",
 "ad.signedas": "Signed in as",
 "ad.logout": "Sign out",
 "ad.t.ov": "Overview",
 "ad.t.co": "Company detail",
 "ad.t.wa": "Issuer wallets",
 "ad.pv": "Platform value (marked)",
 "ad.pvnote": "Sum of each company's valuation mark. Steps happen on issuance and on approved SVI revaluations. Simulated values are never included.",
 "ad.grades": "Companies by grade",
 "ad.movers": "Top movers · 30 days",
 "ad.co": "Tokenized companies",
 "ad.clickrow": "Click a row for detail",
 "ad.c.tk": "Ticker",
 "ad.c.name": "Company",
 "ad.c.grade": "Grade",
 "ad.c.val": "Valuation",
 "ad.c.mark": "Mark / share",
 "ad.c.trend": "30d trend",
 "ad.c.hold": "Holders",
 "ad.c.anch": "Anchor",
 "ad.feed": "Activity",
 "ad.simt": "Show simulated growth",
 "ad.l.mark": "Mark (SVI-derived, A$ per share)",
 "ad.l.sim": "Simulated · not a price (P10–P90 band)",
 "ad.l.ev": "Event: issuance, revaluation",
 "ad.aw": "Admin wallet · server keystore · visible to admins only",
 "ad.aw2": "Owner wallet · MetaMask",
 "ad.awnote": "Both hold DEFAULT_ADMIN_ROLE. Grants and revokes below are sent on-chain after you confirm, and appear here once the RoleGranted event is indexed.",
 "ad.iw": "Wallets approved to issue",
 "ad.grant": "Grant role",
 "ad.w.label": "Label",
 "ad.w.status": "Status",
 "ad.w.since": "Since",
 "ad.audit": "Audit log",
 "ad.k.30d": "30d",
 "ad.k.co": "Companies tokenized",
 "ad.k.tok": "Token contracts",
 "ad.k.toksub": "BlockID Chain + Hoodi mirrors",
 "ad.k.sh": "Shares issued",
 "ad.k.tx": "Transaction value",
 "ad.k.val": "Total valuation",
 "ad.k.avg": "Average valuation",
 "ad.k.median": "median",
 "ad.k.mult": "Avg mark vs A$1",
 "ad.k.anch": "Cap tables anchored",
 "ad.k.anchsub": "all roots match",
 "ad.ev.iss": "issued",
 "ad.ev.rv": "revalued",
 "ad.ev.div": "dividend round",
 "ad.today": "today",
 "ad.ago": "{n}d ago",
 "ad.range": "selected range",
 "ad.cagr": "CAGR since issue",
 "ad.issue1": "issue price A$1.00",
 "ad.simnote": "Simulated with geometric Brownian motion for grade {g}: drift {mu}%/yr, volatility {sg}%/yr, 240 paths, seed {seed}. Illustration only, never used in totals.",
 "ad.marknote": "The mark changes only on issuance and on approved SVI revaluations. Between events it stays flat.",
 "ad.k.issued1": "issued at A$1.00",
 "ad.k.kyc": "all KYC-verified",
 "ad.k.simlive": "Simulated live",
 "ad.k.mark": "Current mark",
 "ad.k.asof": "as of last revaluation",
 "ad.st.active": "Active",
 "ad.st.pending": "Pending grant",
 "ad.st.revoked": "Revoked",
 "ad.confirm": "Confirm revoke",
 "ad.revoke": "Revoke",
 "au.grant": "granted ISSUER_ROLE to",
 "au.revoke": "revoked ISSUER_ROLE from",
 "au.req": "requested ISSUER_ROLE for",
 "ad.bad.addr": "Enter a 0x address with 40 hex characters.",
 "ad.bad.label": "Add a label so others know whose wallet this is.",
 "ad.bad.pass": "Wrong username or password.",
 "ad.bad.wallet": "This wallet is not on the admin list.",
 "ad.live": "Live · updated {s}s ago",
 "foot.legal": "Testnet demo. Not an offer of securities or financial advice."
} as const;

export const protoVi: Record<keyof typeof protoEn, string> = {
 "nav.how": "Cách hoạt động",
 "nav.walk": "Từng bước",
 "nav.dash": "Sổ cổ đông",
 "nav.net": "Testnet",
 "nav.next": "Tiếp",
 "nav.back": "Quay lại",
 "cta.primary": "Định giá startup",
 "cta.secondary": "Xem báo cáo mẫu",
 "hero.eyebrow": "Định giá bằng AI · Sổ cổ đông số · Bản demo testnet",
 "hero.h1a": "Biết startup của bạn đáng giá bao nhiêu,",
 "hero.h1b": "và ai đang sở hữu nó.",
 "hero.pitch": "Chỉ cần dán website. AI agent nghiên cứu công ty và đối thủ, chấm điểm trên 7 tiêu chí và dẫn nguồn cho từng con số. Sau đó biến danh sách cổ đông thành sổ cổ đông đã xác minh, sẵn sàng gọi vốn và chia cổ tức.",
 "hero.legal": "Bản demo testnet. Không phải chào bán chứng khoán.",
 "chip.1": "Mọi con số đều có nguồn",
 "chip.2": "7 tiêu chí · hạng A–E · khoảng A$",
 "chip.3": "Phát hành có admin duyệt và KYC",
 "chip.4": "Sổ cổ đông neo trên Ethereum",
 "hs.1": "Nghiên cứu",
 "hs.2": "Định giá",
 "hs.3": "Phát hành",
 "hs.4": "Neo",
 "ht.sources": "Nguồn trích dẫn",
 "ht.svi": "Định giá SVI",
 "ht.range": "Khoảng A$2,4 tr – A$4,3 tr · SVI 66,7",
 "ht.token": "Token cổ phần",
 "ht.holders": "3.360.000 cổ phần · A$1,00 mỗi cổ phần",
 "ht.anchored": "Đã neo · Hoodi #3.694.512",
 "how.eyebrow": "Cách hoạt động",
 "how.h2": "AI nghiên cứu. Con người duyệt. Chỉ một service giữ key.",
 "how.p": "Agent chỉ đọc dữ liệu công khai và đề xuất. Không gì lên blockchain cho tới khi admin ký duyệt, và chỉ issuer service mới gửi được giao dịch.",
 "how.cap": "Mũi tên vàng là đường duy nhất từ kết quả AI tới blockchain. Nó cần chữ ký của admin; khung nét đứt là service duy nhất ký được giao dịch.",
 "d.lane1": "AI AGENT · CHỈ ĐỌC · KHÔNG GIỮ KEY",
 "d.lane2": "ISSUER SERVICE · THÀNH PHẦN DUY NHẤT GIỮ KEY",
 "d.n1": "Website của bạn",
 "d.n1s": "trang công khai",
 "d.n2": "Đọc website",
 "d.n2s": "hồ sơ công ty",
 "d.n3": "Tìm đối thủ",
 "d.n4": "Phân tích thị trường",
 "d.n4s": "có dẫn nguồn",
 "d.n5": "Định giá SVI",
 "d.n5s": "hạng + khoảng A$",
 "d.e1": "đọc",
 "d.e2": "tên",
 "d.e3": "nguồn",
 "d.e4": "điểm",
 "d.gate": "admin ký duyệt",
 "d.b1": "Phát hành trên BlockID",
 "d.b1s": "KYC + mint, 0 phí gas",
 "d.b2": "Neo lên Hoodi",
 "d.b2s": "Merkle root + bản sao",
 "d.b3": "Ví cổ đông",
 "d.b4": "Sổ cổ đông & cổ tức",
 "d.b4s": "mint · nhận · explorer",
 "d.f1": "băm",
 "d.f2": "thêm token",
 "d.f3": "theo dõi",
 "walk.eyebrow": "Từng bước",
 "walk.h2": "Tám bước từ website tới ví",
 "walk.p": "Bấm qua luồng với một công ty ví dụ. Các bước màu vàng cần admin duyệt trước khi ghi lên chain.",
 "step.1": "Website",
 "step.2": "AI nghiên cứu",
 "step.3": "Định giá",
 "step.4": "Mã cổ phần",
 "step.5": "Cổ đông",
 "step.6": "Phát hành",
 "step.7": "Neo",
 "step.8": "Vào ví",
 "gate.admin": "Admin duyệt",
 "s1.h": "Dán website của bạn",
 "s1.p": "Chúng tôi chỉ đọc trang công khai: sản phẩm, đội ngũ, bảng giá, báo chí. Không cần đăng nhập hay tài liệu để bắt đầu.",
 "s1.btn": "Bắt đầu định giá",
 "s1.c1": "Đọc những gì",
 "s1.c1p": "Tối đa 20 trang công khai, tôn trọng robots.txt. Email và số điện thoại bị loại khỏi truy vấn tìm kiếm.",
 "s1.c2": "Bạn nhận được",
 "s1.c2p": "Hạng SVI từ A tới E, khoảng định giá A$ và bảng đối thủ, mỗi con số đều dẫn nguồn.",
 "s1.c3": "Thời gian và giới hạn",
 "s1.c3p": "Khoảng 2–4 phút. Mỗi ví 3 lượt định giá mỗi ngày trên testnet.",
 "s2.h": "AI agent đang làm việc",
 "s2.p": "Mỗi agent báo kết quả khi xong. Bạn có thể đóng tab; link này mở lại được tác vụ.",
 "s2.replay": "Chạy lại",
 "s2.found": "Đã thu thập",
 "s2.pages": "trang đã đọc",
 "s2.comp": "đối thủ",
 "s2.src": "nguồn",
 "s2.note": "Nhận định nào dẫn tới trang mà agent chưa thực sự tải sẽ bị loại tự động.",
 "log.1": "Đọc website",
 "log.2": "Trích hồ sơ công ty",
 "log.3": "Tìm đối thủ qua Brave",
 "log.4": "Phân tích thị trường có nguồn",
 "log.5": "Chấm 7 tiêu chí SVI",
 "log.6": "Viết nhận định định giá",
 "s3.h": "Báo cáo định giá",
 "s3.p": "Điểm đến từ mô hình và từ số liệu của bạn. Admin có thể chỉnh bất kỳ điểm nào do AI chấm trước khi duyệt.",
 "s3.radar": "Hồ sơ SVI",
 "s3.build": "Chỉ số được tính thế nào",
 "s3.buildp": "Điểm × trọng số = đóng góp. Tổng là chỉ số SVI.",
 "s3.range": "Khoảng định giá",
 "s3.method": "Phương pháp: doanh thu × hệ số ngành có dẫn nguồn (thấp · trung vị · cao) × hệ số SVI 1,17.",
 "s3.comp": "Đối thủ · vốn đã gọi (triệu A$)",
 "s3.approve": "Duyệt định giá",
 "s3.total": "Chỉ số SVI · hạng B",
 "dim.founder": "Sáng lập",
 "dim.product": "Sản phẩm",
 "dim.market": "Thị trường",
 "dim.revenue": "Doanh thu",
 "dim.growth": "Tăng trưởng",
 "dim.ready": "Sẵn sàng",
 "dim.trust": "Tin cậy",
 "s4.h": "Mã cổ phần của bạn",
 "s4.p": "Ba chữ cái gắn rõ với tên công ty, theo kiểu mã ASX. Chọn một mã hoặc tự nhập.",
 "s4.name": "Tên token",
 "s4.rules": "Cách chọn mã",
 "s4.r1": "Bỏ \"Pty Ltd\" → HARBOURLINE LOGISTICS",
 "s4.r2": "Chữ đầu + các phụ âm tiếp theo",
 "s4.r3": "Không nằm trong danh sách cấm",
 "s4.r4": "Chưa có token nào dùng trên BlockID Chain",
 "s4.r5": "HAR đã có người dùng (Harvest Agri)",
 "s5.h": "Cổ đông",
 "s5.p": "Mặc định mỗi cổ phần phát hành giá A$1,00, nên tổng số cổ phần bằng mức định giá đã duyệt. Nhập ví và tỷ lệ của từng cổ đông; hệ thống đổi sang số cổ phần nguyên để tổng luôn chính xác.",
 "s5.supply": "Tổng cổ phần",
 "s5.preview": "Xem trước sở hữu",
 "s5.kyc": "Mỗi ví được đăng ký KYC on-chain trước khi mint, và được cấp một ít BLKD làm phí gas.",
 "s5.review": "Xem lại phát hành",
 "s5.ok": "Tổng 100,00% · sẵn sàng",
 "s5.bad": "Tổng {p}% · phải bằng 100%",
 "t.holder": "Cổ đông",
 "t.wallet": "Ví",
 "t.shares": "Cổ phần",
 "s6.h": "Duyệt và phát hành trên BlockID Chain",
 "s6.p": "Admin thấy từng giao dịch trước khi gửi. Sau khi ký, issuer service gửi chúng lên chain không phí gas.",
 "s6.net": "Mạng",
 "s6.token": "Token",
 "s6.txn": "Giao dịch",
 "s6.signer": "Người ký",
 "s6.sign": "Ký duyệt & phát hành",
 "s6.reject": "Từ chối",
 "tx.reg": "Deploy IdentityRegistry",
 "tx.tok": "Deploy token cổ phần HBL",
 "tx.div": "Deploy DividendDistributor",
 "tx.kyc": "KYC 5 ví",
 "tx.gas": "Cấp phí gas cho 5 ví",
 "tx.mint": "Mint 3.360.000 HBL",
 "tx.val": "Neo hash báo cáo SVI",
 "tx.wait": "chờ ký duyệt",
 "s7.h": "Neo lên Ethereum Hoodi",
 "s7.p": "Có hai thứ được đưa lên Hoodi: dấu vân tay của toàn bộ sổ cổ đông, và một bản sao token bị khoá để cổ đông thấy trong ví.",
 "s7.cap": "Mỗi cổ đông có thể chứng minh số dư của mình với root công khai mà không lộ toàn bộ sổ. Token bản sao giúp ví và Etherscan hiển thị được; sổ trên BlockID Chain vẫn là nguồn gốc.",
 "s7.approve": "Ký & neo",
 "a.block": "tại block 18.204",
 "a.hash": "băm từng dòng",
 "a.anchor": "neo",
 "a.mirror": "Token HBL bản sao",
 "a.paused": "cùng số dư · khoá chuyển nhượng",
 "a.mint": "mint cùng số dư, rồi khoá",
 "s8.h": "HBL đã phát hành. Thêm vào ví của bạn",
 "s8.p": "Bấm nút, hoặc sao chép contract address và tự nhập vào MetaMask.",
 "s8.local": "Contract token · BlockID Chain (262626)",
 "s8.hoodi": "Bản neo · Ethereum Hoodi (560048)",
 "s8.copy": "Sao chép địa chỉ",
 "s8.scan": "Xem trên scan.blockid.au",
 "s8.ether": "Xem trên Etherscan",
 "s8.add": "Thêm vào MetaMask",
 "s8.manual": "Thêm thủ công",
 "s8.m1": "Mở MetaMask và chọn mạng: BlockID Chain hoặc Ethereum Hoodi.",
 "s8.m2": "Vào Tokens → Import tokens.",
 "s8.m3": "Dán contract address ở trên. Symbol HBL và decimals 0 tự điền.",
 "s8.m4": "Xác nhận. Số dư hiển thị số cổ phần nguyên.",
 "s8.m5": "Trên điện thoại, mở trang này trong trình duyệt của app MetaMask.",
 "s8.net": "Thông số mạng",
 "s8.name": "Tên",
 "s8.sym": "Đơn vị",
 "s8.dash": "Mở dashboard",
 "toast.copied": "Đã sao chép địa chỉ.",
 "toast.nomm": "Không tìm thấy MetaMask trong trình duyệt này. Làm theo các bước thủ công bên dưới.",
 "toast.added": "Đã thêm token vào MetaMask.",
 "dash.eyebrow": "Sau khi phát hành",
 "dash.h2": "Sổ cổ đông luôn cập nhật",
 "dash.p": "Đọc trực tiếp từ chain. Mô phỏng vòng gọi vốn trước khi mint, và chia cổ tức mà cổ đông nhận không tốn phí gas.",
 "k.shares": "Cổ phần lưu hành",
 "k.holders": "Cổ đông",
 "k.kyc": "đều đã KYC",
 "k.price": "Giá trị mỗi cổ phần",
 "k.pricesub": "giá phát hành · SVI giữa A$3,36 tr",
 "k.anchor": "Lần neo gần nhất",
 "m.h": "Mô phỏng vòng mới",
 "m.p": "Cổ phần mới cho nhà đầu tư. Cổ đông hiện hữu bị pha loãng theo tỷ lệ.",
 "m.new": "Cổ phần mới",
 "m.before": "Trước",
 "m.after": "Sau",
 "m.request": "Gửi admin duyệt",
 "m.investor": "Nhà đầu tư mới",
 "dv.h": "Lập kế hoạch cổ tức",
 "dv.p": "Chia theo tỷ lệ tại một block chốt, công bố dưới dạng Merkle root. Cổ đông tự nhận; relayer trả phí gas.",
 "dv.amt": "Tổng (mAUD)",
 "dv.root": "Merkle root",
 "dv.deadline": "hạn nhận 30 ngày",
 "dv.request": "Gửi duyệt",
 "fin.h": "Biết con số của startup chỉ sau vài phút.",
 "fin.p": "Đăng nhập bằng MetaMask, dán website và nhận báo cáo định giá có dẫn nguồn. Phát hành cổ phần là tuỳ chọn và luôn cần duyệt.",
 "nav.admin": "Admin",
 "ad.eyebrow": "Khu vực admin",
 "ad.h2": "Mọi doanh nghiệp đã token hoá trong một màn hình",
 "ad.p": "Duyệt ví phát hành, theo dõi tổng giá trị nền tảng và xem chi tiết giá cổ phần của từng doanh nghiệp. Đăng nhập bằng ví admin hoặc tài khoản admin.",
 "ad.signin": "Đăng nhập admin",
 "ad.m.wallet": "MetaMask",
 "ad.m.pass": "Tài khoản",
 "ad.walletp": "Ký một thông điệp dùng một lần (SIWE). Chỉ ví trong danh sách admin mới vào được.",
 "ad.siwe": "Đăng nhập bằng MetaMask",
 "ad.user": "Tên đăng nhập",
 "ad.pass": "Mật khẩu",
 "ad.enter": "Đăng nhập",
 "ad.demo": "Tài khoản demo: admin / admin. Bạn sẽ được yêu cầu đổi mật khẩu sau lần đăng nhập đầu.",
 "ad.signedas": "Đang đăng nhập",
 "ad.logout": "Đăng xuất",
 "ad.t.ov": "Tổng quan",
 "ad.t.co": "Chi tiết doanh nghiệp",
 "ad.t.wa": "Ví phát hành",
 "ad.pv": "Tổng giá trị nền tảng (theo định giá)",
 "ad.pvnote": "Tổng giá trị định giá của các doanh nghiệp. Chỉ thay đổi khi phát hành và khi định giá lại SVI được duyệt. Không bao gồm số liệu giả lập.",
 "ad.grades": "Doanh nghiệp theo hạng",
 "ad.movers": "Biến động mạnh · 30 ngày",
 "ad.co": "Doanh nghiệp đã token hoá",
 "ad.clickrow": "Bấm vào dòng để xem chi tiết",
 "ad.c.tk": "Mã",
 "ad.c.name": "Doanh nghiệp",
 "ad.c.grade": "Hạng",
 "ad.c.val": "Định giá",
 "ad.c.mark": "Giá / cổ phần",
 "ad.c.trend": "Xu hướng 30 ngày",
 "ad.c.hold": "Cổ đông",
 "ad.c.anch": "Neo",
 "ad.feed": "Hoạt động",
 "ad.simt": "Hiện tăng trưởng giả lập",
 "ad.l.mark": "Giá định giá (theo SVI, A$ mỗi cổ phần)",
 "ad.l.sim": "Giả lập · không phải giá (dải P10–P90)",
 "ad.l.ev": "Sự kiện: phát hành, định giá lại",
 "ad.aw": "Ví admin · keystore trên server · chỉ admin thấy",
 "ad.aw2": "Ví chủ sở hữu · MetaMask",
 "ad.awnote": "Cả hai giữ DEFAULT_ADMIN_ROLE. Cấp và thu hồi quyền bên dưới được gửi on-chain sau khi bạn xác nhận, và hiện ở đây khi sự kiện RoleGranted được index.",
 "ad.iw": "Ví được quyền phát hành",
 "ad.grant": "Cấp quyền",
 "ad.w.label": "Nhãn",
 "ad.w.status": "Trạng thái",
 "ad.w.since": "Từ ngày",
 "ad.audit": "Nhật ký kiểm toán",
 "ad.k.30d": "30 ngày",
 "ad.k.co": "Doanh nghiệp token hoá",
 "ad.k.tok": "Hợp đồng token",
 "ad.k.toksub": "BlockID Chain + bản sao Hoodi",
 "ad.k.sh": "Cổ phần đã phát hành",
 "ad.k.tx": "Giá trị giao dịch",
 "ad.k.val": "Tổng định giá",
 "ad.k.avg": "Định giá trung bình",
 "ad.k.median": "trung vị",
 "ad.k.mult": "Giá TB so với A$1",
 "ad.k.anch": "Sổ cổ đông đã neo",
 "ad.k.anchsub": "mọi root đều khớp",
 "ad.ev.iss": "phát hành",
 "ad.ev.rv": "định giá lại",
 "ad.ev.div": "vòng cổ tức",
 "ad.today": "hôm nay",
 "ad.ago": "{n} ngày trước",
 "ad.range": "khoảng đã chọn",
 "ad.cagr": "tăng trưởng kép từ khi phát hành",
 "ad.issue1": "giá phát hành A$1,00",
 "ad.simnote": "Giả lập bằng chuyển động Brown hình học cho hạng {g}: xu hướng {mu}%/năm, biến động {sg}%/năm, 240 kịch bản, seed {seed}. Chỉ để minh hoạ, không cộng vào tổng.",
 "ad.marknote": "Giá chỉ đổi khi phát hành và khi định giá lại SVI được duyệt. Giữa các sự kiện, giá đứng yên.",
 "ad.k.issued1": "phát hành giá A$1,00",
 "ad.k.kyc": "đều đã KYC",
 "ad.k.simlive": "Giả lập trực tiếp",
 "ad.k.mark": "Giá hiện tại",
 "ad.k.asof": "theo lần định giá gần nhất",
 "ad.st.active": "Đang hoạt động",
 "ad.st.pending": "Chờ cấp quyền",
 "ad.st.revoked": "Đã thu hồi",
 "ad.confirm": "Xác nhận thu hồi",
 "ad.revoke": "Thu hồi",
 "au.grant": "cấp ISSUER_ROLE cho",
 "au.revoke": "thu hồi ISSUER_ROLE của",
 "au.req": "yêu cầu ISSUER_ROLE cho",
 "ad.bad.addr": "Nhập địa chỉ 0x gồm 40 ký tự hex.",
 "ad.bad.label": "Thêm nhãn để mọi người biết ví này của ai.",
 "ad.bad.pass": "Sai tên đăng nhập hoặc mật khẩu.",
 "ad.bad.wallet": "Ví này không có trong danh sách admin.",
 "ad.live": "Trực tiếp · cập nhật {s} giây trước",
 "foot.legal": "Bản demo testnet. Không phải chào bán chứng khoán hay tư vấn tài chính."
};
