/**
 * BlockID HR v3 strings (docs/PLAN-HR-V3.md §3): Decision card, Verification tab (claim ledger), Fit tab lenses,
 * live "checking the CV's claims" step, team trust / current-role columns + heat map, the eth Founding team card
 * additions and the JD reader in the form. "Not found" is never "false"; a conflict "needs human review".
 * VI must cover every EN key (checked by the type).
 */
export const hv3En = {
  /* tabs + overview */
  "hv.tab.fit": "Fit",
  "hv.tab.ver": "Verification",
  "hv.ov.h": "CV checked against public sources",
  "hv.ov.p": "{v} verified · {p} partly · {c} conflicts · {n} not found — of {m} claims",
  "hv.ov.open": "Open the verification",
  "hv.ov.cv": "{y} years · {r} roles · long breaks: {g}",

  /* decision card */
  "hv.dec.eyebrow": "Decision",
  "hv.dec.fit": "Fit",
  "hv.dec.trust": "Trust in the CV",
  "hv.dec.nofit": "No target to compare with.",
  "hv.dec.notrust": "No CV to check.",
  "hv.dec.why": "Why",
  "hv.dec.verify": "Check before deciding",
  "hv.dec.openver": "See every claim and its source",
  "hv.dec.aria": "Decision matrix: {q}",
  "hv.dec.ax.trust": "Trust",
  "hv.dec.ax.fit": "Fit",
  "hv.q.proceed": "Proceed",
  "hv.q.verify_first": "Verify first",
  "hv.q.other_role": "Consider another role",
  "hv.q.stop": "Stop",
  "hv.q.proceed.p": "A good fit, and public sources back the CV. Move to interviews and references.",
  "hv.q.verify_first.p": "A good fit on paper, but key CV claims are not backed yet. Check them before the next step.",
  "hv.q.other_role.p": "The CV holds up, but the fit to this lens is weak. Look at another role for this person.",
  "hv.q.stop.p": "A weak fit and a CV that public sources do not back. Not recommended for this role.",

  /* trust */
  "hv.trust.short": "Trust",
  "hv.trust.tip": "How far public sources back the CV's claims (CV Trust Index).",
  "hv.trust.h": "Trust in the CV",
  "hv.trust.hidden": "The exact score and the conflict details are visible to the report owner.",
  "hv.trust.cov": "coverage {p}%",
  "hv.trust.cov.l": "Coverage: {p}% of the CV's claims (by importance) could be checked.",
  "hv.trust.ckey": "{n} key claims conflict with a public source — needs human review.",
  "hv.trust.cons": "Timeline consistency: {o} overlaps · {d} date issues.",
  "hv.trust.cons.ok": "Timeline consistency: the dates add up.",
  "hv.trust.p": "Weighted by importance: the current role and recent roles count most. Career breaks are never scored.",
  "hv.tb.high": "High",
  "hv.tb.medium": "Medium",
  "hv.tb.low": "Low / needs review",

  /* verification tab */
  "hv.ver.h": "What the CV says vs what public sources say",
  "hv.ver.n": "{n} claims",
  "hv.ver.note.b": "Not found does not mean false.",
  "hv.ver.note": "Many true facts are simply not on the public web. A conflict is never a verdict: it needs a person to review both sides.",
  "hv.st.verified": "Verified",
  "hv.st.partly_verified": "Partly verified",
  "hv.st.not_found": "Not found",
  "hv.st.unverifiable": "Cannot be verified",
  "hv.st.contradicted": "Conflict — needs human review",
  "hv.led.h": "Claim ledger",
  "hv.led.empty": "No claims in this group.",
  "hv.flt.aria": "Show claims",
  "hv.flt.all": "All",
  "hv.flt.contradicted": "Conflicts",
  "hv.flt.not_found": "Not found",
  "hv.flt.unverifiable": "Cannot be verified",
  "hv.flt.verified": "Verified",
  "hv.col.cv": "CV says",
  "hv.col.src": "Public source says",
  "hv.col.checks": "Checks",
  "hv.col.status": "Status",
  "hv.col.tier": "Source",
  "hv.kind.role": "Role",
  "hv.kind.education": "Education",
  "hv.kind.certification": "Certification",
  "hv.kind.venture": "Venture",
  "hv.kind.achievement": "Achievement",
  "hv.kind.award": "Award",
  "hv.kind.publication": "Publication",
  "hv.imp.key": "key claim",
  "hv.dim.identity": "Identity",
  "hv.dim.org": "Org",
  "hv.dim.title": "Title",
  "hv.dim.dates": "Dates",
  "hv.dim.metric": "Metric",
  "hv.dim.degree": "Degree",
  "hv.dim.y": "matches",
  "hv.dim.n": "differs",
  "hv.dim.na": "not checked",
  "hv.conf.field": "{f} on the source: {v}",
  "hv.src.none": "No public source quoted.",
  "hv.src.notfound": "No public page we could read names this.",
  "hv.src.unverifiable": "The source type is not public (e.g. a private employer or LinkedIn only).",
  "hv.tier.1": "Tier 1: the issuer, a registry, the organisation's own site or the university",
  "hv.tier.2": "Tier 2: established press, a conference, GitHub, OpenAlex or ORCID",
  "hv.tier.3": "Tier 3: another public page",
  "hv.tier.4": "Tier 4: a search result snippet only",
  "hv.tier.none": "No source",
  "hv.tier.legend": "Source tiers: T1 issuer, registry or the organisation's own site · T2 established press, GitHub, OpenAlex / ORCID · T3 other pages · T4 search snippet.",
  "hv.tl.h": "Career timeline, checked",
  "hv.tl.p": "Each role from the CV, coloured by what public sources say about it.",
  "hv.tl.unv": "Not verified yet",
  "hv.tl.bad": "Conflict",
  "hv.tl.noclaim": "Not checked",
  "hv.ns.h": "Possible namesakes left out",
  "hv.ns.p": "These pages name someone with the same name but none of this person's organisations or places, so they were not used.",
  "hv.lk.h": "Structured lookups",
  "hv.lk.wayback": "Web archive (Wayback)",
  "hv.lk.github": "GitHub",
  "hv.lk.openalex": "OpenAlex (publications)",
  "hv.lk.found": "Found",
  "hv.lk.nf": "Nothing found",

  /* CV analysis tab + live */
  "hv.cv.moved.h": "The CV's claims are checked in the Verification tab",
  "hv.cv.moved.p": "{n} claims, each with what the CV says, what public sources say and the source.",
  "hv.cv.stat": "claims verified",
  "hv.live.h": "Checking the CV's claims",
  "hv.live.wait": "After the public sources are read",
  "hv.live.done": "{v} verified · {c} conflict · {n} not found",
  "hv.live.part": "{p} partly verified",

  /* fit tab */
  "hv.lens.aria": "Compare with",
  "hv.lens.business": "Business",
  "hv.lens.jd": "JD",
  "hv.lens.current_role": "Current role",
  "hv.lens.business.long": "Fit to the business",
  "hv.lens.jd.long": "Fit to the job description",
  "hv.lens.current_role.long": "Fit to the role held now",
  "hv.v.strong": "Strong fit",
  "hv.v.conditional": "Fit with conditions",
  "hv.v.weak": "Weak fit",
  "hv.v.not_suitable": "Not suitable",
  "hv.tpl": "Compared with what a {r} needs at the {s} stage.",
  "hv.tpl.nostage": "Compared with what a {r} needs.",
  "hv.fit.v1": "This report was made before fit lenses existed: one fit score, without the claimed / verified split.",
  "hv.fit.claimed": "Claimed fit",
  "hv.fit.verified": "Verified fit",
  "hv.fit.gap": "{n} points of this fit rest on unverified CV claims.",
  "hv.fit.cap": "Capped at {c}: a must-have or knock-out criterion is missing or in conflict.",
  "hv.fit.cap.tip": "Cap at {c}",
  "hv.fit.scale": "Strong fit 75+ · Fit with conditions 55–74 or a knock-out · Weak fit 35–54 · Not suitable under 35. The score shown is the verified fit.",
  "hv.yrs.h": "Relevant experience",
  "hv.yrs.min": "min {m}",
  "hv.yrs.vs": "{y} relevant years against a minimum of {m}",
  "hv.yrs.only": "{y} relevant years",
  "hv.yrs.vs.p": "relevant years · the role asks for {m}",
  "hv.yrs.only.p": "relevant years",
  "hv.yrs.short": "below the minimum",
  "hv.yrs.roles": "How it was counted ({n} roles)",
  "hv.yrs.months": "{n} months",
  "hv.yrs.foot": "Highly relevant roles count in full, medium ones half; roles older than 5 years count 0.6×.",
  "hv.rel.high": "High",
  "hv.rel.medium": "Medium",
  "hv.rel.low": "Low",
  "hv.ko.h": "Knock-out criteria",
  "hv.ko.p": "A missing knock-out caps the fit at 60; one in conflict caps it at 40.",
  "hv.alt.h": "Stronger as {r} ({s})",
  "hv.rq.h": "Risks and interview questions",
  "hv.rq.q": "Ask in the interview",
  "hv.ev.verified": "Verified",
  "hv.ev.cv_only": "CV only",
  "hv.ev.contradicted": "Conflict",
  "hv.ev.none": "No evidence",
  "hv.ev.verified.d": "Backed by a stored public page that names the person.",
  "hv.ev.cv_only.d": "Only the CV says so. Counts half in the verified fit.",
  "hv.ev.contradicted.d": "A public source says something different. Counts zero until a person reviews it.",
  "hv.ev.none.d": "Nothing found either way.",
  "hv.ev.legend": "Evidence: Verified counts in full · CV only counts half · Conflict counts zero in the verified fit.",
  "hv.flag.h": "Left out of scoring — this wording may be discriminatory under Australian law:",

  /* team report */
  "hv.col.trust": "Trust in CV",
  "hv.col.rolefit": "Current-role fit",
  "hv.hm.h": "What the business needs × people",
  "hv.hm.n": "{r} needs · {p} people",
  "hv.hm.p": "Each cell shows whether the person meets that need of the business. Striped cells rest on the CV only.",
  "hv.hm.need": "Need",
  "hv.hm.cvonly": "striped = CV only",

  /* eth Founding team card */
  "hv.tl3.trust": "CV trust: {b}",
  "hv.tl3.role": "Current role: {v} {s}",

  /* form: JD reader */
  "hv.jd.read": "Read the JD",
  "hv.jd.busy": "Reading…",
  "hv.jd.hint": "Paste the JD above, then let us pull out the requirements, years and knock-outs.",
  "hv.jd.done": "Added {n} requirements and {k} knock-outs. {f} flagged items were left out. Check and edit below.",
  "hv.jd.fail": "We could not read the JD right now, so we suggested requirements from its keywords instead.",
  "hv.jd.limit": "JD reading limit reached for now. We suggested requirements from its keywords instead.",
  "hv.np.minyears": "Minimum relevant years (optional)",
  "hv.np.minyears.hint": "Years of relevant experience the role needs.",
  "hv.np.e.minyears": "Enter a whole number of years from 0 to 50.",
  "hv.np.seniority": "Seniority (optional)",
  "hv.np.seniority.any": "Any level",
  "hv.np.ko": "Knock-out criteria",
  "hv.np.ko.hint": "Hard requirements, e.g. a licence, a degree or a clearance. Missing one caps the fit.",
  "hv.np.ko.ph": "e.g. Current CPA registration",
  "hv.np.ko.add": "Add a knock-out criterion",
};

export const hv3Vi: Record<keyof typeof hv3En, string> = {
  "hv.tab.fit": "Mức phù hợp",
  "hv.tab.ver": "Đối chiếu",
  "hv.ov.h": "CV đã được đối chiếu với nguồn công khai",
  "hv.ov.p": "{v} đã xác minh · {p} một phần · {c} mâu thuẫn · {n} không tìm thấy — trên {m} thông tin",
  "hv.ov.open": "Xem phần đối chiếu",
  "hv.ov.cv": "{y} năm · {r} vị trí · {g} khoảng nghỉ dài",

  "hv.dec.eyebrow": "Quyết định",
  "hv.dec.fit": "Mức phù hợp",
  "hv.dec.trust": "Độ tin cậy của CV",
  "hv.dec.nofit": "Chưa có mục tiêu để so sánh.",
  "hv.dec.notrust": "Không có CV để đối chiếu.",
  "hv.dec.why": "Lý do",
  "hv.dec.verify": "Cần kiểm tra trước khi quyết định",
  "hv.dec.openver": "Xem từng thông tin và nguồn của nó",
  "hv.dec.aria": "Ma trận quyết định: {q}",
  "hv.dec.ax.trust": "Tin cậy",
  "hv.dec.ax.fit": "Phù hợp",
  "hv.q.proceed": "Tiến hành",
  "hv.q.verify_first": "Xác minh trước",
  "hv.q.other_role": "Cân nhắc vai trò khác",
  "hv.q.stop": "Dừng",
  "hv.q.proceed.p": "Phù hợp tốt và nguồn công khai ủng hộ CV. Chuyển sang phỏng vấn và tham chiếu.",
  "hv.q.verify_first.p": "Trên giấy tờ thì phù hợp, nhưng các thông tin chính trong CV chưa được xác minh. Hãy kiểm tra trước bước tiếp theo.",
  "hv.q.other_role.p": "CV đáng tin, nhưng mức phù hợp với góc nhìn này còn yếu. Hãy cân nhắc một vai trò khác cho người này.",
  "hv.q.stop.p": "Mức phù hợp thấp và nguồn công khai không ủng hộ CV. Không khuyến nghị cho vai trò này.",

  "hv.trust.short": "Tin cậy",
  "hv.trust.tip": "Mức độ nguồn công khai ủng hộ các thông tin trong CV (Chỉ số tin cậy CV).",
  "hv.trust.h": "Độ tin cậy của CV",
  "hv.trust.hidden": "Điểm chính xác và chi tiết mâu thuẫn chỉ người sở hữu báo cáo xem được.",
  "hv.trust.cov": "độ phủ {p}%",
  "hv.trust.cov.l": "Độ phủ: kiểm tra được {p}% thông tin trong CV (tính theo mức quan trọng).",
  "hv.trust.ckey": "{n} thông tin chính mâu thuẫn với nguồn công khai — cần người xem lại.",
  "hv.trust.cons": "Tính nhất quán của mốc thời gian: {o} chỗ trùng · {d} lỗi ngày tháng.",
  "hv.trust.cons.ok": "Tính nhất quán của mốc thời gian: các mốc khớp nhau.",
  "hv.trust.p": "Tính theo mức quan trọng: vị trí hiện tại và các vị trí gần đây nặng ký nhất. Khoảng nghỉ trong sự nghiệp không bao giờ bị tính điểm.",
  "hv.tb.high": "Cao",
  "hv.tb.medium": "Trung bình",
  "hv.tb.low": "Thấp / cần xem lại",

  "hv.ver.h": "CV nói gì và nguồn công khai nói gì",
  "hv.ver.n": "{n} thông tin",
  "hv.ver.note.b": "Không tìm thấy không có nghĩa là sai.",
  "hv.ver.note": "Nhiều thông tin đúng đơn giản là không có trên mạng. Mâu thuẫn không phải là kết luận: cần một người xem lại cả hai phía.",
  "hv.st.verified": "Đã xác minh",
  "hv.st.partly_verified": "Xác minh một phần",
  "hv.st.not_found": "Không tìm thấy",
  "hv.st.unverifiable": "Không thể xác minh",
  "hv.st.contradicted": "Mâu thuẫn — cần người xem lại",
  "hv.led.h": "Sổ đối chiếu thông tin",
  "hv.led.empty": "Không có thông tin nào trong nhóm này.",
  "hv.flt.aria": "Hiển thị thông tin",
  "hv.flt.all": "Tất cả",
  "hv.flt.contradicted": "Mâu thuẫn",
  "hv.flt.not_found": "Không tìm thấy",
  "hv.flt.unverifiable": "Không thể xác minh",
  "hv.flt.verified": "Đã xác minh",
  "hv.col.cv": "CV ghi",
  "hv.col.src": "Nguồn công khai ghi",
  "hv.col.checks": "Kiểm tra",
  "hv.col.status": "Trạng thái",
  "hv.col.tier": "Nguồn",
  "hv.kind.role": "Vị trí",
  "hv.kind.education": "Học vấn",
  "hv.kind.certification": "Chứng chỉ",
  "hv.kind.venture": "Doanh nghiệp",
  "hv.kind.achievement": "Thành tích",
  "hv.kind.award": "Giải thưởng",
  "hv.kind.publication": "Công bố",
  "hv.imp.key": "thông tin chính",
  "hv.dim.identity": "Danh tính",
  "hv.dim.org": "Tổ chức",
  "hv.dim.title": "Chức danh",
  "hv.dim.dates": "Thời gian",
  "hv.dim.metric": "Số liệu",
  "hv.dim.degree": "Bằng cấp",
  "hv.dim.y": "khớp",
  "hv.dim.n": "khác",
  "hv.dim.na": "không kiểm tra",
  "hv.conf.field": "{f} theo nguồn: {v}",
  "hv.src.none": "Chưa có nguồn công khai nào được trích.",
  "hv.src.notfound": "Không có trang công khai nào đọc được nêu thông tin này.",
  "hv.src.unverifiable": "Loại nguồn này không công khai (ví dụ công ty tư nhân hoặc chỉ có trên LinkedIn).",
  "hv.tier.1": "Bậc 1: đơn vị cấp, cơ quan đăng ký, trang của chính tổ chức hoặc trường đại học",
  "hv.tier.2": "Bậc 2: báo chí uy tín, hội nghị, GitHub, OpenAlex hoặc ORCID",
  "hv.tier.3": "Bậc 3: một trang công khai khác",
  "hv.tier.4": "Bậc 4: chỉ là đoạn trích kết quả tìm kiếm",
  "hv.tier.none": "Không có nguồn",
  "hv.tier.legend": "Bậc nguồn: T1 đơn vị cấp, cơ quan đăng ký hoặc trang của chính tổ chức · T2 báo chí uy tín, GitHub, OpenAlex / ORCID · T3 trang khác · T4 đoạn trích tìm kiếm.",
  "hv.tl.h": "Dòng thời gian sự nghiệp, đã đối chiếu",
  "hv.tl.p": "Mỗi vị trí trong CV được tô màu theo những gì nguồn công khai cho biết.",
  "hv.tl.unv": "Chưa xác minh",
  "hv.tl.bad": "Mâu thuẫn",
  "hv.tl.noclaim": "Chưa kiểm tra",
  "hv.ns.h": "Người trùng tên đã bị loại",
  "hv.ns.p": "Các trang này nêu một người cùng tên nhưng không nhắc tới tổ chức hay nơi chốn nào của người này, nên không được dùng.",
  "hv.lk.h": "Tra cứu có cấu trúc",
  "hv.lk.wayback": "Kho lưu trữ web (Wayback)",
  "hv.lk.github": "GitHub",
  "hv.lk.openalex": "OpenAlex (công bố khoa học)",
  "hv.lk.found": "Tìm thấy",
  "hv.lk.nf": "Không tìm thấy gì",

  "hv.cv.moved.h": "Các thông tin trong CV được đối chiếu ở thẻ Đối chiếu",
  "hv.cv.moved.p": "{n} thông tin, mỗi thông tin có nội dung CV, nội dung nguồn công khai và nguồn.",
  "hv.cv.stat": "thông tin đã xác minh",
  "hv.live.h": "Đang đối chiếu các thông tin trong CV",
  "hv.live.wait": "Sau khi đọc xong nguồn công khai",
  "hv.live.done": "{v} đã xác minh · {c} mâu thuẫn · {n} không tìm thấy",
  "hv.live.part": "{p} xác minh một phần",

  "hv.lens.aria": "So sánh với",
  "hv.lens.business": "Doanh nghiệp",
  "hv.lens.jd": "Mô tả công việc",
  "hv.lens.current_role": "Vai trò hiện tại",
  "hv.lens.business.long": "Mức phù hợp với doanh nghiệp",
  "hv.lens.jd.long": "Mức phù hợp với mô tả công việc",
  "hv.lens.current_role.long": "Mức phù hợp với vai trò đang giữ",
  "hv.v.strong": "Rất phù hợp",
  "hv.v.conditional": "Phù hợp có điều kiện",
  "hv.v.weak": "Ít phù hợp",
  "hv.v.not_suitable": "Không phù hợp",
  "hv.tpl": "So với yêu cầu của một {r} ở giai đoạn {s}.",
  "hv.tpl.nostage": "So với yêu cầu của một {r}.",
  "hv.fit.v1": "Báo cáo này được tạo trước khi có các góc nhìn phù hợp: một điểm phù hợp, không tách phần tự khai và phần đã xác minh.",
  "hv.fit.claimed": "Theo CV",
  "hv.fit.verified": "Đã xác minh",
  "hv.fit.gap": "{n} điểm của mức phù hợp này dựa trên thông tin CV chưa được xác minh.",
  "hv.fit.cap": "Giới hạn ở {c}: thiếu hoặc có mâu thuẫn ở một yêu cầu bắt buộc hay tiêu chí loại trừ.",
  "hv.fit.cap.tip": "Giới hạn {c}",
  "hv.fit.scale": "Rất phù hợp từ 75 · Phù hợp có điều kiện 55–74 hoặc vướng tiêu chí loại trừ · Ít phù hợp 35–54 · Không phù hợp dưới 35. Điểm hiển thị là điểm đã xác minh.",
  "hv.yrs.h": "Kinh nghiệm liên quan",
  "hv.yrs.min": "tối thiểu {m}",
  "hv.yrs.vs": "{y} năm liên quan so với mức tối thiểu {m}",
  "hv.yrs.only": "{y} năm liên quan",
  "hv.yrs.vs.p": "năm liên quan · vai trò yêu cầu {m}",
  "hv.yrs.only.p": "năm liên quan",
  "hv.yrs.short": "dưới mức tối thiểu",
  "hv.yrs.roles": "Cách tính ({n} vị trí)",
  "hv.yrs.months": "{n} tháng",
  "hv.yrs.foot": "Vị trí liên quan cao được tính đủ, trung bình tính một nửa; vị trí cách đây hơn 5 năm tính 0,6×.",
  "hv.rel.high": "Cao",
  "hv.rel.medium": "Trung bình",
  "hv.rel.low": "Thấp",
  "hv.ko.h": "Tiêu chí loại trừ",
  "hv.ko.p": "Thiếu một tiêu chí loại trừ thì mức phù hợp tối đa là 60; có mâu thuẫn thì tối đa là 40.",
  "hv.alt.h": "Phù hợp hơn ở vai trò {r} ({s})",
  "hv.rq.h": "Rủi ro và câu hỏi phỏng vấn",
  "hv.rq.q": "Nên hỏi khi phỏng vấn",
  "hv.ev.verified": "Đã xác minh",
  "hv.ev.cv_only": "Chỉ có trong CV",
  "hv.ev.contradicted": "Mâu thuẫn",
  "hv.ev.none": "Không có bằng chứng",
  "hv.ev.verified.d": "Được một trang công khai đã lưu có nêu tên người đó ủng hộ.",
  "hv.ev.cv_only.d": "Chỉ CV nói vậy. Tính một nửa trong mức phù hợp đã xác minh.",
  "hv.ev.contradicted.d": "Một nguồn công khai nói khác. Tính bằng 0 cho đến khi có người xem lại.",
  "hv.ev.none.d": "Không tìm thấy gì ở cả hai phía.",
  "hv.ev.legend": "Bằng chứng: Đã xác minh tính đủ · Chỉ có trong CV tính một nửa · Mâu thuẫn tính bằng 0 trong mức phù hợp đã xác minh.",
  "hv.flag.h": "Không đưa vào chấm điểm — cách diễn đạt này có thể mang tính phân biệt đối xử theo luật Úc:",

  "hv.col.trust": "Tin cậy CV",
  "hv.col.rolefit": "Phù hợp vai trò hiện tại",
  "hv.hm.h": "Nhu cầu của doanh nghiệp × từng người",
  "hv.hm.n": "{r} nhu cầu · {p} người",
  "hv.hm.p": "Mỗi ô cho biết người đó có đáp ứng nhu cầu ấy của doanh nghiệp không. Ô có sọc chỉ dựa trên CV.",
  "hv.hm.need": "Nhu cầu",
  "hv.hm.cvonly": "có sọc = chỉ có trong CV",

  "hv.tl3.trust": "Tin cậy CV: {b}",
  "hv.tl3.role": "Vai trò hiện tại: {v} {s}",

  "hv.jd.read": "Đọc mô tả công việc",
  "hv.jd.busy": "Đang đọc…",
  "hv.jd.hint": "Dán mô tả công việc ở trên, rồi để chúng tôi tách ra yêu cầu, số năm và tiêu chí loại trừ.",
  "hv.jd.done": "Đã thêm {n} yêu cầu và {k} tiêu chí loại trừ. {f} mục bị gắn cờ đã được bỏ ra. Hãy kiểm tra và sửa bên dưới.",
  "hv.jd.fail": "Hiện chưa đọc được mô tả công việc, nên chúng tôi gợi ý yêu cầu theo từ khóa.",
  "hv.jd.limit": "Đã hết lượt đọc mô tả công việc lúc này. Chúng tôi gợi ý yêu cầu theo từ khóa.",
  "hv.np.minyears": "Số năm liên quan tối thiểu (không bắt buộc)",
  "hv.np.minyears.hint": "Số năm kinh nghiệm liên quan mà vai trò cần.",
  "hv.np.e.minyears": "Nhập số năm nguyên từ 0 đến 50.",
  "hv.np.seniority": "Cấp bậc (không bắt buộc)",
  "hv.np.seniority.any": "Mọi cấp bậc",
  "hv.np.ko": "Tiêu chí loại trừ",
  "hv.np.ko.hint": "Yêu cầu cứng, ví dụ giấy phép hành nghề, bằng cấp hoặc chứng nhận an ninh. Thiếu một tiêu chí sẽ giới hạn mức phù hợp.",
  "hv.np.ko.ph": "vd. Đang có chứng chỉ CPA",
  "hv.np.ko.add": "Thêm tiêu chí loại trừ",
};
