/** Business updates copy (founder workspace, admin queue, investor portal). Plain words; no internal terms on
 * investor screens (see docs/FACTS.md "Terms to avoid"). */
export const updEn = {
  // workspace section + admin queue
  "ws.updates": "Updates",
  "ws.d.updates": "Regular business updates for shareholders: enter the numbers, check the draft, send it for approval.",
  "ad.q.updates": "Business updates",
  "ad.d.updates": "Business updates waiting for a person to approve them. Approving records them on blockchain and shows them to every shareholder.",
  "ev.update_published": "Business update published",

  // metrics
  "upd.m.revenue": "Revenue",
  "upd.m.gross_profit": "Gross profit",
  "upd.m.net_profit": "Net profit",
  "upd.m.cash": "Cash",
  "upd.m.customers": "Customers",
  "upd.m.headcount": "Team size",
  "upd.unit.aud": "A$",
  "upd.unit.count": "number",

  // cadence + status
  "upd.cad.weekly": "Weekly",
  "upd.cad.monthly": "Monthly",
  "upd.cad.quarterly": "Quarterly",
  "upd.cad.annual": "Yearly",
  "upd.st.draft": "Draft",
  "upd.st.pending_approval": "Waiting for approval",
  "upd.st.publishing": "Being recorded",
  "upd.st.published": "Published",
  "upd.st.rejected": "Sent back",
  "upd.st.failed": "Not recorded yet",

  // founder form
  "upd.f.h": "Prepare an update",
  "upd.f.p": "Enter this period's numbers. We compare them with the previous period and write a first draft in plain words. You can edit it before sending it for approval.",
  "upd.f.cadence": "How often",
  "upd.f.end": "Period ends on",
  "upd.f.note": "Note for shareholders (optional)",
  "upd.f.notePh": "What happened this period, in your own words",
  "upd.f.prepare": "Prepare update",
  "upd.f.prepared": "Draft ready. Check it below, edit the words if you like, then send it for approval.",
  "upd.f.need": "Enter at least one number.",
  "upd.f.loaded": "Numbers already entered for this period are filled in.",
  "upd.f.onlylive": "Updates start once the shares are issued.",
  "upd.f.viewer": "Published updates of this business. Company admins prepare them; a person approves each one before it is shown.",

  // lists + drafts
  "upd.list.h": "Updates",
  "upd.list.mine": "All updates, including drafts (only company admins see drafts)",
  "upd.list.empty": "No updates yet.",
  "upd.edit.title": "Title",
  "upd.edit.summary": "Summary",
  "upd.edit.save": "Save changes",
  "upd.edit.saved": "Saved.",
  "upd.send": "Send for approval",
  "upd.sent": "Sent. A person will check it before it is published.",
  "upd.rejected": "Sent back: {r}",
  "upd.failed": "Approved, but not recorded yet: {e}",
  "upd.open": "Open",
  "upd.by": "Prepared by {w}",

  // update body
  "upd.period": "{c} · {p}",
  "upd.highlights": "Highlights",
  "upd.risks": "Things to watch",
  "upd.norisks": "Nothing flagged from the numbers.",
  "upd.note": "Note from the business",
  "upd.kpi.h": "Key numbers",
  "upd.kpi.metric": "Measure",
  "upd.kpi.now": "This period",
  "upd.kpi.prev": "Previous",
  "upd.kpi.chg": "Change",
  "upd.kpi.new": "new",
  "upd.published": "Published {d}",
  "upd.selfrep": "Numbers are reported by the business and checked by a person before publishing. They are not audited.",

  // proof
  "upd.rec.h": "Recorded on blockchain",
  "upd.rec.p": "When this update was approved, its digital fingerprint was recorded on BlockID Chain. If anyone changes a single word or number, the fingerprint no longer matches.",
  "upd.rec.tx": "See the record",
  "upd.rec.block": "block {b}",
  "upd.rec.fp": "Fingerprint",
  "upd.rec.none": "Not recorded yet.",
  "upd.chk.btn": "Check this update",
  "upd.chk.busy": "Checking…",
  "upd.chk.text": "The text and numbers shown here are the ones that were approved",
  "upd.chk.fp": "Your browser worked out the same fingerprint",
  "upd.chk.chain": "The same fingerprint is in the record on blockchain",
  "upd.chk.chainSkip": "The blockchain record could not be read right now",
  "upd.chk.ok": "Everything matches. This update has not been changed since it was approved.",
  "upd.chk.bad": "Something does not match. Treat this update with care and contact the business.",

  // investor portal
  "upd.feed.h": "Latest updates",
  "upd.feed.p": "News from the businesses you own shares in, approved by a person before it is shown.",
  "upd.feed.empty": "No updates from your businesses yet.",
  "upd.pos.h": "Business updates",
  "upd.pos.empty": "This business has not published an update yet.",
  "upd.page.back": "Back",
  "upd.page.missing": "This update does not exist or is not published.",
  "upd.legal": "Testnet demo. Figures are reported by the business, checked by a person and not audited. Not an offer of securities or financial advice.",

  // admin
  "upd.ad.p": "Read the whole update. Approving records its fingerprint on blockchain and shows it to every shareholder; it cannot be changed afterwards.",
  "upd.ad.reason": "Reason (shown to the business if you send it back)",
  "upd.ad.approve": "Approve and publish",
  "upd.ad.reject": "Send back",
  "upd.ad.rejected": "Sent back to the business.",
  "upd.ad.published": "Approved. It is being recorded on blockchain and will appear for shareholders in a few seconds.",
};

export const updVi: Record<keyof typeof updEn, string> = {
  "ws.updates": "Cập nhật",
  "ws.d.updates": "Cập nhật kinh doanh định kỳ cho cổ đông: nhập số liệu, kiểm tra bản nháp, gửi đi để phê duyệt.",
  "ad.q.updates": "Cập nhật kinh doanh",
  "ad.d.updates": "Các cập nhật kinh doanh đang chờ một người phê duyệt. Khi duyệt, cập nhật được ghi lên blockchain và hiển thị cho mọi cổ đông.",
  "ev.update_published": "Đã công bố cập nhật kinh doanh",

  "upd.m.revenue": "Doanh thu",
  "upd.m.gross_profit": "Lợi nhuận gộp",
  "upd.m.net_profit": "Lợi nhuận ròng",
  "upd.m.cash": "Tiền mặt",
  "upd.m.customers": "Khách hàng",
  "upd.m.headcount": "Số nhân sự",
  "upd.unit.aud": "A$",
  "upd.unit.count": "số lượng",

  "upd.cad.weekly": "Hằng tuần",
  "upd.cad.monthly": "Hằng tháng",
  "upd.cad.quarterly": "Hằng quý",
  "upd.cad.annual": "Hằng năm",
  "upd.st.draft": "Bản nháp",
  "upd.st.pending_approval": "Đang chờ phê duyệt",
  "upd.st.publishing": "Đang ghi nhận",
  "upd.st.published": "Đã công bố",
  "upd.st.rejected": "Bị trả lại",
  "upd.st.failed": "Chưa ghi nhận được",

  "upd.f.h": "Soạn cập nhật",
  "upd.f.p": "Nhập số liệu của kỳ này. Chúng tôi so sánh với kỳ trước và viết bản nháp đầu tiên bằng lời lẽ dễ hiểu. Bạn có thể sửa trước khi gửi đi phê duyệt.",
  "upd.f.cadence": "Tần suất",
  "upd.f.end": "Kỳ kết thúc vào",
  "upd.f.note": "Ghi chú cho cổ đông (không bắt buộc)",
  "upd.f.notePh": "Điều gì đã diễn ra trong kỳ này, theo lời của bạn",
  "upd.f.prepare": "Soạn cập nhật",
  "upd.f.prepared": "Bản nháp đã sẵn sàng. Hãy kiểm tra bên dưới, sửa lời nếu muốn, rồi gửi đi phê duyệt.",
  "upd.f.need": "Hãy nhập ít nhất một con số.",
  "upd.f.loaded": "Các số liệu đã nhập cho kỳ này được điền sẵn.",
  "upd.f.onlylive": "Cập nhật bắt đầu sau khi cổ phần được phát hành.",
  "upd.f.viewer": "Các cập nhật đã công bố của doanh nghiệp này. Quản trị viên công ty soạn, và một người duyệt từng bản trước khi hiển thị.",

  "upd.list.h": "Các cập nhật",
  "upd.list.mine": "Tất cả cập nhật, kể cả bản nháp (chỉ quản trị viên công ty thấy bản nháp)",
  "upd.list.empty": "Chưa có cập nhật nào.",
  "upd.edit.title": "Tiêu đề",
  "upd.edit.summary": "Tóm tắt",
  "upd.edit.save": "Lưu thay đổi",
  "upd.edit.saved": "Đã lưu.",
  "upd.send": "Gửi đi phê duyệt",
  "upd.sent": "Đã gửi. Một người sẽ kiểm tra trước khi công bố.",
  "upd.rejected": "Bị trả lại: {r}",
  "upd.failed": "Đã duyệt nhưng chưa ghi nhận được: {e}",
  "upd.open": "Mở",
  "upd.by": "Soạn bởi {w}",

  "upd.period": "{c} · {p}",
  "upd.highlights": "Điểm nổi bật",
  "upd.risks": "Điều cần lưu ý",
  "upd.norisks": "Số liệu không cho thấy điều gì đáng lo.",
  "upd.note": "Ghi chú từ doanh nghiệp",
  "upd.kpi.h": "Số liệu chính",
  "upd.kpi.metric": "Chỉ số",
  "upd.kpi.now": "Kỳ này",
  "upd.kpi.prev": "Kỳ trước",
  "upd.kpi.chg": "Thay đổi",
  "upd.kpi.new": "mới",
  "upd.published": "Công bố {d}",
  "upd.selfrep": "Số liệu do doanh nghiệp cung cấp và được một người kiểm tra trước khi công bố. Số liệu chưa được kiểm toán.",

  "upd.rec.h": "Đã ghi nhận trên blockchain",
  "upd.rec.p": "Khi cập nhật này được duyệt, dấu vân tay số của nó đã được ghi lên BlockID Chain. Nếu ai đó sửa dù chỉ một chữ hay một con số, dấu vân tay sẽ không còn khớp.",
  "upd.rec.tx": "Xem bản ghi",
  "upd.rec.block": "khối {b}",
  "upd.rec.fp": "Dấu vân tay",
  "upd.rec.none": "Chưa được ghi nhận.",
  "upd.chk.btn": "Kiểm tra cập nhật này",
  "upd.chk.busy": "Đang kiểm tra…",
  "upd.chk.text": "Nội dung và số liệu hiển thị ở đây đúng là bản đã được duyệt",
  "upd.chk.fp": "Trình duyệt của bạn tính ra cùng một dấu vân tay",
  "upd.chk.chain": "Bản ghi trên blockchain có cùng dấu vân tay",
  "upd.chk.chainSkip": "Hiện chưa đọc được bản ghi trên blockchain",
  "upd.chk.ok": "Mọi thứ đều khớp. Cập nhật này không bị thay đổi kể từ khi được duyệt.",
  "upd.chk.bad": "Có điểm không khớp. Hãy thận trọng với cập nhật này và liên hệ doanh nghiệp.",

  "upd.feed.h": "Cập nhật mới nhất",
  "upd.feed.p": "Tin từ các doanh nghiệp bạn có cổ phần, được một người duyệt trước khi hiển thị.",
  "upd.feed.empty": "Chưa có cập nhật nào từ các doanh nghiệp của bạn.",
  "upd.pos.h": "Cập nhật kinh doanh",
  "upd.pos.empty": "Doanh nghiệp này chưa công bố cập nhật nào.",
  "upd.page.back": "Quay lại",
  "upd.page.missing": "Cập nhật này không tồn tại hoặc chưa được công bố.",
  "upd.legal": "Bản demo testnet. Số liệu do doanh nghiệp cung cấp, được một người kiểm tra và chưa được kiểm toán. Không phải chào bán chứng khoán hay tư vấn tài chính.",

  "upd.ad.p": "Đọc toàn bộ cập nhật. Khi duyệt, dấu vân tay của nó được ghi lên blockchain và cập nhật hiển thị cho mọi cổ đông; sau đó không thể thay đổi.",
  "upd.ad.reason": "Lý do (hiển thị cho doanh nghiệp nếu bạn trả lại)",
  "upd.ad.approve": "Duyệt và công bố",
  "upd.ad.reject": "Trả lại",
  "upd.ad.rejected": "Đã trả lại cho doanh nghiệp.",
  "upd.ad.published": "Đã duyệt. Cập nhật đang được ghi lên blockchain và sẽ hiện cho cổ đông sau vài giây.",
};
