/**
 * Admin "Operations" screen (/admin/ops/:tab, docs/PLAN-OPS.md §1–5; API agents/src/blockid_agents/ops/). Plain words.
 * VI must cover every EN key (checked by the type).
 */
export const opsEn = {
  "ad.nav.ops": "Operations",
  "ad.t.ops": "Operations",
  "ad.d.ops": "Incidents with step-by-step fixes, traffic and users, server errors and the weekly report to admin@blockid.au.",
  "ops.tab.overview": "Overview",
  "ops.tab.incidents": "Incidents",
  "ops.tab.traffic": "Traffic & users",
  "ops.tab.errors": "Errors",
  "ops.tab.reports": "Weekly reports",
  "ops.none": "No data yet.",
  "ops.err.stale": "The latest refresh failed — showing the last data received.",

  "ops.sb.ok": "All checks passing",
  "ops.sb.open": "{c} critical · {w} warning open",
  "ops.sb.meta": "Updated {s} s ago · refreshes every 30 s",
  "ops.sb.see": "See incidents",
  "ops.s.open": "Open incidents",
  "ops.s.check": "Last health check",
  "ops.s.never": "Not run yet",
  "ops.s.mail": "E-mail alerts",
  "ops.s.nosmtp": "SMTP not configured",
  "ops.s.nosmtp.d": "Incidents and reports are stored here but not e-mailed ({n} waiting).",
  "ops.s.runbook": "How to set it up",
  "ops.s.mailok": "Delivering to {to}",

  "ops.k.visitors": "Visitors (7 days)",
  "ops.k.views": "Page views (7 days)",
  "ops.k.users": "Registered users",
  "ops.k.new7": "+{n} new in 7 days",
  "ops.k.active": "Active users (7 days)",
  "ops.k.vals": "Valuations this week",
  "ops.k.hr": "HR reports this week",
  "ops.k.ai": "AI spend today",
  "ops.k.vsweek": "vs last week",
  "ops.k.vsday": "vs yesterday",
  "ops.k.new": "new",
  "ops.o.open": "Needs attention",
  "ops.o.all": "All incidents",
  "ops.o.none": "Nothing open. Every check is passing.",

  "ops.sev.critical": "Critical",
  "ops.sev.warn": "Warning",
  "ops.sev.info": "Info",
  "ops.st.open": "Open",
  "ops.st.acknowledged": "Acknowledged",
  "ops.st.resolved": "Resolved",
  "ops.i.filter": "Show incidents",
  "ops.i.f.open": "Open ({n})",
  "ops.i.f.resolved": "Resolved",
  "ops.i.f.all": "All",
  "ops.i.empty": "No incidents in this list.",
  "ops.i.sev": "Severity",
  "ops.i.title": "What happened",
  "ops.i.status": "Status",
  "ops.i.since": "Since",
  "ops.i.seen": "Last seen",
  "ops.i.count": "Times seen",
  "ops.d.close": "Close",
  "ops.d.impact": "Impact",
  "ops.d.auto": "automatically (check passing again)",
  "ops.d.ack": "Acknowledge",
  "ops.d.acked": "Acknowledged — reminders are paused while you work on it.",
  "ops.d.note": "Note for the timeline (optional)",
  "ops.d.resolve": "Mark resolved",
  "ops.d.resolved": "Marked resolved. If the check fails again a new incident opens.",
  "ops.d.resolve.h": "Acknowledge stops the 2-hour reminder e-mails. Resolve closes the incident and sends a “resolved” e-mail.",
  "ops.d.fix": "How to fix it",
  "ops.d.runbook": "Full runbook",
  "ops.d.nofix": "No runbook steps for this check yet.",
  "ops.d.details": "Details",
  "ops.d.timeline": "Timeline",
  "ops.d.emails": "E-mails",
  "ops.d.noemail": "No e-mail for this incident.",
  "ops.tl.opened": "Opened",
  "ops.tl.acknowledged": "Acknowledged",
  "ops.tl.resolved": "Resolved",
  "ops.tl.reopened": "Opened again",
  "ops.tl.reminder": "Reminder",
  "ops.tl.seen": "Seen again",
  "ops.mail.sent": "Sent",
  "ops.mail.failed": "Failed",
  "ops.mail.pending": "Waiting",
  "ops.mail.not_configured": "Not e-mailed — SMTP not configured",
  "ops.mk.open": "New incident",
  "ops.mk.reminder": "Reminder",

  "ops.t.range": "Time range",
  "ops.t.d": "{n} days",
  "ops.t.parsed": "Logs read at {t}",
  "ops.t.traffic": "Traffic per site, last {n} days",
  "ops.t.table": "Show as table",
  "ops.t.chart": "Show as chart",
  "ops.t.date": "Date",
  "ops.t.vis": "visitors",
  "ops.t.visitors": "Unique visitors per day",
  "ops.t.views": "Page views per day",
  "ops.t.note": "From the nginx access logs. Visitors are counted with a daily-salted hash of the IP; raw IPs are never stored.",
  "ops.t.bots": "{n} bot requests filtered out.",
  "ops.t.pages": "Top pages",
  "ops.t.page": "Page",
  "ops.t.refs": "Top referrers",
  "ops.t.ref": "Came from",
  "ops.t.countries": "Countries",
  "ops.t.country": "Country",
  "ops.u.accounts": "Accounts (Google)",
  "ops.u.wallets": "Linked wallets",
  "ops.u.a7": "Active users · 7 days",
  "ops.u.a30": "Active users · 30 days",
  "ops.u.reg": "New registrations per day",
  "ops.u.method": "Method",
  "ops.u.count": "Sign-ins",
  "ops.m.google": "Google",
  "ops.m.guest": "Guest wallet",
  "ops.m.demo": "Demo",
  "ops.m.password": "Admin password",
  "ops.p.h": "Product activity",
  "ops.p.what": "Activity",
  "ops.p.valuations_started": "Valuations started",
  "ops.p.valuations_finished": "Valuations finished",
  "ops.p.hr_reports": "HR reports",
  "ops.p.offerings": "Offerings",
  "ops.p.dividends": "Dividends",

  "ops.e.24h": "24 h",
  "ops.e.n": "{n} kinds of error · {c} in total",
  "ops.e.none": "No server errors in this period.",
  "ops.e.first": "first {t}",
  "ops.e.last": "last {t}",
  "ops.e.req": "Example request id:",
  "ops.e.stack": "Stack trace",
  "ops.e.copy": "Copy",
  "ops.e.copied": "Copied",
  "ops.e.nostack": "No stack trace was recorded for this error.",
  "ops.e.adminonly": "Stack traces are shown to platform admins only.",
  "ops.e.keep": "Errors with the same cause are grouped by fingerprint. Kept for 30 days.",

  "ops.r.h": "Weekly report",
  "ops.r.sched": "Sent every Monday at 08:00 (Sydney) to admin@blockid.au: traffic, users, product activity, incidents, AI spend, wallet balances, top errors and recommended actions.",
  "ops.r.send": "Send now",
  "ops.r.test": "Send test email",
  "ops.r.sending": "Sending…",
  "ops.r.sent": "Report sent to {to}.",
  "ops.r.tested": "Test e-mail sent to {to}. Check the inbox (and spam).",
  "ops.r.nosmtp": "Stored, but not e-mailed: SMTP is not configured.",
  "ops.r.test.nosmtp": "Not sent: SMTP is not configured.",
  "ops.r.fail": "Could not send: {e}",
  "ops.r.hist": "History",
  "ops.r.none": "No report yet. The first one is made next Monday, or press “Send now”.",
  "ops.r.week": "Week of {d}",
  "ops.r.sentat": "sent {t}",
  "ops.r.madeat": "made {t}",
  "ops.r.preview": "Preview",
  "ops.r.nohtml": "This report has no HTML version.",
  "ops.s.acked": "{n} of them acknowledged and being worked on",
  "ops.s.checks": "{n} checks · {f} failing",
  "ops.s.errors": "{n} server errors in 24 h",
  "ops.s.disabled": "The ops monitor is switched off (OPS_ENABLED=0): no checks run and nothing is e-mailed.",
  "ops.s.unsent": "{n} not sent yet",
  "ops.s.lastrep": "last report e-mailed {t}",
  "ops.s.lastrep.no": "last report {t} was not e-mailed",
  "ops.s.norep": "no report yet",
  "ops.err.kpi": "Some numbers could not be loaded — tiles show what is available.",
  "ops.k.nochange": "no change",
  "ops.k.wallets": "{n} wallets linked",
  "ops.k.started": "{n} started",
  "ops.k.budget": "daily budget {b}",
  "ops.k.nobudget": "no daily budget set",
  "ops.o.gen": "Data as of {t}",
  "ops.c.h": "Health checks",
  "ops.c.n": "{ok} of {n} passing",
  "ops.c.all": "Show all checks",
  "ops.c.problems": "Show problems only",
  "ops.c.allok": "Every check is passing.",
  "ops.c.inc": "Open incident",
  "ops.c.follower": "this API process is not the monitor leader; another process runs the checks",
  "ops.cs.ok": "OK",
  "ops.cs.warn": "Warning",
  "ops.cs.critical": "Critical",
  "ops.cs.info": "Info",
  "ops.cs.unknown": "Not checked",
  "ops.tl.escalated": "Got worse",
  "ops.tl.emailed": "E-mailed",
  "ops.tl.email_failed": "E-mail failed",
  "ops.t.pvs": "views",
  "ops.t.visits": "Visits",
  "ops.t.unavail": "The nginx access logs are not readable by the API yet, so traffic is not counted. See the runbook (traffic logs).",
  "ops.t.empty": "No traffic recorded in this period yet.",
  "ops.u.signins": "Sign-ins by method ({n} days)",
  "ops.u.in7": "· {n} in 7 days",
  "ops.u.newn": "+{n} in {d} days",
  "ops.u.signedin": "{n} signed in within {d} days",
  "ops.u.today": "{n} today",
  "ops.u.reg.acc": "Google accounts",
  "ops.u.reg.wal": "New wallets",
  "ops.m.wallet": "Wallet (MetaMask)",
  "ops.p.week": "Last 7 days",
  "ops.p.total": "Total",
  "ops.p.valuations_failed": "Valuations failed",
  "ops.p.companies": "Companies created",
  "ops.p.note": "{r} valuations queued or running now · {a} admin actions in 7 days.",
  "ops.r.day": "Daily digest {d}",
  "ops.r.manual": "sent by hand",
};

export const opsVi: Record<keyof typeof opsEn, string> = {
  "ad.nav.ops": "Vận hành",
  "ad.t.ops": "Vận hành",
  "ad.d.ops": "Sự cố kèm cách khắc phục từng bước, lượt truy cập và người dùng, lỗi máy chủ và báo cáo hằng tuần gửi admin@blockid.au.",
  "ops.tab.overview": "Tổng quan",
  "ops.tab.incidents": "Sự cố",
  "ops.tab.traffic": "Truy cập & người dùng",
  "ops.tab.errors": "Lỗi",
  "ops.tab.reports": "Báo cáo tuần",
  "ops.none": "Chưa có dữ liệu.",
  "ops.err.stale": "Lần làm mới gần nhất bị lỗi — đang hiển thị dữ liệu nhận được trước đó.",

  "ops.sb.ok": "Mọi kiểm tra đều đạt",
  "ops.sb.open": "{c} nghiêm trọng · {w} cảnh báo đang mở",
  "ops.sb.meta": "Cập nhật {s} giây trước · tự làm mới mỗi 30 giây",
  "ops.sb.see": "Xem sự cố",
  "ops.s.open": "Sự cố đang mở",
  "ops.s.check": "Lần kiểm tra gần nhất",
  "ops.s.never": "Chưa chạy",
  "ops.s.mail": "Cảnh báo qua e-mail",
  "ops.s.nosmtp": "Chưa cấu hình SMTP",
  "ops.s.nosmtp.d": "Sự cố và báo cáo được lưu ở đây nhưng chưa gửi e-mail ({n} đang chờ).",
  "ops.s.runbook": "Cách thiết lập",
  "ops.s.mailok": "Đang gửi tới {to}",

  "ops.k.visitors": "Khách truy cập (7 ngày)",
  "ops.k.views": "Lượt xem trang (7 ngày)",
  "ops.k.users": "Người dùng đã đăng ký",
  "ops.k.new7": "+{n} mới trong 7 ngày",
  "ops.k.active": "Người dùng hoạt động (7 ngày)",
  "ops.k.vals": "Định giá tuần này",
  "ops.k.hr": "Báo cáo nhân sự tuần này",
  "ops.k.ai": "Chi phí AI hôm nay",
  "ops.k.vsweek": "so với tuần trước",
  "ops.k.vsday": "so với hôm qua",
  "ops.k.new": "mới",
  "ops.o.open": "Cần xử lý",
  "ops.o.all": "Tất cả sự cố",
  "ops.o.none": "Không có sự cố nào đang mở. Mọi kiểm tra đều đạt.",

  "ops.sev.critical": "Nghiêm trọng",
  "ops.sev.warn": "Cảnh báo",
  "ops.sev.info": "Thông tin",
  "ops.st.open": "Đang mở",
  "ops.st.acknowledged": "Đã xác nhận",
  "ops.st.resolved": "Đã xử lý",
  "ops.i.filter": "Lọc sự cố",
  "ops.i.f.open": "Đang mở ({n})",
  "ops.i.f.resolved": "Đã xử lý",
  "ops.i.f.all": "Tất cả",
  "ops.i.empty": "Không có sự cố nào trong danh sách này.",
  "ops.i.sev": "Mức độ",
  "ops.i.title": "Chuyện gì xảy ra",
  "ops.i.status": "Trạng thái",
  "ops.i.since": "Từ lúc",
  "ops.i.seen": "Thấy lần cuối",
  "ops.i.count": "Số lần",
  "ops.d.close": "Đóng",
  "ops.d.impact": "Ảnh hưởng",
  "ops.d.auto": "tự động (kiểm tra đã đạt lại)",
  "ops.d.ack": "Xác nhận",
  "ops.d.acked": "Đã xác nhận — tạm dừng e-mail nhắc trong lúc bạn xử lý.",
  "ops.d.note": "Ghi chú cho dòng thời gian (không bắt buộc)",
  "ops.d.resolve": "Đánh dấu đã xử lý",
  "ops.d.resolved": "Đã đánh dấu xử lý. Nếu kiểm tra lỗi lại, một sự cố mới sẽ được mở.",
  "ops.d.resolve.h": "Xác nhận sẽ dừng e-mail nhắc mỗi 2 giờ. Đánh dấu đã xử lý sẽ đóng sự cố và gửi e-mail “đã xử lý”.",
  "ops.d.fix": "Cách khắc phục",
  "ops.d.runbook": "Runbook đầy đủ",
  "ops.d.nofix": "Chưa có các bước khắc phục cho mục kiểm tra này.",
  "ops.d.details": "Chi tiết",
  "ops.d.timeline": "Dòng thời gian",
  "ops.d.emails": "E-mail",
  "ops.d.noemail": "Chưa có e-mail nào cho sự cố này.",
  "ops.tl.opened": "Mở",
  "ops.tl.acknowledged": "Đã xác nhận",
  "ops.tl.resolved": "Đã xử lý",
  "ops.tl.reopened": "Mở lại",
  "ops.tl.reminder": "Nhắc lại",
  "ops.tl.seen": "Lại xuất hiện",
  "ops.mail.sent": "Đã gửi",
  "ops.mail.failed": "Gửi lỗi",
  "ops.mail.pending": "Đang chờ",
  "ops.mail.not_configured": "Chưa gửi — chưa cấu hình SMTP",
  "ops.mk.open": "Sự cố mới",
  "ops.mk.reminder": "Nhắc lại",

  "ops.t.range": "Khoảng thời gian",
  "ops.t.d": "{n} ngày",
  "ops.t.parsed": "Đọc log lúc {t}",
  "ops.t.traffic": "Lượt truy cập theo trang web, {n} ngày qua",
  "ops.t.table": "Xem dạng bảng",
  "ops.t.chart": "Xem dạng biểu đồ",
  "ops.t.date": "Ngày",
  "ops.t.vis": "khách",
  "ops.t.visitors": "Khách truy cập duy nhất mỗi ngày",
  "ops.t.views": "Lượt xem trang mỗi ngày",
  "ops.t.note": "Lấy từ log truy cập nginx. Khách được đếm bằng mã băm IP có muối thay đổi theo ngày; không bao giờ lưu IP gốc.",
  "ops.t.bots": "Đã lọc bỏ {n} yêu cầu của bot.",
  "ops.t.pages": "Trang được xem nhiều nhất",
  "ops.t.page": "Trang",
  "ops.t.refs": "Nguồn giới thiệu hàng đầu",
  "ops.t.ref": "Đến từ",
  "ops.t.countries": "Quốc gia",
  "ops.t.country": "Quốc gia",
  "ops.u.accounts": "Tài khoản (Google)",
  "ops.u.wallets": "Ví đã liên kết",
  "ops.u.a7": "Người dùng hoạt động · 7 ngày",
  "ops.u.a30": "Người dùng hoạt động · 30 ngày",
  "ops.u.reg": "Đăng ký mới mỗi ngày",
  "ops.u.method": "Cách thức",
  "ops.u.count": "Lượt đăng nhập",
  "ops.m.google": "Google",
  "ops.m.guest": "Ví khách",
  "ops.m.demo": "Demo",
  "ops.m.password": "Mật khẩu quản trị",
  "ops.p.h": "Hoạt động sản phẩm",
  "ops.p.what": "Hoạt động",
  "ops.p.valuations_started": "Định giá đã bắt đầu",
  "ops.p.valuations_finished": "Định giá đã hoàn tất",
  "ops.p.hr_reports": "Báo cáo nhân sự",
  "ops.p.offerings": "Đợt chào bán",
  "ops.p.dividends": "Cổ tức",

  "ops.e.24h": "24 giờ",
  "ops.e.n": "{n} loại lỗi · tổng {c} lần",
  "ops.e.none": "Không có lỗi máy chủ trong khoảng thời gian này.",
  "ops.e.first": "lần đầu {t}",
  "ops.e.last": "lần cuối {t}",
  "ops.e.req": "Mã yêu cầu ví dụ:",
  "ops.e.stack": "Stack trace",
  "ops.e.copy": "Sao chép",
  "ops.e.copied": "Đã sao chép",
  "ops.e.nostack": "Không ghi lại stack trace cho lỗi này.",
  "ops.e.adminonly": "Stack trace chỉ hiển thị cho quản trị viên nền tảng.",
  "ops.e.keep": "Các lỗi cùng nguyên nhân được gộp theo dấu vân tay (fingerprint). Lưu trong 30 ngày.",

  "ops.r.h": "Báo cáo hằng tuần",
  "ops.r.sched": "Gửi mỗi thứ Hai lúc 08:00 (giờ Sydney) tới admin@blockid.au: lượt truy cập, người dùng, hoạt động sản phẩm, sự cố, chi phí AI, số dư ví, lỗi hàng đầu và việc nên làm.",
  "ops.r.send": "Gửi ngay",
  "ops.r.test": "Gửi e-mail thử",
  "ops.r.sending": "Đang gửi…",
  "ops.r.sent": "Đã gửi báo cáo tới {to}.",
  "ops.r.tested": "Đã gửi e-mail thử tới {to}. Hãy kiểm tra hộp thư (và thư rác).",
  "ops.r.nosmtp": "Đã lưu nhưng chưa gửi e-mail: chưa cấu hình SMTP.",
  "ops.r.test.nosmtp": "Chưa gửi được: chưa cấu hình SMTP.",
  "ops.r.fail": "Không gửi được: {e}",
  "ops.r.hist": "Lịch sử",
  "ops.r.none": "Chưa có báo cáo. Báo cáo đầu tiên sẽ được tạo vào thứ Hai tới, hoặc bấm “Gửi ngay”.",
  "ops.r.week": "Tuần từ {d}",
  "ops.r.sentat": "gửi {t}",
  "ops.r.madeat": "tạo {t}",
  "ops.r.preview": "Xem trước",
  "ops.r.nohtml": "Báo cáo này không có bản HTML.",
  "ops.s.acked": "{n} sự cố đã được xác nhận và đang xử lý",
  "ops.s.checks": "{n} mục kiểm tra · {f} đang lỗi",
  "ops.s.errors": "{n} lỗi máy chủ trong 24 giờ",
  "ops.s.disabled": "Bộ giám sát vận hành đang tắt (OPS_ENABLED=0): không chạy kiểm tra và không gửi e-mail.",
  "ops.s.unsent": "{n} chưa gửi",
  "ops.s.lastrep": "báo cáo gần nhất đã gửi {t}",
  "ops.s.lastrep.no": "báo cáo gần nhất ({t}) chưa được gửi",
  "ops.s.norep": "chưa có báo cáo",
  "ops.err.kpi": "Không tải được một số số liệu — các ô hiển thị phần có sẵn.",
  "ops.k.nochange": "không đổi",
  "ops.k.wallets": "{n} ví đã liên kết",
  "ops.k.started": "{n} đã bắt đầu",
  "ops.k.budget": "ngân sách ngày {b}",
  "ops.k.nobudget": "chưa đặt ngân sách ngày",
  "ops.o.gen": "Dữ liệu tính đến {t}",
  "ops.c.h": "Các mục kiểm tra",
  "ops.c.n": "{ok} / {n} đạt",
  "ops.c.all": "Xem tất cả",
  "ops.c.problems": "Chỉ xem mục có vấn đề",
  "ops.c.allok": "Mọi mục kiểm tra đều đạt.",
  "ops.c.inc": "Mở sự cố",
  "ops.c.follower": "tiến trình API này không giữ khoá giám sát; một tiến trình khác đang chạy kiểm tra",
  "ops.cs.ok": "Đạt",
  "ops.cs.warn": "Cảnh báo",
  "ops.cs.critical": "Nghiêm trọng",
  "ops.cs.info": "Thông tin",
  "ops.cs.unknown": "Chưa kiểm tra",
  "ops.tl.escalated": "Nặng hơn",
  "ops.tl.emailed": "Đã gửi e-mail",
  "ops.tl.email_failed": "Gửi e-mail lỗi",
  "ops.t.pvs": "lượt xem",
  "ops.t.visits": "Lượt truy cập",
  "ops.t.unavail": "API chưa đọc được log truy cập nginx nên chưa đếm lượt truy cập. Xem runbook (traffic logs).",
  "ops.t.empty": "Chưa ghi nhận lượt truy cập nào trong khoảng này.",
  "ops.u.signins": "Đăng nhập theo cách thức ({n} ngày)",
  "ops.u.in7": "· {n} trong 7 ngày",
  "ops.u.newn": "+{n} trong {d} ngày",
  "ops.u.signedin": "{n} đã đăng nhập trong {d} ngày",
  "ops.u.today": "{n} hôm nay",
  "ops.u.reg.acc": "Tài khoản Google",
  "ops.u.reg.wal": "Ví mới",
  "ops.m.wallet": "Ví (MetaMask)",
  "ops.p.week": "7 ngày qua",
  "ops.p.total": "Tổng",
  "ops.p.valuations_failed": "Định giá bị lỗi",
  "ops.p.companies": "Doanh nghiệp được tạo",
  "ops.p.note": "{r} định giá đang chờ hoặc đang chạy · {a} thao tác quản trị trong 7 ngày.",
  "ops.r.day": "Bản tin ngày {d}",
  "ops.r.manual": "gửi thủ công",
};
