/** Plan v3 phase 1 strings: two-path home, link check, status bar, compact notes. VI must cover every EN key. */
export const v3En = {
  "cta.list": "List on blockchain",
  "hv.demoChip": "You're in the demo account",
  "hv.demoChip.tip": "Shared with every visitor. Sign in any time to use your own wallet.",
  "hv.paths.eyebrow": "Two ways to use BlockID",
  "hv.paths.h2": "For investors and for businesses.",
  "hv.paths.p": "The same records serve both sides, so what the business reports is what every investor sees.",
  "hv.pi.h": "For investors",
  "hv.pi.p": "Check a business before you invest, and follow it after.",
  "hv.pi.1": "Pick a business, or paste its website",
  "hv.pi.2": "Read a plain report with a fair value approved by a person",
  "hv.pi.3": "Hold your shares in your own wallet",
  "hv.pi.4": "Get the same updates and dividends as every other investor",
  "hv.pb.h": "For businesses",
  "hv.pb.p": "List your business and turn its shares into tokens on blockchain.",
  "hv.pb.1": "Paste your website and, if you like, your numbers",
  "hv.pb.2": "Get a fair value, approved by a person",
  "hv.pb.3": "Set up your shares and shareholders",
  "hv.pb.4": "List on blockchain and update every investor at once",
  "hv.pi.cta": "Evaluate a business",
  "hv.pb.cta": "List on blockchain",
  "new.eyebrow.list": "List on blockchain",
  "new.h2.list": "List your business on blockchain",
  "new.p.list": "Start with your website. We set a fair value that a person approves, then create your shares on blockchain so every investor gets the same updates at the same time.",
  "url.checking": "Checking the link…",
  "url.empty": "Enter the business's website address.",
  "url.spaces": "A website address cannot contain spaces.",
  "url.bad_url": "This is not a website address. Try something like example.com.au.",
  "url.no_tld": "The address needs a domain ending, like .com or .com.au.",
  "url.ip": "Use the business's domain name, not an IP address.",
  "url.not_public": "This address is not a public website.",
  "url.lookalike": "This address uses look-alike letters, so it may not be the site you mean.",
  "url.dns": "We couldn't find this website. Check the spelling.",
  "url.unreachable": "We couldn't open this website. Check the address or try again later.",
  "url.http_error": "The website answered with an error page. Check the address.",
  "url.rate": "Too many link checks. Wait a minute and try again.",
  "url.didyou": "Did you mean {h}?",
  "url.use": "Use {h}",
  "sb.label": "Status",
  "sb.step": "Step {n} of {N}",
  "sb.elapsed": "{t} so far",
  "sb.st.queued": "Queued",
  "sb.st.researching": "Researching",
  "sb.st.waiting": "Waiting for approval",
  "sb.st.approved": "Approved",
  "sb.st.rejected": "Rejected",
  "sb.st.failed": "Failed",
  "sb.st.draft": "Draft",
  "sb.st.creating": "Creating shares",
  "sb.st.copying": "Copying to public chains",
  "sb.st.live": "Live",
  "sb.st.private": "Private",
  "sb.st.sample": "Sample",
  "sb.st.demo": "Demo account",
  "sb.st.mine": "Your wallet",
  "sb.next.approve": "Approve it yourself (demo)",
  "sb.next.retry": "Try again",
  "sb.pf.meta": "{n} businesses · {v}",
  "sb.pf.signin": "Use your own wallet",
  "v.score": "Business score {s}",
  "v.notes": "Notes ({n})",
  "v.notes.p": "Things the research could not confirm. A person reads these before approving.",
  "v.site.h": "We couldn't read this website",
  "v.site.p": "The site may block visitors, be down, or the link may be wrong. Check the link and try again.",
  "v.site.btn": "Check the link and try again",
  "v.stopped": "The evaluation stopped: {e}",
  "v.private.h": "This evaluation is private",
  "v.private.p": "Only the account that asked for it can see it, until the business is listed.",
  "v.private.btn": "Start your own evaluation",
  "demo.chip": "Demo",
  "demo.chip.p": "Sign in as admin / admin and press “{a}”.",
  "demo.chip.btn": "Approve it yourself",
  "lb.quiet": "Low fee balance on {n} wallet(s). The step may pause until it is topped up.",
  "lb.quiet.link": "Top up",
  "in.chip.sample": "Sample data",
  "in.chip.demo": "Demo account · shared with every visitor",
  "tk.checking": "Checking {t}…",
  "tk.ok": "{t} is free to use.",
  "tk.taken": "{t} is already used by another company. Choose another code.",
  "tk.reserved": "{t} is a reserved word. Choose another code.",
  "tk.format": "Use exactly 3 letters A–Z.",
  "tk.try": "Free codes:",
  "tk.stale": "{t} is no longer free. Pick another code before you add shareholders.",
  "tk.first": "Choose a share code first.",
  "tk.back": "Back to share code",
  "tk.name": "Enter the company name.",
} as const;

export const v3Vi: Record<keyof typeof v3En, string> = {
  "cta.list": "Niêm yết trên blockchain",
  "hv.demoChip": "Bạn đang dùng tài khoản demo",
  "hv.demoChip.tip": "Dùng chung cho mọi khách truy cập. Đăng nhập bất cứ lúc nào để dùng ví của riêng bạn.",
  "hv.paths.eyebrow": "Hai cách dùng BlockID",
  "hv.paths.h2": "Cho nhà đầu tư và cho doanh nghiệp.",
  "hv.paths.p": "Cả hai bên dùng chung một hồ sơ, nên những gì doanh nghiệp báo cáo cũng là những gì mọi nhà đầu tư thấy.",
  "hv.pi.h": "Cho nhà đầu tư",
  "hv.pi.p": "Kiểm tra doanh nghiệp trước khi đầu tư, và theo dõi sau đó.",
  "hv.pi.1": "Chọn một doanh nghiệp, hoặc dán website của họ",
  "hv.pi.2": "Đọc báo cáo dễ hiểu với giá trị hợp lý được một người duyệt",
  "hv.pi.3": "Giữ cổ phần trong ví của chính bạn",
  "hv.pi.4": "Nhận cùng cập nhật và cổ tức như mọi nhà đầu tư khác",
  "hv.pb.h": "Cho doanh nghiệp",
  "hv.pb.p": "Niêm yết doanh nghiệp và chuyển cổ phần thành token trên blockchain.",
  "hv.pb.1": "Dán website và, nếu muốn, số liệu của bạn",
  "hv.pb.2": "Nhận giá trị hợp lý, được một người duyệt",
  "hv.pb.3": "Thiết lập cổ phần và cổ đông",
  "hv.pb.4": "Niêm yết trên blockchain và cập nhật cho mọi nhà đầu tư cùng lúc",
  "hv.pi.cta": "Đánh giá doanh nghiệp",
  "hv.pb.cta": "Niêm yết trên blockchain",
  "new.eyebrow.list": "Niêm yết trên blockchain",
  "new.h2.list": "Niêm yết doanh nghiệp của bạn trên blockchain",
  "new.p.list": "Bắt đầu với website của bạn. Chúng tôi xác định giá trị hợp lý được một người duyệt, rồi tạo cổ phần trên blockchain để mọi nhà đầu tư nhận cùng cập nhật, cùng một lúc.",
  "url.checking": "Đang kiểm tra link…",
  "url.empty": "Nhập địa chỉ website của doanh nghiệp.",
  "url.spaces": "Địa chỉ website không được có dấu cách.",
  "url.bad_url": "Đây không phải địa chỉ website. Thử dạng như example.com.au.",
  "url.no_tld": "Địa chỉ cần có đuôi tên miền, như .com hoặc .com.au.",
  "url.ip": "Hãy dùng tên miền của doanh nghiệp, không dùng địa chỉ IP.",
  "url.not_public": "Địa chỉ này không phải website công khai.",
  "url.lookalike": "Địa chỉ này dùng chữ cái trông giống nhau, có thể không phải website bạn muốn.",
  "url.dns": "Không tìm thấy website này. Hãy kiểm tra chính tả.",
  "url.unreachable": "Không mở được website này. Kiểm tra địa chỉ hoặc thử lại sau.",
  "url.http_error": "Website trả về trang lỗi. Hãy kiểm tra địa chỉ.",
  "url.rate": "Kiểm tra link quá nhiều lần. Đợi một phút rồi thử lại.",
  "url.didyou": "Có phải ý bạn là {h}?",
  "url.use": "Dùng {h}",
  "sb.label": "Trạng thái",
  "sb.step": "Bước {n}/{N}",
  "sb.elapsed": "đã {t}",
  "sb.st.queued": "Đang xếp hàng",
  "sb.st.researching": "Đang nghiên cứu",
  "sb.st.waiting": "Chờ duyệt",
  "sb.st.approved": "Đã duyệt",
  "sb.st.rejected": "Bị từ chối",
  "sb.st.failed": "Thất bại",
  "sb.st.draft": "Bản nháp",
  "sb.st.creating": "Đang tạo cổ phần",
  "sb.st.copying": "Đang sao chép lên chuỗi công khai",
  "sb.st.live": "Đang niêm yết",
  "sb.st.private": "Riêng tư",
  "sb.st.sample": "Mẫu",
  "sb.st.demo": "Tài khoản demo",
  "sb.st.mine": "Ví của bạn",
  "sb.next.approve": "Tự duyệt (demo)",
  "sb.next.retry": "Thử lại",
  "sb.pf.meta": "{n} doanh nghiệp · {v}",
  "sb.pf.signin": "Dùng ví của riêng bạn",
  "v.score": "Điểm doanh nghiệp {s}",
  "v.notes": "Ghi chú ({n})",
  "v.notes.p": "Những điều nghiên cứu chưa xác nhận được. Một người sẽ đọc trước khi duyệt.",
  "v.site.h": "Không đọc được website này",
  "v.site.p": "Website có thể chặn khách truy cập, đang lỗi, hoặc link bị sai. Hãy kiểm tra link rồi thử lại.",
  "v.site.btn": "Kiểm tra link và thử lại",
  "v.stopped": "Lượt đánh giá đã dừng: {e}",
  "v.private.h": "Lượt đánh giá này là riêng tư",
  "v.private.p": "Chỉ tài khoản đã yêu cầu mới xem được, cho đến khi doanh nghiệp được niêm yết.",
  "v.private.btn": "Tự bắt đầu một lượt đánh giá",
  "demo.chip": "Demo",
  "demo.chip.p": "Đăng nhập bằng admin / admin và bấm “{a}”.",
  "demo.chip.btn": "Tự duyệt",
  "lb.quiet": "Số dư phí thấp ở {n} ví. Bước này có thể tạm dừng cho tới khi được nạp thêm.",
  "lb.quiet.link": "Nạp thêm",
  "in.chip.sample": "Dữ liệu mẫu",
  "in.chip.demo": "Tài khoản demo · dùng chung cho mọi khách",
  "tk.checking": "Đang kiểm tra {t}…",
  "tk.ok": "{t} dùng được.",
  "tk.taken": "{t} đã có công ty khác dùng. Hãy chọn mã khác.",
  "tk.reserved": "{t} là từ bị cấm dùng. Hãy chọn mã khác.",
  "tk.format": "Dùng đúng 3 chữ cái A–Z.",
  "tk.try": "Mã còn trống:",
  "tk.stale": "{t} không còn trống. Hãy chọn mã khác trước khi khai báo cổ đông.",
  "tk.first": "Hãy chọn mã cổ phần trước.",
  "tk.back": "Quay lại chọn mã",
  "tk.name": "Nhập tên công ty.",
};
