/**
 * Valuation v3 strings ("How we reached this value"). Not wired into dict.ts yet — the lead merges valEn/valVi.
 * Plain words only: no "AI" / "SVI" in labels. VI must cover every EN key (checked by the type).
 */
export const valEn = {
  "val.h": "How we reached this value",
  "val.sub": "We combine up to three methods. Each one uses only figures we found written in a source, and the better the evidence, the more it counts.",
  "val.value": "Fair value",
  "val.range": "Range {lo} – {hi}",
  "val.conf": "Confidence",
  "val.conf.high": "High",
  "val.conf.medium": "Medium",
  "val.conf.low": "Low",
  "val.conf.why": "Why this confidence",
  "val.col.method": "Method",
  "val.col.value": "Value",
  "val.col.weight": "Counts for",
  "val.col.based": "Based on",
  "val.m.market_anchor": "The business's own price",
  "val.m.market_anchor.d": "Its latest funding round, share sale, investor valuation or, for a listed business, its market value.",
  "val.m.revenue_multiple": "Revenue × what similar businesses are worth",
  "val.m.revenue_multiple.d": "Yearly revenue times the value-to-revenue ratio of comparable businesses or the sector.",
  "val.m.stage_scorecard": "Stage benchmark",
  "val.m.stage_scorecard.d": "A typical value for a business at this stage, adjusted by its quality score. Used most when little else is known.",
  "val.notused": "not used",
  "val.kind.market_cap": "Market value on the stock exchange",
  "val.kind.priced_round": "Funding round",
  "val.kind.secondary_sale": "Share sale",
  "val.kind.investor_mark": "Investor valuation",
  "val.kind.reported_valuation": "Reported valuation",
  "val.age": "{n} months ago",
  "val.age.new": "this month",
  "val.age.unknown": "date not stated",
  "val.rev": "Revenue {v} a year",
  "val.rev.self_reported": "given by the business, not checked",
  "val.rev.website": "stated on its website",
  "val.rev.cited_source": "found in a news or data source",
  "val.mult": "{m}× revenue",
  "val.mult.range": "(range {lo}× – {hi}×)",
  "val.ms.comps_3plus": "from {n} comparable businesses",
  "val.ms.comps_1_2": "from {n} comparable business(es)",
  "val.ms.sector_cited": "sector figure from a source",
  "val.ms.market_analysis": "from the market research",
  "val.ms.default": "standard figure (no source found)",
  "val.discount": "minus {p} because shares of a private business are harder to sell",
  "val.stage": "{stage} stage, quality factor {f}",
  "val.sources": "Sources",
  "val.src.open": "Open source",
  "val.listed": "Listed: {x}",
  "val.fx": "Currencies converted to AUD at fixed rates dated {d}.",
  "val.asof": "Evidence gathered {d}.",
  "val.comps": "Comparable businesses",
  "val.anchors": "Prices found for this business",
  "val.quote": "Quote from the source",
  "val.none": "No method could be applied.",
  "val.disclaimer": "An indicative fair value checked by a person, not financial advice or a formal valuation.",
};

export type ValKey = keyof typeof valEn;

export const valVi: Record<ValKey, string> = {
  "val.h": "Cách chúng tôi tính ra giá trị này",
  "val.sub": "Chúng tôi kết hợp tối đa ba phương pháp. Mỗi phương pháp chỉ dùng những con số được ghi rõ trong một nguồn, và bằng chứng càng tốt thì càng được tính nặng hơn.",
  "val.value": "Giá trị hợp lý",
  "val.range": "Khoảng {lo} – {hi}",
  "val.conf": "Độ tin cậy",
  "val.conf.high": "Cao",
  "val.conf.medium": "Trung bình",
  "val.conf.low": "Thấp",
  "val.conf.why": "Vì sao có độ tin cậy này",
  "val.col.method": "Phương pháp",
  "val.col.value": "Giá trị",
  "val.col.weight": "Tỷ trọng",
  "val.col.based": "Dựa trên",
  "val.m.market_anchor": "Giá của chính doanh nghiệp",
  "val.m.market_anchor.d": "Vòng gọi vốn, giao dịch cổ phần hoặc định giá của nhà đầu tư gần nhất; với doanh nghiệp niêm yết là giá trị thị trường.",
  "val.m.revenue_multiple": "Doanh thu × mức giá của doanh nghiệp tương tự",
  "val.m.revenue_multiple.d": "Doanh thu năm nhân với tỷ lệ giá trị trên doanh thu của các doanh nghiệp tương đương hoặc của ngành.",
  "val.m.stage_scorecard": "Chuẩn theo giai đoạn",
  "val.m.stage_scorecard.d": "Giá trị điển hình của doanh nghiệp ở giai đoạn này, điều chỉnh theo điểm chất lượng. Dùng nhiều nhất khi có ít thông tin khác.",
  "val.notused": "không dùng",
  "val.kind.market_cap": "Giá trị thị trường trên sàn chứng khoán",
  "val.kind.priced_round": "Vòng gọi vốn",
  "val.kind.secondary_sale": "Giao dịch cổ phần",
  "val.kind.investor_mark": "Định giá của nhà đầu tư",
  "val.kind.reported_valuation": "Định giá được báo chí nêu",
  "val.age": "{n} tháng trước",
  "val.age.new": "tháng này",
  "val.age.unknown": "không ghi ngày",
  "val.rev": "Doanh thu {v} mỗi năm",
  "val.rev.self_reported": "do doanh nghiệp cung cấp, chưa kiểm tra",
  "val.rev.website": "ghi trên website của doanh nghiệp",
  "val.rev.cited_source": "tìm thấy trong một nguồn tin hoặc dữ liệu",
  "val.mult": "{m}× doanh thu",
  "val.mult.range": "(khoảng {lo}× – {hi}×)",
  "val.ms.comps_3plus": "từ {n} doanh nghiệp tương đương",
  "val.ms.comps_1_2": "từ {n} doanh nghiệp tương đương",
  "val.ms.sector_cited": "số liệu ngành từ một nguồn",
  "val.ms.market_analysis": "từ phần nghiên cứu thị trường",
  "val.ms.default": "số liệu chuẩn (không tìm thấy nguồn)",
  "val.discount": "trừ {p} vì cổ phần doanh nghiệp tư nhân khó bán hơn",
  "val.stage": "giai đoạn {stage}, hệ số chất lượng {f}",
  "val.sources": "Nguồn",
  "val.src.open": "Mở nguồn",
  "val.listed": "Niêm yết: {x}",
  "val.fx": "Ngoại tệ được đổi sang AUD theo tỷ giá cố định ngày {d}.",
  "val.asof": "Bằng chứng thu thập ngày {d}.",
  "val.comps": "Doanh nghiệp tương đương",
  "val.anchors": "Các mức giá tìm thấy cho doanh nghiệp này",
  "val.quote": "Trích dẫn từ nguồn",
  "val.none": "Không áp dụng được phương pháp nào.",
  "val.disclaimer": "Giá trị hợp lý mang tính tham khảo, đã được người kiểm tra; không phải tư vấn tài chính hay thẩm định chính thức.",
};
