/** Simulated share offering copy (company workspace, investor pages, admin queue). Plain words; no internal terms on
 * investor or founder screens and no promise of gains (see docs/FACTS.md "Terms to avoid"). */
export const ofEn = {
  "nav.offerings": "Offerings",
  "ws.offering": "Share offering",
  "ws.d.offering": "Offer new shares to investors at a set price, with all the information they need. Simulated on testnet: no money moves.",
  "ad.q.offerings": "Offerings",
  "ad.d.offerings": "Share offerings waiting for a person: to open one for investors, or to issue the shares once it has closed with its minimum reached.",

  // events (company activity)
  "ev.offering_opened": "Share offering opened",
  "ev.offering_closed": "Share offering closed",
  "ev.offering_released": "Share offering closed, reservations released",
  "ev.offering_settled": "Share offering completed",
  "evd.of.opened": "{n} shares at {p}, closes {d}",
  "evd.of.closed": "{n} shares reserved · investors: {k}",
  "evd.of.released": "{k} reservations released",
  "evd.of.settled": "{n} new shares · investors: {k}",

  // status
  "of.st.draft": "Draft",
  "of.st.none": "No offering",
  "of.st.pending_approval": "Waiting for approval",
  "of.st.rejected": "Sent back",
  "of.st.cancelled": "Cancelled",
  "of.st.open": "Open",
  "of.st.awaiting_settlement": "Closed · waiting to issue shares",
  "of.st.settling": "Issuing shares",
  "of.st.settled": "Completed",
  "of.st.released": "Closed · reservations released",
  "of.st.failed": "Needs attention",
  "of.rs.reserved": "Reserved",
  "of.rs.withdrawn": "Withdrawn",
  "of.rs.released": "Released",
  "of.rs.allocated": "Shares issued",
  "of.sim": "Simulated: no money moves on testnet",
  "of.legal": "Testnet demo. A simulated share offering: no money moves and nothing is paid. Not an offer of securities or financial advice.",

  // company: terms
  "of.c.h": "Terms of the offering",
  "of.c.p": "Choose a price, how many new shares to offer and the smallest amount that makes the offering worth doing. A person checks the terms and the information pack before investors can see it.",
  "of.f.price": "Price per share (A$)",
  "of.f.priceHint": "Latest approved price: {p}",
  "of.f.shares": "Shares offered",
  "of.f.sharesHint": "Today there are {n} shares.",
  "of.f.min": "Minimum to raise (A$)",
  "of.f.minHint": "If less is reserved by the closing date, every reservation is released.",
  "of.f.max": "Most shares per investor",
  "of.f.close": "Closing date",
  "of.f.holders": "Most shareholders (optional)",
  "of.f.holdersHint": "Up to {n}. Today: {h}.",
  "of.f.use": "Use of funds",
  "of.f.usePh": "What the money will be used for",
  "of.sum": "{n} shares at {p} each, up to {max} in total. Minimum {min}. At most {per} shares per investor. Closes {d}.",
  "of.need": "Fill in the price, the shares offered, the most per investor and a closing date in the future.",
  "of.save": "Save terms",
  "of.submit": "Send for approval",
  "of.cancel": "Cancel offering",
  "of.close": "Close offering now",
  "of.closeConfirm": "Close the offering now? If the minimum is reached, the shares are issued after a person approves it. If not, every reservation is released.",
  "of.saved": "Terms saved. Check the information pack, then send it for approval.",
  "of.submitted": "Sent. A BlockID admin will check the terms and the information pack.",
  "of.cancelled": "Offering cancelled.",
  "of.closedMsg": "Offering closed.",
  "of.rejected": "Sent back: {r}",
  "of.onlylive": "You can offer shares once your shares are issued.",
  "of.none": "No offering yet. Set the terms below.",
  "of.edit": "Change terms",
  "of.keep": "Keep current terms",
  "of.wait": "Waiting for a BlockID admin to check the terms and the information pack.",
  "of.approveLink": "Open the approval",
  "of.openNote": "Open to investors until {d}. You can close it early.",
  "of.awaitNote": "Closed with the minimum reached. A person approves issuing the reserved shares to every investor.",
  "of.settlingNote": "Issuing the shares to every investor. This page updates by itself.",
  "of.settledNote": "Completed on {d}. The new shares are in the investors' wallets.",
  "of.releasedNote": "Closed without reaching the minimum. Every reservation was released.",
  "of.failedNote": "Issuing the shares did not finish. A BlockID admin can try again.",
  "of.sb.meta": "{n} of {N} shares reserved · closes {d}",

  // information pack
  "of.pack.h": "Information pack",
  "of.pack.p": "Put together automatically from the approved valuation, the published updates and the share register. Investors read it before they reserve.",
  "of.pack.preview": "Preview. It is fixed when you send the offering for approval.",
  "of.pack.frozen": "Fixed on {d}. Fingerprint {h}",
  "of.p.terms": "Terms",
  "of.p.price": "Price per share",
  "of.p.offered": "Shares offered",
  "of.p.maxraise": "Most that can be raised",
  "of.p.min": "Minimum to raise",
  "of.p.per": "Most per investor",
  "of.p.closes": "Closes",
  "of.p.cool": "Cooling-off",
  "of.p.coolV": "{n} days",
  "of.p.vsmark": "{p} compared with the latest approved price",
  "of.p.val": "Fair value",
  "of.p.valP": "Latest approved value {v} ({p} per share).",
  "of.p.range": "Range at the last full valuation: {lo} – {hi}",
  "of.p.conf": "Confidence: {c}",
  "of.p.conf.high": "high",
  "of.p.conf.medium": "medium",
  "of.p.conf.low": "low",
  "of.p.report": "Read the valuation report",
  "of.p.check": "Check the records",
  "of.p.upd": "Latest updates",
  "of.p.noupd": "No published updates yet.",
  "of.p.cap": "Share register before and after",
  "of.p.before": "Today",
  "of.p.after": "If every share is taken",
  "of.p.newpct": "The new shares would be {p} of the business.",
  "of.p.holders": "{n} shareholders",
  "of.p.total": "{n} shares",
  "of.p.use": "Use of funds",
  "of.p.nouse": "Not given.",
  "of.p.risks": "Risks",
  "of.p.notices": "Please note",
  "of.risk.loss": "You could lose all the money you put in. Young businesses often fail.",
  "of.risk.illiquid": "Shares in a business that is not on a stock exchange are hard to sell. You may not be able to sell them when you want to.",
  "of.risk.dilution": "Your share of the business gets smaller if the business issues more shares later.",
  "of.risk.dividends": "Dividends are not promised. The business may never pay one.",
  "of.risk.info": "The fair value is an estimate approved by a person, not a market price. The numbers come from the business and from public sources.",
  "of.risk.testnet": "This is a testnet demo. No money moves and the shares have no real value.",
  "of.n.price_above_mark": "The price is more than 20% above the latest approved price.",
  "of.n.no_updates": "This business has not published an update yet.",
  "of.n.stale_updates": "The latest published update is more than 90 days old.",

  // progress + reservations
  "of.pr.reserved": "{n} of {N} shares reserved",
  "of.pr.min": "Minimum {m} · {p} reached",
  "of.pr.minok": "Minimum reached",
  "of.pr.investors": "Investors: {n}",
  "of.pr.left": "{n} shares left",
  "of.pr.closes": "Closes {d}",
  "of.pr.closed": "Closed {d}",
  "of.res.h": "Reservations",
  "of.res.empty": "No reservations yet.",
  "of.res.who": "Investor",
  "of.res.shares": "Shares",
  "of.res.amount": "Amount",
  "of.res.status": "Status",
  "of.res.date": "Reserved",
  "of.hist.h": "Past offerings",

  // investor pages
  "of.i.h": "Share offerings",
  "of.i.p": "Businesses offering new shares, with all the information you need to decide.",
  "of.i.empty": "No offerings right now. Businesses that offer shares appear here.",
  "of.i.open": "Open now",
  "of.i.past": "Finished",
  "of.i.see": "See the offering",
  "of.i.back": "All offerings",
  "of.d.reserve": "Reserve shares",
  "of.d.p": "A reservation is a promise to buy at the price above. Payment is simulated on testnet.",
  "of.d.by": "Reserve by",
  "of.d.byShares": "Number of shares",
  "of.d.byAud": "Amount in A$",
  "of.d.eq": "{n} shares for {a}",
  "of.d.ack": "I have read the information pack and the risks",
  "of.d.name": "Name on the share register (optional)",
  "of.d.btn": "Reserve shares",
  "of.d.done": "Reserved. You can withdraw it until {d}.",
  "of.d.room": "You can reserve up to {n} more shares.",
  "of.d.full": "You have reserved the most shares allowed per investor.",
  "of.d.soldout": "All shares are reserved.",
  "of.d.closed": "This offering is closed.",
  "of.d.signin": "Sign in to reserve shares.",
  "of.d.mine": "My reservations",
  "of.d.withdraw": "Withdraw",
  "of.d.withdrawn": "Reservation withdrawn.",
  "of.d.until": "Can be withdrawn until {d}",
  "of.d.firm": "Cooling-off ended",
  "of.d.cool": "You can change your mind: each reservation can be withdrawn for {n} days, or until the offering closes if that comes first.",
  "of.d.how": "If the minimum is reached by the closing date, a person approves it and the shares go to your wallet. If not, every reservation is released and nothing happens.",
  "of.d.private": "Only the company's admins can see this offering until it is approved.",
  "of.d.need": "Enter how many shares, or an amount of at least one share.",
  "of.pf.h": "My share reservations",
  "of.pf.p": "Shares you reserved in offerings. They reach your wallet when the offering completes.",
  "of.pf.all": "See all offerings",
  "of.pf.none": "No reservations yet.",
  "of.badge": "Offering open",
  "of.badge.see": "See the offering",
  "of.co.open": "This business is offering new shares until {d}.",

  // admin queue
  "of.ad.open.p": "Check the terms and the information pack. Approving opens the offering to every investor.",
  "of.ad.settle.p": "The offering closed with its minimum reached. Approving issues the reserved shares to every investor in one job, then refreshes the public copies once.",
  "of.ad.approve": "Approve and open",
  "of.ad.reject": "Send back",
  "of.ad.reason": "Reason (sent to the company)",
  "of.ad.settle": "Approve and issue shares",
  "of.ad.release": "Release all reservations",
  "of.ad.failed": "Last attempt failed: {e}",
  "of.ad.opened": "Offering opened.",
  "of.ad.settling": "Issuing the shares. The status updates on the company page.",
  "of.ad.released": "Reservations released.",
  "of.ad.rejected": "Sent back to the company.",
  "of.ad.alloc": "{n} shares · investors: {k}",
};

export const ofVi: Record<keyof typeof ofEn, string> = {
  "nav.offerings": "Chào bán",
  "ws.offering": "Chào bán cổ phần",
  "ws.d.offering": "Chào bán cổ phần mới cho nhà đầu tư với giá cố định, kèm đủ thông tin họ cần. Mô phỏng trên testnet: không có tiền thật chuyển đi.",
  "ad.q.offerings": "Chào bán",
  "ad.d.offerings": "Các đợt chào bán chờ một người duyệt: để mở cho nhà đầu tư, hoặc để phát hành cổ phần khi đợt đã đóng và đạt mức tối thiểu.",

  "ev.offering_opened": "Mở đợt chào bán cổ phần",
  "ev.offering_closed": "Đóng đợt chào bán cổ phần",
  "ev.offering_released": "Đóng đợt chào bán, hủy mọi đăng ký",
  "ev.offering_settled": "Hoàn tất đợt chào bán",
  "evd.of.opened": "{n} cổ phần giá {p}, đóng ngày {d}",
  "evd.of.closed": "{n} cổ phần được {k} nhà đầu tư đăng ký",
  "evd.of.released": "Hủy {k} đăng ký",
  "evd.of.settled": "{n} cổ phần mới cho {k} nhà đầu tư",

  "of.st.draft": "Bản nháp",
  "of.st.none": "Chưa có đợt chào bán",
  "of.st.pending_approval": "Chờ duyệt",
  "of.st.rejected": "Bị trả lại",
  "of.st.cancelled": "Đã hủy",
  "of.st.open": "Đang mở",
  "of.st.awaiting_settlement": "Đã đóng · chờ phát hành cổ phần",
  "of.st.settling": "Đang phát hành cổ phần",
  "of.st.settled": "Hoàn tất",
  "of.st.released": "Đã đóng · đăng ký được hủy",
  "of.st.failed": "Cần xử lý",
  "of.rs.reserved": "Đã đăng ký",
  "of.rs.withdrawn": "Đã rút",
  "of.rs.released": "Đã hủy",
  "of.rs.allocated": "Đã nhận cổ phần",
  "of.sim": "Mô phỏng: không có tiền thật chuyển đi trên testnet",
  "of.legal": "Bản demo testnet. Đợt chào bán mô phỏng: không có tiền chuyển đi và không ai phải trả tiền. Không phải chào bán chứng khoán hay tư vấn tài chính.",

  "of.c.h": "Điều khoản chào bán",
  "of.c.p": "Chọn giá, số cổ phần mới muốn chào bán và số tiền tối thiểu để đợt chào bán có ý nghĩa. Một người sẽ kiểm tra điều khoản và bộ thông tin trước khi nhà đầu tư nhìn thấy.",
  "of.f.price": "Giá mỗi cổ phần (A$)",
  "of.f.priceHint": "Giá được duyệt gần nhất: {p}",
  "of.f.shares": "Số cổ phần chào bán",
  "of.f.sharesHint": "Hiện có {n} cổ phần.",
  "of.f.min": "Số tiền tối thiểu cần huy động (A$)",
  "of.f.minHint": "Nếu đến ngày đóng mà số đăng ký ít hơn, mọi đăng ký sẽ được hủy.",
  "of.f.max": "Tối đa cổ phần mỗi nhà đầu tư",
  "of.f.close": "Ngày đóng",
  "of.f.holders": "Số cổ đông tối đa (không bắt buộc)",
  "of.f.holdersHint": "Tối đa {n}. Hiện tại: {h}.",
  "of.f.use": "Mục đích sử dụng vốn",
  "of.f.usePh": "Số tiền sẽ được dùng vào việc gì",
  "of.sum": "{n} cổ phần, giá {p} mỗi cổ phần, tổng tối đa {max}. Tối thiểu {min}. Mỗi nhà đầu tư tối đa {per} cổ phần. Đóng ngày {d}.",
  "of.need": "Hãy nhập giá, số cổ phần chào bán, số tối đa mỗi nhà đầu tư và một ngày đóng trong tương lai.",
  "of.save": "Lưu điều khoản",
  "of.submit": "Gửi duyệt",
  "of.cancel": "Hủy đợt chào bán",
  "of.close": "Đóng đợt chào bán ngay",
  "of.closeConfirm": "Đóng đợt chào bán ngay? Nếu đạt mức tối thiểu, cổ phần được phát hành sau khi một người duyệt. Nếu không, mọi đăng ký sẽ được hủy.",
  "of.saved": "Đã lưu điều khoản. Hãy xem bộ thông tin rồi gửi duyệt.",
  "of.submitted": "Đã gửi. Quản trị viên BlockID sẽ kiểm tra điều khoản và bộ thông tin.",
  "of.cancelled": "Đã hủy đợt chào bán.",
  "of.closedMsg": "Đã đóng đợt chào bán.",
  "of.rejected": "Bị trả lại: {r}",
  "of.onlylive": "Bạn có thể chào bán cổ phần sau khi cổ phần đã được phát hành.",
  "of.none": "Chưa có đợt chào bán. Hãy đặt điều khoản bên dưới.",
  "of.edit": "Sửa điều khoản",
  "of.keep": "Giữ điều khoản hiện tại",
  "of.wait": "Đang chờ quản trị viên BlockID kiểm tra điều khoản và bộ thông tin.",
  "of.approveLink": "Mở mục duyệt",
  "of.openNote": "Mở cho nhà đầu tư đến {d}. Bạn có thể đóng sớm.",
  "of.awaitNote": "Đã đóng và đạt mức tối thiểu. Một người sẽ duyệt việc phát hành cổ phần đã đăng ký cho mọi nhà đầu tư.",
  "of.settlingNote": "Đang phát hành cổ phần cho mọi nhà đầu tư. Trang này tự cập nhật.",
  "of.settledNote": "Hoàn tất ngày {d}. Cổ phần mới đã nằm trong ví của nhà đầu tư.",
  "of.releasedNote": "Đã đóng mà không đạt mức tối thiểu. Mọi đăng ký đã được hủy.",
  "of.failedNote": "Việc phát hành cổ phần chưa xong. Quản trị viên BlockID có thể thử lại.",
  "of.sb.meta": "{n} / {N} cổ phần đã được đăng ký · đóng ngày {d}",

  "of.pack.h": "Bộ thông tin",
  "of.pack.p": "Được tự động tổng hợp từ định giá đã duyệt, các bản cập nhật đã công bố và sổ cổ đông. Nhà đầu tư đọc trước khi đăng ký.",
  "of.pack.preview": "Bản xem trước. Nội dung được cố định khi bạn gửi duyệt.",
  "of.pack.frozen": "Cố định ngày {d}. Mã kiểm tra {h}",
  "of.p.terms": "Điều khoản",
  "of.p.price": "Giá mỗi cổ phần",
  "of.p.offered": "Số cổ phần chào bán",
  "of.p.maxraise": "Số tiền tối đa có thể huy động",
  "of.p.min": "Số tiền tối thiểu",
  "of.p.per": "Tối đa mỗi nhà đầu tư",
  "of.p.closes": "Ngày đóng",
  "of.p.cool": "Thời gian cân nhắc",
  "of.p.coolV": "{n} ngày",
  "of.p.vsmark": "{p} so với giá được duyệt gần nhất",
  "of.p.val": "Giá trị hợp lý",
  "of.p.valP": "Giá trị được duyệt gần nhất {v} ({p} mỗi cổ phần).",
  "of.p.range": "Khoảng giá ở lần định giá đầy đủ gần nhất: {lo} – {hi}",
  "of.p.conf": "Độ tin cậy: {c}",
  "of.p.conf.high": "cao",
  "of.p.conf.medium": "trung bình",
  "of.p.conf.low": "thấp",
  "of.p.report": "Đọc báo cáo định giá",
  "of.p.check": "Kiểm tra hồ sơ",
  "of.p.upd": "Các bản cập nhật gần nhất",
  "of.p.noupd": "Chưa có bản cập nhật nào được công bố.",
  "of.p.cap": "Sổ cổ đông trước và sau",
  "of.p.before": "Hiện tại",
  "of.p.after": "Nếu mọi cổ phần được mua",
  "of.p.newpct": "Cổ phần mới sẽ chiếm {p} doanh nghiệp.",
  "of.p.holders": "{n} cổ đông",
  "of.p.total": "{n} cổ phần",
  "of.p.use": "Mục đích sử dụng vốn",
  "of.p.nouse": "Không nêu.",
  "of.p.risks": "Rủi ro",
  "of.p.notices": "Xin lưu ý",
  "of.risk.loss": "Bạn có thể mất toàn bộ số tiền bỏ ra. Doanh nghiệp trẻ thường thất bại.",
  "of.risk.illiquid": "Cổ phần của doanh nghiệp chưa niêm yết trên sàn rất khó bán. Bạn có thể không bán được khi muốn.",
  "of.risk.dilution": "Tỷ lệ sở hữu của bạn sẽ giảm nếu sau này doanh nghiệp phát hành thêm cổ phần.",
  "of.risk.dividends": "Cổ tức không được hứa trước. Doanh nghiệp có thể không bao giờ chia cổ tức.",
  "of.risk.info": "Giá trị hợp lý là ước tính được một người duyệt, không phải giá thị trường. Số liệu đến từ doanh nghiệp và nguồn công khai.",
  "of.risk.testnet": "Đây là bản demo testnet. Không có tiền chuyển đi và cổ phần không có giá trị thật.",
  "of.n.price_above_mark": "Giá cao hơn 20% so với giá được duyệt gần nhất.",
  "of.n.no_updates": "Doanh nghiệp này chưa công bố bản cập nhật nào.",
  "of.n.stale_updates": "Bản cập nhật gần nhất đã hơn 90 ngày.",

  "of.pr.reserved": "{n} / {N} cổ phần đã được đăng ký",
  "of.pr.min": "Tối thiểu {m} · đạt {p}",
  "of.pr.minok": "Đã đạt mức tối thiểu",
  "of.pr.investors": "{n} nhà đầu tư",
  "of.pr.left": "Còn {n} cổ phần",
  "of.pr.closes": "Đóng ngày {d}",
  "of.pr.closed": "Đã đóng ngày {d}",
  "of.res.h": "Đăng ký",
  "of.res.empty": "Chưa có đăng ký nào.",
  "of.res.who": "Nhà đầu tư",
  "of.res.shares": "Cổ phần",
  "of.res.amount": "Số tiền",
  "of.res.status": "Trạng thái",
  "of.res.date": "Ngày đăng ký",
  "of.hist.h": "Các đợt chào bán trước",

  "of.i.h": "Chào bán cổ phần",
  "of.i.p": "Các doanh nghiệp chào bán cổ phần mới, kèm đủ thông tin để bạn quyết định.",
  "of.i.empty": "Hiện chưa có đợt chào bán nào. Doanh nghiệp chào bán cổ phần sẽ xuất hiện ở đây.",
  "of.i.open": "Đang mở",
  "of.i.past": "Đã kết thúc",
  "of.i.see": "Xem đợt chào bán",
  "of.i.back": "Tất cả đợt chào bán",
  "of.d.reserve": "Đăng ký mua cổ phần",
  "of.d.p": "Đăng ký là lời cam kết mua với giá ở trên. Việc thanh toán được mô phỏng trên testnet.",
  "of.d.by": "Đăng ký theo",
  "of.d.byShares": "Số cổ phần",
  "of.d.byAud": "Số tiền A$",
  "of.d.eq": "{n} cổ phần với {a}",
  "of.d.ack": "Tôi đã đọc bộ thông tin và các rủi ro",
  "of.d.name": "Tên ghi trong sổ cổ đông (không bắt buộc)",
  "of.d.btn": "Đăng ký mua cổ phần",
  "of.d.done": "Đã đăng ký. Bạn có thể rút đến {d}.",
  "of.d.room": "Bạn có thể đăng ký thêm tối đa {n} cổ phần.",
  "of.d.full": "Bạn đã đăng ký số cổ phần tối đa cho mỗi nhà đầu tư.",
  "of.d.soldout": "Tất cả cổ phần đã được đăng ký.",
  "of.d.closed": "Đợt chào bán này đã đóng.",
  "of.d.signin": "Đăng nhập để đăng ký mua cổ phần.",
  "of.d.mine": "Đăng ký của tôi",
  "of.d.withdraw": "Rút",
  "of.d.withdrawn": "Đã rút đăng ký.",
  "of.d.until": "Có thể rút đến {d}",
  "of.d.firm": "Hết thời gian cân nhắc",
  "of.d.cool": "Bạn có thể đổi ý: mỗi đăng ký có thể rút trong {n} ngày, hoặc đến khi đợt chào bán đóng nếu sớm hơn.",
  "of.d.how": "Nếu đến ngày đóng đạt mức tối thiểu, một người sẽ duyệt và cổ phần được chuyển vào ví của bạn. Nếu không, mọi đăng ký được hủy và không có gì xảy ra.",
  "of.d.private": "Chỉ quản trị viên của doanh nghiệp thấy đợt chào bán này cho đến khi được duyệt.",
  "of.d.need": "Hãy nhập số cổ phần, hoặc số tiền đủ cho ít nhất một cổ phần.",
  "of.pf.h": "Đăng ký mua cổ phần của tôi",
  "of.pf.p": "Các cổ phần bạn đã đăng ký. Chúng được chuyển vào ví khi đợt chào bán hoàn tất.",
  "of.pf.all": "Xem mọi đợt chào bán",
  "of.pf.none": "Chưa có đăng ký nào.",
  "of.badge": "Đang chào bán",
  "of.badge.see": "Xem đợt chào bán",
  "of.co.open": "Doanh nghiệp này đang chào bán cổ phần mới đến {d}.",

  "of.ad.open.p": "Kiểm tra điều khoản và bộ thông tin. Duyệt sẽ mở đợt chào bán cho mọi nhà đầu tư.",
  "of.ad.settle.p": "Đợt chào bán đã đóng và đạt mức tối thiểu. Duyệt sẽ phát hành cổ phần đã đăng ký cho mọi nhà đầu tư trong một lần, rồi làm mới các bản sao công khai một lần.",
  "of.ad.approve": "Duyệt và mở",
  "of.ad.reject": "Trả lại",
  "of.ad.reason": "Lý do (gửi cho doanh nghiệp)",
  "of.ad.settle": "Duyệt và phát hành cổ phần",
  "of.ad.release": "Hủy mọi đăng ký",
  "of.ad.failed": "Lần thử trước thất bại: {e}",
  "of.ad.opened": "Đã mở đợt chào bán.",
  "of.ad.settling": "Đang phát hành cổ phần. Trạng thái cập nhật trên trang doanh nghiệp.",
  "of.ad.released": "Đã hủy mọi đăng ký.",
  "of.ad.rejected": "Đã trả lại doanh nghiệp.",
  "of.ad.alloc": "{n} cổ phần cho {k} nhà đầu tư",
};
