/** Automatic dividends copy (company dividends screen, admin queue, investor portal). Plain words; no internal terms
 * on investor screens (see docs/FACTS.md "Terms to avoid"). */
export const divEn = {
  // admin queue + events
  "ad.q.policies": "Dividend rules",
  "ad.d.policies": "Standing dividend rules sent by companies. Approving one lets the company pay dividends automatically from each published update, within its limit.",
  "ev.dividend_declared": "Dividend announced",
  "ev.dividend_vetoed": "Announced dividend cancelled",
  "evd.declared": "{n} mAUD, paid from {d}",

  // company: the rule
  "dvp.h": "Automatic dividends",
  "dvp.p": "Set a rule once. Each time a business update with a profit is approved and published, a dividend is announced to shareholders and paid to their wallets after a waiting time.",
  "dvp.none": "No rule yet. Dividends are paid only when you ask for one below.",
  "dvp.kind": "How much to pay",
  "dvp.kind.payout_ratio": "A share of net profit",
  "dvp.kind.fixed": "A fixed amount",
  "dvp.ratio": "Share of net profit (%)",
  "dvp.fixed": "Amount per payment (mAUD)",
  "dvp.max": "Most per payment (mAUD)",
  "dvp.freq": "How often",
  "dvp.freq.monthly": "Every month",
  "dvp.freq.quarterly": "Every quarter",
  "dvp.veto": "Waiting time before paying (hours)",
  "dvp.sum.payout_ratio": "Pay {r}% of net profit {f}, at most {max} mAUD per payment.",
  "dvp.sum.fixed": "Pay {a} mAUD {f} when there is a profit (never more than the profit), at most {max} mAUD per payment.",
  "dvp.sum.f.monthly": "every month",
  "dvp.sum.f.quarterly": "every quarter",
  "dvp.sum.only": "It uses the net profit in each published {c} update. Nothing is paid when there is no profit.",
  "dvp.sum.wait": "Shareholders are told {h} hours before it is paid. You can cancel it in that time.",
  "dvp.save": "Save rule",
  "dvp.submit": "Send rule for approval",
  "dvp.edit": "Change rule",
  "dvp.keep": "Keep current rule",
  "dvp.editwarn": "Changing the rule stops automatic payments until a person approves the new rule.",
  "dvp.pause": "Pause",
  "dvp.resume": "Resume",
  "dvp.saved": "Rule saved. Send it for approval when you are ready.",
  "dvp.submitted": "Sent. A BlockID admin will check the rule.",
  "dvp.paused": "Paused. No new dividends will be announced.",
  "dvp.resumed": "Resumed. Updates published from now on count.",
  "dvp.st.draft": "Draft",
  "dvp.st.pending_approval": "Waiting for approval",
  "dvp.st.active": "On",
  "dvp.st.paused": "Paused",
  "dvp.st.rejected": "Sent back",
  "dvp.rejected": "Sent back: {r}",
  "dvp.approved": "Approved on {d}",
  "dvp.next": "Next expected payment",
  "dvp.next.p": "After the {p} update is approved and published, paid {h} hours later (at most {max} mAUD).",
  "dvp.onlylive": "You can set a dividend rule once the shares are issued.",
  "dvp.need": "Enter the amounts first.",
  "dvp.legal": "Testnet demo. Dividends are paid in test Australian dollars (mAUD), which have no real value. Not an offer of securities or financial advice.",

  // company: list of dividends
  "dvl.h": "Dividends of this company",
  "dvl.empty": "No dividends yet.",
  "dvl.date": "Date",
  "dvl.period": "Period",
  "dvl.amount": "Amount (mAUD)",
  "dvl.how": "How",
  "dvl.status": "Status",
  "dvl.pays": "Pays on",
  "dvl.src.policy": "Automatic",
  "dvl.src.manual": "Requested",
  "dvl.cancel": "Cancel payment",
  "dvl.confirm": "Cancel this announced payment of {n} mAUD? Shareholders will see that it was cancelled.",
  "dvl.cancelled": "Payment cancelled.",
  "dvs.st.pending": "Waiting for approval",
  "dvs.st.scheduled": "Announced",
  "dvs.st.approved": "Being paid",
  "dvs.st.paying": "Being paid",
  "dvs.st.paid": "Paid",
  "dvs.st.failed": "Not paid yet",
  "dvs.st.rejected": "Rejected",
  "dvs.st.vetoed": "Cancelled",
  "dvs.st.skipped": "No payment",

  // admin queue item
  "pol.ad.p": "Read the rule. Once approved, this company's dividends are announced and paid automatically from each published update, within this limit, after a waiting time in which the company can cancel. Nothing is paid now.",
  "pol.ad.by": "Sent by {w}",
  "pol.ad.reason": "Reason (shown to the company if you send it back)",
  "pol.ad.approve": "Approve rule",
  "pol.ad.reject": "Send back",
  "pol.ad.approved": "Approved. The rule is on.",
  "pol.ad.rejected": "Sent back to the company.",

  // investor
  "inv.up.h": "Upcoming dividend",
  "inv.up.row": "{n} mAUD for {p}",
  "inv.up.rowNoP": "{n} mAUD",
  "inv.up.pays": "paid on {d}",
  "inv.up.p": "Announced by the business. It is paid to your wallet automatically on that date. The business can still cancel it before then.",
  "inv.led.h": "Your dividends",
  "inv.led.p": "Every dividend paid to your wallet, across all your businesses.",
  "inv.led.empty": "No dividends paid yet.",
  "inv.led.date": "Date",
  "inv.led.co": "Business",
  "inv.led.amt": "Amount (mAUD)",
  "inv.led.tx": "Payment record",
  "inv.led.view": "View",
  "inv.led.csv": "Download CSV",
  "inv.led.total": "Total received: {n} mAUD",
  "inv.led.upcoming": "Announced, not paid yet",
  "inv.led.note": "Paid in test Australian dollars (mAUD) on a test network. They have no real value.",
};

export const divVi: Record<keyof typeof divEn, string> = {
  "ad.q.policies": "Quy tắc cổ tức",
  "ad.d.policies": "Quy tắc cổ tức cố định do doanh nghiệp gửi. Khi được duyệt, doanh nghiệp tự động trả cổ tức từ mỗi cập nhật đã công bố, trong giới hạn đã đặt.",
  "ev.dividend_declared": "Đã công bố cổ tức",
  "ev.dividend_vetoed": "Đã hủy cổ tức đã công bố",
  "evd.declared": "{n} mAUD, trả từ {d}",

  "dvp.h": "Cổ tức tự động",
  "dvp.p": "Đặt quy tắc một lần. Mỗi khi một cập nhật kinh doanh có lợi nhuận được duyệt và công bố, cổ tức được thông báo cho cổ đông và trả vào ví của họ sau một thời gian chờ.",
  "dvp.none": "Chưa có quy tắc. Cổ tức chỉ được trả khi bạn yêu cầu ở bên dưới.",
  "dvp.kind": "Trả bao nhiêu",
  "dvp.kind.payout_ratio": "Một phần lợi nhuận ròng",
  "dvp.kind.fixed": "Một số tiền cố định",
  "dvp.ratio": "Tỷ lệ lợi nhuận ròng (%)",
  "dvp.fixed": "Số tiền mỗi lần trả (mAUD)",
  "dvp.max": "Tối đa mỗi lần trả (mAUD)",
  "dvp.freq": "Bao lâu một lần",
  "dvp.freq.monthly": "Mỗi tháng",
  "dvp.freq.quarterly": "Mỗi quý",
  "dvp.veto": "Thời gian chờ trước khi trả (giờ)",
  "dvp.sum.payout_ratio": "Trả {r}% lợi nhuận ròng {f}, tối đa {max} mAUD mỗi lần.",
  "dvp.sum.fixed": "Trả {a} mAUD {f} khi có lợi nhuận (không bao giờ vượt quá lợi nhuận), tối đa {max} mAUD mỗi lần.",
  "dvp.sum.f.monthly": "mỗi tháng",
  "dvp.sum.f.quarterly": "mỗi quý",
  "dvp.sum.only": "Dùng lợi nhuận ròng trong mỗi cập nhật {c} đã công bố. Không trả gì khi không có lợi nhuận.",
  "dvp.sum.wait": "Cổ đông được báo trước {h} giờ. Bạn có thể hủy trong thời gian đó.",
  "dvp.save": "Lưu quy tắc",
  "dvp.submit": "Gửi duyệt quy tắc",
  "dvp.edit": "Đổi quy tắc",
  "dvp.keep": "Giữ quy tắc hiện tại",
  "dvp.editwarn": "Đổi quy tắc sẽ dừng trả tự động cho đến khi một người duyệt quy tắc mới.",
  "dvp.pause": "Tạm dừng",
  "dvp.resume": "Tiếp tục",
  "dvp.saved": "Đã lưu quy tắc. Gửi duyệt khi bạn sẵn sàng.",
  "dvp.submitted": "Đã gửi. Admin BlockID sẽ kiểm tra quy tắc.",
  "dvp.paused": "Đã tạm dừng. Sẽ không công bố cổ tức mới.",
  "dvp.resumed": "Đã tiếp tục. Các cập nhật công bố từ bây giờ được tính.",
  "dvp.st.draft": "Bản nháp",
  "dvp.st.pending_approval": "Chờ duyệt",
  "dvp.st.active": "Đang bật",
  "dvp.st.paused": "Tạm dừng",
  "dvp.st.rejected": "Bị trả lại",
  "dvp.rejected": "Bị trả lại: {r}",
  "dvp.approved": "Duyệt ngày {d}",
  "dvp.next": "Lần trả dự kiến tiếp theo",
  "dvp.next.p": "Sau khi cập nhật {p} được duyệt và công bố, trả sau {h} giờ (tối đa {max} mAUD).",
  "dvp.onlylive": "Bạn có thể đặt quy tắc cổ tức khi cổ phần đã được phát hành.",
  "dvp.need": "Hãy nhập số tiền trước.",
  "dvp.legal": "Bản demo testnet. Cổ tức được trả bằng đô la Úc thử nghiệm (mAUD), không có giá trị thật. Không phải chào bán chứng khoán hay tư vấn tài chính.",

  "dvl.h": "Cổ tức của công ty này",
  "dvl.empty": "Chưa có cổ tức.",
  "dvl.date": "Ngày",
  "dvl.period": "Kỳ",
  "dvl.amount": "Số tiền (mAUD)",
  "dvl.how": "Cách",
  "dvl.status": "Trạng thái",
  "dvl.pays": "Ngày trả",
  "dvl.src.policy": "Tự động",
  "dvl.src.manual": "Theo yêu cầu",
  "dvl.cancel": "Hủy khoản trả",
  "dvl.confirm": "Hủy khoản cổ tức {n} mAUD đã công bố? Cổ đông sẽ thấy khoản này đã bị hủy.",
  "dvl.cancelled": "Đã hủy khoản trả.",
  "dvs.st.pending": "Chờ duyệt",
  "dvs.st.scheduled": "Đã công bố",
  "dvs.st.approved": "Đang trả",
  "dvs.st.paying": "Đang trả",
  "dvs.st.paid": "Đã trả",
  "dvs.st.failed": "Chưa trả được",
  "dvs.st.rejected": "Bị từ chối",
  "dvs.st.vetoed": "Đã hủy",
  "dvs.st.skipped": "Không trả",

  "pol.ad.p": "Đọc quy tắc. Khi được duyệt, cổ tức của công ty này được công bố và trả tự động từ mỗi cập nhật đã công bố, trong giới hạn này, sau một thời gian chờ để công ty có thể hủy. Chưa có khoản nào được trả lúc này.",
  "pol.ad.by": "Gửi bởi {w}",
  "pol.ad.reason": "Lý do (hiển thị cho công ty nếu bạn trả lại)",
  "pol.ad.approve": "Duyệt quy tắc",
  "pol.ad.reject": "Trả lại",
  "pol.ad.approved": "Đã duyệt. Quy tắc đang bật.",
  "pol.ad.rejected": "Đã trả lại cho công ty.",

  "inv.up.h": "Cổ tức sắp trả",
  "inv.up.row": "{n} mAUD cho {p}",
  "inv.up.rowNoP": "{n} mAUD",
  "inv.up.pays": "trả vào {d}",
  "inv.up.p": "Doanh nghiệp đã công bố. Khoản này được trả tự động vào ví của bạn vào ngày đó. Doanh nghiệp vẫn có thể hủy trước ngày đó.",
  "inv.led.h": "Cổ tức của bạn",
  "inv.led.p": "Mọi khoản cổ tức đã trả vào ví của bạn, từ tất cả doanh nghiệp bạn sở hữu.",
  "inv.led.empty": "Chưa có cổ tức nào được trả.",
  "inv.led.date": "Ngày",
  "inv.led.co": "Doanh nghiệp",
  "inv.led.amt": "Số tiền (mAUD)",
  "inv.led.tx": "Bản ghi thanh toán",
  "inv.led.view": "Xem",
  "inv.led.csv": "Tải CSV",
  "inv.led.total": "Tổng đã nhận: {n} mAUD",
  "inv.led.upcoming": "Đã công bố, chưa trả",
  "inv.led.note": "Trả bằng đô la Úc thử nghiệm (mAUD) trên mạng thử nghiệm. Không có giá trị thật.",
};
