/** Inline input checks (business updates, dividend rules, manual dividends, share offerings). Plain words: say what is
 * wrong and what to type instead. The API enforces the same rules. */
export const fx2En = {
  "fx2.fix": "Fix the fields marked in red first.",

  "fx2.kpi.bad": "Enter a plain number, like 125000 or -3500.50.",
  "fx2.kpi.big": "This number is too large.",
  "fx2.kpi.neg": "This cannot be below 0.",
  "fx2.kpi.whole": "Enter a whole number.",
  "fx2.kpi.cleared": "Left empty: the number saved for this period will be removed.",

  "fx2.upd.month": "Month",
  "fx2.upd.yearEnd": "Year ends in (month)",
  "fx2.upd.quarter": "Quarter",
  "fx2.upd.year": "Year",
  "fx2.upd.q1": "Q1 (Jan to Mar)",
  "fx2.upd.q2": "Q2 (Apr to Jun)",
  "fx2.upd.q3": "Q3 (Jul to Sep)",
  "fx2.upd.q4": "Q4 (Oct to Dec)",
  "fx2.upd.weekEnd": "Week ends on",
  "fx2.upd.p.range": "Period: {a} to {b}",
  "fx2.upd.p.bad": "Pick a period.",
  "fx2.upd.p.month": "A monthly or yearly period ends on the last day of a month.",
  "fx2.upd.p.quarter": "A quarter ends on 31 Mar, 30 Jun, 30 Sep or 31 Dec.",
  "fx2.upd.p.future": "This period has not finished yet. You can report it after {d}.",
  "fx2.upd.p.taken": "The update for this period is already {s}. Pick another period.",
  "fx2.upd.p.overlap": "This period shares days with the update for {p} ({a} to {b}), which is {s}. Each day can be reported once per frequency, so pick another period.",
  "fx2.upd.titleEmpty": "The title cannot be empty.",
  "fx2.upd.summaryEmpty": "The summary cannot be empty.",

  "fx2.dv.cents": "Enter an amount of at least 0.01, with at most 2 decimals.",
  "fx2.dv.tooBig": "This amount is too large (at most 1,000,000,000).",
  "fx2.dv.ratio": "Enter a percentage above 0 and at most 100.",
  "fx2.dv.veto": "Enter a whole number of hours from 1 to 168.",
  "fx2.dv.fixedOverCap": "The fixed amount cannot be more than the most per payment ({m}).",
  "fx2.dv.announced": "{n} announced payment(s), {a} mAUD in total, will still be paid when their waiting time ends. Pausing or changing the rule does not stop them.",
  "fx2.dv.cancelAll": "Cancel them",
  "fx2.dv.cancelConfirm": "Cancel {n} announced payment(s)? Shareholders will not receive them.",
  "fx2.dv.cancelReason": "cancelled when the rule was paused or changed",
  "fx2.dv.cancelledAll": "{n} announced payment(s) cancelled.",

  "fx2.div.amt": "Enter an amount of at least 0.01, with at most 2 decimals.",
  "fx2.div.paid": "{x} mAUD will be paid.",
  "fx2.div.paidRest": "{x} mAUD will be paid; {y} mAUD left over from rounding stays with the company.",

  "fx2.of.price": "Enter a price above 0 (at most A$1,000,000).",
  "fx2.of.whole": "Enter a whole number, 1 or more.",
  "fx2.of.amount": "Enter an amount in A$, 0 or more.",
  "fx2.of.minOver": "The minimum cannot be more than all the shares offered are worth ({a}).",
  "fx2.of.perOver": "Cannot be more than the shares offered ({n}).",
  "fx2.of.closeBad": "Pick a closing date and time.",
  "fx2.of.closeSoon": "Pick a closing time at least 5 minutes from now.",
  "fx2.of.closeFar": "Pick a closing date within {d} days.",
  "fx2.of.holdersLow": "The business already has {h} shareholders. Enter {h} or more, or leave it empty.",
  "fx2.of.holdersHigh": "The share register allows at most {c} shareholders.",
  "fx2.of.holdersNoCap": "No limit on the share register. Today: {h}.",
  "fx2.of.wholeShares": "Whole shares only. Enter a number without decimals.",
  "fx2.of.overRoom": "Too many. You can add {n} more shares.",
  "fx2.of.minCent": "A reservation must be worth at least A$0.01 ({n} shares or more at this price).",
  "fx2.of.canAdd": "you can add {n} more after this",
  "fx2.of.missing": "This offering doesn't exist or isn't open yet.",
  "fx2.of.seeAll": "See all offerings",
  "fx2.of.reg": "Shareholders on BlockID Chain: {n} of {c} allowed. After issuing: {a}.",
  "fx2.of.regNoCap": "Shareholders on BlockID Chain: {n} (no limit). After issuing: {a}.",
  "fx2.of.regOver": "That is more than the share register allows, so issuing would fail. Release the reservations instead.",
  "fx2.of.regUnknown": "The share register on BlockID Chain could not be read right now.",
  "fx2.of.releaseRest": "Release what was not issued",
};

export const fx2Vi: Record<keyof typeof fx2En, string> = {
  "fx2.fix": "Hãy sửa các ô được đánh dấu đỏ trước.",

  "fx2.kpi.bad": "Hãy nhập một con số bình thường, ví dụ 125000 hoặc -3500.50.",
  "fx2.kpi.big": "Con số này quá lớn.",
  "fx2.kpi.neg": "Giá trị này không được nhỏ hơn 0.",
  "fx2.kpi.whole": "Hãy nhập một số nguyên.",
  "fx2.kpi.cleared": "Để trống: con số đã lưu cho kỳ này sẽ bị xóa.",

  "fx2.upd.month": "Tháng",
  "fx2.upd.yearEnd": "Năm kết thúc vào (tháng)",
  "fx2.upd.quarter": "Quý",
  "fx2.upd.year": "Năm",
  "fx2.upd.q1": "Quý 1 (tháng 1 đến tháng 3)",
  "fx2.upd.q2": "Quý 2 (tháng 4 đến tháng 6)",
  "fx2.upd.q3": "Quý 3 (tháng 7 đến tháng 9)",
  "fx2.upd.q4": "Quý 4 (tháng 10 đến tháng 12)",
  "fx2.upd.weekEnd": "Tuần kết thúc vào",
  "fx2.upd.p.range": "Kỳ: từ {a} đến {b}",
  "fx2.upd.p.bad": "Hãy chọn một kỳ.",
  "fx2.upd.p.month": "Kỳ theo tháng hoặc theo năm kết thúc vào ngày cuối cùng của một tháng.",
  "fx2.upd.p.quarter": "Một quý kết thúc vào 31/3, 30/6, 30/9 hoặc 31/12.",
  "fx2.upd.p.future": "Kỳ này chưa kết thúc. Bạn có thể báo cáo sau ngày {d}.",
  "fx2.upd.p.taken": "Cập nhật cho kỳ này đã ở trạng thái {s}. Hãy chọn kỳ khác.",
  "fx2.upd.p.overlap": "Kỳ này trùng ngày với cập nhật {p} (từ {a} đến {b}), hiện ở trạng thái {s}. Mỗi ngày chỉ được báo cáo một lần cho mỗi tần suất, vì vậy hãy chọn kỳ khác.",
  "fx2.upd.titleEmpty": "Tiêu đề không được để trống.",
  "fx2.upd.summaryEmpty": "Tóm tắt không được để trống.",

  "fx2.dv.cents": "Hãy nhập số tiền từ 0,01 trở lên, tối đa 2 chữ số thập phân.",
  "fx2.dv.tooBig": "Số tiền này quá lớn (tối đa 1.000.000.000).",
  "fx2.dv.ratio": "Hãy nhập tỷ lệ phần trăm lớn hơn 0 và tối đa 100.",
  "fx2.dv.veto": "Hãy nhập số giờ là số nguyên từ 1 đến 168.",
  "fx2.dv.fixedOverCap": "Số tiền cố định không được lớn hơn mức tối đa mỗi lần trả ({m}).",
  "fx2.dv.announced": "{n} khoản chi trả đã thông báo, tổng cộng {a} mAUD, vẫn sẽ được trả khi hết thời gian chờ. Tạm dừng hoặc thay đổi quy tắc không dừng các khoản này.",
  "fx2.dv.cancelAll": "Hủy các khoản này",
  "fx2.dv.cancelConfirm": "Hủy {n} khoản chi trả đã thông báo? Cổ đông sẽ không nhận được các khoản này.",
  "fx2.dv.cancelReason": "đã hủy khi quy tắc được tạm dừng hoặc thay đổi",
  "fx2.dv.cancelledAll": "Đã hủy {n} khoản chi trả đã thông báo.",

  "fx2.div.amt": "Hãy nhập số tiền từ 0,01 trở lên, tối đa 2 chữ số thập phân.",
  "fx2.div.paid": "Sẽ trả {x} mAUD.",
  "fx2.div.paidRest": "Sẽ trả {x} mAUD; {y} mAUD dư do làm tròn được giữ lại cho công ty.",

  "fx2.of.price": "Hãy nhập giá lớn hơn 0 (tối đa 1.000.000 A$).",
  "fx2.of.whole": "Hãy nhập một số nguyên từ 1 trở lên.",
  "fx2.of.amount": "Hãy nhập số tiền A$ từ 0 trở lên.",
  "fx2.of.minOver": "Mức tối thiểu không được lớn hơn tổng giá trị số cổ phần chào bán ({a}).",
  "fx2.of.perOver": "Không được nhiều hơn số cổ phần chào bán ({n}).",
  "fx2.of.closeBad": "Hãy chọn ngày và giờ đóng.",
  "fx2.of.closeSoon": "Hãy chọn thời điểm đóng ít nhất 5 phút kể từ bây giờ.",
  "fx2.of.closeFar": "Hãy chọn ngày đóng trong vòng {d} ngày.",
  "fx2.of.holdersLow": "Doanh nghiệp đã có {h} cổ đông. Hãy nhập {h} trở lên, hoặc để trống.",
  "fx2.of.holdersHigh": "Sổ cổ đông cho phép tối đa {c} cổ đông.",
  "fx2.of.holdersNoCap": "Sổ cổ đông không giới hạn. Hiện tại: {h}.",
  "fx2.of.wholeShares": "Chỉ nhận số cổ phần nguyên. Hãy nhập số không có phần thập phân.",
  "fx2.of.overRoom": "Quá nhiều. Bạn chỉ có thể đăng ký thêm {n} cổ phần.",
  "fx2.of.minCent": "Mỗi đăng ký phải có giá trị ít nhất 0,01 A$ (từ {n} cổ phần trở lên ở mức giá này).",
  "fx2.of.canAdd": "sau đó bạn còn có thể thêm {n}",
  "fx2.of.missing": "Đợt chào bán này không tồn tại hoặc chưa mở.",
  "fx2.of.seeAll": "Xem tất cả đợt chào bán",
  "fx2.of.reg": "Cổ đông trên BlockID Chain: {n} trên tối đa {c}. Sau khi phát hành: {a}.",
  "fx2.of.regNoCap": "Cổ đông trên BlockID Chain: {n} (không giới hạn). Sau khi phát hành: {a}.",
  "fx2.of.regOver": "Con số này vượt quá mức sổ cổ đông cho phép, nên việc phát hành sẽ thất bại. Hãy hủy các đăng ký.",
  "fx2.of.regUnknown": "Hiện không đọc được sổ cổ đông trên BlockID Chain.",
  "fx2.of.releaseRest": "Hủy phần chưa phát hành",
};
