/**
 * "Running" tray (components/ActiveJobs.tsx, GET /v1/me/active-jobs) and the "Continue where you left off" card on
 * eth /start and hr / , /new, /new/person. Plain words. VI must cover every EN key (checked by the type).
 */
export const jobsEn = {
  "jobs.pill.running": "{n} running",
  "jobs.pill.ready": "{n} ready",
  "jobs.pill.aria": "Your analyses: {n} running, {r} ready. Open the list.",
  "jobs.menu.h": "Your analyses",
  "jobs.menu.sub": "They keep running while you use the rest of the app. Come back any time.",
  "jobs.kind.valuation": "Business valuation",
  "jobs.kind.hr_team": "Founding-team report",
  "jobs.kind.hr_person": "Person report",
  "jobs.st.queued": "Queued",
  "jobs.st.running": "Running",
  "jobs.st.done": "Ready",
  "jobs.st.failed": "Stopped",
  "jobs.eta": "about {t} left",
  "jobs.eta.soon": "almost done",
  "jobs.t.s": "{n} s",
  "jobs.t.min": "{n} min",
  "jobs.back": "Back to it",
  "jobs.view": "Ready — view result",
  "jobs.failed.view": "See what happened",
  "jobs.dismiss": "Hide from this list",
  "jobs.finished": "finished {t}",
  "jobs.toast.done": "{title} is ready",
  "jobs.toast.failed": "{title} stopped before the end",
  "jobs.toast.view": "View result",
  "jobs.toast.close": "Close",
  "jobs.cont.h": "Continue where you left off",
  "jobs.cont.p": "Nothing is lost when you open another page — your analyses keep running and your form is kept in this browser.",
  "jobs.cont.draft.start": "Unfinished form: {w}",
  "jobs.cont.draft.start.none": "Unfinished form",
  "jobs.cont.draft.people": "{n} people",
  "jobs.cont.draft.restored": "restored below",
  "jobs.cont.draft.discard": "Start over",
  "jobs.cont.draft.person": "Unfinished person review: {n}",
  "jobs.cont.draft.person.none": "Unfinished person review",
  "jobs.cont.draft.open": "Continue the form",
  "jobs.cont.hide": "Hide",
  "jobs.ph.queued": "Waiting to start",
  "jobs.ph.read_site": "Reading the website",
  "jobs.ph.profile": "Building the business profile",
  "jobs.ph.competitors": "Finding competitors",
  "jobs.ph.market": "Researching the market",
  "jobs.ph.svi": "Scoring",
  "jobs.ph.narrative": "Writing the report",
  "jobs.ph.reading": "Reading sources",
  "jobs.ph.searching": "Searching public sources",
  "jobs.ph.extracting": "Checking facts",
  "jobs.ph.scoring": "Scoring",
  "jobs.ph.stalled": "No progress — retrying",
  "jobs.ph.done": "Done",
  "jobs.ph.failed": "Stopped",
};

export const jobsVi: Record<keyof typeof jobsEn, string> = {
  "jobs.pill.running": "{n} đang chạy",
  "jobs.pill.ready": "{n} đã xong",
  "jobs.pill.aria": "Phân tích của bạn: {n} đang chạy, {r} đã xong. Mở danh sách.",
  "jobs.menu.h": "Phân tích của bạn",
  "jobs.menu.sub": "Phân tích vẫn tiếp tục chạy khi bạn dùng các trang khác. Quay lại bất cứ lúc nào.",
  "jobs.kind.valuation": "Định giá doanh nghiệp",
  "jobs.kind.hr_team": "Báo cáo đội ngũ sáng lập",
  "jobs.kind.hr_person": "Báo cáo cá nhân",
  "jobs.st.queued": "Đang chờ",
  "jobs.st.running": "Đang chạy",
  "jobs.st.done": "Đã xong",
  "jobs.st.failed": "Đã dừng",
  "jobs.eta": "còn khoảng {t}",
  "jobs.eta.soon": "sắp xong",
  "jobs.t.s": "{n} giây",
  "jobs.t.min": "{n} phút",
  "jobs.back": "Quay lại xem",
  "jobs.view": "Đã xong — xem kết quả",
  "jobs.failed.view": "Xem chuyện gì đã xảy ra",
  "jobs.dismiss": "Ẩn khỏi danh sách",
  "jobs.finished": "xong {t}",
  "jobs.toast.done": "{title} đã có kết quả",
  "jobs.toast.failed": "{title} đã dừng trước khi xong",
  "jobs.toast.view": "Xem kết quả",
  "jobs.toast.close": "Đóng",
  "jobs.cont.h": "Tiếp tục từ chỗ bạn dừng lại",
  "jobs.cont.p": "Không mất gì khi bạn mở trang khác — phân tích vẫn tiếp tục chạy và biểu mẫu được lưu trong trình duyệt này.",
  "jobs.cont.draft.start": "Biểu mẫu chưa xong: {w}",
  "jobs.cont.draft.start.none": "Biểu mẫu chưa xong",
  "jobs.cont.draft.people": "{n} người",
  "jobs.cont.draft.restored": "đã khôi phục bên dưới",
  "jobs.cont.draft.discard": "Làm lại từ đầu",
  "jobs.cont.draft.person": "Đánh giá cá nhân chưa xong: {n}",
  "jobs.cont.draft.person.none": "Đánh giá cá nhân chưa xong",
  "jobs.cont.draft.open": "Tiếp tục điền",
  "jobs.cont.hide": "Ẩn",
  "jobs.ph.queued": "Đang chờ bắt đầu",
  "jobs.ph.read_site": "Đang đọc website",
  "jobs.ph.profile": "Đang lập hồ sơ doanh nghiệp",
  "jobs.ph.competitors": "Đang tìm đối thủ",
  "jobs.ph.market": "Đang nghiên cứu thị trường",
  "jobs.ph.svi": "Đang chấm điểm",
  "jobs.ph.narrative": "Đang viết báo cáo",
  "jobs.ph.reading": "Đang đọc nguồn",
  "jobs.ph.searching": "Đang tìm nguồn công khai",
  "jobs.ph.extracting": "Đang kiểm chứng dữ kiện",
  "jobs.ph.scoring": "Đang chấm điểm",
  "jobs.ph.stalled": "Không có tiến triển — đang thử lại",
  "jobs.ph.done": "Xong",
  "jobs.ph.failed": "Đã dừng",
};
