/** Investor portal + sign-in copy. Plain words; no internal terms (see docs/FACTS.md "Terms to avoid"). */
export const invEn = {
  "nav.investors": "My portfolio",
  "foot.contact": "Contact",
  "nav.signin": "Sign in",
  "nav.role.guest": "guest",
  "nav.role.google": "Google",
  "nav.role.demo": "demo",
  "nav.portfolio": "My portfolio",
  "in.demo.acct": "You are in the demo account, shared by everyone who visits. Sign in to use your own wallet.",
  "in.acc.m.demo": "Demo account, shared by all visitors",
  "nav.accountlink": "Account and key backup",

  "in.title": "My portfolio",
  "in.eyebrow": "For investors",
  "in.crumbs": "Breadcrumb",
  "in.h.mine": "My portfolio",
  "in.h.demo": "Sample portfolio",
  "in.p.mine": "Every business you own shares in, what your shares are worth at the latest approved price, and the dividends paid to your wallet.",
  "in.p.demo": "A real shareholder on our test network. This is what you see once you own shares.",
  "in.demo.banner": "Sample data from the test network. Sign in to see your own portfolio.",
  "in.legal": "Testnet demo. Values use the latest price approved by people, not a market price. Not an offer of securities or financial advice.",
  "in.k.value": "Value of my shares",
  "in.k.valueSub": "at the latest approved price",
  "in.k.cos": "Businesses",
  "in.k.cosSub": "that I own shares in",
  "in.k.div": "Dividends received",
  "in.k.divSub": "test Australian dollars (mAUD)",
  "in.k.wallet": "My wallet",
  "in.k.walletSub": "where my shares are recorded",
  "in.c.shares": "{n} shares · {p} of the business",
  "in.c.since": "since first issued",
  "in.c.div": "{n} mAUD dividends received",
  "in.c.nodiv": "No dividends paid yet",
  "in.pos.sentence": "You own {n} of {s} shares ({p}). At the latest approved price of {price} per share, your shares are worth {v}.",
  "in.pos.price": "{p} per share",
  "in.pos.own": "Your share of the business",
  "in.pos.ownSub": "{n} shares",
  "in.pos.since": "Price change",
  "in.pos.sinceSub": "since first issued at {p}",
  "in.pos.trend": "Price per share, last 30 days",
  "in.pos.trendSub": "The price moves only when a new value is checked and approved.",
  "in.pos.divs": "Dividends paid to your wallet",
  "in.pos.divSub": "Paid automatically to every shareholder, in proportion to their shares.",
  "in.pos.next": "Follow this business",
  "in.pos.nextSub": "Every change to the business and its share register is listed, and you can check your shares yourself.",
  "in.pos.profile": "Business profile",
  "in.pos.updates": "Updates and history",
  "in.pos.check": "Check my shares",
  "in.empty.h": "You don't own shares yet",
  "in.empty.p": "Browse the businesses listed here, or list your own business and issue its shares in a few steps.",
  "in.empty.browse": "Browse businesses",
  "in.empty.list": "List your business",
  "in.sample.eyebrow": "See how it looks",

  "in.sign.h": "Sign in to see your portfolio",
  "in.sign.try": "Use the demo account",
  "in.sign.trySub": "A shared demo investor with sample shares. No sign-up.",
  "in.sign.googleSub": "Use your Gmail. Your key is created in this browser, and we never see it.",
  "in.sign.mm": "Use my crypto wallet",
  "in.sign.mmSub": "MetaMask or another browser wallet.",
  "in.google.off": "Google sign-in is being set up.",

  "in.acc.h": "Account",
  "in.acc.p": "How you signed in, your wallet address, and a backup of your private key.",
  "in.acc.how": "How you signed in",
  "in.acc.m.guest": "Quick try: a private key in this browser",
  "in.acc.m.google": "Google account",
  "in.acc.m.wallet": "Crypto wallet (MetaMask)",
  "in.acc.m.password": "Admin password",
  "in.acc.keep": "Want to come back from another device? Connect your Google account. Your wallet stays the same.",
  "in.acc.backup": "Back up your private key",
  "in.acc.backupP": "Your key lives only in this browser. If you clear the browser or lose this device, you need this backup to use the same wallet again. Keep it private: anyone with it controls your wallet.",
  "in.acc.show": "Show my private key",
  "in.acc.hide": "Hide",
  "in.acc.copy": "Copy",
  "in.acc.copied": "Copied. Store it somewhere safe.",
  "in.acc.toHold": "Go to my portfolio",
  "in.acc.restore": "Restore a wallet from a backed-up key",
  "in.acc.restoreP": "Paste the private key you saved earlier. It is stored in this browser only.",
  "in.acc.restoreBtn": "Restore and sign in",
};

export const invVi: Record<keyof typeof invEn, string> = {
  "nav.investors": "Danh mục của tôi",
  "foot.contact": "Liên hệ",
  "nav.signin": "Đăng nhập",
  "nav.role.guest": "dùng thử",
  "nav.role.google": "Google",
  "nav.role.demo": "demo",
  "nav.portfolio": "Danh mục của tôi",
  "in.demo.acct": "Bạn đang dùng tài khoản demo, dùng chung cho mọi khách truy cập. Đăng nhập để dùng ví của riêng bạn.",
  "in.acc.m.demo": "Tài khoản demo dùng chung cho mọi khách",
  "nav.accountlink": "Tài khoản và sao lưu khoá",

  "in.title": "Danh mục của tôi",
  "in.eyebrow": "Dành cho nhà đầu tư",
  "in.crumbs": "Đường dẫn",
  "in.h.mine": "Danh mục của tôi",
  "in.h.demo": "Danh mục mẫu",
  "in.p.mine": "Mọi doanh nghiệp bạn có cổ phần, giá trị cổ phần theo mức giá được duyệt gần nhất, và cổ tức đã trả vào ví của bạn.",
  "in.p.demo": "Một cổ đông thật trên mạng thử nghiệm. Đây là những gì bạn thấy khi đã sở hữu cổ phần.",
  "in.demo.banner": "Dữ liệu mẫu trên mạng thử nghiệm. Đăng nhập để xem danh mục của bạn.",
  "in.legal": "Bản demo testnet. Giá trị dùng mức giá mới nhất do con người phê duyệt, không phải giá thị trường. Không phải chào bán chứng khoán hay tư vấn tài chính.",
  "in.k.value": "Giá trị cổ phần của tôi",
  "in.k.valueSub": "theo giá được duyệt gần nhất",
  "in.k.cos": "Doanh nghiệp",
  "in.k.cosSub": "tôi đang có cổ phần",
  "in.k.div": "Cổ tức đã nhận",
  "in.k.divSub": "đô la Úc thử nghiệm (mAUD)",
  "in.k.wallet": "Ví của tôi",
  "in.k.walletSub": "nơi ghi nhận cổ phần của tôi",
  "in.c.shares": "{n} cổ phần · {p} doanh nghiệp",
  "in.c.since": "từ lúc phát hành",
  "in.c.div": "Đã nhận {n} mAUD cổ tức",
  "in.c.nodiv": "Chưa có cổ tức",
  "in.pos.sentence": "Bạn sở hữu {n} trên {s} cổ phần ({p}). Với giá được duyệt gần nhất là {price} mỗi cổ phần, cổ phần của bạn trị giá {v}.",
  "in.pos.price": "{p} mỗi cổ phần",
  "in.pos.own": "Phần sở hữu của bạn",
  "in.pos.ownSub": "{n} cổ phần",
  "in.pos.since": "Thay đổi giá",
  "in.pos.sinceSub": "so với giá phát hành {p}",
  "in.pos.trend": "Giá mỗi cổ phần, 30 ngày qua",
  "in.pos.trendSub": "Giá chỉ thay đổi khi có giá trị mới được kiểm tra và phê duyệt.",
  "in.pos.divs": "Cổ tức đã trả vào ví của bạn",
  "in.pos.divSub": "Trả tự động cho mọi cổ đông, theo tỷ lệ cổ phần.",
  "in.pos.next": "Theo dõi doanh nghiệp này",
  "in.pos.nextSub": "Mọi thay đổi của doanh nghiệp và sổ cổ đông đều được liệt kê, và bạn có thể tự kiểm tra cổ phần của mình.",
  "in.pos.profile": "Hồ sơ doanh nghiệp",
  "in.pos.updates": "Cập nhật và lịch sử",
  "in.pos.check": "Kiểm tra cổ phần của tôi",
  "in.empty.h": "Bạn chưa sở hữu cổ phần nào",
  "in.empty.p": "Xem các doanh nghiệp đang có ở đây, hoặc đăng doanh nghiệp của bạn và phát hành cổ phần chỉ trong vài bước.",
  "in.empty.browse": "Xem các doanh nghiệp",
  "in.empty.list": "Đăng doanh nghiệp của bạn",
  "in.sample.eyebrow": "Xem trước giao diện",

  "in.sign.h": "Đăng nhập để xem danh mục của bạn",
  "in.sign.try": "Dùng tài khoản demo",
  "in.sign.trySub": "Nhà đầu tư demo dùng chung, có sẵn cổ phần mẫu. Không cần đăng ký.",
  "in.sign.googleSub": "Dùng Gmail của bạn. Khoá được tạo ngay trong trình duyệt này, chúng tôi không bao giờ thấy nó.",
  "in.sign.mm": "Dùng ví crypto của tôi",
  "in.sign.mmSub": "MetaMask hoặc ví trình duyệt khác.",
  "in.google.off": "Đăng nhập Google đang được thiết lập.",

  "in.acc.h": "Tài khoản",
  "in.acc.p": "Cách bạn đăng nhập, địa chỉ ví, và bản sao lưu khoá riêng.",
  "in.acc.how": "Cách bạn đăng nhập",
  "in.acc.m.guest": "Dùng thử nhanh: khoá riêng trong trình duyệt này",
  "in.acc.m.google": "Tài khoản Google",
  "in.acc.m.wallet": "Ví crypto (MetaMask)",
  "in.acc.m.password": "Mật khẩu admin",
  "in.acc.keep": "Muốn quay lại từ thiết bị khác? Kết nối tài khoản Google. Ví của bạn vẫn giữ nguyên.",
  "in.acc.backup": "Sao lưu khoá riêng",
  "in.acc.backupP": "Khoá chỉ nằm trong trình duyệt này. Nếu xoá dữ liệu trình duyệt hoặc mất thiết bị, bạn cần bản sao lưu này để dùng lại đúng ví. Hãy giữ kín: ai có khoá này sẽ điều khiển được ví của bạn.",
  "in.acc.show": "Hiện khoá riêng của tôi",
  "in.acc.hide": "Ẩn",
  "in.acc.copy": "Sao chép",
  "in.acc.copied": "Đã sao chép. Hãy cất ở nơi an toàn.",
  "in.acc.toHold": "Đến danh mục của tôi",
  "in.acc.restore": "Khôi phục ví từ khoá đã sao lưu",
  "in.acc.restoreP": "Dán khoá riêng bạn đã lưu trước đó. Khoá chỉ được lưu trong trình duyệt này.",
  "in.acc.restoreBtn": "Khôi phục và đăng nhập",
};
