"""Build UNSIGNED transactions for the issuer's Safe multisig.

No key material exists anywhere in the agent runtime. The output is a Safe Transaction Builder
batch (JSON) that a human imports into Safe{Wallet}, reviews and co-signs.
Only static ABI types are used, so encoding is a sequence of 32-byte words.
"""
from __future__ import annotations

import time

from ..schemas import SafeBatch, UnsignedTx
from .merkle import keccak256


def selector(signature: str) -> bytes:
    return keccak256(signature.encode())[:4]


def _word(kind: str, v) -> bytes:
    if kind == "address":
        h = str(v).lower().removeprefix("0x")
        if len(h) != 40:
            raise ValueError(f"bad address {v}")
        return bytes(12) + bytes.fromhex(h)
    if kind.startswith("uint"):
        bits = int(kind[4:] or 256)
        n = int(v)
        if n < 0 or n >= 2**bits:
            raise ValueError(f"{v} out of range for {kind}")
        return n.to_bytes(32, "big")
    if kind == "bytes32":
        h = str(v).removeprefix("0x")
        if len(h) != 64:
            raise ValueError(f"bad bytes32 {v}")
        return bytes.fromhex(h)
    raise ValueError(f"unsupported ABI type {kind}")


def encode_call(signature: str, *args) -> str:
    types = signature[signature.index("(") + 1 : -1].split(",") if not signature.endswith("()") else []
    if len(types) != len(args):
        raise ValueError(f"{signature} expects {len(types)} args, got {len(args)}")
    return "0x" + (selector(signature) + b"".join(_word(t, a) for t, a in zip(types, args))).hex()


def to_bytes32_hex(sha256_hex: str) -> str:
    h = sha256_hex.removeprefix("0x")
    if len(h) != 64:
        raise ValueError("expected 32-byte hex digest")
    return "0x" + h


# ------------------------------------------------------------------ typed builders
def tx_register_investor(registry: str, wallet: str, country: int, expires_at: int, kyc_ref: str) -> UnsignedTx:
    return UnsignedTx(
        to=registry,
        data=encode_call("registerInvestor(address,uint16,uint64,bytes32)", wallet, country, expires_at, kyc_ref),
        description=f"KYC register {wallet} (country {country})",
    )


def tx_issue(token: str, to: str, shares: int, resolution_ref: str) -> UnsignedTx:
    return UnsignedTx(
        to=token,
        data=encode_call("issue(address,uint256,bytes32)", to, shares, resolution_ref),
        description=f"Issue {shares} shares to {to}",
    )


def tx_anchor_valuation(token: str, report_hash: str, per_share_cents: int) -> UnsignedTx:
    return UnsignedTx(
        to=token,
        data=encode_call("anchorValuation(bytes32,uint256)", report_hash, per_share_cents),
        description=f"Anchor SVI report {report_hash[:10]}… at {per_share_cents} cents/share",
    )


def tx_approve(erc20: str, spender: str, amount: int) -> UnsignedTx:
    return UnsignedTx(
        to=erc20, data=encode_call("approve(address,uint256)", spender, amount), description=f"Approve {amount} to {spender}"
    )


def tx_create_round(
    distributor: str, root: str, pay_token: str, total: int, record_block: int, deadline: int, resolution: str
) -> UnsignedTx:
    return UnsignedTx(
        to=distributor,
        data=encode_call(
            "createRound(bytes32,address,uint256,uint64,uint64,bytes32)",
            root,
            pay_token,
            total,
            record_block,
            deadline,
            resolution,
        ),
        description=f"Dividend round: {total} units, root {root[:10]}…",
    )


def safe_batch(chain_id: int, name: str, txs: list[UnsignedTx], created_by: str) -> SafeBatch:
    return SafeBatch(
        chainId=str(chain_id),
        createdAt=int(time.time() * 1000),
        meta={"name": name, "description": "Generated by BlockID agents — review every call before signing", "createdFromSafeAddress": "", "createdBy": created_by},
        transactions=txs,
    )
